### ISSUE TITLE
[3ds Max] Animated camera orientation problem

### ISSUE THREAD

**Issue by Remi-Tribia** [BabylonJS/Exporters#1003]
Hi, ​

I've noticed something strange happening when exporting an animated camera (without target). Position is ok, but rotation goes up and down, then seems ok, and the up and down starts again (see gif below). The only solution I could find at the moment is to add an animated camera target, and update camera lookAt at each frame.

![animated_camera_issue](https://user-images.githubusercontent.com/40400644/133057037-bca60c63-3b3d-4441-8e82-ed5fad0b2688.gif)

I thought it was related to my code, but it's also happening when loading it in the sandbox. Is there something I'm missing, when exporting or setting animations in `Animation Groups` ?

Thanks :)

**Comment by pandaGaume** [comment]
please share the scene if possible.

**Comment by pandaGaume** [comment]
Hey,
I'm sorry but can not reproduce.  Here the result in Babylon and GLTF.
[test.zip](https://github.com/BabylonJS/Exporters/files/7162529/test.zip)
Did i miss something ?

**Comment by Remi-Tribia** [comment]
Hi! Thanks for taking the time to test it!
I'm so dumb I forgot to update the exporter before posting this issue... I was using `20210308.2` and now with `20210811.2` everything seems fine. 
Sorry for the inconvenience and waste of time!

**Comment by Remi-Tribia** [comment]
In fact the issue was still happening in another scene even with the latest version of the exporter.
It is resolved by checking `Do not optimize animations`. 

![optimized_animations_issue](https://user-images.githubusercontent.com/40400644/133305541-1349c7bf-8460-4bbf-8afb-324103dfc016.gif)
_Only thing I did between those 2 curves is just checking `do not optimize animations`_

As you can see when keys are optimized there's an offset compared to the actual value.

**Comment by pandaGaume** [comment]
I'm gona check, the good news is there is a workarround.

**Comment by pandaGaume** [comment]
could you send me the other scene ??

**Comment by Remi-Tribia** [comment]
There you go, that's the camera exported above

[export cam.zip](https://github.com/BabylonJS/Exporters/files/7194940/export.cam.zip)

**Comment by pandaGaume** [comment]
Hey,
The problem is coming from this [FixCamera ](https://github.com/BabylonJS/Exporters/blob/215b5b4064ed3750d64b045addf4e1cb19f57972/3ds%20Max/Max2Babylon/Exporter/BabylonExporter.cs#L501)call, where transformation are introducing erratic values...
```
      // In 3DS Max the default camera look down (in the -z direction for the 3DS Max reference (+y for babylon))
      // In Babylon the default camera look to the horizon (in the +z direction for the babylon reference)
      // In glTF the default camera look to the horizon (in the +Z direction for glTF reference)
      RaiseMessage("Update camera rotation and position", 1);
      for (int index = 0; index < babylonScene.CamerasList.Count; index++)
      {
          BabylonCamera camera = babylonScene.CamerasList[index];
          FixCamera(ref camera, ref babylonScene);
      }

```
I have to dig in.

**Comment by pandaGaume** [comment]
Hey,
This is an issue with animation group, which was done for Babylon Format. Delete the animation group from the camera properties, then everything will be fine for GLTF/GLB
Historically, the exporter was designed first to babylon, then mainly use and maintained for gltf. All subsequent PR was done with GLTF only in mind, and this broke some logic such the one into animation group and camera.
I will discuss with the team to address this.
Let me know if deleting the animation group is fixing your case.
G.

**Comment by pandaGaume** [comment]
Hello,
the bug was more viscous than I thought. It was into FixCamera methods where the transformation was applied to animation.keys which is a subset of animation.fullkeys (do not ask why we get all these, this is historic for sure). Then only a part of the keys was updated. By then reaching the AnimationGroup, the process relies on animation.fullkeys which was then no longer consistent.
