### ISSUE TITLE
Took 6 hours to export a simple sphere with a phong material and simple texture...

### ISSUE THREAD

**Issue by morrisolmsted** [BabylonJS/Exporters#1004]
Myself and a couple of artists are all trying this tool and overall its amazing.  However while theirs works flawlessly, Mine takes so long its useless.  I made a simple poly sphere and put a phong on it with a simple 512x512 texture on that.  My artists can export whole characters in under 30 seconds but my sphere takes 6 hours to export and didn't generate a file I could open.  Any help here would be appreciated.
I am using Maya 2020.3 and have uninstalled and reinstalled the software but I cannot seem to find out what is the matter.

thanks,
Morris

**Comment by pandaGaume** [comment]
Hey,
6 hours for a sphere.. it's a guinness world record. Please share your scene with us, then we can have a look on it and see what's going wrong.

**Comment by morrisolmsted** [comment]
[ballTest.zip](https://github.com/BabylonJS/Exporters/files/7213015/ballTest.zip)
It is very likely I have something setup wrong but any help would be great.

**Comment by morrisolmsted** [comment]
I created a new Maya scene with a cube and exported this morning and here is the spew and time it took from that...

Export started
Selected nodes full path
	|pCube1
DAG: full
	name=	 type=kWorld
		name=persp	 type=kTransform
			name=perspShape	 type=kCamera
		name=top	 type=kTransform
			name=topShape	 type=kCamera
		name=front	 type=kTransform
			name=frontShape	 type=kCamera
		name=side	 type=kTransform
			name=sideShape	 type=kCamera
		name=pCube1	 type=kTransform
			name=pCubeShape1	 type=kMesh
DAG: relevant
	name=	 type=kWorld
		name=pCube1	 type=kTransform
			name=pCubeShape1	 type=kMesh
Exporting nodes
	pCube1
		no morph targets
		mFnMesh.fullPathName=|pCube1|pCubeShape1
		24 vertices, 12 faces
		BabylonExporter.Mesh | done
	Total meshes: 1
	No camera defined
	Total lights: 0
Exporting materials
	StingrayPBS3
	kPluginHardwareShader
		Stingray shader
		StingrayPBS3.TEX_color_map
			Only file or aiImage texture are supported.
			Texture path is not a valid string.
	Total: 1
Export animation groups
GLTFExporter | Exportation started
GLTFExporter | Exporting nodes
	GLTFExporter | ExportNode pCube1
		GLTFExporter.Node | Add pCube1 as root node to scene
GLTFExporter | Exporting meshes
	GLTFExporter.Mesh | Export mesh named: pCube1
		GLTFExporter.Mesh | Mesh from babylon
			GLTFExporter.Mesh | nbVertices=24
			GLTFExporter.Mesh | hasUV=True
			GLTFExporter.Mesh | hasUV2=False
			GLTFExporter.Mesh | hasColor=False
			GLTFExporter.Mesh | hasBones=False
			GLTFExporter.Mesh | hasBonesExtra=False
			GLTFExporter.Mesh | hasMetadata=False
			GLTFExporter.Mesh | hasNormals=True
		GLTFExporter.Mesh | Init glTF
		GLTFExporter.Mesh | glTF primitives
			GLTFExporter.Mesh | Material
			GLTFExporter.Mesh | Geometry
GLTFExporter | Exporting skins, lights and cameras
	GLTFExporter | ExportNode pCube1 of Type BabylonExport.Entities.BabylonMesh
		GLTFExporter.AbstractMesh | Export abstract mesh named: pCube1
GLTFExporter | Exporting materials
	GLTFExporter.Material | Export material named: StingrayPBS3
		GLTFExporter.Material | create gltfMaterial
		GLTFExporter.Material | create gltfPbrMetallicRoughness
	GLTFExporter | Nb materials exported: 1
GLTFExporter | Exporting Animations
	GLTFExporter.Animation | No AnimationGroups: exporting all animations together.
		GLTFExporter.Animation | Export animations of node named: pCube1
GLTFExporter | Saving to output file
Export done in 20015.59s

**Comment by pandaGaume** [comment]
Did you try to reset preference file ?
https://knowledge.autodesk.com/support/maya/troubleshooting/caas/sfdcarticles/sfdcarticles/Laggy-performance-or-freezing-in-Maya.html

**Comment by morrisolmsted** [comment]
yes, I have done those steps

**Comment by morrisolmsted** [comment]
OK, been testing and testing and finally uninstalled everything including my .mod file that points to a shared directory with my team of extra scripts and python libs and it works perfectly.  Again, I don't know what exactly did it but looks like I have various code from 6 versions of Maya with scripts and libs sitting there including pymel.  it is possible that these somehow overwrote what your tool expected and caused the issues.  Thanks for your help!
