### ISSUE TITLE
PBR material exported from Maya not setting Metalic Roughness map

### ISSUE THREAD

**Issue by Chargeuk** [BabylonJS/Exporters#1009]
This is an issue raised for a bug discussed at [The Babylon.js forum](https://forum.babylonjs.com/t/pbr-material-exported-from-maya-not-setting-metalic-roughness-map/24031) and is raised as requested by @pandaGaume 

When exporting an aiStandardSurface material with an ORM texture attached to its Metalness and Specular Roughness attributes, I would expect the resulting Babylonjs PBRMaterial to have:

1. The ORM texture set as  the Metallic Roughness texture
2.  The ORM texture set as  the Ambient texture
3. The "Ambient in greyscale" attribute to be set as true

Instead, we get:
1. The ORM texture set as the Reflectivity texture (incorrect)
2.  The ORM texture set as the Ambient texture (correct)
3. The "Ambient in greyscale" attribute to be set as false (incorrect)

Thanks.

**Comment by pandaGaume** [comment]
@bghgary 
the code seem not finished... the attempt in the current version is to transform a BabylonPBRMetallicRoughnessMaterial or BabylonPBRSpecularGlossinessMaterial to a BabylonPBRMaterial

```
        public BabylonPBRMaterial(BabylonPBRMetallicRoughnessMaterial origin) : this((BabylonPBRBaseSimpleMaterial)origin)
        {
            useRoughnessFromMetallicTextureAlpha = false;
            useRoughnessFromMetallicTextureGreen = true;
            useMetallnessFromMetallicTextureBlue = true;

            roughness = origin.roughness;
            metallic = origin.metallic;
            reflectivityTexture = origin.metallicRoughnessTexture;
        }

        public BabylonPBRMaterial(BabylonPBRSpecularGlossinessMaterial origin) : this((BabylonPBRBaseSimpleMaterial)origin)
        {
        }
```
this approach seems a bit simplistic ...

**Comment by pandaGaume** [comment]
@Chargeuk does the attached file is correct for you ? 
[fullpbr.zip](https://github.com/BabylonJS/Exporters/files/7366672/fullpbr.zip)
