### ISSUE TITLE
Exporter Request: Autodesk Navisworks

### ISSUE THREAD

**Issue by j-te** [BabylonJS/Exporters#1017]
Hello!

I would like to see a Navisworks exporter to .glb/.gltf files, it could create many workflows for the AEC industries. It would also be important to read the **property sets** and carry the data into `metadata.gltf.extras`. This could (positively) disrupt "BIM" and IFC. The aim is for it to be a super user friendly export workflow for non techies.

I can help develop this plugin but would like some guidance/assistance on the approach for the exporter, this is also an opportunity to discuss if others have attempted it.

There are workflows for exporting FBX from Navisworks but the fbx implementation is pants and the data/IDs does not come through to 3ds Max.

I've found this which may be a start: https://github.com/bimangle/forge-engine-samples

**Comment by pandaGaume** [comment]
Hello  @j-te , welcome to the exporter side.
We are awaiting Autodesk's announcement regarding GLTF, before taking further actions on the subject.
Regards

**Comment by gevimon** [comment]
Hi! i also need something of the sort
im a beginner at Visual Studio also a beginner in C# and also a beginner at NAVIS
but i believe that if there is a way to export out of NAVIS a table of model object coordinates then thats all you need to work with
