### ISSUE TITLE
The Maya 2022 exporter doesn't seem to be exporting opacity correctly.

### ISSUE THREAD

**Issue by jdswiney** [BabylonJS/Exporters#1018]
It will export opacity kind of. I just don't know where it is pulling it from. I followed the step by step in the documents and I even tried using both the Arnold shader step by step and the StingRay step by step. Just seems to grab some random opacity when using the blend setting.

**Comment by pandaGaume** [comment]
hey,
Thanks for the comment. Did this behavior is only affecting 2022 or was also with 2020 ? May you share your test scene with us ?

**Comment by jdswiney** [comment]
Hey thanks for the reply. It's NOT the Babylon.js exporter. I have the same or very similar issue exporting out of Substance Painter. I have narrowed it down to either the model itself being the problem or some weird bug in GLTF itself. I can get simple models to work just fine in both Maya and Substance Painter. I am not the only person out there with this issue. It's just no one seems to have a cause or a solution.

Thanks for your time!

**Comment by pandaGaume** [comment]
Hey, before closing the issue, could you share a simple scene with us, highlighting the problem. I'm very curious about these "no one have a cause or a solution" problems. 
Thank's.

**Comment by jdswiney** [comment]
I read on a link at the Khronos Group that this has something to do with using BLEND on an object that contains the following: Both Opaque and Transparent surfaces on same material along with poly models that have concave structures and are open like the example I include. It's some sort of inability to sort depth under those conditions. I guess it is known but most laypeople like myself are not in the know.

So, basically it was me using a model that triggered this problem and misidentifying its cause

I can't include the actual project model but I built you one that demonstrates the exact issue. 

There is a work around for artists that I am now using. Simply apply a different shader to the transparent area. This still requires the whole model be unchecked for being opaque and the blend setting is only activated on the transparent shader. The opaque shader is left as opaque. I hope this little journey of mine helps someone in the future. : )

[Window.zip](https://github.com/BabylonJS/Exporters/files/7486013/Window.zip)

**Comment by jdswiney** [comment]
Here is a fixed version using the 2 shader method. 
[WindowFixed.zip](https://github.com/BabylonJS/Exporters/files/7486202/WindowFixed.zip)

**Comment by bghgary** [comment]
This is a common issue with alpha blend. For many real-time renderers, it sorts the meshes in order to render the alpha blended meshes after the opaque meshes. If the alpha blended part is not separated into its own mesh, there will be no way for these renderers to sort correctly.

**Comment by pandaGaume** [comment]
Thanks for the infos.
