### ISSUE TITLE
The influence order is getting flipped.

### ISSUE THREAD

**Issue by akhil81989** [BabylonJS/Exporters#1023]
I have a model which has blend shape applied and then skin cluster on top of it. This is working fine in Maya. but when i export the same file using babylon.js(Maya plugin) the order of influence swaps. like first skin cluster is applied then morph target gets applied. Hence when I rotate hands down and then activate morph target the hands are going back to its original position because morph target is overriding the skin cluster.
Versions:-
Maya 2018.
Babylon.js exporter plugin version V20211102.1(even updating to latest version didn't help).

![3447e1ea-dea3-4ace-8a97-714b6b8f5a9e](https://user-images.githubusercontent.com/28824055/147378376-f5815b35-46f8-4820-89c3-778ccd624544.jpg)

**Comment by pandaGaume** [comment]
Hello please send us a repro to track the problem.

**Comment by akhil81989** [comment]
Please find maya file through which i was exporting to GLTF.

https://drive.google.com/file/d/1w1rEAK9axtVA5iEu0i0j-P6fZndBOILh/view?usp=sharing

**Comment by pandaGaume** [comment]
sorry canot load the file 
<img width="539" alt="image" src="https://user-images.githubusercontent.com/22658224/147413880-c42d6927-5fe5-4b53-9d11-82eef69f6dcb.png">

**Comment by pandaGaume** [comment]
@akhil81989 may you post back the scene ??
- G.

**Comment by pandaGaume** [comment]
no more activity here.
