### ISSUE TITLE
Maya blendshape animation

### ISSUE THREAD

**Issue by qqba** [BabylonJS/Exporters#1024]
hi
I created two blendshapes, but only one blendshape works after exporting? 
And skinning and blendshape can't be exported at the same time? 
Looking forward to your reply

**Comment by pandaGaume** [comment]
Hello,
please could you share the scene with us in order to reproduce ?
-G.

**Comment by qqba** [comment]
[test.zip](https://github.com/BabylonJS/Exporters/files/7872182/test.zip)
Thank you for your reply.
 I packed the files together and named them. I hope they can be solved

**Comment by pandaGaume** [comment]
Hello,
After a short survey into the code, it's appear that both are currently exporter limitation.
```
                if (exportParameters.exportSkins && mFnSkinCluster != null)
                {
                    RaiseWarning("A mesh with both skinning and morph target is not fully supported. Please set the playhead at the frame you want to choose as the bind pose before exporting.", 3);
                }

                if(blendShapeDeformers.Count > 1)
                {
                    RaiseWarning($"There are {blendShapeDeformers.Count} blend shapes. The exporter currently support one. So all blend shapes will be exported as one.", 3);
                }

```
Then I tag this issue as ehancement, but keep it active because we are currently addressing skinning and morphing limitation of the exporter.

**Comment by pandaGaume** [comment]
After review, no need to keep it open so far.
