### ISSUE TITLE
3dsmax exporter locks source texture files

### ISSUE THREAD

**Issue by conceptfarm** [BabylonJS/Exporters#1033]
I'm having issues with the 3dsmax exporter locking source texture files post export. Closing 3dsmax release the lock but its not the best workflow if you need to edit and re-export textures a few times.

**Comment by pandaGaume** [comment]
Hello,
Version of Max ? Version of the exporter ?
I understand the issue but we manipulate several texture sources. Could you be more specific or sending us a project and/or way to reproduce. 
Thank's.

**Comment by conceptfarm** [comment]
I am using max 2020 latest update, exporter v20210811.2
To reproduce:
- in a new file create a box
- create a standard material and assign a bitmap texmap to the diffuse channel
- input any file for the texture map, i used a random jpeg file
- assign the material to the box
- select the box and launch the exporter
- set the path for the model and the path for the texture (not same path as the original material texture)
- set output to gtfl, and set export materials, export textures, write textures to on
- export
- try to rename/delete the original source texture which was referenced in the material, you can't its locked to 3dsmax.

**Comment by conceptfarm** [comment]
Also tried with the latest release v20220308.1, same behaviour.

**Comment by pandaGaume** [comment]
Thank's.
I will have a look on it asap. 
.G
