### ISSUE TITLE
Max2Babylon - support for 2023 and GLTF materials?

### ISSUE THREAD

**Issue by CiuffoliniFLx** [BabylonJS/Exporters#1040]
Hi,
as you probably know the new 3dsmax 2023 offers GLTF support out of the box - but that seems clunky at best, with no support for animation and complex hierarchies (it flattens the whole scene!).

I was wondering if a 2023 max2babylon version is in the works. 
Personally the 2 things i care the most for are:
1. if it can export 3dsmax GLTF materials (including transmission parameters)
2. if it can export hierarchies of objects, respecting parent/child relationships

can you share any insight?
best!

Federico

**Comment by bghgary** [comment]
We are working on this with Autodesk.

Please use the forum for questions next time. :-)

**Comment by bghgary** [comment]
See PR: https://github.com/BabylonJS/Exporters/pull/1041
