### ISSUE TITLE
 3DSMax 2023 & GLTFMaterial Preview #1041 - issue with Alpha mode export

### ISSUE THREAD

**Issue by CiuffoliniFLx** [BabylonJS/Exporters#1044]
Hi, 
this issue is specific for the 3dsmax exporter existing on branch https://github.com/pandaGaume/Exporters/tree/2023-support , managed by @pandaGaume .
Trying out the branch, it seems that the the Alpha Mode of the new GLTFMaterials is not correctly exported, and the output materials are always opaque. I thought it was a good idea to publicly discuss this, and possibly intercept a bug.

<img width="1029" alt="image" src="https://user-images.githubusercontent.com/55701107/162213605-f2ac63c3-8a6a-418c-a8be-06d4563ce241.png">

(on the right 3dsmax UI, on the left babylon's sandbox inspector)

Were you aware of this issue, or maybe does this happen on my side only?

Thank you,

**Comment by pandaGaume** [comment]
Hello,
I'm not aware of this, thanks to pointing me on it. I will make a check on the last code, that i did not commited yet, to see if still the case.
However, this branch is not already an official release and the Pandagaume fork is intended to dev and test, so while not merged we may have these discussion on forum or under the panda gaume fork.
Thank's again for test it and help us to improve the product.
G.
