### ISSUE TITLE
Installer.zip download fail - virus detected

### ISSUE THREAD

**Issue by nymbl3d** [BabylonJS/Exporters#1051]
Hi,

When downloading the installer, the download was blocked due to a virus threat being identified.  
For you info here is the log from the windows "Threat blocked".
![installerThreatBlocked](https://user-images.githubusercontent.com/19493374/169017939-9314a80d-8d49-4208-9fea-573b075aaa1a.png)

If this is somethingthat can be allowed, let me know. 

Many thanks

D

**Comment by pandaGaume** [comment]
Hello,
The installer is build on server side, into azure pipeline. I do not see a trojan going there.
i believe its false positive. i just double checked by downloading the installer (zip), unzip it and analyzed with defender.
if you downloaded the zip from [https://github.com/BabylonJS/Exporters/releases/tag/Release20220505.2](https://github.com/BabylonJS/Exporters/releases/tag/Release20220505.2) the file itself must be safe.
@bghgary ???

**Comment by bghgary** [comment]
Basically what @pandaGaume said. Maybe you can [report a false positive](https://docs.microsoft.com/en-us/microsoft-365/security/defender/m365d-autoir-report-false-positives-negatives?view=o365-worldwide) to Microsoft? Another possibility is that there is a virus on the machine that is adding this Trojan to the zip.

**Comment by pandaGaume** [comment]
closing for now.
