### ISSUE TITLE
Maya 2023 plugin not loading

### ISSUE THREAD

**Issue by shafnaz** [BabylonJS/Exporters#1054]
Hi devs,

Having some issues loading the .dll
It's not showing up in the plug-in manager either.

![image](https://user-images.githubusercontent.com/37254287/173612474-6e53fe2e-5084-4ffa-b0a9-f1bf445ffee3.png)

![image](https://user-images.githubusercontent.com/37254287/173612747-32d39aa3-627b-4944-a527-801798e577ff.png)

![image](https://user-images.githubusercontent.com/37254287/173612802-8f2ec96c-b722-466f-ab25-39a22428024e.png)

**Comment by shafnaz** [comment]
I copied all the .dll to bin/plug-ins

**Comment by bghgary** [comment]
I believe @pandaGaume still needs to update the installer.

**Comment by shafnaz** [comment]
cool

**Comment by bghgary** [comment]
> @bghgary We also need to rename the Maya2Babylon.dll to Maya2Babylon.nll.dll which is specificity of Maya plugin.

Fixed. We also discussed offline that we should just change the solution to output the correct name instead of renaming it in the build pipeline.
