### ISSUE TITLE
No User Defined Properties are exported in 3ds Max 2021

### ISSUE THREAD

**Issue by Paxilon** [BabylonJS/Exporters#1067]
Reproduce: 
open 3ds Max 2021
create a cube or any kind of mesh
right-click the cube -> Object properties -> User defined
type e.g. data = mydata
export as GLB or GLTF
open in e.g Blender -> under custom properties everything is empty, should show data: and in the textfield "mydata"

**Comment by pandaGaume** [comment]
Hello, thanks for the clear repro step.
This is not a bug. You may define a specific user defined entry named `extras` to be exported.
`extras` MUST be a json valid string. You may use such [tool ](https://jsonlint.com/) to validate your property value
for example
`extras = {"name":"a", "description":"b"}`
You may use first the [forum ](https://forum.babylonjs.com/)to ask for help and then post an issue if we identify a bug or potential ehancement.
Thanks for your support.
