### ISSUE TITLE
3ds Max 2018 Exporter: gltf output does not render correctly

### ISSUE THREAD

**Issue by hololite** [BabylonJS/Exporters#107]
I am using the exporter for 3ds Max 2018. The exported .Babylon format renders correctly.
The gltf output though looks like mono color. I would expect the rendering to be the same as .babylon. 
I am using all the default options of the exporter. Let me know if there are certain configs I need to override. 
Here is the sample max project you can use to repro this issue. 
https://raw.githubusercontent.com/hololite/models/master/3dsmax/projects/old_house_max.zip 

Linked issue in babylon forum: 
http://www.html5gamedevs.com/topic/36060-3dsmax-2018-exporter-gltf-output-does-not-seem-to-render-correctly/?tab=comments#comment-206805

**Comment by deltakosh** [comment]
This seems to be a priority one

**Comment by noalak** [comment]
Specular level map is not exported only specular color map is.

However, the specular level parameter is exported. This gives a specular color for babylon which is used when converting standard material to PBR one.

Here, the specular level is very high which leads to an almost white baseColor texture in gltf.
When set to 0, the gltf result is really close to the babylon one.

**Comment by hololite** [comment]
Is the fix going to be in the next beta? Thx!

**Comment by deltakosh** [comment]
There is no fix per se but more a feature setup. You have to use specular color map in association with specular level
