### ISSUE TITLE
3ds Max 2023 - Normal map not exporting on glTF material

### ISSUE THREAD

**Issue by gortnarj** [BabylonJS/Exporters#1072]
When exporting a scene with the 3ds Max glTF material node, the normal map slot seems to get ignored (no normal map displayed in output log). If I change the material to Physical Material the export of the same texture works fine. 
![image](https://user-images.githubusercontent.com/16923579/185798774-3ee15853-66b6-4206-88eb-50a30852f591.png)

**Comment by pandaGaume** [comment]
I can not reproduce.
<img width="200" alt="image" src="https://user-images.githubusercontent.com/22658224/185986685-6d7ec9d5-0e0f-4855-917a-733789ec2182.png">
give
<img width="477" alt="image" src="https://user-images.githubusercontent.com/22658224/185986647-a5f2bce9-903c-4d92-8d83-7b28f11946ba.png">
Could you please share you scene with us ?

**Comment by pandaGaume** [comment]
still work here...
<img width="818" alt="image" src="https://user-images.githubusercontent.com/22658224/187076664-9feb8f5b-a66d-4782-875d-9ab34dd574b9.png">
and the log
<img width="286" alt="image" src="https://user-images.githubusercontent.com/22658224/187076688-63ab1e5d-429d-4d77-83cb-5d2b3f3b0815.png">
May you share your log ?

**Comment by gortnarj** [comment]
Tried chainging the directory, making a new scene with only a cube and a gltf material with just a normal map, but still the same issue. Here's the log:
![image](https://user-images.githubusercontent.com/16923579/187254220-097e5da4-40ee-4eec-b177-5adb80252fa3.png)

**Comment by pandaGaume** [comment]
Could you expand the first "exporting materials" log ??

**Comment by gortnarj** [comment]
Here it is:
![image](https://user-images.githubusercontent.com/16923579/187659387-7941c1d4-4c1c-46f7-9824-a24029283417.png)

**Comment by pandaGaume** [comment]
Ok this not give any usefull informations.. i update Max2023 to the latest version and re-install the exporter and still not able to reproduce...

**Comment by pandaGaume** [comment]
Any news on this ? otherwise i will close the issue.

**Comment by gortnarj** [comment]
Updated Max to 2023.1 and reinstalled Babylon, no difference. 
Did some more testing today and turns out after unstalling a plugin I had (Wall Worm), the export now works as expected. Would this be a Babylon issue or a Wall Worm issue?

**Comment by pandaGaume** [comment]
I beleive Wall worm should modify the model source and then the interaction did not going well. This is not a bug from Babylon nor Wall worm, it's side effect from one part or another. We might investigate but honestly we do not have a high bandwith actually... i will try to install wall worm an see if i can find something.

**Comment by pandaGaume** [comment]
Just had a quick look and find that the WallWorm plugin change (in any way) the name of the normalMap to lowerCase. `normalMap` become `normalmap`. The cache implementation we use is case sensitive and did not perfom well in this situation. I will implement a fallback to search first case sensitive then unsensitive if failed. This may help in other similar situation and make our exporter more resilient. PR to come.
