### ISSUE TITLE
Export Texture transparency as opacity map with gltf

### ISSUE THREAD

**Issue by saidmoya12** [BabylonJS/Exporters#1077]
The [documentation](https://doc.babylonjs.com/features/featuresDeepDive/Exporters/3DSMax#texture-transparency) describe that is possible to create an opacity map but using png or jpg but always is exported in diffuse texture

![image](https://user-images.githubusercontent.com/1872974/202230870-1d63e1ed-95c2-4306-a18b-678bf8a0a8d4.png)

I need separate alpha and diffuse texture so how can I do it? or is a feature not supported by GLTF or **3dsmax plugin**?

Thanks for your help

**Comment by thomlucc** [comment]
This documentation is for the .babylon format but this is not supported by the glTF format
