### ISSUE TITLE
Control space layout should be improved

### ISSUE THREAD

**Issue by kelilife** [BabylonJS/Exporters#1086]
![image](https://user-images.githubusercontent.com/115648681/232748394-1b819c18-139b-4d88-8471-3f3440305a92.png)

**Comment by bghgary** [comment]
If you are willing to contribute a fix, that would be great!

**Comment by kelilife** [comment]
I am very sorry, I am not good at UI programming skills other than c#.

**Comment by kelilife** [comment]
I decided I'd better do the improvement, I'm okay with the UI.

**Comment by kelilife** [comment]
Of course, there are still many details to improve, such as line spacing, padding, alignment, etc.
