### ISSUE TITLE
mesh information not embedded in .gltf

### ISSUE THREAD

**Issue by torchesburn** [BabylonJS/Exporters#1098]
When i try to export .gltf format, i get an extra .bin file, which would make sense if i did not want it embedded, but no I noticed there was no option for embedded GLTF without bin.

Is this the case?
and also is this project abandoned?

**Comment by bghgary** [comment]
Embedded GLTF without bin is not efficient and we don't support exporting in this form. It is better to export as a GLB.

See [here](https://github.com/BabylonJS/Exporters#%EF%B8%8F) for the current status of this project.
