### ISSUE TITLE
Maya Export Skin info, result only has two joints and weights

### ISSUE THREAD

**Issue by xjedges** [BabylonJS/Exporters#1102]
My mesh have 4 bones to aflect on each vertex, but after use Maya_to_glTF to export, the result only has two bones. anyway to  keep all skin data?

**Comment by thomlucc** [comment]
Hi @xjedges - could you please send a repro? Maya file + exported glTF

**Comment by xjedges** [comment]
@thomlucc Thanks for reply, actually it is a bug for  [https://gltf.report/](url), it shows only two bones. After I import to 3d software, it is fine.
