### ISSUE TITLE
An issue with the 3dmax exported GLTF model

### ISSUE THREAD

**Issue by sui0312feng** [BabylonJS/Exporters#1109]
In the exported gltf file, the position of the text on the model is incorrect and the model under the text is not exported
[test.zip](https://github.com/BabylonJS/Exporters/files/13871873/test.zip)
![Uploading 1704793038994.png…]()

**Comment by sui0312feng** [comment]
![1704793038994](https://github.com/BabylonJS/Exporters/assets/9710113/55b3d30a-ae97-431e-8e76-185488e0779d)

**Comment by sui0312feng** [comment]
![1704793605273](https://github.com/BabylonJS/Exporters/assets/9710113/521b6098-5da4-4fa3-a698-10f2df942037)
this is correct

**Comment by sebavan** [comment]
@PatrickRyanMS and @SergioRZMasson can you have a look ?
