### ISSUE TITLE
Draco compression problem in 3ds max 2024

### ISSUE THREAD

**Issue by AlexZhigin** [BabylonJS/Exporters#1111]
Hello! When exporting to glTF with draco compression, the code has incorrect indexes for transmissionTexture and thicknessTexture. They are also not in the "textures" and "image" sections. The textures themselves are created, but for now you have to write them in the code manually. Without draco compression everything is fine. I would be very grateful if you could fix it in exporter.

**Comment by bghgary** [comment]
Can you provide a max file for repro?

**Comment by AlexZhigin** [comment]
@
[Cream 2024.zip](https://github.com/BabylonJS/Exporters/files/14057057/Cream.2024.zip)

**Comment by FrogsInSpace** [comment]
@bghgary @AlexZhigin 
I found the reason for this: 
apparently gltf-pipline strips the two textures from the gltf. I don't really see a reason for this ( possibly some bug in gltf-pipeline ), but adding "--keepUnusedElements" to the command arguments fixes this.
As i'm currently fixing some other smaller issues too, i'll include that in an upcoming PR

BTW: 
i also created a PR for 3ds Max 2025 support, would be happy if someone would review it
see https://github.com/BabylonJS/Exporters/pull/1121

**Comment by AlexZhigin** [comment]
@FrogsInSpace @bghgary
Thanks Joseph. Actually I think the gltf pipeline is the problem too.

I've found another problem since then.
![issue](https://github.com/user-attachments/assets/80cd9b79-b7af-4ad0-bbe6-b82ffa8880bc)
https://doc.babylonjs.com/features/featuresDeepDive/Exporters/3DSMax_to_glTF

This doesn't work. When trying to combine the base color texture and the transparency weight parameter value, the texture is not exported and the log says "Texture path is missing".
This is an annoying bug for the company I work for, because contrary to the official documentation, we have to manually make color textures with an alpha channel.
I saved a simple scene to test this.
[Transparency test.zip](https://github.com/user-attachments/files/17532030/Transparency.test.zip)

**Comment by FrogsInSpace** [comment]
@AlexZhigin Thanks , i will look into this alpha problem - no guaranties though :)

**Comment by FrogsInSpace** [comment]
BTW: just for completeness, could you please create a seperate issue for the alpha weight problem , thanks

**Comment by AlexZhigin** [comment]
> BTW: just for completeness, could you please create a seperate issue for the alpha weight problem , thanks

Thanks for the quick response @FrogsInSpace. Done:
https://github.com/BabylonJS/Exporters/issues/1122#issue-2617775377

**Comment by FrogsInSpace** [comment]
argghh .. jsut created one myself -> will delete it :)
Fix is already done and working too

**Comment by AlexZhigin** [comment]
))))
