### ISSUE TITLE
3ds max 2024

### ISSUE THREAD

**Issue by Stas73rus** [BabylonJS/Exporters#1114]
Good afternoon! babylon automatically renames texture names to Image1 or Image_0.003 when exporting to glb 3ds max, can this be fixed? Exported from 3ds max with the texture ID_color (32832_color), I import the model into Blender and see the texture name as follows: Image_0.003 and so on.
![image](https://github.com/BabylonJS/Exporters/assets/25531269/0c00b60c-4bce-42b7-bd03-8f3d0b710fdd)
![image](https://github.com/BabylonJS/Exporters/assets/25531269/9bce373f-194e-44d2-b9ab-3eb12076001a)

**Comment by Stas73rus** [comment]
3ds max 2024

**Comment by thomlucc** [comment]
duplicate
