### ISSUE TITLE
Log Window not scrolling to the bottom

### ISSUE THREAD

**Issue by oo0o00oo0** [BabylonJS/Exporters#1117]
I have an error that is preventing me from exporting a model from 3DS Max, however I can not see the error as the window does not scroll all the way to the bottom. Is the log file saved/possible to output anywhere?
![Untitled](https://github.com/BabylonJS/Exporters/assets/96986564/0fcc3b2f-756a-4f5f-b138-ae6eeadaac7b)

**Comment by thomlucc** [comment]
Thanks for reaching out. We'll looking at this in July.

**Comment by oo0o00oo0** [comment]
Thanks for the reply Thom, is there a workaround in the meantime do you think? 

The error is pointing to a missing asset but without knowing what this is I cant find it to replace it!

**Comment by SergioRZMasson** [comment]
@oo0o00oo0 , which version of 3DS Max are you using?

**Comment by oo0o00oo0** [comment]
> @oo0o00oo0 , which version of 3DS Max are you using?

2023

**Comment by SergioRZMasson** [comment]
@oo0o00oo0 , we recently had a commit that should fix this issue. Can you verify it got fixed for you?
