### ISSUE TITLE
When the extension for maya 2025，2024 will be avaiable

### ISSUE THREAD

**Issue by kaihekaihe** [BabylonJS/Exporters#1127]
When the extension for maya 2025，2024 will be avaiable

**Comment by thomlucc** [comment]
Hi @kaihekaihe - The Exporters are no longer in active development by the core team (see [Forum post](https://forum.babylonjs.com/t/no-longer-actively-supporting-autodesk-exporters/35288/8 )). If you can/are interested in helping us maintain these tools for new versions of Maya, we'd GLADLY welcome the help. For instance, support Max 2024/2025 was added via a contribution: https://github.com/BabylonJS/Exporters/pull/1118
