### ISSUE TITLE
Maya Exporter doesn't work

### ISSUE THREAD

**Issue by kopacabana** [BabylonJS/Exporters#120]
Hello,
 I try to deploy Maya Exporter for Maya 2018 and 3DSMax exporter for 3DS 2017...
I've got error with these 2 plugins.

Error in Maya :
// Error: file: C:/Program Files/Autodesk/Maya2018/scripts/others/pluginWin.mel line 290: Invoking ExecuteInDefaultAppDomain() failed. // 
// Error: file: C:/Program Files/Autodesk/Maya2018/scripts/others/pluginWin.mel line 290:  (Maya2Babylon.nll) // 

Error in Max : 
System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
   at System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence)
   at System.Reflection.Assembly.LoadFile(String path)
   at Autodesk.Max.Manager.LoadAssembly(String name, Boolean startingUp)
   at Autodesk.Max.Manager.LoadAssemblies()

What's  wrong ???
I just try to keep UVWmapping fromù maya to Babylon for texture but that don't work...

Please help !!!!
Thanks
Loïc

**Comment by deltakosh** [comment]
Hello, so for 3dsmax did you make sure to follow the installation guide?
http://doc.babylonjs.com/resources/3dsmax#how-to-install-the-3ds-max-plugin

It looks like your dlls are flagged as unsecure and thus cannot be loaded.

For Maya please let me ping @noalak

**Comment by kopacabana** [comment]
Thanks a lot !!! You save my day.
I forgot to Unblock :((

It might be necessary to put an alert for this crucial part on documentation...

It's work also for Maya.

Thank you very much.
Loïcc
