### ISSUE TITLE
Question/Feature: Fix or recalculate normals during export?

### ISSUE THREAD

**Issue by tkazik** [BabylonJS/Exporters#127]
I got some models that have pretty weird normals: The models look fine in 3ds max, but once exported to gltf, their nastiness is revealed:

![dirty_normals_issue](https://user-images.githubusercontent.com/15689124/37846317-945f644e-2ecd-11e8-871d-7f39195a7efc.png)

The issue can be fixed using the reset XForm modifier. However, as the models contain animations, resetting the XForm basically means recreating the animations. This is why I am looking for a possible fix during export. I am aware, that some artist use custom normals for some effects, but in my case, I am interested in recalculating 'standard' normals from a mesh. Does this sound feasible/reasonable to you? Any hints or tips from you side?

**Comment by deltakosh** [comment]
You can always do it from bjs side: `mesh.createNormals(true)`

**Comment by tkazik** [comment]
Sweet, thanks for the quick reply!
Just tested it in the playground, but no luck so far:

http://www.babylonjs-playground.com/#WGZLGJ#31

What am I missing? Thx!

PS: Sorry, should have asked this question in the forum...

**Comment by deltakosh** [comment]
Please :)
