### ISSUE TITLE
[3dsMax][FeatureRequest] Option to recompute normals during export

### ISSUE THREAD

**Issue by tkazik** [BabylonJS/Exporters#128]
As mentioned [here](https://github.com/BabylonJS/Exporters/issues/127), I got some models with weird normals. Unfortunately, I don't have the option to recompute the normals in [Cesium](https://cesiumjs.org/). Also from a performance point of view, it would probably make sense, to recompute the normals at export stage rather than at import/loading time in babylonjs.
There is already a function to recompute the normals in the Tools section of this project, see [here](https://github.com/BabylonJS/Exporters/blob/4d80c3a80c6dcf18fed7782fc391271011133ec0/3ds%20Max/Max2Babylon/Tools/Tools.cs#L265), which is currently not used. The function looks like a translation from [this](https://help.autodesk.com/view/3DSMAX/2018/ENU/?guid=__developer_3ds_max_sdk_features_modeling_meshes_computing_vertex_normals_html) one and seems a bit buggy during the tests I have tried so far. (especially with the option 'not optimize', there is something fishy with the smoothing groups)
What do you think about it? Has anyone else tested this function?

A sample model can be found here: [recomputeNormals.zip](https://github.com/BabylonJS/Exporters/files/1848216/recomputeNormals.zip)

![recomputenormals](https://user-images.githubusercontent.com/15689124/37912493-f08fdfea-3112-11e8-95e4-fd5e420eea90.png)
left: good normals, 
right: bad normals

**Comment by deltakosh** [comment]
Is there an option in 3dsmax SDK to covert this need? I would prefer not changing data received from Max if possible and instead use a tools from Max

**Comment by tkazik** [comment]
I am not aware of an option or an existing plugin in 3ds max that does just recalculate the normals without touching anything else. Sure, I understand that an exporter is not expected to change data...maybe we could add an optional button in the GUI for that, so that it is clear. It is just too tempting to add this option, especially as a function in Tools.cs already exists. There just seems to be a bug with the smoothing groups, either [here](https://github.com/BabylonJS/Exporters/blob/4d80c3a80c6dcf18fed7782fc391271011133ec0/3ds%20Max/Max2Babylon/Tools/Tools.cs#L286) or [here](https://github.com/BabylonJS/Exporters/blob/4d80c3a80c6dcf18fed7782fc391271011133ec0/3ds%20Max/Max2Babylon/Tools/VNormal.cs#L43). I am still trying to understand how the smoothing groups work...so far I just figured out, that their value in the exporter is wrong. E.g. for a cube, I get:

- smGrp values used in 3ds Max: 2, 3, 4, 5, 6, 7
- smGrp values showing up in the exporter: 2, 4, 8, 16, 32, 64

So maybe there is a wrong declaration somewhere. This might be the reason why the bit-wise OR [here](https://github.com/BabylonJS/Exporters/blob/4d80c3a80c6dcf18fed7782fc391271011133ec0/3ds%20Max/Max2Babylon/Tools/VNormal.cs#L43) does not work as intended. Have you tried and tested this function before? Your thoughts?

**Comment by tkazik** [comment]
Closing this for now. As you say, it is not really the duty of the exporter to fix normals and it is probably easier to do in maxscript anyway. Thank you very much for you hints!

**Comment by tkazik** [comment]
Just for the sake of documentation, in case someone else wants to tackle this in the future. I noticed
 a difference between the sdk docs and the current implementation. See here:

![sdk_doc](https://user-images.githubusercontent.com/15689124/38352507-b8d50f50-38b3-11e8-8749-080cf17d86b8.png)

![code](https://user-images.githubusercontent.com/15689124/38352514-c18c3a6a-38b3-11e8-873b-6978859d9c22.png)

Cheers
