### ISSUE TITLE
Maya Exporter: Does not match the current architecture (Maya2Babylon.nll)

### ISSUE THREAD

**Issue by SlimMarten** [BabylonJS/Exporters#130]
When trying to load the Maya Exporter I get the following error in my Maya Command Line Output:

`// Error: file: /Applications/Autodesk/maya2018/Maya.app/Contents/scripts/others/pluginWin.mel line 905: does not match the current architecture (Maya2Babylon.nll)`

**Comment by noalak** [comment]
Hi,

Which system are you using Windows or Mac ?

**Comment by deltakosh** [comment]
Closing as no response so far..
Please reopen if required :)

**Comment by SlimMarten** [comment]
Sorry for not having responed yet.
I am on Mac OS High Sierra
