### ISSUE TITLE
No "texCoord" exported in the .gltf material definitions

### ISSUE THREAD

**Issue by corentinjaffre** [BabylonJS/Exporters#131]
I'm using a material which use texCoord0 for all the textures, and texCoord1 for the emissive texture.
I set it up in the physical material of my scene.

The 2 texcoords are exported by 3dsMax babylon exporter with the geometries, but there is no "texCoord": in the materials definition.
The result is that every textures are using the texCoord0 by default.

**Comment by deltakosh** [comment]
We'll look at it ASAP

**Comment by corentinjaffre** [comment]
It works. Thanks!
