### ISSUE TITLE
Export looks bad when exporting from 3ds studio max via Babylon plugin (BUG)

### ISSUE THREAD

**Issue by rodrix385** [BabylonJS/Exporters#132]
Files and screenshots are detailed on this thread by the community:
http://www.html5gamedevs.com/topic/36776-mesh-looks-strange-when-exported-from-3ds-max/

Attached files on link: .max original file, output .glb and .babylon files

Would really appreciate if you could fix this asap.
Thank you!

**Comment by tkazik** [comment]
Hi 

Could you also please provide these missing files?
![missing_files](https://user-images.githubusercontent.com/15689124/38292475-2d67bcd0-37e4-11e8-90bb-fb80bdf87ef2.png)

Without these, I get the following appearance in babylon's sandbox (lights turned off):
![piano2](https://user-images.githubusercontent.com/15689124/38292633-bf380fac-37e4-11e8-8579-69ef1c139fef.png)

**Comment by rodrix385** [comment]
Hi tzazik,
I have been doing some tests. It seems that on the sandbox the files are fine.

However, on the local server (that automatically opens on export)  and on http://editor.babylonjs.com/ is where the issues occur. Please try using the same export using glb format on both and tell me what you get.

P.S: Here are the textures: 
https://www.dropbox.com/s/i68snfqrkdq8lxn/textures.zip?dl=0

Thanks in advance!

**Comment by tkazik** [comment]
Alright, I am quite sure the model is fine. There seems to be an issue in the editor. I also tested a simple model and it looked flipped as well, see:
![flipped](https://user-images.githubusercontent.com/15689124/38328198-8c4076be-384a-11e8-8565-6708c246db89.png)
I guess this issue isn't related to the exporter, but rather to the editor. Other thoughts? @deltakosh or @noalak maybe?

**Comment by rodrix385** [comment]
Yes, I think the issue is random polygons get "flipped". I see this issue occurring both on Editor and Internal Server preview.

**Comment by deltakosh** [comment]
I think so. Do you mind closing this issue and opening a new one in the editor repo?

**Comment by rodrix385** [comment]
I find this very sad news, but even the Sandbox is failing. Try with this glb file:
https://www.dropbox.com/s/f2qbaju6y2czjgd/test.glb?dl=0

ThreeJS can handle it perfectly: https://gltf-viewer.donmccurdy.com/
Babylon Sandbox fails: http://sandbox.babylonjs.com/

This means two things:
- The file is not exporting correctly, but ThreeJs is able to correct the errors.
- The file is being corrected and there are bugs on Editor, Sandbox, and Babylon internal server script.

This puts our project on halt.

**Comment by rodrix385** [comment]
@deltakosh I don't think this issue should be closed yet on the Editor. Please check the latest file I provided. It fails everywhere on Babylon, but ThreeJs is able to render it perfectly!

**Comment by deltakosh** [comment]
Pinging @bghgary for the gltf loader issue

**Comment by bghgary** [comment]
@deltakosh The model uses a material that is marked as `BLEND` which turns on alpha blending.

It looks correct in ThreeJS because they write depth.

**Comment by bghgary** [comment]
If I manually remove the `BLEND` line from the glTF, then it looks right in the sandbox.

**Comment by deltakosh** [comment]
We can also write depth if required: http://doc.babylonjs.com/resources/transparency_and_how_meshes_are_rendered#alpha-blended-meshes

**Comment by rodrix385** [comment]
The error is consistent. I exported another glb. I see no "BLEND" inside it.
Still I get the same error on Babylon Editor. Sides are "flipped".

Please check: https://www.dropbox.com/s/ybtkxp3ia9xb5tj/test2.glb?dl=0

**Comment by rodrix385** [comment]
![image](https://user-images.githubusercontent.com/26559703/38347164-21030512-3870-11e8-8438-d16cd58489ca.png)
With the last model it renders well on Sandbox, but bad on Editor.

**Comment by deltakosh** [comment]
I think we are facing two problems. I recommend mention the editor issues on the editor repo

**Comment by rodrix385** [comment]
I created an issue on the Editor Issues repo:
https://github.com/BabylonJS/Editor/issues/53

I agree with you @deltakosh , I believe we are having two (or multiple) concurrent bugs. One here, one on the editor, to begin.

Anyone that could help?

I believe this is a critical issue. It breaks the 3ds Max Export workflow, and the gltf export workflow.

**Comment by deltakosh** [comment]
Just seen your forum message. Do you suggest that Blend should not be in the file?
Pinging @noalak  to check

**Comment by rodrix385** [comment]
My two cents: removing BLEND from the file, fixes the issue.
I believe BLEND should not be on the export.

If there is no way to tell if the model should or should not use BLEND mode, then I suggest adding a checkbox on the Babylon Exporter to enable or disable the BLEND option (and off by default).

**Comment by rodrix385** [comment]
UPDATE: This issue has been just solved on the Editor (https://github.com/BabylonJS/Editor/issues/53). The editor now has the ´need depth-pre-pass" option.

The only thing left would be to add an option to the exporter called "Blend Off": a checkbox.
If unchecked, the exporter does what it considers better and exports with blend or without it (with  best-guess). If "Blend Off" checkbox is checked, then BLEND will be overriden with "off" value, and so even if BLEND is detected as necessary it will not be included on the export. Basically, this new option will override BLEND and turn it off, if it is checked.

@deltakosh, what do you think of this fix?

**Comment by deltakosh** [comment]
Not a big fan of this one. It is far better to not use Tiff files. They are heavy and are really designed for the web. So I highly suggest using jpg files

**Comment by rodrix385** [comment]
>>Not a big fan of this one. It is far better to not use Tiff files. They are heavy and are really designed for the web. So I highly suggest using jpg file

I believe you wrote this comment in the wrong thread. There is no mention of Tiff files here...

**Comment by noalak** [comment]
Hi again rodrix385 :)

To detail what @deltakosh said, when you assign a tif file to a texture, 3ds max doesn't check Alpha Source and its default value is 'Image Alpha'.
To fix your issue you can either:
- use other image formats like @deltakosh said
- select 'None (Opaque)' for your tif textures

Also, Mix textures are not supported by the exporter. Only Bitmaps are. You will need to merge your textures with an external software.

A warning message has been added in last version of the exporter about those cases.

**Comment by rodrix385** [comment]
Thank you @noalak !
Is this what you mean:
![image](https://user-images.githubusercontent.com/26559703/38693579-b7ff54d2-3e5d-11e8-9955-112e00effe03.png)

Is that the setting to make opaque so that the exporter ignores BLEND mode?

**Comment by noalak** [comment]
Absolutely

When providing a **png** file, 3ds max checks if it actually contains any alpha value (at least 1 pixel with alpha < 255). If not, you can't set Alpha Source to Image Alpha.

As I said, for **tif** files, 3ds max does not perform this check.
