### ISSUE TITLE
3ds Max Exporter - Support Channel 2 for Textures - enhancement / bug

### ISSUE THREAD

**Issue by rodrix385** [BabylonJS/Exporters#145]
On 3ds Max, you can define the UV Map Channel to be used for every texture:
![image](https://user-images.githubusercontent.com/26559703/38593769-6971c5ce-3d19-11e8-8943-0050cb0a5b0e.png)

This parameter, is being IGNORED by the exporter.
It would be REALLY helpful to include support, at least for **diffuse roughness** slot which is usually used for AO maps (Ambient occlusion maps), which goes usually on channel 2. The importance of this is HIGH for Babylon high-end users who are creating photo-realistic scenes, which include the use of pre-baked AO maps, which are used on channel 2.

If channel 2 is detected, the gltf exporter should write:
"occlusionTexture":{"index":0,**"texCoord":1**}

...instead of:
"occlusionTexture":{"index":0}

Just adding: **"texCoord":1**.
Max is 1-indexed while Babylon is 0-indexed (so channel 2  on Max is actually channel 1 on Babylon).
You may also add the **"texCoord":X** parameter for EVERY texture. This would give universal support for UV map channels on all textures.

This simple change will be of great benefit to the community, simplifying the workflow between coders and artists; so artists can text the AO maps directly  from 3ds Studio Max using Babylon Exporter, without needing to touch any code.
![image](https://user-images.githubusercontent.com/26559703/38594016-c7255ae0-3d1a-11e8-8c8c-098ff2511b6e.png)

**Comment by deltakosh** [comment]
Sure! Fancy doing a PR?

**Comment by rodrix385** [comment]
Hi @deltakosh! Good seeing you again. PR= Pull request?

**Comment by deltakosh** [comment]
Yes sir:) this way you can have the change asap

**Comment by rodrix385** [comment]
Sorry,  I am a bit new to GIT collaboration, but I am loving this community! Let me try.. I have been browsing the source code to see if I can find where is this code...

**Comment by rodrix385** [comment]
I am testing with Channel 2:
![image](https://user-images.githubusercontent.com/26559703/38594913-246ad384-3d1f-11e8-8e0c-3b9d8f9ebc62.png)

..and still on the gltf it reads:
occlusionTexture":{"index":1}

**Comment by rodrix385** [comment]
From what I can tell the value is stored here:
https://github.com/BabylonJS/Exporters/blob/780b19574fc165137bd09ed23f920e2298845b37/3ds%20Max/Max2Babylon/Exporter/BabylonExporter.Texture.cs#L494

**Comment by noalak** [comment]
Hi rodrix385,

Issue has been fixed a short time ago in PR #140 
Update your dlls with last ones and you should be fine

**Comment by rodrix385** [comment]
Thanks! It works. :)
