### ISSUE TITLE
3ds Max - Export Shadowmap - Enhancement / Question

### ISSUE THREAD

**Issue by rodrix385** [BabylonJS/Exporters#154]
I need a way to export the *shadowmap* from 3ds Max into Babylon.

I am already using the *diffuse roughness* slot for the *tilable* occlusion map texture on channel 1 (tilable uvs), and I would like to use another slot for the *shadowmap* that uses UV channel 2 (planar uvs).

Where should I add the Shadowmap on 3ds Max so it is automatically exported on Babylon Exporter?
If this feature does not exist, and there is no way to automatically export a shadowmap from 3ds max. Could it be implemented?

Thanks so much.

**Comment by deltakosh** [comment]
Will it be for gltf or .babylon file format?

**Comment by rodrix385** [comment]
Good question @deltakosh .

Gtlf (physical materials)

**Comment by deltakosh** [comment]
Pinging @noalak

**Comment by deltakosh** [comment]
My question then will be: how to map that to glTF? Which channel?

**Comment by deltakosh** [comment]
Closing for now as we have nowhere to store it in glTF for now
