### ISSUE TITLE
[3dsMax

### ISSUE THREAD

**Issue by johanos** [BabylonJS/Exporters#167]
Hey, i've been looking into this thing, is there an easy way to use it with maxscript?

**Comment by johanos** [comment]
Hey, i've been looking into this thing, is there an easy way to use it with maxscript?

**Comment by deltakosh** [comment]
?

**Comment by WVNicolayeff** [comment]
Seems like the guy was asking was if there is a way to access Max2Babylon's export functions from Maxscript, 3ds Max's built-in scripting language. which would allow it to be used with scripted tools like other common formats.

**Comment by deltakosh** [comment]
OK thanks !
For the record, we support maxscript: http://doc.babylonjs.com/resources/3dsmax#export-with-maxscript

**Comment by johanos** [comment]
The original question didn’t make sense because I accidentally hit enter and posted like 3 words in an issue. But yeah this got resolved a couple of months ago

**Comment by WVNicolayeff** [comment]
> OK thanks !
> For the record, we support maxscript: http://doc.babylonjs.com/resources/3dsmax#export-with-maxscript

Awesome. Thanks!
