### ISSUE TITLE
[3dsMax][Feature Request] Maxscript Compatibility?

### ISSUE THREAD

**Issue by johanos** [BabylonJS/Exporters#168]
Hey is this integrated with Maxscript at all? im looking into calling it from maxscript but can't find a specific way . i know actionMan.executeAction can bring up the window, but i wanted to see if there's an object exposed to use with it

**Comment by deltakosh** [comment]
Hello 
Unfortunately the exporter function cannot be reached from ma script.
But that could be a good idea for a future release

**Comment by noalak** [comment]
Hi johanos,

Here is the first version of the maxscript compatibily.
You can export the scene by setting an output path. Each parameter may be customized at will.

Have a look at this MAXScript using the attached dlls and give me your feedbacks.
[MAXScript_Max2Babylon_v1.zip](https://github.com/BabylonJS/Exporters/files/2009290/MAXScript_Max2Babylon_v1.zip)

Printed messages are errors, warnings and core messages. Shouldn't flood at all. Do you want more ? Less ? Customizable log level ?
Any additionnal feature ?

Things to do:
- more checks to output path to ensure validity
