### ISSUE TITLE
[3dsMax] Exporting Mesh with Diffuse Roughness Map turns off writing to the depth buffer

### ISSUE THREAD

**Issue by johanos** [BabylonJS/Exporters#169]
Hello, 

i found that if I set up the materials like so 

![image](https://user-images.githubusercontent.com/6535806/39381547-7f037f3a-4a30-11e8-964a-ad09c90a94fb.png)

the diffuse roughness map is taken in as the AO map but then the exported gltf doesn't write to the depth buffer, it might not be the diffuse roughness map on its own. but its where i see the issue

so it looks like this 

![image](https://user-images.githubusercontent.com/6535806/39382439-7a3e53b4-4a33-11e8-8e09-e6d5fe20ea17.png)

when it should look like this 

![image](https://user-images.githubusercontent.com/6535806/39382454-8d174b94-4a33-11e8-8a79-3c64c9417629.png)

i can fix it by selecting needDepthPrePass but i'd like to have this be taken care of at the export step 

Edit: investigating more, if i set the alpha source property to RGB intensity for my non transparent objects it will export correctly.  let me know if you'd like a version of the file i'm using as well

**Comment by deltakosh** [comment]
This is the expected behavior. As you are using a PNG file the exporter will flag the mesh as transparent. If you want to avoid it, just do exactly what you did :)
