### ISSUE TITLE
Export ambient occlusion in R channel of Metallic texture

### ISSUE THREAD

**Issue by deltakosh** [BabylonJS/Exporters#17]

**Comment by deltakosh** [comment]
http://www.html5gamedevs.com/topic/33790-3ds-max-getting-ambient-occlusion-into-gltf-export/

**Comment by noalak** [comment]
gltf format supports AO through the "occlusionTexture" attribute of a material. Seems better than R channel of MetallicRoughness.

**Comment by deltakosh** [comment]
This is another option. Question is: where can we get this data in 3dsmax ?

**Comment by emackey** [comment]
@noalak I'm late to this party, but, over in glTF land [it was decided](https://github.com/KhronosGroup/glTF/issues/857#issuecomment-290530762) that the occlusion texture is only ever sampled from its R channel, ignoring G and B, and the metalRough texture is only ever sampled from the G and B channels, ignoring R.  Thus, you can keep the textures separate (typically for spec/gloss), or, you can save a bit of space/bandwidth by combining occlusion-roughness-metal into a single image, and using the same image for both occlusion and metalRough in the glTF.  Typically this is done by referencing the same texture index number from two places in the material.

So, you're not doing anything wrong by keeping them separate, but you do have the option to combine the two in glTF.
