### ISSUE TITLE
Nested multimaterials cause an exception

### ISSUE THREAD

**Issue by Selmar** [BabylonJS/Exporters#175]
If you put a multimaterial in a multimaterial, an exception is thrown:

![image](https://user-images.githubusercontent.com/3010534/39633894-96e4a5fa-4fb9-11e8-8bb5-14b3c21a93ee.png)

**Comment by deltakosh** [comment]
Can you provide a repro scene?

**Comment by Selmar** [comment]
Upon closer inspection, it seems to happen when a multi-material references itself. That's a silly mistake to make...


[multiMatException.zip](https://github.com/BabylonJS/Exporters/files/1974866/multiMatException.zip)

**Comment by deltakosh** [comment]
Ok so this is mostly an user error ;)
