### ISSUE TITLE
Add support for instances in Maya

### ISSUE THREAD

**Issue by FrozenBrain** [BabylonJS/Exporters#178]
Currently multiple instances of the same object (Edit -> Duplicate Special -> Geometry Type: Instance) are exported as two separate meshes even though BabylonJS supports mesh instances.
It would be beneficial for performance and file size if the exporter would make use of this functionality.

More information:
[BabylonJS: How to use Instances](https://doc.babylonjs.com/how_to/how_to_use_instances)
[BabylonJS: Instances in .babylon-files (referenced in Meshes)](https://doc.babylonjs.com/resources/file_format_map_(.babylon)#instances)
[Maya: Copies vs. Instances](https://knowledge.autodesk.com/support/maya/learn-explore/caas/CloudHelp/cloudhelp/2016/ENU/Maya/files/GUID-2851AE11-C3EF-4AE1-B7C5-8773E2068BB9-htm.html)
[Maya: Duplicate](https://knowledge.autodesk.com/support/maya/learn-explore/caas/CloudHelp/cloudhelp/2016/ENU/Maya/files/GUID-579BED6D-6DE4-4074-BCC8-2A8E813B8AE4-htm.html)

**Comment by deltakosh** [comment]
Excellent point. Will add support for it
