### ISSUE TITLE
Exportation cancelled when using the Stingray PBS shader.

### ISSUE THREAD

**Issue by jdswiney** [BabylonJS/Exporters#182]
![babylontest](https://user-images.githubusercontent.com/39228827/39963095-d5b04e82-5627-11e8-9fdb-cd60cbce7e25.jpg)

**Comment by noalak** [comment]
Hi jdswiney, could you share the scene to reproduce the bug ?

**Comment by jdswiney** [comment]
It happens in any scene that I use the Stingray PBS shader. Here is a very basic example scene.

[testscene.zip](https://github.com/BabylonJS/Exporters/files/2000887/testscene.zip)
