### ISSUE TITLE
[max][gltf] non-uniform scales result in distorted normals

### ISSUE THREAD

**Issue by tkazik** [BabylonJS/Exporters#194]
How to reproduce:
Create an object, scale it with different scales along the three axis (node scales). The exported gltf seems to have distorted normals compared to the same object that has uniform scales (with resetX), see:

![appearance_babylon](https://user-images.githubusercontent.com/15689124/40514279-d9d20368-5fa8-11e8-9d10-a73b77b87336.png)

I suspect that we are missing something during the export...some sort of scaling of the normals is missing. Here you see the normals in max:

![non-uniform_scales](https://user-images.githubusercontent.com/15689124/40514271-d730d4ae-5fa8-11e8-8460-634ace62b0d3.png)

Here is the sample model including the glb:
[nonUniformScales.zip](https://github.com/BabylonJS/Exporters/files/2037143/nonUniformScales.zip)

Any ideas? Thx!

**Comment by deltakosh** [comment]
Can you try to bake transforms into vertices before exporting?

**Comment by deltakosh** [comment]
OK makes sense
I'll have a look asap

**Comment by deltakosh** [comment]
Ok it will be fixed by next commit
Now you can do this:
```
mesh.ignoreNonUniformScaling = true;
```

@noalak: Do you mind exporting all 3dsmax meshes (in Babylon.js) with this option set to on?

**Comment by tkazik** [comment]
Puh, you were quick! 
Just to double-check: You fixed it in the framework, right?
My gut feeling tells me, that there might be something fishy with the exporter, as also three.js displays the model incorrectly. So either, the normals are messed up during export or three.js needs the same fix...what do you think?

**Comment by deltakosh** [comment]
It is a framework fix and yeah three will probably need some way to disable non uniform scaling process for normals

**Comment by tkazik** [comment]
@noalak: Do you see an option to adapt the normals in the exporter? This would be an alternative...instead of adapting all loaders. Or what do you think?

**Comment by Selmar** [comment]
The normals are currently retrieved in world space. I remember there was a problem retrieving this information in local space, I do not remember why...
`Normal = mesh.GetNormal((int)face.Norm[facePart], false)`

After that, they are transformed into local space and normalized:
`vertex.Normal = invertedWorldMatrix.VectorTransform(vertex.Normal).Normalize;`

Checking the output, everything seems to be okay actually. Here's a snippet from the raw data:

```
one mesh:
   -0.01375     0.99953    -0.02750 
   -0.01009     0.98884    -0.14863 
   -0.03877     0.99018    -0.13430 
   -0.01375     0.99953    -0.02750 
   -0.03877     0.99018    -0.13430 

other mesh:
   -0.01278     0.99947     0.03001 
   -0.03774     0.98844     0.14685 
   -0.01089     0.98722     0.15896 
   -0.01278     0.99947     0.03001 
   -0.07359     0.99287     0.09379 
```

I can also verify that our engine does render it correctly, so it's really just a client-side issue and not an exporter issue.

**Comment by deltakosh** [comment]
Oh so we just need to retrieve them in local and we are good..
Excellent!

**Comment by Selmar** [comment]
I think the exporter is already exporting normals properly since #105. I believe they just have to be normalized in the client after the scaling is applied.

**Comment by deltakosh** [comment]
Not sure to follow you. We have the bug in the sandbox if I do not turn off uniform scaling support

**Comment by Selmar** [comment]
Yes, and I believe that is due to a bug in the sandbox dealing with scale and not in the exporter.

**Comment by deltakosh** [comment]
I don't think so as the sandbox is a doing nothing but landing the gltf and display it. 
I think that either the normalize is wrong in the exporter or there is something else. Even three.js has the same issue which leads me to think this is an exporter prob

**Comment by noalak** [comment]
Currently, normals are retrieved in world space then converted to local space.
We have done that to fix normals when rotating (#102).

Making a PR to fix issue with scaling.

**Comment by deltakosh** [comment]
Can we get them directly in local space?

**Comment by noalak** [comment]
In object space at best

**Comment by deltakosh** [comment]
Which is local space no?

**Comment by noalak** [comment]
3ds Max differenciates world, object and local transformation matrices.
Object is taking pivot into account and local do not, or vice versa.

**Comment by noalak** [comment]
@deltakosh mesh.ignoreNonUniformScaling = true seems like doing nothing in Babylon and does weird things in glTF.

**Comment by deltakosh** [comment]
Seems ok here: https://www.babylonjs-playground.com/#PN1NNI#5

**Comment by deltakosh** [comment]
Just pushed an additional check just in case

**Comment by noalak** [comment]
Here is the result with fixed version:

![2018-05-28 19_26_16-babylonjs - test](https://user-images.githubusercontent.com/20560340/40624504-64620d96-62ad-11e8-91e2-ab26674de135.jpg)

The mesh in the middle is now the exact same as the one on the left.

Meaning:
- scaled normals and scaled node at export (middle)
- unscaled normals and unscaled node at export, then mesh scaled in engine (left)

are the same.

Moreover, triangles are visible on both middle and left models. Model on the right is all right.

**Comment by noalak** [comment]
In glTF:

![2018-05-28 19_40_10-babylonjs - test](https://user-images.githubusercontent.com/20560340/40624811-0513218e-62af-11e8-9359-b58387505a82.jpg)

**Comment by deltakosh** [comment]
Excellent!

**Comment by noalak** [comment]
@tkazik Is it ok for you?

**Comment by tkazik** [comment]
@noalak Perfect, exactly what I was hoping for! Thank you very much for the quick and excellent work!

Closing the issue :)
