### ISSUE TITLE
Giving error while exporting in Maya 2016

### ISSUE THREAD

**Issue by rsrechetu** [BabylonJS/Exporters#195]
Hi,

This plugin is not working in Maya 2016 and giving error while exporting to *.babylon file format. Can you please suggest if there is any other version for Maya 2016 or any patch or something to fix the error?

Thank you

**Comment by deltakosh** [comment]
I think you have to use the latest (2018)

**Comment by noalak** [comment]
Yes the plug-in is designed for Maya 2018
