### ISSUE TITLE
Blender: No export options

### ISSUE THREAD

**Issue by tristan-shelton** [BabylonJS/Exporters#198]
In both Blender 2.79 and 2.8 preview I'm noticing that the Blender exporter doesn't show any export options at all. It seems to be a bug or omission in the official exporter which while great to have seems pretty limited.

I patched the exporter to serve my own purposes for the moment, but I'm curious if there's any interest in pull requests for the exporter? I'm no Python expert but I think I could improve what's currently available, at least a little bit.

**Comment by deltakosh** [comment]
Pinging @palmer_jc

**Comment by deltakosh** [comment]
But anyway all PRs are welcome obviously

**Comment by tristan-shelton** [comment]
Great! I'll patch up what I changed and put in a small initial PR. :smile:

**Comment by Vinc3r** [comment]
JCPalmer commit new version with this [commit](https://github.com/BabylonJS/Exporters/commit/4da6f638e4a02d423910ab964a4cde3609983e8e), I think this issue can be closed isn'it?
