### ISSUE TITLE
Animation export | Feature request

### ISSUE THREAD

**Issue by Gil-1** [BabylonJS/Exporters#203]
Hello,

I would love to be able to only export the animation of the selected element.
That way, it's easy to work on different animation and get them back easily in Babylon.

I hope it's easy to implement.

Regards :)

**Comment by noalak** [comment]
Hi Gil-1,

I guess it's using 3ds Max exporter ?

Have you tried the "Export only selected" [option ](https://doc.babylonjs.com/resources/3dsmax#the-exporter-window)?

**Comment by Gil-1** [comment]
Yes but then I get the mesh and the animation. The idea would be to get only a file with the animation keys.

**Comment by deltakosh** [comment]
This is a good idea

**Comment by noalak** [comment]
Is the [animation group](https://github.com/BabylonJS/Exporters/issues/7) system something you would like ?

In a nutshell, setup in 3ds Max animation ranges of frames like [0, 30] "Run", [31, 50] "Jump"...

**Comment by Gil-1** [comment]
Yes and no. That's a good idea but here the purpose here is to re export only the needed part.

It's easier for me to remember to just export "animation run" than to have to remember that this file have run, walk, jump....  I think when a team is working on a project it's easier to manage also. But that's a personnal preference.

**Comment by deltakosh** [comment]
We now have animation group and we can only export a selected mesh. It will export mesh + animations
We do not plan to only export animations for now
