### ISSUE TITLE
[Max] Exceptions while debugging

### ISSUE THREAD

**Issue by Selmar** [BabylonJS/Exporters#206]
Hey, there's quite a number of exceptions when debugging. They originate from here, where parentNode is null. The callstack shows almost all come from `BabylonExporter.ExportMesh()`

![image](https://user-images.githubusercontent.com/3010534/40713729-f331de9e-6400-11e8-8944-612275221764.png)

I've encountered this with our custom material exporter as well, when you give the wrong rank to RaiseMessage. The result is that the messages are shown on the lowest rank, which is ok behaviour I think, because otherwise they'd be hard to find. It would be nice if there was no exception when debugging if this mistake is made.

**Comment by deltakosh** [comment]
Yes this is an easy fix. @Selmar fancy doing the PR?

**Comment by Selmar** [comment]
Sure. Perhaps we want to show an exception message in the tree view when this happens? These are bugs in the exporter, after all, just "hidden" because they come from a different thread.

**Comment by Selmar** [comment]
For example, the recent modifications from the worldmodifier also trigger this exception.

**Comment by deltakosh** [comment]
I would just fix it by letting it display as lowest rank (and add a warning for us to know)
