### ISSUE TITLE
[Max] Skeleton exportation

### ISSUE THREAD

**Issue by Selmar** [BabylonJS/Exporters#207]
There is an error message here, in BabylonExporter.Skeleton, which could use more information (which skin, which "root nodes"). Also, I believe the convention so far was not to throw exceptions but only error messages and then cancel or continue exportation?

However, from my point of view, it should be fine if two nodes or on the scene root; this means the scene becomes the skeleton root, which is legal in glTF (see the skin section [here](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#skin)). I'm not sure how the babylon format deals with this?

  | Type | Description
-- | -- | --
skeleton | integer | The index of the node used as a skeleton root. When undefined, joints transforms resolve to scene root.

```C#

List<IIGameNode> rootNodes = revelantNodes.FindAll(node => node.NodeParent == null);
if (rootNodes.Count > 1)
{
    RaiseError("More than one root node for the skin!");
    throw new Exception("More than one root node for the skin!");
}
```

**Comment by deltakosh** [comment]
Ok for adding more info to the message but I prefer we keep the one rootnode constraint for now as BJS file format does not support more than 1
