### ISSUE TITLE
3DS Max Issue Exporting Double Sided Materials 

### ISSUE THREAD

**Issue by mattWayfair** [BabylonJS/Exporters#209]
When exporting a scene where an object has a doubled side material in gltf or glb format nothing shows up in the BabylonJs sandbox but the message #/meshes/4: Primitives are missing. 
![2018_06_01_11_59_10_greenshot](https://user-images.githubusercontent.com/39838142/40855640-0c57a81a-65a3-11e8-9597-16d80ba07762.jpg)

If exported in Babylon format the objects that have doubled sided materials don't show up in the sandbox but all the other objects do.

**Comment by deltakosh** [comment]
Hello thank you for your report
The team will work on it asap (probably Monday :))

**Comment by noalak** [comment]
Hi mattWayfair,

I can't reproduce the bug, can you provide a repro scene ?

**Comment by mattWayfair** [comment]
In Max create a standard sphere or plane.   Select it open the Slate Material Editor, create a double sided material.   Select the material and hit the "Assign Material to Selection."  Save. In the Babylon exporter select Export or Export and Run.  The sphere will not show up in the sandbox viewer.

**Comment by mattWayfair** [comment]
I am using the Scanline Renderer.

**Comment by mattWayfair** [comment]
[bugTest.zip](https://github.com/BabylonJS/Exporters/files/2068531/bugTest.zip)

Here is my scene with the test case.  When you export the scene you will see the errors with the plane as it has a doubled sided material attached.  But the sphere in the scene is fine. It has no material attached at all.

**Comment by noalak** [comment]
Okay! I missunderstood what you are talking about when saying the double sided material.

Currently, only the "2-Sided" **option** (checkbox) in a standard material is handled.
![standard_mat](https://user-images.githubusercontent.com/20560340/40921960-2ea5abf4-6811-11e8-8364-a7f149ba318b.png)

The true "Double sided" material is not meant to be exported.
![twosided_mat](https://user-images.githubusercontent.com/20560340/40922013-4f45f1ca-6811-11e8-8544-0fea9afa6ae9.png)

Meshes with such material have their geometry not exported which is defintely a bug.
I will fix that first and then see what we can do for double sided materials.

**Comment by noalak** [comment]
Double sided material has no equivalent in Babylon and glTF formats, thus it can't be exported as such.

@deltakosh
Currently, a Double Sided material is considered by the exporter as a MultiMaterial, but there is no sense to split a mesh into sub meshes and the export is failing.

Here are the options:
- raise a warning and convert the Double Sided material into a MultiMaterial with 2 sub materials where meshes are using only the first one (only one sub mesh)
- raise a warning and convert the Double Sided material into a SingleMaterial (Facing one)
- raise an error and don't export this material (as #45 )

Which do you prefer?

**Comment by deltakosh** [comment]
Are you sure double sided is not part of gltf? @bghgary

**Comment by noalak** [comment]
Just to be crystal clear,
When saying double sided = invert of back-face culling, babylon and glTF does have an equivalent.
When saying double sided material = material face + material back, they don't.

**Comment by deltakosh** [comment]
Yep I agree. In this case we should raise an error and do not export as this is not supported

**Comment by bghgary** [comment]
Just to be super clear, double sided in glTF means two things:
* back-face culling is off
* two-sided lighting is on

https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#double-sided

**Comment by noalak** [comment]
Same as #45
