### ISSUE TITLE
render error？

### ISSUE THREAD

**Issue by sonygod** [BabylonJS/Exporters#21]
![image](https://user-images.githubusercontent.com/748320/32402316-083f3342-c15c-11e7-91c2-69125a972877.png)

unity 2017.2
exporter unity new version
babylon.js 3.x  2017-11-4

viewer: 
![image](https://user-images.githubusercontent.com/748320/32402327-52a26b3e-c15c-11e7-8857-bc3856e05de6.png)

**Comment by deltakosh** [comment]
Did you try using sandbox.babylonjs.com?
Ping @mackeyk24

**Comment by sonygod** [comment]
@deltakosh 
 how to upload texture at sandbox.bab......com?
![image](https://user-images.githubusercontent.com/748320/32402850-9604a120-c167-11e7-9127-5597115f0799.png)

**Comment by MackeyK24** [comment]
I dont know what are showing me... is this a toolkit made scene

**Comment by MackeyK24** [comment]
Ok i see... your trying to use an external raw .babylon file... so you got
no kind of code driving things... other than what that vscode viewer
provides... if you are using the new toolkit... just hit the play button at
top if screen ir hit build and preview button using the actual toolkit...
thats what its made for... a complete game IDE for Babylon... if you dont
want any of my toolkit features that use Metadata... then Uncheck the
export metadata check box and Dont use ANY toolkit features... just raw
geometry with Standard Shaders

**Comment by MackeyK24** [comment]
Also... Just try open Sandbox... Drag the scene file with all the .png or .jpg texture file to the sandbox... With or without metadata it should at least render your initial scene... wont run any code, but should at least render.

I can take any Babylon Toolkit scene file (with it textures) and simply drag and drop onto the sandbox... So try that and see what happens... Otherwise... Email me the scene and i will take at look at it :)

MackeyK24@gmail.com

I dont mind my email going public for anybody BabylonJS related... 
Heck if you got some help info about ANYTHING toolkit related... By all means...Hit me up :)

**Comment by sonygod** [comment]
thank you for reply ,I just use new toolkit with default set  and with standard shader export 
never  change  the setting value of  toolkit

**Comment by sonygod** [comment]
hi,@MackeyK24 
here is my source package
https://github.com/sonygod/unityAssets/blob/master/Assets/testmodel.unitypackage

**Comment by MackeyK24** [comment]
Ok... First thing... Lets move this to the forums... Let other folks not tuned into this PR get some benefit from the info. Please post your original problem (with snapshots) to this forum:

http://www.html5gamedevs.com/topic/33802-babylonjs-toolkit-problems/

**Comment by MackeyK24** [comment]
Ok i looked at your scene... First thing you are NOT using Standard Unity Shaders... You are using all kind of 3rd party unity shaders with cgincludes... You gotta remember THIS IS NOT UNITY GAME. We are exporting as much unity info to babylon entities.

So ANY material that is NOT using the unity PBR "Standard" and "Standard (specular setup)"  WILL GET EXPORTED AS A STANDARD MATERIAL... Most likly only exporting the primary diffuse texture and bump map... All those other 3rd party textures on that that third part material... Like you got some metallic gloss map texture... whell that will never get used unless it is on a standard UNITY PBR material or a custom material you setup (which your in charge of using and assigning textures to shader binds)

Anyways here is a shot using toolkit and your 3rd party shaders (exported as a Standard Material)

![screen shot 2017-11-04 at 12 08 21 am](https://user-images.githubusercontent.com/5013415/32404545-3b06f402-c0f5-11e7-9537-e88553b6ace7.png)

**Comment by MackeyK24** [comment]
And with STANDARD PBR material... Throws out any extra textures NOT a PBR named texture

![screen shot 2017-11-04 at 12 18 46 am](https://user-images.githubusercontent.com/5013415/32404568-db32b4d4-c0f5-11e7-96a0-325814ab8a60.png)

**Comment by sonygod** [comment]
I'm sorry ,I link wrong url

here is the desk for test
https://github.com/sonygod/unityAssets/blob/master/Assets/fuqlbaach0055.unitypackage

**Comment by sonygod** [comment]
this originally  shader use uv2 for OCC. but standard pbr shader have no uv2,only uv1.

**Comment by MackeyK24** [comment]
The only thing i can suggest is a custom shader then... Take a look at the Amiga Shader i made in the Material Library content package.

https://github.com/BabylonJS/Exporters/tree/master/Unity%205/EditorToolkit/Content

That way you have total control over the shader code and the shader material you use to bind whatever you want info the shader
