### ISSUE TITLE
[max][gltf] non-uniform objectoffsetscales result in distorted normals

### ISSUE THREAD

**Issue by tkazik** [BabylonJS/Exporters#214]
Very similar to https://github.com/BabylonJS/Exporters/issues/194 .

The above (solved) was for the node scales, this issue is for the object-offset-scales. For background info see:

http://help.autodesk.com/view/3DSMAX/2018/ENU/?guid=__files_GUID_3B001F21_8FE9_4663_A972_E648682A0ACD_htm
http://help.autodesk.com/view/3DSMAX/2018/ENU/?guid=__files_GUID_C17D0E4B_C408_426B_B300_7E23A0D98515_htm

Or in maxscript, type:

`$.scale` vs. `$.objectoffsetscale`

Sample screenshot of the glb-model:
![fixobjoffsetscales](https://user-images.githubusercontent.com/15689124/40943686-5ba80a52-6852-11e8-960f-820af6d3921b.png)

The model: [nonUniformObjectoffsetscales.zip](https://github.com/BabylonJS/Exporters/files/2070098/nonUniformObjectoffsetscales.zip)

Thx a lot!

**Comment by noalak** [comment]
Hi tkazik,

Thanks for reporting another issue. Looks like you are already well informed!
You've contribute to the project before, maybe you can keep up the good work now :) ?

Vertex normals are retreived from 3ds max in the 'CreateGlobalVertex' function of the BabylonExporter.Mesh.cs file.

**Comment by tkazik** [comment]
Sure, I can have a look...just thought you might be way quicker, as you probably have a much better understanding of both 3ds max and the c#-code.
Will keep you updated.

**Comment by deltakosh** [comment]
Any news?

**Comment by tkazik** [comment]
Still working/digging on it...time is a bit sparse at the moment :)
The interesting scales of the offset transform are hidden under the following:

`meshNode.MaxNode.ObjOffsetScale.S`

So I just need to figure out, how to apply them properly. Hope to be able to create a PR soon.
