### ISSUE TITLE
3DS Max exporter bug

### ISSUE THREAD

**Issue by RemusMar** [BabylonJS/Exporters#234]
First of all, congrats to @deltakosh and other valuable contibutors for the entire work.
Well done!

Now back to the problem ...
Folks, did you ever export from 3DS Max 2016 to GLTF (or Babylon) a skinned mesh with standard material (Diffuse + Specular + Normal) ?
I ask because the exported materials are a complete mess.
SEA3D (Phong - perfect): http://necromanthus.com/Test/html5/Lara.html 
GLTF (that PBR crap): http://necromanthus.com/Test/html5/Lara_gltf.html 

Why do you process the Diffuse + Specular textures (and the result is so terrible) ?

All you have to do is to set:
```javascript
	map: mat1.map,
	metalnessMap: mat1.specularMap,
	normalMap: mat1.normalMap,
```
and the result will be close to perfect.

Example: http://necromanthus.com/Test/html5/Lara_mirror.html 
Click on the stage to switch between Phong and Standard (PBR).
Almost the same results.

Please fix the exporter.

cheers

**Comment by deltakosh** [comment]
Hello!
First I would like to keep the tone  of discussions polite and respectful, so please keep your anger for you.

Then did you try with sandbox.babylonjs.com to make sure it is not a three.js issue?

pinging @bghgary as he wrote the formula to move from standard to PBR

**Comment by RemusMar** [comment]
> Then did you try with sandbox.babylonjs.com to make sure it is not a three.js issue?

I don't need to try with BabylonJS or ThreeJS.
I see the messed up JPG exported textures.

**Comment by RemusMar** [comment]
> pinging @bghgary as he wrote the formula to move from standard to PBR

You don't need any formula.
Please read again my posted message and check out the working link.

**Comment by deltakosh** [comment]
I read it. Already

**Comment by deltakosh** [comment]
Will wait for @noalak to comment on why the textures are updated. If this is a bug we will fix it obviously.

**Comment by RemusMar** [comment]
> I read it. Already

Glad to hear.
I'm here to help YOU (getting better results).
And I'm not angry at all ... LOL

**Comment by deltakosh** [comment]
Sure..thanks for your invaluable help

**Comment by RemusMar** [comment]
> Sure..thanks for your invaluable help

Anytime dear, anytime.
p.s.
You are sarcastic (but I like that).

**Comment by bghgary** [comment]
@RemusMar 
> You don't need any formula.

glTF does not support Phong materials, so there has to be some conversion. What are you expecting when you say this?

**Comment by RemusMar** [comment]
> glTF does not support Phong materials

Did I say that?
You don't need to convert anything.
I gave you the solution and the working link in the first posted message.
cheers

**Comment by RemusMar** [comment]
When the source material is PHONG, don't process anything!
Just set "metalnessMap: = specularMap".
That's all and nothing more.

**Comment by RemusMar** [comment]
@bghgary 

To make you understand better why the result is messed up:

Original Diffuse and Specular maps:
![diffuse_specular](https://user-images.githubusercontent.com/11772787/41736384-f754be9c-7594-11e8-880d-9a44f0260c44.jpg)

Exported baseColor and metallicRoughness maps:
![basecolor_metallicroughness](https://user-images.githubusercontent.com/11772787/41736413-0d99a564-7595-11e8-9ce1-9ee80d1c2028.jpg)

So don't convert anything (because you don't do it properly).
Just RENAME the original maps:

Diffuse ---> baseColor
Specular ---> metallicRoughness

And the result will be close to perfect:
http://necromanthus.com/Test/html5/Lara_mirror.html 
Click on the stage to switch between Phong and Standard (PBR).

**Comment by deltakosh** [comment]
> because you don't do it properly
Stop doing that or I will close the entire issue.

I told you it could be a bug, we will check

**Comment by RemusMar** [comment]
> Stop doing that or I will close the entire issue.

Feel free to close it.
You are too smart and you don't need help, isn't it?

> I told you it could be a bug, we will check

The bug is OBVIOUS !

**Comment by RemusMar** [comment]
> I told you we will fix it

Very friendly people around here.
And with a great sense of humor!

**Comment by bghgary** [comment]
@RemusMar 
> Diffuse ---> baseColor
> Specular ---> metallicRoughness

You cannot just map these directly since PBR metallic roughness workflow is not the same as Phong.

**Comment by bghgary** [comment]
Here is what the model looks like in the sandbox: 
![image](https://user-images.githubusercontent.com/19158740/41737565-84bec51c-7544-11e8-9a26-d73f4c5661fb.png)

**Comment by deltakosh** [comment]
The fact the metal map is green means it is full rough so this expected 
And when we render your glb in Babylon.js it looks good

**Comment by RemusMar** [comment]
> Here is what the model looks like in the sandbox:

It doesn't look right.
Again: your PBR implementation is not good.
This is how this model should look:
![lara](https://user-images.githubusercontent.com/11772787/41761930-ae21d4e0-7601-11e8-9880-5d3b14b459a5.jpg)

For the last time:
LET THE TEXTURES UNTOUCHED !!
GLTF is a container and nothing more.
Many people want to use their own shaders (faster & better than PBR).
And to do that they need the original textures.
On top of that, let the users to tune up the textures as they want.
Don't mess them up with the 3DS Max exporter !

**Comment by RemusMar** [comment]
> The fact the metal map is green means it is full rough so this expected
> And when we render your glb in Babylon.js it looks good

You are wrong dear (and invalid).

**Comment by RemusMar** [comment]
And here is the best workflow for your 3DS Max exporter when exporting PBR (from PHONG):

1) LET THE TEXTURES UNTOUCHED !!

2) use the following settings:
baseColor = DiffuseMap
metalness = 0.5
metalnessMap = specularMap
roughness = 1.0
roughnessMap =.specularMap
normalMap = normalMap

And here is the (updated) working sample:
http://necromanthus.com/Test/html5/Lara_mirror.html
Click on the stage to switch between Phong and PBR.

cheers

**Comment by deltakosh** [comment]
Well if you want to use your own shader nothing prevent you from exporting to gltf and use your own texture.
Gltf 2.0 spec is based on PBR so we should cover with PBR in mind.

**Comment by RemusMar** [comment]
> Well if you want to use your own shader nothing prevent you from exporting to gltf and use your own texture.

You still don't get it, isn't it?
For the last time:
WHY DO YOU MESS UP THE TEXTURES?
Why do you put those WHITE areas in the Diffuse (baseColor) texture and remove details from the original texture.
OMG ... you guys are really hopeless.

**Comment by bghgary** [comment]
_Disclaimer: I am a member of the 3d formats working under Khronos and I work on the spec._

> GLTF is a container and nothing more.

See https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#materials. glTF uses the PBR metallic/roughness material model.

The textures are being converted because of this.

**Comment by RemusMar** [comment]
> The textures are being converted because of this.

If you don't know how to do it properly (and you mess up the diffuse texture), LET THEM UNTOUCHED !

**Comment by RemusMar** [comment]
> Disclaimer: I am a member of the 3d formats working under Khronos and I work on the spec.

I see the quality of your work in the Babylon sandbox:
- the eyes and the lips are messed up (she looks like a zombie).
- the bra and the bikini are messed up (wrong color and no specularity (metalness) at all.

**Comment by RemusMar** [comment]
This is the expected quality from your GLTF exporters:
http://necromanthus.com/Test/html5/Lara_PBR.html 
very important note: THE TEXTURES ARE UNTOUCHED.

Fix your exporters!
(this was my last message posted here)

**Comment by bghgary** [comment]
There isn't a "correct" way to convert since there is not a good way to determine how metallic something is from the Phong material. If for your specific case, it happens to look good by taking the diffuse texture as the base color texture, that's possible, but it doesn't work in general. Base color texture is a combination of BRDF diffuse and specular depending on the "metalness" of the material. This [reflectivity section in this article](https://marmoset.co/posts/physically-based-rendering-and-you-can-too/#refl) talks about how this works, though this article uses the term albedo for base color. glTF expects a PBR metallic roughness material model with a base color texture and a metallic roughness texture where the green channel is for roughness and blue channel is for metalness. Assigning Phong's diffuse and specular maps directly into baseColorTexture and metallicRoughnessTexture for your specific case might look okay, but it isn't technically correct and won't work in general.
