### ISSUE TITLE
Mesh/Armature are automatically move after the export.

### ISSUE THREAD

**Issue by anemol** [BabylonJS/Exporters#235]
With: Blender 2.79b (Linux) /  Babylon exporter  5.6.3

My meshs and armatures are automatically moved right after exporting them.

Before:
![spectacle j22483](https://user-images.githubusercontent.com/10926763/41772403-cf61d4cc-7618-11e8-9d68-12c8b7fe3f38.png)

And now, just after the export:
![spectacle m22568](https://user-images.githubusercontent.com/10926763/41772410-d4cf55ce-7618-11e8-9226-d574fcb093cc.png)

I have to do a CTRL-Z to replace correctly my scene.

Is it a bug or is it necessary to have a setting to avoid this?

**Comment by deltakosh** [comment]
Pinging @Palmer-JC

**Comment by anemol** [comment]
I think i resolved my problem. The problem is that my mesh hadn't, in *Object Mode* the scale to 1 and the rotation to 0.

**Comment by deltakosh** [comment]
Good news

**Comment by Nodragem** [comment]
hohoho! I solved my issue after being inspired by your solution.
In my case it was the _Armature_'s location in _Object Mode_ that I needed to apply (so it becomes [0,0,0]).
