### ISSUE TITLE
Add tags export per node in 3dsmax

### ISSUE THREAD

**Issue by deltakosh** [BabylonJS/Exporters#244]
https://github.com/BabylonJS/Babylon.js/issues/4618

**Comment by Remi-Tribia** [comment]
Hi,
I installed the latest exporter (1.2.18) and I thought tags would be added in the node's "extras" property in the gltf file, but can't find it. Did I do something wrong?

 - Right click on object in max and open Babylon properties
 - Write something in tag textbox
 - Export to gltf

I can't find any reference to what I typed in max in the gltf file. Maybe that's not the intended use, in this case would it be possible to add what's inside the tag textbox inside an "extras" property in the corresponding node ?

Cheers!

**Comment by deltakosh** [comment]
Tags where only in Babylon files but you are right this is an excellent idea.

**Comment by Remi-Tribia** [comment]
Great! I'll have use for it ^^
While I'm at it, would it be possible to pass object (or json) like `{ key1:value, key2:value, etc. }` ?

**Comment by deltakosh** [comment]
Tags are strings so yes:)

**Comment by Jaskar** [comment]
@deltakosh , @Remi-Tribia ,
Is this ok for you ? :)

**Comment by Remi-Tribia** [comment]
I tried it yesterday, it works perfectly!
