### ISSUE TITLE
downloader/installer for the exporter

### ISSUE THREAD

**Issue by gabrieljbaker** [BabylonJS/Exporters#245]
It would be great to have a more user-friendly installer/executable for this exporter so that the process to get up and running with it is more streamlined. We are directing users to this exporter, but some of them aren't very technical and they would greatly benefit from an installer.

**Comment by deltakosh** [comment]
Excellent point! We will definitely work on that

**Comment by deltakosh** [comment]
We are currently working on this featue

**Comment by sebavan** [comment]
@Jaskar Do we have any ETA to communicate on this feature ? that would be awesome :-)

**Comment by Jaskar** [comment]
Hi !
@sebavan It should be done by the end of the month :)

**Comment by sebavan** [comment]
@Jaskar Thanks a Ton for the ETA !!!

**Comment by sebavan** [comment]
Last missing bits are:

- [ ] Auto Deploy
- [ ] Update install docs

**Comment by sebavan** [comment]
Reference to the doc commit: https://github.com/BabylonJS/Exporters/commit/d85eed74f4c43ae91483db3fcc52a3310ddf6f74

**Comment by sebavan** [comment]
First release available here: https://github.com/BabylonJS/Exporters/releases/tag/preRelease20190617.6
