### ISSUE TITLE
[Maya] Instances of groups are exported to incorrect positions

### ISSUE THREAD

**Issue by FrozenBrain** [BabylonJS/Exporters#247]
When creating an instance copy of a group of objects the instanced objects are exported to the same position as the original object even after moving the group to a different location.

**Steps to reproduce:**
1. Create some object (for example a cube)
2. Group the object (Edit -> Group; Ctrl+G)
3. Create an instance of that group (Edit -> Duplicate Special with geometry type set to "Instance")
4. Move the new group
5. Export the scene

**Result:**
In Maya the two cubes are at different positions. In the exported Babylon scene both cubes are at the same position (therefore it looks like only the original object has been exported).

The following zip contains an example scene and the exported Babylon scene: [instancegroupbug.zip](https://github.com/BabylonJS/Exporters/files/2150082/instancegroupbug.zip)

**Comment by Jaskar** [comment]
@noalak or @rlouvat will take a look at this issue monday :)
