### ISSUE TITLE
[Max] 2 different materials with the same ID

### ISSUE THREAD

**Issue by kutomer** [BabylonJS/Exporters#248]
Hello :)

Attached `.max` file with two materials: `white` and `slate1`, when exported (see attached `.babylon` file) both have the same `id`.

```
{
      // ....
      "name": "slate1",
      "id": "ddcd6394-3427-4423-be2b-933bcfb8c9d5",
      // ....
}, {
      // ....
      "name": "white",
      "id": "ddcd6394-3427-4423-be2b-933bcfb8c9d5",
      // ....
}
```

Not sure how it's possible but when shown imported to a scene the crib is gray.
*After deleting `slate1` and recreating it the problem solved.

Tomer.
[Archive.zip](https://github.com/BabylonJS/Exporters/files/2152795/Archive.zip)

**Comment by deltakosh** [comment]
Pinging @noalak

**Comment by rlouvat** [comment]
Hi @kutomer,
Can you explain me how you created your two materials `white` and `slate1` ? It seems that somehow they were duplicated.

**Comment by kutomer** [comment]
Hey @rlouvat 
To be honest, I'm not the one that works on 3dsMax, so I've asked my colleague how she made it and this is what she said: "the materials were sampled from an imported Model and then attached to this model".

**Comment by rlouvat** [comment]
Hi @kutomer,
Thank you for your answer. I was able to find a solution to the problem.

**Comment by kutomer** [comment]
@rlouvat awesome thanks!
When will I be able to check it?
