### ISSUE TITLE
DDS texture results in Export Error

### ISSUE THREAD

**Issue by Alexees** [BabylonJS/Exporters#25]
When using a DDS texture on a material, when exporting, the following error appears and nothing is generated:

`Exportation cancelled: Parameter is not valid.`

**Comment by deltakosh** [comment]
In 3dsmax exporter? Ping @noalak

**Comment by noalak** [comment]
Yes, currently textures are read as Bitmap which doesn't support dds extension. A special treatment is required for those files.

**Comment by Alexees** [comment]
Yes, it is 3Ds Max we're using. What's the "special treatment"?

**Comment by noalak** [comment]
A fix in the exporter code. You should have nothing more to do :)

**Comment by Alexees** [comment]
Hm. So this is a bug then and you fix it, am I understanding that correctly?

**Comment by noalak** [comment]
Yes

**Comment by Alexees** [comment]
I don't know it's this will be a feature automatically available when incorporating dds formats, but we're looking at creating 3d launch icons for the Mircosoft Mixed Reality home with this:

https://github.com/sbtron/glTF/tree/MSFT_lod/extensions/Vendor/MSFT_texture_dds

Extracted from this:
https://developer.microsoft.com/en-us/windows/mixed-reality/creating_3d_models_for_use_in_the_windows_mixed_reality_home#materials

**Comment by Alexees** [comment]
Has been a week. Just wanted to know when this is going to be addressed

**Comment by noalak** [comment]
Hi, currently working on it. Should be quick, probably tomorrw.
You will be allowed to set DDS map textures in 3DS MAX. The exporter then automatically converts all textures into jpg/png format, which are the only formats supported by gltf.
