### ISSUE TITLE
[Max][glTF] Add option to just copy all input textures as-is

### ISSUE THREAD

**Issue by Ben-Mack** [BabylonJS/Exporters#252]
Currently while export to GLTF, the Max exporter does all the works from texture compression to merge Roughness, Metalness into the same map.

In my case, the input textures were already compressed, so recompression makes file size bigger for nothing. 

It'll be much better if the Max exporter to glTF has an option to just copy all the input textures as-is (that might make the exportation process faster too?).

**Comment by Selmar** [comment]
Agreed, this would be good to have.

For us it's actually a non-issue currently, because we have a custom material exporter which just copies the textures instead.

**Comment by noalak** [comment]
Hi,
glTF specs require the metallic and roughness maps to be merged together.

If maps are already merged, the exporter simply copy/paste the image.
Otherwise it read metallic and roughness files, merged them and write a new file.

Since version 1.2.11 3ds max exporter has an option to specify compression quality.

**Comment by Ben-Mack** [comment]
That's quite reasonable. But as I see, every maps like diffuse map (which require no processing) still got reprocessed instead of just copy original texture. 
I think reprocess a compressed jpg is not a good idea (output file size sometime much larger without any gain).

**Comment by Selmar** [comment]
@Ben-Mack I don't know what you're doing, but it's probably overkill (requires coding obviously). In our case, we have a different material, but you could write it for an already supported material too (I don't see the point to that though).

There's a branch here that adds support for custom material exporters: `https://github.com/Selmar/Exporters/tree/custom_material_exporters`, see #68. In the project I've added a class that inherits from IGLTFMaterialExporter:

```C#
namespace Max2Babylon
{
    public class YourMaterialExporter : IGLTFMaterialExporter
    {
        readonly ClassIDWrapper class_ID = new ClassIDWrapper({yourmaterialidpart1}, {yourmaterialidpart2});

        ClassIDWrapper IMaterialExporter.MaterialClassID => class_ID;

        GLTFMaterial IGLTFMaterialExporter.ExportGLTFMaterial(...)
        {
            // some code here that outputs a GLTFMaterial
        }
    }
}
```
