### ISSUE TITLE
Invoking ExecuteInDefaultAppDomain() Error

### ISSUE THREAD

**Issue by chaddyng** [BabylonJS/Exporters#255]
When I try to load the Maya2Babylon Exporter Version 1.2.X in the plugin manager I get this error.
But if I copy for example version 1.3.3 in my plugin path, I can load the export plugin. 
Can you help me out here? Thanks!

// Error: file: C:/Program Files/Autodesk/Maya2018/scripts/others/pluginWin.mel line 290: Invoking ExecuteInDefaultAppDomain() failed. // 
// Error: file: C:/Program Files/Autodesk/Maya2018/scripts/others/pluginWin.mel line 290:  (Maya2Babylon.nll) //

**Comment by rlouvat** [comment]
Hi @chaddyng,
Can you tell me which Maya version are you working on?
Also I didn't find the version 1.3.3... Currently the last version is Maya2Babylon-1.2.9.zip.

**Comment by rlouvat** [comment]
Sorry I can't reproduce the bug. So I need more information...
Did it happen on a fresh Maya install or on a upgraded version?
Did you follow the install procedure https://doc.babylonjs.com/resources/maya?

**Comment by deltakosh** [comment]
Closing for now as no response

**Comment by clayrain** [comment]
Hi, same issue. Fresh Maya 2018 (was fresh when installed last year, not upgrade). Windows 10 64bit. When clicking LOADED get the following error:

// Error: file: C:/Program Files/Autodesk/Maya2018/scripts/others/pluginWin.mel line 290: Invoking ExecuteInDefaultAppDomain() failed. // 
// Error: file: C:/Program Files/Autodesk/Maya2018/scripts/others/pluginWin.mel line 290:  (Maya2Babylon.nll) // 

Used the Maya2Babylon-1.2.26.zip version. Is there another version (older to try, if so where).  Thank you.
