### ISSUE TITLE
Add option to not merge AO map

### ISSUE THREAD

**Issue by rodrix385** [BabylonJS/Exporters#259]
Please add an option to not merge Ambient Occlusion shadow map (stored on Diffuse Roughness slot on 3d Studio Max) with the Metalness and Roughness map.

The new update has broken our entire pipeline!
The usual thing for our workflow is to have metalness and roughness maps that are MUCH smaller
than the Ambient Occlusion shadow map.

We are working with metalness and roughness of about 2048 and Ambient Occlusion maps of 8096.

Can you please add an option on export (a checkbox) to not merge Ambient Occlusion with Metalness Roughness map?

Thank you so much in advance!

**Comment by deltakosh** [comment]
Sure thing!

**Comment by rodrix385** [comment]
Thanks so much @deltakosh. It's increible how fast you replied. HUGS!!!!!! <3 You are the best.

**Comment by deltakosh** [comment]
My pleasure :)
