### ISSUE TITLE
Where is the Actions Builder plugin?

### ISSUE THREAD

**Issue by yzthr** [BabylonJS/Exporters#263]
Hello! 
When i right-click the meshes in 3ds max after i install the plugin, it only show two choices(Babylon property and Babylon Animation Groups). I can't find the Actions Builder.

**Comment by deltakosh** [comment]
Action builder il 3dsmax was discontinued as we are working on a better version.
You can still find it in the editor.babylonjs.com

**Comment by yzthr** [comment]
OK, got it. thank u!
