### ISSUE TITLE
The correct Specular ---> metalRoughness workflow

### ISSUE THREAD

**Issue by RemusMar** [BabylonJS/Exporters#269]
To @deltakosh and @bghgary :

As I said in another topic, the current Phong ---> PBR workflow (in all the exporters) is not correct.
It generates materials with no specularity at all.

Input textures (Diffuse  + Specular):
![diffuse_specular](https://user-images.githubusercontent.com/11772787/42870434-85e8068c-8a80-11e8-8f93-44ad32dfcb4f.jpg)

Current WRONG exported textures (baseColor + metallicRoughness):
![basecolor_metallicroughness_bad](https://user-images.githubusercontent.com/11772787/42870530-c85dd456-8a80-11e8-8d28-dd229c127081.jpg)

How the textures should be processed and exported:
![basecolor_metallicroughness_good](https://user-images.githubusercontent.com/11772787/42870579-e4771a3a-8a80-11e8-85b5-149a22fd6792.jpg)

And here is the correct result at runtime:
http://necromanthus.com/Test/html5/Lara_gltf_envMap.html 
See the specularity for bikini, bra, eyes and lips.

I've tested this workflow on a few dozens Phong based materials and the result was always good.

**Comment by deltakosh** [comment]
Adding @noalak to see what can be done.

@remusmar: what should be changed in the current process?

**Comment by RemusMar** [comment]
> what should be changed in the current process?

Hi David,
The best workflow for Phong (the most popular material for now) is the following:
1) baseColor = Diffuse (untouched)
2) Specular converted to metallicRoughness in this way:
- Black = Green (Roughness)
- White = Black
So the best solution is to keep Metalness to zero.
The explanation is this one:
![metalness_roughness](https://user-images.githubusercontent.com/11772787/42887031-b2cb4722-8aad-11e8-9744-775a9f3921c7.jpg)

p.s.
A tip for the Babylon sandbox:
you need to add a (default) spot light.
Otherwise (ambient light only) all the materials look very basic.
The spot light is the best light for complex (multilayered) materials

**Comment by deltakosh** [comment]
This seems fine for me, just want to make sure with @bghgary

**Comment by noalak** [comment]
I'm okay doing it!

**Comment by deltakosh** [comment]
Ok let's just confirm with Gary and if ok then go :)

**Comment by bghgary** [comment]
Agree with metalness being zero as there is no way to infer metallic from a Phong material without doing some ML object recognition or something.

> Black = Green (Roughness)
> White = Black

I'm not totally sure what curve should be used for specular converted to roughness.

This is what we did for the [Babylon glTF serializer](https://github.com/BabylonJS/Babylon.js/blob/master/serializers/src/glTF/2.0/babylon.glTFMaterialExporter.ts#L175). We ended up using a bezier curve to translate the specular power to roughness based on some visual testing we did on different values. This is specific to how Babylon handles its standard materials though (which is not exactly Phong), so the curve might be different for different tools that may handle specular power differently.

**Comment by RemusMar** [comment]
> Agree with metalness being zero as there is no way to infer metallic from a Phong material without doing some ML object recognition or something.

If you remove Blue from the metallicRoughness texture, you'll end up with a "Black on Green" texture.
There is no better workflow for the Specular (White on Black) texture.

**Comment by sebavan** [comment]
@bghgary for follow up and chosing the curve :-)
