### ISSUE TITLE
[Toolkit] Putting Illegal characters in the file path makes the VSCode code tab un accessible under preferences 

### ISSUE THREAD

**Issue by HeadClot** [BabylonJS/Exporters#270]
Hey @MackeyK24 

Info:
Unity Version: 2018.2.0f2
Toolkit version: Alpha 12

Bug Description - 

After putting  "" (Example "D:/MyFilePath")  around a file path one night I keep getting the following errors in the console. This does not matter if I make a new project.

https://shrib.com/#Error%201
https://shrib.com/#Gui%20Error

If I delete VSCode.CS the error goes away. But I am unable to use VSCode with Unity and the Babylon Toolkit.

The solution for the Gui related error is below.

https://answers.unity.com/questions/1127273/editor-window-gui-error-you-are-pushing-more-guicl.html

It may also be worth adding a check for illegal characters such as "()!%.~ etc.

Here is a video. https://www.youtube.com/watch?v=ve-l5Ja88WY 

--------------------- Original Post -----------------------------------------
Hey @MackeyK24

I accidentally put an illegal character in my file path. Such as "!. etc. But opposed to throwing an error saying that this is not allowed. It allowed it and I am unable to access it.

Would it be possible to put a check in to prevent the toolkit from accepting illegal characters in the future?

Before selecting the VSCode tab.
After Selecting the VSCode tab

It also throws the error - "You are pushing more gui clips than you are popping. Make sure they are balanced."

https://answers.unity.com/questions/1127273/editor-window-gui-error-you-are-pushing-more-guicl.html

**Comment by MackeyK24** [comment]
Which path, the main export folder ?

**Comment by HeadClot** [comment]
I think it was the main export folder under the VSCode Tab. I do not recall the exact terminology used.

**Comment by MackeyK24** [comment]
Show me where, and I will see what I can do about that one

**Comment by HeadClot** [comment]
Hey found the file that is causing the issue. It is VSCode.cs 
I deleted the file and now it is no longer throwing errors. However I can no longer use VS Code with the BJS Toolkit. It is the "VS Code Path" cannot have illegal characters. Hope this helps.

**Comment by MackeyK24** [comment]
That sounds like the actual unity game folder path has the illegal characters... cause the vs code path is relative to the assets folder in the game project folder...

Just make new clean project... install Babylon Toolkit and copy any assets and scripts from your old project

**Comment by HeadClot** [comment]
> Just make new clean project... install Babylon Toolkit

I have done that multiple times, I have set up my unity game folder path to be "D:\UnityProjects" I have also re installed unity multiple times. I am just not sure what is going on.

**Comment by MackeyK24** [comment]
I dunno bro... can you my make a recording showing the exact problem

**Comment by deltakosh** [comment]
Up?

**Comment by HeadClot** [comment]
Hey - Sorry for the delay on my end. I should have a video about what is going on soon.

**Comment by HeadClot** [comment]
Here is the video. https://www.youtube.com/watch?v=ve-l5Ja88WY

**Comment by MackeyK24** [comment]
Im sorry HeadClot.... I dont get how you put " " around the Path... What Path ??? At what point do you EVER have to enter a path to have the opportunity to put " " around a path...

What is D:\MyFilePath ???

The path to where Unity is installed or the path to where the project is installed or what ???

So i just dont get HOW you entered illegal charaters... So i can tell what in the VSCode.cs you are having problems with... Sorry :(

**Comment by MackeyK24** [comment]
Dude... Are you talking about the Path You Installed VSCode To What ???

**Comment by MackeyK24** [comment]
Yo i gotta go, working on something... I cant tell what path you are talking about yet alone how you enter illegal characters. If you are talking about WHERE you install VSCode... And i dont see how you could enter illegal characters UNLESS when specifying the PATH during the install of VSCode or something like that...

Anyways... is sounds like like the BAD PATH might be installed the the Unity Default Editor Preferences...

Try a dummy like of code some to clear or reset VSCode Path...

ClearVsCode.cs

`
        [MenuItem("Tools/Clear VS Code Path", false, 10)]
        public static void ClearVSCode()
        {
            EditorPrefs.DeleteKey("VSCode_CodePath");
            UnityEngine.Debug.Log"Vs Code Cleared ");
        }
`

**Comment by MackeyK24** [comment]
[MenuItem("Tools/Clear VS Code Path", false, 10)]
public static void ClearVSCode()
{
       EditorPrefs.DeleteKey("VSCode_CodePath");
       UnityEngine.Debug.Log"Vs Code Cleared ");
}

**Comment by MackeyK24** [comment]
Sorry ... try that VSCode clear path code in a CLEAN project WITHOUT the Babylon Toolkit.... Then go back in and load Babylon Toolkit AFTER you clear the Editor Prefs VS Code Path property... Hope that helps :)

**Comment by HeadClot** [comment]
Let me give that bit of code a shot. Been super busy the last few days.

**Comment by MackeyK24** [comment]
Headclot... that was you the whole time. It says your name is Benjamin... didn’t realize that was you 😄

**Comment by HeadClot** [comment]
Hey @MackeyK24 - I messed up my unity3d editor preferences. But I am at a loss because does not offer anyway even in most recent versions such as their 2018 releases to reset them.

**Comment by MackeyK24** [comment]
Did you try the Clear VSCodePath snippet I sent you?

**Comment by HeadClot** [comment]
Yeah I have.

**Comment by MackeyK24** [comment]
Did that work? Removing illegal characters

**Comment by MackeyK24** [comment]
What error

**Comment by HeadClot** [comment]
Hey - I am using Visual Studio Community 2017 now and I am not having any issues :)
