### ISSUE TITLE
[Max] Enable/disable the default hemispheric light ?

### ISSUE THREAD

**Issue by Remi-Tribia** [BabylonJS/Exporters#272]
Hi,
First, thanks for your incredible reactivity on the "extras" node tags!
Would it be possible to add a checkbox to enable/disable adding a default hemispheric light when exporting a scene with no light?
Cheers!

**Comment by deltakosh** [comment]
So your goal will be to turn the default light off?

**Comment by Remi-Tribia** [comment]
Yes.
I merge multiple gltf files on a main scene, some of them doesn't have any light. I can filter the results to get rid of it, but having the exporter adding an unwanted default light seems weird.
