### ISSUE TITLE
Where is the manifest file?

### ISSUE THREAD

**Issue by Nodragem** [BabylonJS/Exporters#277]
Hello,

I exported a scene to .babylon from blender, and then I loaded the scene using:

```javascript
///<reference path="../def/babylon.d.ts" />

class Game {

    private _canvas: HTMLCanvasElement;
    private _engine: BABYLON.Engine;
    private _scene: BABYLON.Scene;
    private _camera: BABYLON.FreeCamera;
    private _light: BABYLON.Light;

    constructor(canvasElement : string) {
        // Create canvas and engine.
        this._canvas = document.getElementById(canvasElement) as HTMLCanvasElement;
        this._engine = new BABYLON.Engine(this._canvas, true);
    }
  
    loadBlenderScene() : void {
        // Create a basic BJS Scene object.
        //this._scene = new BABYLON.Scene(this._engine);

        BABYLON.SceneLoader.Load("./assets/", "level1.babylon", this._engine, 
        (scene) => {this.initRendering(scene)} );
            // this way this_scene is attributed only whent the blender scene is loaded

    }
  
    initRendering(scene : BABYLON.Scene): void {
        this._scene = scene
        // Run the render loop.
        this._engine.runRenderLoop(() => {
            this._scene.render();
        });

        // The canvas/window resize event handler.
            window.addEventListener('resize', () => {
            this._engine.resize();
        });
    }
  }
  
  window.addEventListener('DOMContentLoaded', () => {
    // Create the game using the 'renderCanvas'.
    let game = new Game('renderCanvas');
  
    // Create the scene.
    game.loadBlenderScene();

  });
```

Chrome and Opera (but not Firefox) complained that they can't find the level1.babylon.manisfest file.

After some research, I finally just created one following these instructions:
http://doc.babylonjs.com/how_to/caching_resources_in_indexeddb

Would it be nicer if the blender exporter was creating a default manifest file for us? we could even consider letting the user chose the manisfest options in the export menu in Blender.

:D Hope that helps!

**Comment by deltakosh** [comment]
@kcoley: interested to have a look?
Or perhaps @Palmer-JC?

**Comment by kcoley** [comment]
Sure I can look into this

**Comment by Nodragem** [comment]
I found the issue I think. In Blender, there is an checkbox for automatically creating the manifest. It was not checked by default (which I think it should, to avoid people thinking there is a problem).

**Comment by kcoley** [comment]
@Nodragem good find.  The change is simple, so I made a PR for enabling this by default: https://github.com/BabylonJS/Exporters/pull/278
