### ISSUE TITLE
[Blender] Mesh/Armature not imported at the good location

### ISSUE THREAD

**Issue by Nodragem** [BabylonJS/Exporters#279]
Hello,

I am making a character who is piloting a plane, so that the character has an armature, while the plane doesn't.

I applied all the Rotation / Location / Scale to every objects I could find, so that the exporter was happy. 
But now when I import my character in BabylonJS, it is offset compared to its plane.

Here how it looks in Blender:
![blender_2018-07-28_09-34-00](https://user-images.githubusercontent.com/10520249/43354771-0763a5ce-924a-11e8-90cf-ea061dc8f55f.png)

Here how it look in BabylonJS:
![chrome_2018-07-28_09-39-12](https://user-images.githubusercontent.com/10520249/43354774-1d9284be-924a-11e8-9d17-9e3755110aa2.png)

Or in the BabylonJS viewer (without the texture):
![opera_2018-07-28_09-39-59](https://user-images.githubusercontent.com/10520249/43354782-3c095030-924a-11e8-93ea-b5f17a7cae52.png)

I am not sure how to solve this problem... 
Although kind of opposite, it might me linked to issue #235 where the Mesh/Armature are moved inside Blender editor after export.

**Comment by Nodragem** [comment]
I tried the glTF2.0 exporter for Blender instead, here is the result when drap-and-dropped in the BabylonJS viewer:
![image](https://user-images.githubusercontent.com/10520249/43356896-eb603bb8-9270-11e8-9c06-b995eb872294.png)
Everything is at the good location!

Hence, this result suggests that the problem I mentioned above come from the Babylon exporter rather than from the blend file...
Hope that helps.

**Comment by kcoley** [comment]
Hi @Nodragem , I'll look into this to see what's going on

**Comment by kcoley** [comment]
@Nodragem do you have a sample Blender file that demonstrates this issue?

**Comment by deltakosh** [comment]
Closing for now as no response

**Comment by Nodragem** [comment]
... that's odd, I was so sure I posted here to say that the issue was resolved.

It was the Armature's location in Object Mode that I needed to apply (so it becomes [0,0,0]).

Interestingly, there exists already an error message asking to apply all transformations, but it was not thrown in this particular case.

Hence, I would suggest that this case also rises the error message asking to apply all transformations.
Maybe, even better, if possible, the message could tell us which transformations need to be applied (i.e. "please apply location of object Prabbit.Armature in Blender (include Keyboard Shortcut)").

**Comment by deltakosh** [comment]
Ok wonderful then :)
Good point for the warning
