### ISSUE TITLE
Error while export to glb on version 1.2.22 on 3DMax 2018

### ISSUE THREAD

**Issue by Pycz** [BabylonJS/Exporters#281]
![export_error](https://user-images.githubusercontent.com/1331077/43426683-3cb9bc1a-945f-11e8-8a11-7a0082a5eb28.png)

3DMax 2018, export to glb don't work, exporter version 1.2.22
Export to babylon works fine.
Error on image.

**Comment by Pycz** [comment]
[test.zip](https://github.com/BabylonJS/Exporters/files/2243096/test.zip)
This, for instance,

**Comment by keyoss** [comment]
Create a Box
Save the Scene
Export with bjs exporter and default settings - NullRef

same goes for all other versions 2015-2018

**Comment by rlouvat** [comment]
Sorry in my previous pr #280 I updated the rotation export for lights. But I didn't double check the default light created by the exporter...
The #282 fixes it.

**Comment by Pycz** [comment]
Works fine now, thanks.
