### ISSUE TITLE
squash bones

### ISSUE THREAD

**Issue by herfst1** [BabylonJS/Exporters#283]
when I export out a spring with a bone set to squash-and-stretch it doesn't export out correctly. Everything works except the squashing.

![image](https://user-images.githubusercontent.com/6582296/43575803-05638382-9648-11e8-812a-4b729f1a5670.png)

[spring.zip](https://github.com/BabylonJS/Exporters/files/2252937/spring.zip)

**Comment by herfst1** [comment]
I forgot to add the bin and gtlf:

[spring.zip](https://github.com/BabylonJS/Exporters/files/2252970/spring.zip)

**Comment by rlouvat** [comment]
Hi @herfst1 
Thank you for your feedback. But I not sure to fully understand what doesn't export out correctly...

Here is my test:  [test.zip](https://github.com/BabylonJS/Exporters/files/2253949/test.zip)
The .max file contains three spheres with different stretch modes and the gltf export looks like the 3DS Max scene.

**Comment by herfst1** [comment]
Oh, I apologise for wasting your time, I really should have checked it in the viewer. It seems the issue is on engine side. Thank you for your response.

**Comment by rlouvat** [comment]
Hi,
Don't worry, you didn't waste my time. Because if you add some animation, the exported result is not as expected... We will look at it ;)

**Comment by Selmar** [comment]
I think @deltakosh missed your request for reopening? :P

**Comment by deltakosh** [comment]
Any news?

**Comment by rlouvat** [comment]
I didn't find a way to convert the the strech type or the strech factor in other bone properties. Currently without animation it works.

**Comment by deltakosh** [comment]
Closing for now as this seems not easy to export in gltf so far
