### ISSUE TITLE
[Feature Request] Unity Timeline support for the Babylon toolkit

### ISSUE THREAD

**Issue by HeadClot** [BabylonJS/Exporters#285]
Unity Timeline is a cinematic tool in unity that used for in game cut scenes and Cinematic.
It would be great if the Babylon Toolkit had support for this.

https://docs.unity3d.com/Manual/TimelineSection.html

**Comment by deltakosh** [comment]
Hello can you ping @MackeyK24 on the forum? Not sure he is following the repo here

**Comment by HeadClot** [comment]
Sure will do.

**Comment by MackeyK24** [comment]
I have never used that feature. Can you make a short video for me about that feature, show me what it looks like when you using and how you think it should fit into toolkit... then I can see what I can do
