### ISSUE TITLE
Exportation cancelled from Maya 2016

### ISSUE THREAD

**Issue by 080993** [BabylonJS/Exporters#286]
Hello! 
I'm trying to export scene from Maya 2016 to Babylon using your exporter.And the exportation is cancelled at next moment: 

Exporting nodes 
Exportation cancelled: Method is not found: "Autodesk.Maya.OpenMaya.MPlug Autodesk.Maya.OpenMaya.MPlug.get_source()". in Maya2Babylon.BabylonExporter.ExportMesh(MDagPath mDagPath, BabylonScene babylonScene) in Maya2Babylon.BabylonExporter.Export(String outpu 

Can you be so kind, please, and tell me how to fix it? The scene consists of one object with diffuse textures. I don't think that problem is in my scene because I exported it to ThreeJS normally, without any warnings or errors. 

Thank you!

**Comment by deltakosh** [comment]
Hello unfortunately we support Maya only since version 2018

**Comment by 080993** [comment]
Ok, thanks, I will try Maya 2018.
