### ISSUE TITLE
Textures with different sizes are not correctly exported - 3DSMax 2018

### ISSUE THREAD

**Issue by keyoss** [BabylonJS/Exporters#287]
When exporting models with different sized textures (e.g. 2048 and 4096) textures will be cut therefore the mapping is incorrect.

Expected result would be: Scale up of the lower textures to match the biggest texture size found.

**Comment by deltakosh** [comment]
This is the expected behavior. We decided to not scale the textures as this could lead to unwanted artifacts. Instead the export will output a warning to let the artist decides how to scale
