### ISSUE TITLE
Texture type not supported warning - 3DSMax 2018

### ISSUE THREAD

**Issue by keyoss** [BabylonJS/Exporters#289]
While using .jpg as source textures i still receive the warning that "Texture type is not supported. Use a Bitmap instead"

**Comment by deltakosh** [comment]
Can you make sure that all slots are using bitmaps?
Can you share the scene?

**Comment by noalak** [comment]
When editing an existing texture, you should have something like this
![edition](https://user-images.githubusercontent.com/20560340/44024896-dc4e8de8-9eee-11e8-9dd6-120559776ecf.jpg)


When creating a new texture, choose bitmap
![creation](https://user-images.githubusercontent.com/20560340/44024782-9c49909e-9eee-11e8-8363-599bf766771f.png)

**Comment by sebavan** [comment]
@keyoss Is it now working for you ?
