### ISSUE TITLE
Max2Babylon support for vertex color?

### ISSUE THREAD

**Issue by echadwick-wayfair** [BabylonJS/Exporters#293]
I'm curious if vertex color can be flagged for use as AO, replacing a bitmap in the Diffuse Roughness Map input of the Physical Material? 

I couldn't find any implementation info in the documentation. My apologies if this is already explained somewhere!

It would be helpful if possible to define multiple uses for VC like: ambient occlusion, albedo multiply, lightmapping, metalness, etc. 

Maybe the different uses could be activated by adding a Vertex Color map node to the Physical Material? For example if I wanted to multiply VC and Base Color, perhaps I could wire both into a RGB Multiply node, and hence into the Base Color Map input of the material. Or if I wanted VC for AO I could wire a Vertex Color node directly into the Diffuse Roughness Map input. 

Perhaps this mechanism could allow the model to store multiple channels of vertex color data. Might be more efficient than bitmaps, for certain uses like metalness, ambient occlusion, baked lighting, etc.

**Comment by sebavan** [comment]
This is not supported at the moment and despite the flexibility it provides it would introduce way more complexity in the shader. Also this would enforce to rely on a node system and change the exporter.

I will close it from the exporters repo and move it as a suggestion for future release.

**Comment by sebavan** [comment]
You can see it here: https://github.com/BabylonJS/Babylon.js/projects/8
