### ISSUE TITLE
Animation Stutter

### ISSUE THREAD

**Issue by gabrieljbaker** [BabylonJS/Exporters#294]
When exporting a model with animations from 3DS Max, we're noticing a stutter effect on the animation when we view the exported model. See below for how this particular animation looks in Max vs. how it looks once exported with the Babylon exporter. You'll notice a subtle stutter happening. 

![ghost_loop_max2018](https://user-images.githubusercontent.com/5530378/44113823-3597ab26-9fbe-11e8-83f0-665fe2415a73.gif)
![ghost_looped_babylongltf](https://user-images.githubusercontent.com/5530378/44113829-39fc0194-9fbe-11e8-84da-59097ed21ff4.gif)

Here also is a link to the source model and exported model if that would be helpful: http://tbf.me/a/CNn2Sz

**Comment by WVNicolayeff** [comment]
Artist on the project here. That top GIF from Max had a few extra frames at the end - in Max it is smooth loop.

**Comment by sebavan** [comment]
Adding @noalak and @Jaskar for deeper analysis.

**Comment by sebavan** [comment]
Closed by the previous PR. Big Thank to @noalak
