### ISSUE TITLE
Max2Babylon viewport shader?

### ISSUE THREAD

**Issue by echadwick-wayfair** [BabylonJS/Exporters#296]
Has anyone looked into creating a viewport FX shader for 3ds Max?

It would be much faster to iterate on materials & geometry if we had a viewport shader in 3ds Max that mimics the BabylonJS default shader. If we could give this to our content creators, they would be able to iterate much more quickly than the "Export & Run" feature in the current Max2Babylon exporter. A viewport shader is a great live-editing tool.

ShaderFX is a built-in FX shader editor for Max. I've used it to create analogous Unity-style shaders for artists to preview their work directly inside Max, without having to wait for export/update in Unity.
http://ericchadwick.com/img/robot_rising.html#utility_shader

![image](https://user-images.githubusercontent.com/40177036/44220683-524afd00-a14d-11e8-9066-7940e290e831.png)

I haven't created a metalness PBR shader though, a bit beyond my skill level. 

Any interest in this?

**Comment by sebavan** [comment]
Would be nice. 

The thing is with PBR at least it should be pretty close (not enough I understand :-) ) as the material definition is "pretty-ish" "standar-ish".

Would you be able to create and make a PR for it ? I can definitely help with the shader we are using.

**Comment by sebavan** [comment]
I will check with our in house artists if this would be possible cause I really like the idea :-)

**Comment by echadwick-wayfair** [comment]
Some implementation problems to factor in, see these 3ds Max Idea Board topics:

https://forums.autodesk.com/t5/3ds-max-ideas/pbr-viewport-shader-environment/idi-p/6806116

https://forums.autodesk.com/t5/3ds-max-ideas/native-pbr-viewport/idi-p/8071453

**Comment by echadwick-wayfair** [comment]
Hey, got that to work, mostly! 

100% roughness is causing a different lighting effect on the color chart than in BabylonJS. But it's pretty darn close.

![image](https://user-images.githubusercontent.com/40177036/44233934-3ce8c980-a173-11e8-8bc9-be0b0256d9d2.png)

![image](https://user-images.githubusercontent.com/40177036/44233607-55a4af80-a172-11e8-9ae3-372ef51e782c.png)

**Comment by echadwick-wayfair** [comment]
Better with a direct light.

![image](https://user-images.githubusercontent.com/40177036/44234513-c1881780-a174-11e8-8174-00ac23a4b533.png)

**Comment by echadwick-wayfair** [comment]
I wonder if Max2Babylon will let me use the DirectX Shader material as a (pass-thru) parent to the Physical Material? 

It would help to be able to keep it there during export, for iterations sake.

**Comment by rlouvat** [comment]
Hi,
Currently the DirectX Shader material is not supported by the 3DS Max exporter. So it is ignored.

But I think the exporter could export the material stored in `RenderMaterial` attribut in stead of ignoring the DirectX Shader. So in your case, the Physical Material would be exported.

**Comment by echadwick-wayfair** [comment]
I like that idea. 

Another one we are considering is the Shell Material, since it has a Render input and a Viewport input. Our current thinking is we might recommend a model contain both a V-Ray material for offline rendering, and a Physical Material for glTF export. So the root would be the Shell, and I guess in the Viewport input we'd have a DirectX, with the Physical plugged into that.

We'd probably write a tool to attempt an auto-convert from an existing V-Ray, and create the Shell + DirectX + Physical layout, and add the (derived) bitmaps. 

The aim would be to help modelers fix the glTF material quickly and efficiently. And we'd get a model that supports both rendering pipelines.

We still need to decimate the model for LODs, but we think that's probably best as a post process. Since revisions are a pain if you have LODs to keep in sync.

Anyhow that's the current thinking. Open to any and all ideas!

**Comment by deltakosh** [comment]
I think we should also support Arnold material in 3dsmax
Pinging @patrickryanms for a sample scene

**Comment by echadwick-wayfair** [comment]
Testing the shader today. 

I'm using the FlightHelmet model, it has great material definition. 
https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/FlightHelmet

Some inconsistent results. 
1. Looks like we need to add alpha blending to the shader. Lenses on the helmet aren’t transparent.
2. Lighting is a bit difficult to control. Shader wants three lights… if I feed it only one it puts default lights in the other two, and the model renders overbright.
3. DirectX shaders don’t like viewport/render gamma control, which conflicts a bit with our use of V-Ray.

I'll keep investigating.

**Comment by rlouvat** [comment]
Hi @echadwick-wayfair 

Regarding the DirectX shaders, do you use other parameters than the `RenderMaterial` ?
![image](https://user-images.githubusercontent.com/35570412/44576314-8ac28a80-a78e-11e8-8c3c-c85507d8f755.png)

**Comment by echadwick-wayfair** [comment]
I think we would prefer support for three materials:

1. Physical Material for Max2Babylon export.
2. DirectX Shader material for 3ds Max live viewport preview.
3. An offline material for non-realtime rendering. This could be for Arnold, VRay, Art, Mental Ray, whichever 3ds Max renderer the content creator wishes to use.

The DirectX Shader material is only for live viewport rendering. It's not a replacement for the Physical Material needed for Max2Babylon export.

To support all three, we're leaning towards a Shell Material, with DirectX in the "baked" input, and the offline material in the other input. Then in the DirectX the Software Render Style input could be for storing the Physical Material.

It would probably help other Babylon users if there was support for a few different setups:

If the modeler didn't need to use a dedicated offline material, they could just forego the Shell, and use a DirectX as the root, with the Physical as the child.

Or if they only cared about export alone, they could just use a Physical Material.

**Comment by echadwick-wayfair** [comment]
For example, all three materials in one. This is what we would prefer to use, if it was possible.
![image](https://user-images.githubusercontent.com/40177036/44594725-0cb5b200-a795-11e8-97e0-5d6894c49158.png)

**Comment by echadwick-wayfair** [comment]
Getting closer. 

Shader already has a parameter for Use_Albedo_Alpha_as_Transparency, you just have to open the shader in ShaderFX to expose it. I'd like to add it as a Boolean to the material interface.

The cubemap is not as bright in the shader as it is in BabylonJS. I do have to disable gamma in 3ds Max to get proper lighting, so that's probably it. 

There are also color differences. Need to look into why Max is warmer.

![image](https://user-images.githubusercontent.com/40177036/44609399-7b126880-a7c5-11e8-90be-060d6461c00f.png)

**Comment by Karttridge** [comment]
@echadwick-wayfair 

Hi :) ,

I didn't know that was possible to have something this good  in 3dsmax viewport. Can you share your shaderFx file ? That would be awesome :o. 

Sorry to post here

Ty
