### ISSUE TITLE
[max][gltf][feature] support for draco compression

### ISSUE THREAD

**Issue by tkazik** [BabylonJS/Exporters#297]
hi folks

just curious whether there are some plans to support draco compression for gltf files, see: 

https://www.khronos.org/news/press/khronos-announces-gltf-geometry-compression-extension-google-draco

would be very interesting!

**Comment by sebavan** [comment]
Hello,

It is already supported in the BabylonJS loader. Do you mean having the ability to compress straight from the exporter ?

**Comment by sebavan** [comment]
Pinging @noalak to check feasibility ?

**Comment by tkazik** [comment]
awesome, thx!

**Comment by padovaproductions** [comment]
I know this is an old topic, but i found it google searching for the same problem. 
![image](https://user-images.githubusercontent.com/87450845/134698250-a0be0e8b-c151-41d5-ab8b-97ebe56d229b.png)
The above message was displayed to me by 3DS Max at the export panel, and according to that I installed the LTS version of Node.js on my computer, and also the gltf-pipeline package **globally** like so: 
`npm install -g gltf-pipeline`. Now 3DS max can access and run it.
After the installation restart 3DS Max, and it'll work, or at least it did for me:)
