### ISSUE TITLE
Normal map causes export error log

### ISSUE THREAD

**Issue by echadwick-wayfair** [BabylonJS/Exporters#301]
Max2Babylon-1.2.25

`Exporting texture <path & name> failed: System.IO.IOException: The process cannot access the file '<path & name>' because it is being used by ano`
<truncated>
![image](https://user-images.githubusercontent.com/40177036/44478255-1c08f400-a60b-11e8-9c2f-75b28cf30e92.png)

[NormalmapExportError_example.zip](https://github.com/BabylonJS/Exporters/files/2311324/NormalmapExportError_example.zip)

However it seems to render OK in the sandbox.
![image](https://user-images.githubusercontent.com/40177036/44478550-0cd67600-a60c-11e8-9a72-144aa5835f97.png)

**Comment by deltakosh** [comment]
Is this file opened by another application (like photoshop?)

**Comment by echadwick-wayfair** [comment]
No other processes open.

I've tried a few variations of filepaths and filenames. Seems to occur only if the normal map is located in the same folder where the exporter is saving the new GLB.

d:\n\n.jpg + d:\n\test.glb = Causes the error.
d:\n\n.jpg + D:\dashes-in-path\CamelCase\test.glb = No error.
