### ISSUE TITLE
Unity Exporter - IE11 error 'endsWith' 

### ISSUE THREAD

**Issue by mreimer01** [BabylonJS/Exporters#304]
Unity Exporter error received in IE11 with default scene (camera and direct light). 

SCRIPT438: Object doesn't support property or method 'endsWith'
index.html (144,9)

![image](https://user-images.githubusercontent.com/23662406/44623831-a9687480-a8a7-11e8-9abf-160cb21cb2eb.png)

**Comment by deltakosh** [comment]
Pinging @MackeyK24

**Comment by deltakosh** [comment]
Up @MackeyK24

**Comment by MackeyK24** [comment]
Next update will have polyfill for startWith and endsWitj
