### ISSUE TITLE
3dsMax glTF exporter: indices are always ushort

### ISSUE THREAD

**Issue by Selmar** [BabylonJS/Exporters#31]
Hi,

We ran into an issue of indices. The problem is two-fold:
- The indices are always stored as an array of unsigned shorts. When the number of vertices exceeds this, the indices wrap around to 0 and are invalid.
- The number of exported vertices is always 3 times the number of triangles. Vertices are not re-used. This means the problem is encountered significantly faster (as well as cause data size bloat).

A side-effect of the second point is that it is significantly harder to optimize a mesh.

Best,
Selmar

**Comment by deltakosh** [comment]
Hello this is for the 3dsmax exporter I guess?
Pinging @noalak

**Comment by Selmar** [comment]
Correct, updated.

**Comment by noalak** [comment]
Hi,

**Comment by Selmar** [comment]
Thanks for the fix!

I'm not sure what you mean by the babylon properties? Will that allow me to reduce the vertex count in the exported file?

For reference, I'm using the babylon exporter as a stand-alone to export glTF files from max. I don't know much about the other parts of Babylon. I use it to be able to import .glTF into another engine I'm working on.

**Comment by noalak** [comment]
Here is the [documentation](https://doc.babylonjs.com/resources/3dsmax#object-properties). Look at 'Try to optimize vertices' property.

**Comment by Selmar** [comment]
I'll just hijack the thread, but I have this error and I don't think it's because of my model. A previous version of babylon (I think downloaded the 17th of november) exported it just fine:

![image](https://user-images.githubusercontent.com/3010534/32960752-6774b7f0-cbc6-11e7-9fe4-c5142128a445.png)

**Comment by deltakosh** [comment]
Do you mind opening another issue?
