### ISSUE TITLE
Maya morph target appears to have inverted Z on export

### ISSUE THREAD

**Issue by PatrickRyanMS** [BabylonJS/Exporters#313]
# Bug 
When exporting morph target animation, vertex position on the Z axis seems to be inverse of what is intended. 

![morphtargetbug](https://user-images.githubusercontent.com/31326855/45060978-402af300-b057-11e8-9873-bf8adadbd223.png)

**Comment by deltakosh** [comment]
@noalak any news on this one?

**Comment by noalak** [comment]
Last PR of @Bloadrick should fix that.

**Comment by deltakosh** [comment]
Wonderful
