### ISSUE TITLE
Could not load file or assembly "Newtonsoft.Json, Version 9.0.0.0..."

### ISSUE THREAD

**Issue by jdavidlists** [BabylonJS/Exporters#323]
After installing the contents of Maya2Babylon-1.2.21.zip to the plugins folder in Maya 2018, activating the plugin works fine.  But while following the excellent setup instructions, I get an error upon clicking "Export" in the plugin's "Export scene" window.

The message is quite long, but it appears right after the "Export animation groups" line.

It begins:

Exportation cancelled: Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=(hex numbers)' or one of its dependencies.  The system cannot find the file specified.  

It goes on from there at some length with what looks like a stack trace.

The Newtonsoft.Json.dll file is most definitely in the plugins folder alongside GDImageLibrary.dll, Maya2Babylon.nll.dll, TargaImage.dll and TQ.Texture.dll.  The version of Newtonsoft.Json.dll that was in the zip file is 9.0.1.19813 and not 9.0.0.0 but I'm not sure if this is significant.

Is there anything useful I can do to troubleshoot this problem?  Unfortunately I am relatively new to both Maya and Babylon.JS, but I'm willing to learn.

Thanks for any help, advice, or kick in the right direction!

**Comment by kcoley** [comment]
Hi @jdavidlists .  To verify, did you unblock the dll files from the zip directory?
<img width="377" alt="screen shot 2018-09-20 at 7 48 01 am" src="https://user-images.githubusercontent.com/3946928/45826639-b3fd0a80-bca9-11e8-989a-83f7d08cbf7a.png">

**Comment by jdavidlists** [comment]
Oh FFS!  I looked at that repeatedly and every time I convinced myself that it was OK because the box wasn't checked.

While I don't that think that particular bit of UI is Microsoft's finest usability moment, this problem appears to be (not surprisingly!) entirely due to operator error. :-(

Sorry for the noise!
