### ISSUE TITLE
.jpg mimetype issue

### ISSUE THREAD

**Issue by Selmar** [BabylonJS/Exporters#324]
We don't use the jpeg format, I just noticed this randomly.. in BabylonExporter.GLTFExporter.cs:
`gltfImage.mimeType = "image/" + gltfImage.FileExtension;`

FileExtension could theoretically be `jpg` or `jpeg`, but only `"image/jpeg"` is a valid `mimeType`.

In fact, the `_getValidImageFormat()` function explicitly converts the `jpeg` extension to `jpg`, so I assume this may always be wrong.

**Comment by kcoley** [comment]
@Selmar yeah looks like a bug.  I'll work on a fix for this.

**Comment by kcoley** [comment]
@Selmar the code was a little confusing to follow, but it looks like the `jpg` texture gets associated with a file extension of `jpeg` in GLTFExporter.Texture.cs`:
```c#
RaiseMessage("GLTFExporter.Texture | create image", 3);
GLTFImage gltfImage = new GLTFImage
{
    uri = name
};
gltfImage.index = gltf.ImagesList.Count;
gltf.ImagesList.Add(gltfImage);
switch (validImageFormat)
 {
    case "jpg":
        gltfImage.FileExtension = "jpeg";
        break;
    case "png":
        gltfImage.FileExtension = "png";
        break;
 }
```
If you hit any issues with this though feel free to reopen this issue.

**Comment by Selmar** [comment]
Alright, odd. I guess it's because most people use `.jpg` and we don't want to rename it to `.jpeg` all the time. That maybe warrants some code comments. Nice find.
