### ISSUE TITLE
[Max][C#] Temporary output directory copies all files from max output directory

### ISSUE THREAD

**Issue by Selmar** [BabylonJS/Exporters#325]
The output directory `3ds Max\assemblies\2015 - 2016` contains all files from my 3dsmax directory, not just the files created by the project. It seems a bit impractical, is this on purpose?

**Comment by kcoley** [comment]
Hi @Selmar .  Is your 3ds Max active project set to that directory or a different location?

**Comment by Selmar** [comment]
The 3dsmax active project directory is set to a completely different directory.

The C# project's `OutDir` (==`TargetDir`) is set to `C:\Program Files\Autodesk\3ds Max 2016\bin\assemblies\`, as is the default

the post build process simply copies all dlls instead of just the ones generated by the project: 
`copy "$(TargetDir)*.dll" "$(SolutionDir)assemblies\2015 - 2016\"`

I imagine it's the same for the other max versions.

**Comment by Selmar** [comment]
Even if you use that directory as the 3ds max plugin directory it wouldn't work well, because only the .dll files are there after this process anyway. This problem has nothing to do with 3dsmax, it's just a minor ussue with copying the output files to our shared tools folders.

**Comment by kcoley** [comment]
@Selmar gotcha, thanks for the insight!  This is indeed an issue with the exporter.  I'll work on a fix for this.

**Comment by kcoley** [comment]
@Selmar is your output path set to `bin\Debug` in Visual Studio solution? (Select the project, go to properties, and select the build tab to check the `Output path:` value)
![image](https://user-images.githubusercontent.com/3946928/46303681-58603600-c561-11e8-8bc5-0c5967f85898.png)

![image](https://user-images.githubusercontent.com/3946928/46303956-2a2f2600-c562-11e8-81c1-744809ca25d5.png)

When I build, I only see the generated dlls in `$(SolutionDir)assemblies\2015 - 2016\` from the build:
![image](https://user-images.githubusercontent.com/3946928/46304108-990c7f00-c562-11e8-9457-f467292709ab.png)

Is it different on your set up?

**Comment by Selmar** [comment]
Yes, as I said, the out directory is set to the 3dsmax application's assemblies directory (`C:\Program Files\Autodesk\3ds Max 2016\bin\assemblies`). These are the default settings I have with the project (which makes sense when you're modifying the code and testing a new version).

**Comment by Selmar** [comment]
I suggest we modify the post-build processes in the project to output the files in the repository's `\3ds Max\assemblies\2015 - 2016` first and then copy to `C:\Program Files\Autodesk\3ds Max 2016\bin\assemblies` instead of vice-versa.

**Comment by kcoley** [comment]
@Selmar, I see, so your `OutDir` is set to `C:\Program Files\Autodesk\3ds Max 2016\bin\assemblies\` by default, whereas mine is set to `bin\Debug\` by default.  This could be a discrepancy between plugin versions.  Did you try against the latest plugin (1.3.0)?

**Comment by deltakosh** [comment]
Closing for now. Please reopen of needed

**Comment by Selmar** [comment]
I'm sorry, I haven't had time to do this yet. I will check it when I get around to it.

**Comment by kcoley** [comment]
@Selmar I think I am able to repro the issue you are hitting now.  I switched my VS project from `Debug` to `Release`, and see the behavior you mentioned.  I will look into a fix for this.

**Comment by Selmar** [comment]
It happened several times before that the different configurations diverged. Usually when changes are made people forget the other configurations. :P

Right now there are more than is necessary (I think visual studio creates some defaults every time you add a project). I think all we need is the x64 builds (debug/release) and one x86 (any, to be able to view the forms inside visual studio, which requires an x86 build for some reason).
