### ISSUE TITLE
[3dsmax] Ambient Occlusion (Textures not on Channel 1) not exported correctly

### ISSUE THREAD

**Issue by johanos** [BabylonJS/Exporters#326]
Hi again 

I haven't tried downgrading but currently i'm on the most recent version of the exporter and i found that this specific file. will not export the ambient occlusion correctly unless i select the option merge AO map. I have done this with other models with a similar set up and its worked in the past. I make the AO map on a different channel / resolution so merging is a non option. 

My hunch is it might be the material set up for this model. I've put it on this aws link 
https://s3.amazonaws.com/wayfair-sandbox/SampleScene.zip

here's a low quality snap shot of the materials on this model. there's an AO map on channel 2 assigned to every model. a certain part of it uses a multimaterial which i think might be the thing causing the issue
 
![image](https://user-images.githubusercontent.com/6535806/45887130-f0ebfe80-bd88-11e8-8298-bd7236e3ef36.png)

Let me know if you need more details

**Comment by kcoley** [comment]
Hi @johanos I'll take a look

**Comment by kcoley** [comment]
Hey @johanos.  I was able to reproduce the ao issue.  I tried reproducing on a simple scene, but the AO exported correctly.  Going back to your scene, I tried deleting the multimaterial and exporting.  The AO exported correctly.  Reapplying the multimaterial also caused the AO to export correctly.  I'm not sure why this worked, but could you give this a try on your end?

**Comment by johanos** [comment]
If it works manually that's interesting. We get to this scene through a maxscript so if we have to remove the multi material and reattach it that might be a bit weird on our end. if we unassign the multimaterial from the model and assign it again through code does that have the same effect as manually doing it

**Comment by kcoley** [comment]
@johanos you unassigning and reassigning in maxscript to see if that works.  I believe it is a weird bug in 3ds Max itself, or perhaps something in the scene file.  Let me know if that works.
