### ISSUE TITLE
Add compatibility with Blender’s custom split normals

### ISSUE THREAD

**Issue by MaximeOrlandi** [BabylonJS/Exporters#328]
This functionnality would save us graphic designers a lot of time and a lot of polys

https://en.blender.org/uploads/9/9e/Average.gif

Thank you !

**Comment by kcoley** [comment]
@MaximeOrlandi thanks for the reference gif!  I'll look into this.

**Comment by kcoley** [comment]
Hi @MaximeOrlandi , I was unable to find the Normal Tools from your reference gif.  It it built into Blender or is it a Blender addon?  Currently we don't have support for any addons.  Do you have a sample fbx file that has been modified?

**Comment by Vinc3r** [comment]
I don't know the addon MaximeOrlandi use, but you can try modiying normals with [YAVNE for example](https://github.com/fedackb/yavne), or more simple, use the [default Normal Edit modifier](https://i.imgur.com/SAPiZi8.png).

The point is to get custom split normals data into the mesh:
[img](https://i.imgur.com/p6EqzaU.png)

**Comment by kcoley** [comment]
@Vinc3r thanks for the additional info.  I'll verify with Blender's default normal edit modifier.  If split normals are not being exported, it may be a bug in the exporter.

**Comment by kcoley** [comment]
@MaximeOrlandi @Vinc3r heads up that this will take me a while to get to since I've been resolving some bugs with the other exporters, but hopefully I'll get to this soon!

**Comment by MaximeOrlandi** [comment]
Great ! Thank you !

**Comment by Palmer-JC** [comment]
Custom split normals has been added on the EEVEE branch of the repo.
