### ISSUE TITLE
Exportation cancelled: startIndex cannot be larger than length of string.

### ISSUE THREAD

**Issue by Selmar** [BabylonJS/Exporters#33]
I have this error and I don't think it's because of my model. A previous version of babylon (I think downloaded the 17th of november) exported it just fine:

![image](https://user-images.githubusercontent.com/3010534/32960752-6774b7f0-cbc6-11e7-9fe4-c5142128a445.png)

**Comment by noalak** [comment]
Hi, i think the path of one of your texture for material '03 - Default' is not set.
It occurs when loading an external file or an old file where paths are no longer up to date.
The exporter is currently not handling such case.
Can you confirm the issue is linked to textures paths?

**Comment by Selmar** [comment]
You seem to be correct, there are two maps, for diffuse and opacity, that are bitmaps referencing a "PNG Image File", but no file seems to have been set on it. They default to black textures in 3dsmax. I believe it was always like this for this file.

Defining textures for the maps fixes the error.

In the previous exported .gltf I simply had no texture maps for this material (which of course incorrectly leads to different results for this material):
```
"pbrMetallicRoughness": {
				"baseColorFactor": [1.0, 1.0, 1.0, 1.0],
				"metallicFactor": 0.0,
				"roughnessFactor": 0.9
			},
			"emissiveFactor": [0.0, 0.0, 0.0],
			"alphaMode": "BLEND",
			"name": "03 - Default"
		}
```

![image](https://user-images.githubusercontent.com/3010534/33024711-21aa2032-ce0c-11e7-9ef8-71cf803a5dd9.png)

**Comment by noalak** [comment]
Next version of exporter will handle invalid/missing texture path, displaying a warning.
