### ISSUE TITLE
Exportation cancelled: Cannot find the method

### ISSUE THREAD

**Issue by jinshim** [BabylonJS/Exporters#332]
Maya2017
to glTF

Exportation stops and this message shows up from the Exporting nodes tab:

Exportation cancelled: Cannot find the method(It's written in other language so I'm not sure if this is the right wording) 'System. String Autodesk. Maya. OpenMaya. MPlug.get_asStringProperty()'

I'm very new to these programs.. help me out!

![error](https://user-images.githubusercontent.com/43852489/46510284-fd8d4e00-c882-11e8-9a5b-c4107dc61c08.png)

**Comment by kcoley** [comment]
Hi @jinshim. Do you know if your scene happens to have Unicode characters? It’s possible the exporter is failing on that.

**Comment by jinshim** [comment]
Hi @kcoley , 
Nope, I even reinstalled the window because the account was in Korean. All the directories and else are in English only...

this is the full error message:


![errormessage](https://user-images.githubusercontent.com/43852489/46515535-54088580-c89f-11e8-8be0-17650170d026.png)

**Comment by kcoley** [comment]
@jinshim ah okay.  Which version of Maya are you using?  I just noticed that there is an issue with Maya 2017.

**Comment by jinshim** [comment]
I'm using Maya2017! I even tried exporting to FBX then to glTF through other softwares but keyed animations dont come together.. Do you have any other ways to export gltf from Maya?

**Comment by kcoley** [comment]
Hi @jinshim this should now work in Maya 2017 if you get the latest release.  Thanks for flagging this issue!
