### ISSUE TITLE
Unity Exporter; Export Scene File error: [FreeImage] Library not available.

### ISSUE THREAD

**Issue by Troxid** [BabylonJS/Exporters#333]
**Version of unity**: 2018.1.3f1 
**Version of plugin**:  	"Babylon Editor Toolkit.unitypackage" 	- 3.3 Beta RC4 
**Errors**:
[FreeImage] Library not available.
Failed to convert exr file: /tmp/SCENENAME_Lightmap-1_comp_light.png
FileNotFoundException: /tmp/SCENENAME_Lightmap-1_comp_light.png does not exist
**Reason of error**:  
The plugin doesn't have a native library of FreeImage for linux-based OSs (at the `Assets/Babylon/Plugins/Utilities/`)

**Comment by deltakosh** [comment]
Pinging @MackeyK24

**Comment by Troxid** [comment]
> What OS are you running ???

KDE neon 5.13 (Ubuntu 18.04 LTS with KDE desktop environment), 64-bit

For the temporal solution i just have disabled backed light and used real-time lights and everything is working without errors

For solving problem i have tried compile FreeImage 5.18.x, place resulted *.so in the plugin folder and create the [map config](https://www.mono-project.com/docs/advanced/pinvoke/#library-names) `FreeImage.dll.config`

```
<configuration>
    <dllmap dll="FreeImage" target="libfreeimage.so" />
 </configuration>
```

The CLR got the native library, but another exceptions was threw. 
May be FreeImage 5.15.x (which used in plugin) and 5.18.0 is not binary compatible.
I will write about errors little bit later (i had deleted all files).

**Comment by MackeyK24** [comment]
Sorry ... I dont support Linux... But if you help me Gather up the Updates Assemblies for BOTH cmft (Cubemap Filter Tool 0 Command Line Edition) and the Latest FreeImage.Net Assemblies.

These are the Native PLUGINS i use... So please try and gather the latest Versions of each with the Linux Files as Well... I will then try and add Linux Support To Toolkit :)
