### ISSUE TITLE
Alpha Test not handled when exporting to PBR

### ISSUE THREAD

**Issue by sebavan** [BabylonJS/Exporters#335]
see http://www.html5gamedevs.com/topic/40472-meshes-from-3ds-max-to-babylon-have-strange-see-through-effects/?tab=comments#comment-231135

**Comment by kcoley** [comment]
I will add buttons to the exporter to enable toggling alpha blend and alpha test

**Comment by kcoley** [comment]
Support for AlphaTest is now available by setting a custom material attribute in 3ds Max.  Here is a references MaxScript: https://github.com/BabylonJS/Exporters/blob/master/3ds%20Max/MaxScripts/BabylonMaterialAttributes.ms

**Comment by cptSwing** [comment]
^ That script only works on Standard materials, correct? No custom attribute will show up on my Physical Materials, anyway.

**Comment by MarnixKuijs** [comment]
Is there anyway to get this in Maya as well? Or is there already a way to get alpha test and I just overlooked it?
