### ISSUE TITLE
Animations are removed from cameras on GLTF export

### ISSUE THREAD

**Issue by pchertok** [BabylonJS/Exporters#34]
If you export a scene with animations on the camera, they are removed when exporting to GLTF.  The camera object in Babylon will have an empty array as it's 'animations' property.  

Issue was originally reported here:

http://www.html5gamedevs.com/topic/34047-babylon-exporter-from-max-removes-camera-animations-in-gltf-export/

**Comment by noalak** [comment]
Hi,
Cameras and their animations are exported to glTF format. However, cameras are not loaded by the Babylon loader from gltf.

The cameras are not loaded but a dummy (empty mesh) is created to preserve hierarchy. This means that if you add a box as child to an animated camera, you will see the box moving.

When you drag&drop the exported gltf files into the Babylon Sandbox, the camera used is created automatically and is not related to any gltf data.

Finally, array property like 'animations' can't be seen inside the Inspector (the debug and performance layer) of the sandbox. However, you can retreive the animations using the console (press F12 > console tab > write something like this: engine.scenes[0].getMeshByName("Camera001") ).
