### ISSUE TITLE
Maya inserted colon in material names causing texture export failure

### ISSUE THREAD

**Issue by PatrickRyanMS** [BabylonJS/Exporters#341]
## Bug
When importing an OBJ file into Maya, the material names will be renamed with a colon in them like this:

**meshName:materialName**

When exporting this mesh to glTF with the Babylon exporter, an error is generated saying the exporter failed to save the bitmap because it contains an invalid character. Renaming the material to remove the colon corrects the issue and it will export correctly. We should automatically remove any invalid characters in material names from Maya as adding the mesh name and a colon is default behavior for importing meshes to prevent conflicts in object names.

![image](https://user-images.githubusercontent.com/31326855/47040748-dadd1e00-d13b-11e8-98ac-344ea42b434e.png)

[InvalidCharacterFileName.zip](https://github.com/BabylonJS/Exporters/files/2484549/InvalidCharacterFileName.zip)

**Comment by kcoley** [comment]
@PatrickRyanMS just merged a fix for this for v1.2.23: https://github.com/BabylonJS/Exporters/tree/master/Maya

**Comment by kcoley** [comment]
Feel free to reopen if the issue comes up again
