### ISSUE TITLE
[3ds Max] Ambient Occlusion not getting exported when code is ran

### ISSUE THREAD

**Issue by johanos** [BabylonJS/Exporters#346]
Hey guys, found a bug in the max exporter.

When i set these parameters through maxscript I am not getting the ambient occlusion in my models. if i do it manually from the Babylon>exporter menu. it works. It also seems to be happening for every model we run this for. 

don't know if its related to this issue https://github.com/BabylonJS/Exporters/issues/326 but even unassigning and reassinging materials manually seems to not work ( and doing this through code might not call some things that need to be updated )

here's my maxscript exporter call
```
paramLOD2 = maxScriptManager.InitParameters ("D:\3DRender\WorkingModels\gltf_pbr_lod2.glb")
paramLOD2.autoSave3dsMaxFile = false
paramLOD2.generateManifest = false
paramLOD2.exportHiddenObjects = false
paramLOD2.writeTextures = true
paramLOD2.exportOnlySelected = true
paramLOD2.scaleFactor = "100"
paramLOD2.txtQuality = "70"
paramLOD2.overwriteTextures = true
paramLOD2.exportTangents = false
paramLOD2.outputFormat = "glb"
paramLOD2.mergeAOwithMR = false
paramLOD2.exportTangents = false 


ForceCompleteRedraw doDisabled:true()

maxScriptManager.Export paramLOD2
```
I'm on the most recent version of the exporter as well
let me know if you need more info. i'm getting a sample scene ready

**Comment by deltakosh** [comment]
Pinging @kcoley

**Comment by kcoley** [comment]
@johanos I'll take a look

**Comment by kcoley** [comment]
@johanos it looks like this line is the culprit in your maxscript:

`paramLOD2.mergeAOwithMR = false`

Setting this to true allows the AO map to be exported.  I'll admit this is unclear since it took me a while to find this.  We have plans for an update to hopefully make this more clear.
