### ISSUE TITLE
Optional use of KHR_texture_transform

### ISSUE THREAD

**Issue by donmccurdy** [BabylonJS/Exporters#347]
I'm seeing bug reports from users whose materials don't look correct in threejs, and inspecting the model all of the materials contain:

```
"KHR_texture_transform": {
  "offset": [
    0.0,
    -1.0
  ],
  "scale": [
    1.0,
    -1.0
  ],
  "texCoord": 0
}
```

generator: babylon.js glTF exporter for 3ds max 2018 v1.2.40

Is this a default value in the 3DS Max exporter? Ideally it would be nice to have the option of applying the transform directly to UVs, without using the extension. If that's not possible, I think `KHR_texture_transform` should be listed in `extensionsRequired` since there is no valid fallback to the UVs here, and clients that don't support it can fail early.

**Comment by kcoley** [comment]
@donmccurdy I'll take a look

**Comment by kcoley** [comment]
@donmccurdy KHR_texture_transform is now opt-in for the 3ds Max exporter and set to required. 

Will need to do the same for Maya: https://github.com/BabylonJS/Exporters/issues/355

**Comment by donmccurdy** [comment]
Thanks — although I don't fully know what that means... textures will be written as-is, without the transform, and users need to transform them in their engine?

If the fallback (apply transform directly to UVs) isn't easy to implement for whatever reason, I could see the argument for going opt-out here too. Three.js will support `KHR_texture_transform` in our next release, with a number of caveats. Essentially, all textures on a given material must share the same transform.

**Comment by kcoley** [comment]
@donmccurdy if the texture transform checkbox is not enabled, textures would be written out without the transform applied.  It's to do with a current edge case in the glTF texture transform extension specification:

1. Two textures share a texture coordinate channel on a mesh (for example base color texture and emissive texture) and only one of these textures uses a texture transform
2.  The second texture coordinate channel is already being used by another texture (for example occlusion).  

In this case, modifying the uvs for the first texture coordinate would break one of the textures referencing the same texture coordinate channel.  Using more than two texture coordinates is against the glTF extension specification, so I cannot assign to a third texture coordinate to prevent one of the textures from breaking.

I wasn't sure of the best way to handle this, so for now, if the KHR texture transform checkbox is not enabled, it will produce a warning, indicating that texture transforms are not enabled, so the resulting texture may look incorrect.

**Comment by donmccurdy** [comment]
Ok thanks, that makes sense.

> Using more than two texture coordinates is against the glTF extension specification, so I cannot assign to a third texture coordinate to prevent one of the textures from breaking.

That isn't strictly true — conforming clients required to implement at least two UV sets. Writing 3+ UV sets is allowed, but will decrease portability of the asset.

**Comment by kcoley** [comment]
@donmccurdy ah right, I should say that it is not compliant to use more than two texture coordinates.  I want to try to keep the exporters as portable as possible.
