### ISSUE TITLE
Hardcoded copyright in glTF exports

### ISSUE THREAD

**Issue by donmccurdy** [BabylonJS/Exporters#348]
The Maya and Max exporters appear to use a hardcoded copyright value of "2017 (c) BabylonJS".

https://github.com/BabylonJS/Exporters/blob/5f435f082ff7352948e81877d834a2d7d5cba621/Maya/Exporter/BabylonExporter.GLTFExporter.cs#L51

From the spec, `copyright` is defined as:

> A copyright message suitable for display to credit the content creator.

My understanding would be that this field should be left blank, unless an end-user provides a string through some exporter setting. In other words, the copyright indicates the creator of the asset, not the creator of the generator.

**Comment by kcoley** [comment]
Thanks for flagging @donmccurdy , just merged a fix for this: https://github.com/BabylonJS/Exporters/pull/349
