### ISSUE TITLE
Max GLTFExporter: Material exportation very slow with large bitmaps.

### ISSUE THREAD

**Issue by Selmar** [BabylonJS/Exporters#35]
Exporting materials is abnormally slow. it is stuck exporting gltf materials for a long time. The total export time is 144 seconds. I don't recall it being this slow last month (same file).

Initially I thought the problem was because I had very large textures attached (multilayer .tiff, > 100 MB), however after replacing the maps with previously exported .jpg files, it still takes around 140+ seconds.

If copy textures to output is selected, the time increases to around 240 seconds (I did not test this with the smaller textures).

There is nothing abnormal about the exported materials.

![image](https://user-images.githubusercontent.com/3010534/33026869-cba38f24-ce11-11e7-9856-334cdeb01c3a.png)

```
	"materials": [{
			"pbrMetallicRoughness": {
				"baseColorFactor": [0.612745166, 0.612745166, 0.612745166, 1.0],
				"metallicFactor": 0.0,
				"roughnessFactor": 0.9
			},
			"emissiveFactor": [0.0, 0.0, 0.0],
			"name": "04 - Default"
		}, {
			"pbrMetallicRoughness": {
				"baseColorFactor": [1.0, 1.0, 1.0, 1.0],
				"baseColorTexture": {
					"index": 0
				},
				"metallicFactor": 0.0,
				"roughnessFactor": 0.9
			},
			"emissiveFactor": [0.0, 0.0, 0.0],
			"name": "09 - Default"
		}, {
			"pbrMetallicRoughness": {
				"baseColorFactor": [1.0, 1.0, 1.0, 1.0],
				"baseColorTexture": {
					"index": 1
				},
				"metallicFactor": 0.0,
				"roughnessFactor": 0.9
			},
			"emissiveFactor": [0.0, 0.0, 0.0],
			"name": "05 - Default"
		}
	],
```

**Comment by noalak** [comment]
Export duration has been drastically reduced when 'Copy textures to output' feature is disabled.

When exporting materials, images are read, each pixel is processed and resulting image is written. We are aware it's a long process, even more for larger images.
