### ISSUE TITLE
[max][gltf] some normals still bugged

### ISSUE THREAD

**Issue by tkazik** [BabylonJS/Exporters#360]
Hi folks

I recently got a model that still seems to have weird normals in certain parts. A simple model to reproduce the issue can be found here: [normal_issue.zip](https://github.com/BabylonJS/Exporters/files/2525082/normal_issue.zip)

![screenshot](https://user-images.githubusercontent.com/15689124/47648011-0539cd00-db79-11e8-92b9-7eab7dfda5ce.jpg)

My first investigations let me conclude that normals are still wrong, when a model has node rotation&scaling and a mesh has offset rotation&scaling. So this most general case is not yet covered in these [lines](https://github.com/BabylonJS/Exporters/blob/c3ee32fc88ba89400da6c95a896b0f1664b1b682/3ds%20Max/Max2Babylon/Exporter/BabylonExporter.Mesh.cs#L756).

Any ideas from your side? Thank you!

**Comment by kcoley** [comment]
@tkazik I'll take a look

**Comment by kcoley** [comment]
@tkazik can you walk us through how you authored this scene?  It would be useful to help figure out how the issue came about.

**Comment by tkazik** [comment]
Thx for the quick follow-up! 
Sure, I wrote a small maxscript, which will guide you through the necessary steps. As maxscript is not recognized as language, I paste it here as a quote:

> meshOrig =mesh vertices:#([-2.5,2,0],[-2.5,-2,0],[2.5,-2,0]) faces:#([1,2,3])
meshOrig.name = "triangle_normals_weird"
> 
> -- node transform
meshOrig.position = [-4,-0.5,3]
meshOrig.rotation = (quat 0.239118 0.369644 -0.0990457 0.892399)
meshOrig.scale = [3,2,1]
> 
> -- offset transform
meshOrig.objectOffsetPos = [1,3,2]
meshOrig.objectOffsetRot = (quat 0 0.331414 -0.191342 0.92388)
meshOrig.objectOffsetScale =[2,0.5,10]
> 
> -- create the reference
meshRef = copy meshOrig
meshRef.name = "triangle_normals_good"
meshRef.position.Y = meshRef.position.Y + 5
ResetXForm meshRef
collapseStack meshRef

And the file itself: 
[createTriangles.zip](https://github.com/BabylonJS/Exporters/files/2529394/createTriangles.zip)

**Comment by kcoley** [comment]
@tkazik so it looks like the issue is related to creating a pivot, which we would have to support in the exporter.  This would probably take a few days to implement, but in the meantime, you could manually create a child transform node and set the position as an offset, instead of setting the offset position.  Later on, this should hopefully be automated.

**Comment by tkazik** [comment]
@kcoley thank you for the hint! I was playing around with the code a bit and initially got good results by taking the normals in object space and basically undoing the offset transform to get the normals in local space. Unfortunately, this approach fails with this test model:

[test3_normalsFix_noAnim_noMat_simple.zip](https://github.com/BabylonJS/Exporters/files/2554668/test3_normalsFix_noAnim_noMat_simple.zip)

Would you mind having a look at this test model? Thank you!

**Comment by kcoley** [comment]
@tkazik sure I'll take a look

**Comment by tkazik** [comment]
The PR https://github.com/BabylonJS/Exporters/pull/370 fixes models that contain an offset transform. The first test file from above (before vs now):
![before_vs_after](https://user-images.githubusercontent.com/15689124/48312571-31aa0c00-e5b1-11e8-9239-cca2a9d55da7.png)

However, the 'test3....'-model is not fixed by this PR (model seems somehow weird and I am unable to reproduce such a model; need to ask the artist). 

Thanks for reviewing!

**Comment by kcoley** [comment]
@tkazik nice work.  Feel free to open a new issue once you find out how the model was created.
