### ISSUE TITLE
Linux support ?

### ISSUE THREAD

**Issue by voidreamer** [BabylonJS/Exporters#363]
Hi guys, is it planned or possible ?
thank you, awesome work!

**Comment by deltakosh** [comment]
Which exporter?

**Comment by voidreamer** [comment]
Sorry, forgot to mention, I mean the Maya exporter

**Comment by kcoley** [comment]
@voidreamer we talked about wanting to support this, though this would take some time as we would have to rewrite the Maya exporter in Python instead of C#.  But this way, it would also work on Mac OS and Linux.

**Comment by tkazik** [comment]
Also adding here the discussions of a forum post on autodesk: python vs C++

https://forums.autodesk.com/t5/3ds-max-programming/using-python-and-max/td-p/6863447

I would vote for C++ ;)

**Comment by deltakosh** [comment]
#381
