### ISSUE TITLE
GLTF IMPORT

### ISSUE THREAD

**Issue by KOTETOhub** [BabylonJS/Exporters#364]

**Comment by deltakosh** [comment]
I guess we could have a better description as well:)

**Comment by KOTETOhub** [comment]
sorry! i didn't open this issue conciously! ‚
I thought I was searching for a topic...
I wish to import glTF files downloaded from Sketchfab into Autodesk Maya 2015 on my OSX

**Comment by KOTETOhub** [comment]
I'm completly new here, and don't even know if this is the right place to ask this :-)

**Comment by kcoley** [comment]
@KOTETOhub no worries! I have an issue for this here already: 

https://github.com/BabylonJS/Exporters/issues/184

I plan on working on this once I fix some standing bugs in the Maya and Max exporters.  Feel free to track progress there!

**Comment by KOTETOhub** [comment]
oh! thanks!
