### ISSUE TITLE
[Max] Export diffuse color even if a diffuse map is specified

### ISSUE THREAD

**Issue by Remi-Tribia** [BabylonJS/Exporters#367]
Hi,

Me again... I noticed that when a diffuse map is set on a Physical Material, the rgb color is ignored and replaced by pure white. It could be useful to export the rgb value specified instead of pure white to be able to tint the material in webgl without the need to use several colored maps.

In my case, I need multiple tints of fabric, I would put a greyscale map in diffuse and tint it with the color value.

Cheers!

**Comment by kcoley** [comment]
Hi @Remi-Tribia just merged a fix for this.

**Comment by Remi-Tribia** [comment]
Hi,
The fix works great, though I noticed a side effect I haven't anticipated...
Consider a transparent material, without diffuse map (only transparency map) and RGB color. Since the transparency map is applied to the alpha of the diffuse map, the exporter generates a PNG `baseColorTexture` with the RGB color specified but still keeps the RGB color value in `baseColorFactor`, so the result is `color = baseColorFactor (from generated color map) * baseColorFactor (from rgb value)`

A solution would be to either keep the baseColorFactor in numbers and put white in the generated PNG ?
