### ISSUE TITLE
[Max][glTF] Exporting .max into several glTF files.

### ISSUE THREAD

**Issue by Selmar** [BabylonJS/Exporters#368]
Hi!

We would like to export separate scenes into one .gltf file.

I imagine it would work by somehow specifying a node as a scene root, which can optionally transform all its children to the scene root node's space (i.e. make it the origin of all its children).

This would simplify exporting many objects that are defined in the same 3dsmax file.

**Comment by Remi-Tribia** [comment]
What do you call separate scenes? Separate .max files?

Cause what you are explaining is just like adding a dummy and parent all other objects to it, then export everything with the exporter.

I mainly work with Three.js (so BabylonJS might import gltf differently) but when I do that (parent dummy or grouped objects) it creates an empty Group object in which every children is parented.

**Comment by Selmar** [comment]
No, one .max file, several glTF scenes: https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#scenes

It's not parenting, it's really a different scene definition; it's much like having separate glTF files.

Right now, the artists have to select the relevant objects and export them to separate gltf files, which takes a large part of their time in some cases.

**Comment by Selmar** [comment]
Actually, come to think of it. If we export several scenes into the same glTF file, we would have to export every scene every time we change one object (which is related to only one scene). This would also cost a lot of time.

I guess a better solution may be to have some kind of scene export configuration; being able to specify which object goes where and whether to reset the pivot, being able to export only the selected "glTF objects", etcetera. Does this make sense to you?

Since we want this kind of tool relatively fast, I would like to implement this this functionality in the babylon exporter. If you are okay with that, we should discuss some implementation details (mostly UI, I guess).

If not, I will probably do something with maxscripts, but this is more difficult to integrate neatly with the exporter.

**Comment by Selmar** [comment]
Perhaps we could even combine the scene and separate gltf export functionalities, but I guess exporting separate gltfs is enough; I will talk to the artists.

**Comment by Selmar** [comment]
I have changed the title to reflect what I would like to add to the exporter.

Instead of having a single file to export to, one would build a list of nodes with export target files. By default it would reference the root node (and thus export everything into one file), with the export target being the name of the `.max` file and the output folder where the `.max` file is.

Some options would be per export, some would be global.

It could be a separate export window if you wish to have both workflows?

Let me know what you prefer.

**Comment by kcoley** [comment]
> Instead of having a single file to export to, one would build a list of nodes with export target files

@Selmar would the list of nodes be groups with export target files, or something else?  If groups, the behavior can probably be toggled with a checkbox in the exporter.  Or did you have something else in mind?

**Comment by Selmar** [comment]
Yes, something like that. A checkbox is a bit odd, perhaps a tab or fold-out pane?

The biggest difficulty is perhaps that the list requires a vertical panel, where the current file export part of the panel is more horizontal, but they both want the logging output part.

**Comment by Selmar** [comment]
Closing! Although there are some more things I would like to implement, the basics are there.
