### ISSUE TITLE
[Max][glTF] Exporter quadruples vertices on export 

### ISSUE THREAD

**Issue by EtagiBI** [BabylonJS/Exporters#369]
Hello,

We're trying to use Babylon's 3DS Max exporter to get glTF files. Unfortunately, the exporter quadruples vertices on export, so output glTF files become very big.

Our export setting are as follows:
![default](https://user-images.githubusercontent.com/20855725/48210456-28deed80-e399-11e8-84b9-9c8da99ec695.png)

Here're our source MAX model and exported glTF model:

[Models.zip](https://github.com/BabylonJS/Exporters/files/2562461/Models.zip)

As you can see, BIN file is extremely big (should be around 1 Mb).

**Comment by Selmar** [comment]
Try selecting all your nodes > right-click > babylon properties, and tick `try optimize vertices`. This should help a lot.

**Comment by Selmar** [comment]
Similarly, if you are using animations, in some cases (especially for rotations) it is very helpful to disable animation optimization:
unselect all nodes > right-click scene background > babylon properties > tick `Do not optimize animations`

**Comment by EtagiBI** [comment]
> Try selecting all your nodes > right-click > babylon properties, and tick `Try to optimize vertices`. This should help a lot.
Thanks, it worked!

Shouldn't it be the exporter option?

**Comment by Selmar** [comment]
I feel the same way. @deltakosh, are there any known cases where it must be disabled (for a specific mesh)?

**Comment by deltakosh** [comment]
We decided to not use it as default because it is a rather expensive process that can make the exportation last forever

**Comment by Selmar** [comment]
That's also the reason for having it per-mesh rather than as a global exporter option?

**Comment by Selmar** [comment]
Alright!

I guess we can close this one, @EtagiBI ?
