### ISSUE TITLE
[Max][glTF] Saving export options as default template

### ISSUE THREAD

**Issue by EtagiBI** [BabylonJS/Exporters#378]
Hello,

It would be very useful to have an option to save current export options as default template: output format, scale factor, texture quality, all the ticks.  

Is it possible?

**Comment by deltakosh** [comment]
@kcoley is on vacations for a week but will get back to you asap:)

**Comment by kcoley** [comment]
@EtagiBI thanks for the feature request.  I think this is a good idea.  It would take me some time to get to it as I fix some pending bugs in the exporters, though if you think you can make a PR I would be happy to review it for merge.

**Comment by deltakosh** [comment]
We will rework the UI completely so closing this one for now
