### ISSUE TITLE
Max GLTFExporter: Object reference not set #2

### ISSUE THREAD

**Issue by Selmar** [BabylonJS/Exporters#38]
This is maybe similar to the other bug with unselected bones, but not the same. Everything is to be exported here, as you can see.

It is an old model (> 5 years), so something here may be invalid. I have no idea what. The last mentioned mesh by the exporter looks like a simple editable mesh. No skin, no animation. I don't know what the next mesh to export would be, the last exported mesh is in the middle of a bunch of meshes that haven't been processed yet.

![image](https://user-images.githubusercontent.com/3010534/33080077-7f7fc59c-ced7-11e7-885c-32d80044b9b0.png)

**Comment by deltakosh** [comment]
Can you share the file?
Pinging @noalak

**Comment by Selmar** [comment]
Perhaps in a private message, I'll have to ask.

**Comment by deltakosh** [comment]
We cannot debug without a repro:(

**Comment by Selmar** [comment]
I understand that may be difficult, yes. I'll update when I have a file I can give to you.

**Comment by Selmar** [comment]
Okay, so I can not share the file. I can not see anything strange about the meshes that seem to throw exceptions either.

Perhaps I can debug it myself? How would I go about that? I cloned the repository, so I have the code already.

**Comment by Selmar** [comment]
I have started to debug it myself, the problem seems to be related to materials. The only materials in the scene are unsupported materials.

There is a babylon mesh which has a non-null `materialId`, however the material can not be found: `babylonMaterial` and `babylonMultiMaterial` are null here. `babylonMaterials` is an empty list, `babylonMultiMaterials` contains 3 materials, but not the referenced one.

![image](https://user-images.githubusercontent.com/3010534/33129448-282f9ef2-cf90-11e7-9d18-6ff2c39d4a74.png)

I also found this:
![image](https://user-images.githubusercontent.com/3010534/33129746-4f186fde-cf91-11e7-8ee3-6c4088d5ea34.png)

**Comment by deltakosh** [comment]
Hello, this is really helpful 
@noalak will check soon

**Comment by Selmar** [comment]
Just fyi, I'll be on vacation until next Tuesday! \o

**Comment by deltakosh** [comment]
No worry...Have fun :D
