### ISSUE TITLE
OS X / linux support for Maya exporter

### ISSUE THREAD

**Issue by smasherknock** [BabylonJS/Exporters#381]
Any progress on OS X support for the Maya exporter? I could use this functionality.

**Comment by sebavan** [comment]
Pinging @bghgary

**Comment by sebavan** [comment]
Our exporter devs are in vacation at the moment, so this will be check in about a week :-)

**Comment by kcoley** [comment]
Hi @smasherknock .  Mac OS and Linux support have been discussed and there are plans on implementing it.  Though the delay is that the Maya exporter would have to be completely rewritten from scratch using either Python (leaning towards this) or C++.  Unfortunately work has not begun on this yet, as I have been resolving the standing issues with the current Maya and Max exporters.  However I plan on starting work on this once the major issues have been resolved.

**Comment by tkazik** [comment]
@kcoley Nice to hear that you are considering a rewrite! If I may jump on this discussion and add my two cents here: C++ seems to be the fastest, most stable and well-documented SDK, see: 

https://forums.autodesk.com/t5/3ds-max-programming/using-python-and-max/td-p/6863447

Thank you for considering that...looking forward to your progress!

PS: I am more interested into Max than Maya :)

**Comment by deltakosh** [comment]
Closing for now as we do not have plan to add OSX and Linux (for now). Will create a new one if the plans change

**Comment by dill0wn** [comment]
Would the Maya exporter need to be completely rewritten? C# and .NET Core is supported on macOS and Linux as well.
