### ISSUE TITLE
Scene property "export morph normal" is not respected initially

### ISSUE THREAD

**Issue by tkazik** [BabylonJS/Exporters#382]
Hi folks

Another (hopefully minor) issue: Normals of morph objects are not exported by default, although the checkbox under scene properties is checked. Un-checking and checking the button again fixes this, so this looks like an initialization issue to me. The code looks fine, but the following line returns 'false' if the checkbox is not re-checked:

https://github.com/BabylonJS/Exporters/blob/3c0d6dccc23ee9777c133c06aa56e56c16cf4f2c/3ds%20Max/Max2Babylon/Exporter/BabylonExporter.Mesh.cs#L503

The dummy file: 
[morpher01.zip](https://github.com/BabylonJS/Exporters/files/2591830/morpher01.zip)

The scene properties:
![exportmorphnormals](https://user-images.githubusercontent.com/15689124/48661677-2d309800-ea76-11e8-9feb-3067bac353e2.png)

Looking forward to your insights!

**Comment by sebavan** [comment]
Our exporter devs are in vacation at the moment, so this will be check in about a week :-)

**Comment by kcoley** [comment]
@tkazik sorry for the delay, I'll take a look at this issue soon

**Comment by kcoley** [comment]
Hi @tkazik I just merged a fix for this: https://github.com/BabylonJS/Exporters/blob/master/3ds%20Max/Max2Babylon-1.3.15.zip
