### ISSUE TITLE
[Max] Texture transform does not match when modified both Offset and Tiling

### ISSUE THREAD

**Issue by Ben-Mack** [BabylonJS/Exporters#383]
Modified only Tiling:  result matched  ✔️
![tiling only](https://user-images.githubusercontent.com/6309393/48671376-91785800-eb59-11e8-9009-5d4fdbe4d133.PNG)

Modified only Offset:  result matched  ✔️
![offset only](https://user-images.githubusercontent.com/6309393/48671384-a2c16480-eb59-11e8-9929-7b86cd9601eb.PNG)

Modified both Tiling + Offset: Incorrect result between 3ds Max and glTF output ❌
![offset tiling](https://user-images.githubusercontent.com/6309393/48671392-cb495e80-eb59-11e8-9f41-40a964a4f6f4.PNG)

I'm using 3ds Max 2018, these files were exported with KHR_texture_transform enabled.

**Comment by sebavan** [comment]
Our exporter devs are in vacation at the moment, so this will be check in about a week :-)

**Comment by kcoley** [comment]
@Ben-Mack this was trickier than expected, but I made an update to texture transform export for glTF.  Feel free to test and open an issue if you hit any other issues.
