### ISSUE TITLE
[Max][glTF] Merge AO Map vs. different UVs

### ISSUE THREAD

**Issue by echadwick-wayfair** [BabylonJS/Exporters#385]
Max2Babylon 1.3.9
3ds Max 2018.4

1. Create and Ambient Occlusion, Roughness, and Metalness maps, all JPG and the same pixel resolutions (512x512 for example).
2. Connect them into a Physical Material.
3. For Roughness and Metalness, specify UV channel 1.
4. For Ambient Occlusion, specify UV channel 2.
5. Assign to a mesh primitive that has two UV channels.
6. Exporter: format GLB, Merge AO Map, Export Materials, Export only selected, Export & Run.

Result: AO/Rough/Metal are combined into a single ORM map, but AO is forced to use UV channel 1.

I would like to pack all three maps into the ORM, but use different UV channels. If there was a limit with shader permutations, then it would be OK if only AO could use a different channel. But it'd be nice if each O/R/M could use different UVs if that was needed for some reason.

![image](https://user-images.githubusercontent.com/40177036/48717718-faa6ac80-ebe7-11e8-8a3f-931514548c66.png)

![image](https://user-images.githubusercontent.com/40177036/48718166-d7303180-ebe8-11e8-820e-976fb3046580.png)

![image](https://user-images.githubusercontent.com/40177036/48718279-1068a180-ebe9-11e8-9535-ec7655d7f9ee.png)

![image](https://user-images.githubusercontent.com/40177036/48717839-33df1c80-ebe8-11e8-92e4-6acb94d5875b.png)
(Merge AO Map = enabled. Not the intended result)

![image](https://user-images.githubusercontent.com/40177036/48717877-435e6580-ebe8-11e8-8f94-ecc3c3bd9668.png)
(Merge AO Map = disabled. Intended visual result.)

**Comment by Selmar** [comment]
The code looks like this:

```
    if (exportParameters.mergeAOwithMR)
    {
        babylonMaterial.occlusionTexture = ormTexture;
    }
    else
    {
        babylonMaterial.occlusionTexture = ExportPBRTexture(materialNode, 6, babylonScene);
    }
```

One texture object stores only one coordinate set, hence the problem. The texture object should be duplicated. However, right now, this would lead to multiple texture exports, so this should probably be tackled first (#386).

**Comment by sebavan** [comment]
Our exporter devs are in vacation at the moment, so this will be check in about a week :-)

**Comment by kcoley** [comment]
@echadwick-wayfair @Selmar I'll take a look at this after fixing texture cloning

**Comment by echadwick-wayfair** [comment]
Thanks Kacey!

Initial reasoning was to tile Roughness and Metalness but not AO. 

For example a red plastic table with tiled "fingerprints/scratches" roughness, and a tiling goldleaf pattern requiring tiled metalness and albedo.

But also interested in tiling Roughness but not tiling AO and Metalness. Start with the same example red table, except now it has metal feet, so the Metalness needs to use a non-tiling atlas UV.

**Comment by kcoley** [comment]
@echadwick-wayfair I made an update to have AO tiled differently from Roughness and Metalness.  

Roughness and Metalness are assumed to be one texture in glTF and BabylonJS, so unfortunately I was not able to have them separately tileable.

Feel free to raise an issue if you hit any problems with this!
