### ISSUE TITLE
[Max][glTF] Texture cloning

### ISSUE THREAD

**Issue by EtagiBI** [BabylonJS/Exporters#386]
Hello,

Models that have one texture applied to different slots of a material (e.g. diffuse and bump) are exported with cloned textures (e.g. one for diffuse and one for bump). Although this problem is caused by inappropriate texturing, it would be nice to check it and prevent the exporter from creating clones.

**Comment by sebavan** [comment]
Sounds reasonable to me, @kcoley will be back in a week for review

**Comment by kcoley** [comment]
@EtagiBI I just merged a fix for this (https://github.com/BabylonJS/Exporters/pull/411)
