### ISSUE TITLE
Skin breaking when exporting model from Max

### ISSUE THREAD

**Issue by PatrickRyanMS** [BabylonJS/Exporters#387]
# Bug
When exporting a skinned FBX model with animation from Max 2019 using the latest exporter and the same FBX file from Maya 2019 with the latest exporter, I am noticing the Max export skin breaks. In the image below, the Max export is on the left and the Maya on the right. I will supply @kcoley with files for investigation.

![maxmayacomparison](https://user-images.githubusercontent.com/31326855/48866986-89066400-ed89-11e8-9b65-48a24886ad4d.png)

**Comment by sbtron** [comment]
Closing as no repro. If there is more info on original asset please reopen
