### ISSUE TITLE
[Max] Problem with Guid generation

### ISSUE THREAD

**Issue by Selmar** [BabylonJS/Exporters#389]
**Guid generation problem:**
Right now, a guid conflict can still happen. It will cause an invalid export once, after which the guid conflict will be solved. This may cause invalid exports which miraculously go away after a second export. So I think we should solve it.

It may happen in these cases (though it should be very rare):
- when merging max scenes (unsure if the appdatachunk is merged too)
- when cloning IAnimatable objects (unsure if the appdatachunk is cloned too)
- when exporting old assets that were created before GUID uniqueness was checked
- when exporting parts of a scene separately, where equal guids are created independently, and after that exporting them together

I see three solutions:
- Use an identifier guaranteed to be unique for an `IAnimatable` (I don't think this is available)
- Restart the entire export process
- Don't store Guids in the appdata chunk, but rather regenerate them on every export
  - It was like this before, but for some reason saving it was re-introduced? (removed #256, reintroduced 29th of august by @noalak)

**Comment by sebavan** [comment]
Adding @kcoley for review

**Comment by kcoley** [comment]
Hi @Selmar I'll take a look when I finish up some pending issues.  I was OOF the other week so wasn't able to get back to issues.

**Comment by kcoley** [comment]
Hi @Selmar do you have a sample file that repros this?

**Comment by Selmar** [comment]
Not anymore, unfortunately. Also, anyone who encounters this would likely dismiss it as "one of those weird one-time problems", so I also doubt we'll ever get a useful bug report for it.

**Comment by Selmar** [comment]
I suppose you could "repro" it by modifying the function that creates the GUID to sometimes generate an identical one?

GUID conflicts should be very rare to begin with. It does not seem unlikely to me that the GUID value in the appdatachunk is copied when an object is cloned, as mentioned in the original post. This would make sense, thinking about the bug that caused me to track down the issue.

**Comment by kcoley** [comment]
@Selmar that makes sense.  This seems to happen rarely, so I think we can close this for now.  But if it becomes a bigger issue, feel free to reopen this.  Otherwise, it may be tricky to ensure all guids are always unique across different authoring scenarios. Thanks for flagging!
