### ISSUE TITLE
[Max][glTF] Export folder becomes read only after export

### ISSUE THREAD

**Issue by EtagiBI** [BabylonJS/Exporters#391]
Hello,

Some models make export folder "read only" after export. Here's the console text:
![image](https://user-images.githubusercontent.com/20855725/49012328-e55af080-f19a-11e8-9d61-a2f17c744791.png)

Test model:
[Model.zip](https://github.com/BabylonJS/Exporters/files/2615351/Model.zip)

**Comment by kcoley** [comment]
@EtagiBI I'll take a look when I get some cycles.  I was OOF the other week and catching up on the issues while I was out.

**Comment by kcoley** [comment]
@EtagiBI I wasn't able to reproduce with the file you provided.  Is the issue still happening on your end?

**Comment by EtagiBI** [comment]
It seems that the problem was caused by source folder with MAX files. This folder was marked as read only. I removed the tick and everything worked.
