### ISSUE TITLE
Blender exporter exports wrong skeletonId

### ISSUE THREAD

**Issue by halkmund** [BabylonJS/Exporters#395]
Module: Blender Exporter.

**Steps to reproduce**:

In Blender: 
Select a mesh and its armature in a scene with mutliple armatures.
Use the exporter in Export Selected.

Result: The babylon.js contains a skeleton with an incorrect skeleton ID. (e.g.: mesh.skeletonId = 2, skeleton.id = 0). The loader then fails to load the skeleton.

**Discussion**:

Cause: This is caused by lines 84 to 90 in the file [mesh.py](https://github.com/BabylonJS/Exporters/blob/master/Blender/src/babylon-js/mesh.py) where the skeletonId is derived from scene.objects which in this case can result in the wrong id.

Possible Fix: The skeleton is available in that scope, so maybe just use skeleton.id instead of trying to calculate the skeletonId.

PS: if I find the time I will create a pull request myself ...

**Comment by Palmer-JC** [comment]
Good find.  I did not add export [Exported selected feature](https://github.com/BabylonJS/Exporters/commit/4da6f638e4a02d423910ab964a4cde3609983e8e#diff-875f5df5e6edddcfa7dbf0f20ad1b63d), 

The fact that you could diagnose probably means that you could at least figure out that a work around of low impact is to just put the desired mesh onto a unique layer & use selected layers instead (assuming that still works).

Though I have a separate branch, EEVEE, where I am currently working, was not really going to do any further changes to master.  If you PR something on master, will certainly update EEVEE.

Will address in that branch.  Blender 2.80 does stuff with layers that I do not understand yet, so  knowing the old code did fully work could be very useful.

**Comment by Palmer-JC** [comment]
@halkmund I have made changes to a test of the exporter for Blender 2.80.  There is a fix for your problem, if you wish to run your .blend file through, & report results.  See forum [topic](https://forum.babylonjs.com/t/blender-eevee-cycles-testing/124/6).

Not actually running on 2.80, yet so test on 2.79.  The major changes are to processing of cycles materials.  If you are using internal render materials, probably want to delete & switch cycles.

**Comment by halkmund** [comment]
@Palmer-JC  Running the original .blend file through the 6.0 alpha resulted in "Animation does not have a .to_scene_file() method". So the export failed. After deleting my animations the resulting babylon file did not contain the SkeletonId attributes anymore so I could not check if your fix works. I think we probably wait until 6.0 is more stable to test the skeleton ID fix. It will be a trivial check then, au contrair: I've spent two hours now adjusting my .blend file just to get the 6.0 alpha exporting ;) ...

Anyway, cudos for taking this up. And good luck with the 6.0 version!!!
