### ISSUE TITLE
[max][gltf] Issue with last frames of animation

### ISSUE THREAD

**Issue by tkazik** [BabylonJS/Exporters#396]
Hi folks

Another issue discovered recently: I noticed that the animation stops a bit early for the model (attached below) if using the frame slider. Please see the screenshot of the sandcastle for details:

![frame_issue](https://user-images.githubusercontent.com/15689124/49451481-8ec76500-f7df-11e8-8b63-190222799b5b.png)

As seen in the screenshot above, the slider for 'current frame' stops at frame 3.30 out of 3.33 while stepping through the frames. I don't think it is an issue with the viewer, but rather with the export settings of the animation. However, I wasn't able to figure out a solution.

The model (glb and max):
[engine_rev.zip](https://github.com/BabylonJS/Exporters/files/2644598/engine_rev.zip)

I appreciate your help and insight!

Edit:
An even simpler model:
[simple_cube_rotation.zip](https://github.com/BabylonJS/Exporters/files/2645597/simple_cube_rotation.zip)

**Comment by kcoley** [comment]
@tkazik I'll take a look

**Comment by kcoley** [comment]
@tkazik it looks like it does set the animation to 3.33 when you use the bottom slider, but it is not displayed in the inspector UI.  I created an issue here to track that bug fix: https://github.com/BabylonJS/Babylon.js/issues/5599
