### ISSUE TITLE
[Max]binary babylon problem from 3ds max exporter 2019 - Max2Babylon-1.3.10

### ISSUE THREAD

**Issue by kristiansvenssonwsp** [BabylonJS/Exporters#397]
Hi!

I'm using the the 2019 version of the 3ds max exporter. Version Max2Babylon-1.3.10
Im on Windows 10.

When I choose to export as "binary babylon" I can see that the exporter logs the message "Generating binary files" and the files seems to be generated in a temp folder. (Saving C:\Temp\xxxxx\Binary\xxx.binary.babylon) However in the next step only the .babylon gets copied, the .binary.babylon file does not get copied/created in my specified output folder.

Any ideas?

**Comment by kcoley** [comment]
@kristiansvenssonwsp I'll take a look

**Comment by kcoley** [comment]
@kristiansvenssonwsp just merged a fix for this (https://github.com/BabylonJS/Exporters/blob/master/3ds%20Max/Max2Babylon-1.3.11.zip).  Feel free to reopen if the bug comes up again!

**Comment by kristiansvenssonwsp** [comment]
Thanks! It now copies the .binary.babylon to the output foilder. However there is another problem, the .babylonbinarymeshdata(which is referenced in the .binary.babylon) files dont get created and copied to the output folder. I'll start another issue regarding that.
