### ISSUE TITLE
Add support for morph targets in 3dsmax exporter

### ISSUE THREAD

**Issue by deltakosh** [BabylonJS/Exporters#4]
@noalak can you provide a sample scene for the morph target in the exporter folder?

**Comment by deltakosh** [comment]
https://github.com/BabylonJS/Babylon.js/issues/2664

**Comment by noalak** [comment]
In the AnimatedMorphCube you can find a FBX file with a morph target example.

The scene only shows a single morphed cube, but other hidden meshes are used as morph targets for this cube.
Morphed cube is animated.

**Comment by deltakosh** [comment]
OK perfect
