### ISSUE TITLE
3d Max export have choose between PBRMetallicRoughnessMaterial and PBRMaterial

### ISSUE THREAD

**Issue by Hersir88** [BabylonJS/Exporters#40]
As there are significant differences between PBRMetallicRoughnessMaterial and PBRMaterial features  but they both support MetallicRoughness workflow, would be nice if there could be some drop down or other way to specify what type you want to export, as right now to use features that are available only in PBRMaterial you need to manually parse exported file and rename fields.

**Comment by sebavan** [comment]
@Hersir88 What features do you miss from the PBRMaterial in the simple ones ?

**Comment by deltakosh** [comment]
Up
