### ISSUE TITLE
[Max] binary babylon problem from 3ds max exporter 2019 - Max2Babylon-1.3.12

### ISSUE THREAD

**Issue by kristiansvenssonwsp** [BabylonJS/Exporters#401]
Hi!
A recent fix was made for "binary babylon" export:
https://github.com/BabylonJS/Exporters/issues/397

However there is another problem as well. When exporting to "binary babylon", one or several ".babylonbinarymeshdata"(which is referenced in the .binary.babylon) files should get created and copied to the output folder but they don't.

**Comment by kcoley** [comment]
@kristiansvenssonwsp I'll make a fix to also export the .babylonbinarymeshdata file.

**Comment by kcoley** [comment]
@kristiansvenssonwsp just merged a fix for this (https://github.com/BabylonJS/Exporters/blob/master/3ds%20Max/Max2Babylon-1.3.13.zip)

**Comment by kristiansvenssonwsp** [comment]
Thanks. Works well now!
