### ISSUE TITLE
[Max][glTF] Problem when multiple textures (pointing to the same image) has different transform

### ISSUE THREAD

**Issue by Ben-Mack** [BabylonJS/Exporters#409]
In a scene with multiple textures pointing to the same image, but each one has a different transform value, then gltf output will be wrong (same transform value on these textures). Babylon format output is correct, please see these screenshots:

Original file in Max, left plane has tiling value of 1.0, the right plane has tiling value of 2.0, both pointing to the same image:
![max](https://user-images.githubusercontent.com/6309393/50042659-9cf76a00-0098-11e9-969d-92e2a519cdcb.PNG)

Result in babylon format ✔️ 
![babylon](https://user-images.githubusercontent.com/6309393/50042661-9f59c400-0098-11e9-9b57-8047b8324fa2.PNG)

Result in glTF format ❌ 
![gltf](https://user-images.githubusercontent.com/6309393/50042664-a1238780-0098-11e9-8ffb-488cb8207d1d.PNG)

Download output files here: 
[tx-transform-babylon-gltf-output.zip](https://github.com/BabylonJS/Exporters/files/2682582/tx-transform-babylon-gltf-output.zip)

**Comment by kcoley** [comment]
@Ben-Mack just merged a fix for this: https://github.com/BabylonJS/Exporters/blob/master/3ds%20Max/Max2Babylon-1.3.17.zip

**Comment by Ben-Mack** [comment]
Thank @kcoley for very quick update! 
But the problem still exist in the latest version v1.3.18, can you recheck it?

**Comment by kcoley** [comment]
@Ben-Mack interesting, sure I'll double check.  Do you have a sample max scene that repros the issue?

**Comment by Ben-Mack** [comment]
Yes, my material setup is different. 

This issue will occurs if you use StandardMaterial (work fine on PhysicalMtl though).

**Comment by kcoley** [comment]
@Ben-Mack I just made another update, which should now allow StandardMaterials to export.  Let me know if you hit any other issues!

**Comment by Ben-Mack** [comment]
I confirm this issue is solved. Thank you!
