### ISSUE TITLE
[Max][glTF] Convert bump maps to normal maps

### ISSUE THREAD

**Issue by EtagiBI** [BabylonJS/Exporters#412]
Hello,

According to GLTF specifications bump maps aren't supported. I can confirm that all bump maps applied to meshes in 3DS Max produce ugly metallic effect in exported GLTFs. It would be very useful to convert bump map to normal map either in Babylon properties or during export.

**Comment by deltakosh** [comment]
Hello. They are exporters only. We do not want to update assets on behalf of the artist. They are several tools already available that can do the conversion:)

**Comment by EtagiBI** [comment]
> Hello. They are exporters only. We do not want to update assets on behalf of the artist. They are several tools already available that can do the conversion:)

Ok, I see. 
I would like to clarify one thing though. In documentation it says "The bump map (or normal map) and its weight are used.". When I export a model with Bump map, I get an ugly metallic cover on my model. When I export a model with Normal map, I get the error: "Texture type is not supported. Use a Bitmap instead.". That's confusing =/. What should I do to keep bump effect after export?

Here're my model:
[CUBES.zip](https://github.com/BabylonJS/Exporters/files/2693439/CUBES.zip)

**Comment by EtagiBI** [comment]
> I guess this is a doc issue as we only support normal maps.

It would be nice to know a correct node setup for normal maps then. Standard scheme "Bitmap->Normal Bump -> Material" doesn't work with exporter.
