### ISSUE TITLE
Y, Z axis reversal

### ISSUE THREAD

**Issue by lc8882972** [BabylonJS/Exporters#417]
[Max][gltf]Do you support Y, Z axis reversal?

**Comment by sebavan** [comment]
ping @kcoley . Please expect a bit of delay on the answer due to the holiday season.

**Comment by kcoley** [comment]
Hi @lc8882972 , can you explain more on what you mean by Y Z axis reversal?

**Comment by kcoley** [comment]
@lc8882972 gotcha,
glTF uses a right-handed coordinate system: https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#coordinate-system-and-units

In this case, the axis for X, Y and Z are strictly defined so an axis reversal is not needed.  glTF importers should treat the file as if it were right-handed.  

The obj file format does not have a specified handedness.  The Y, Z axis reversal option is provided to help import obj files to engines which make an assumption as to what handedness the obj file was authored in.

Hopefully this makes sense!
