### ISSUE TITLE
[Max][glTF] URIs should be percent-encoded?

### ISSUE THREAD

**Issue by Ben-Mack** [BabylonJS/Exporters#419]
According to [glTF URIs specs](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#uris):

> Reserved characters must be percent-encoded

Currently Max glTF Exporter does not encode special characters in URI, so the viewer will fails if URI contains unsafe url character.

![uris-404](https://user-images.githubusercontent.com/6309393/50463283-6507f500-09bd-11e9-8b4e-2e6debdf57b9.PNG)

**Comment by kcoley** [comment]
Hi @Ben-Mack.  Which special characters are being used in the generated glTF?  Do you have a sample file?

**Comment by Ben-Mack** [comment]
Please download the generated glTF here: [babylon bug special character.zip](https://github.com/BabylonJS/Exporters/files/2711759/babylon.bug.special.character.zip)

Just a `#` in texture file name (like `#sample.jpg`) can break the sandbox with error `404 not found`, but only when the Sandbox was opened by `Export and run` command. 

File can be open successfully if I manually drag & drop these generated files into the sandbox.
![capture](https://user-images.githubusercontent.com/6309393/50470410-efaf1b00-09e2-11e9-8e45-945d84405486.PNG)

**Comment by kcoley** [comment]
@Ben-Mack in this case, I ended up having to change the name of the output textures for "Export and run" to work as expected.  I just merged a fix for this.  It will replace special characters with "_" as well as produce a warning about the name modification in the output log.

**Comment by Ben-Mack** [comment]
Thank @kcoley for the quick fix! 

May I ask a question, why you use this approach instead of something like `Uri.EscapeDataString` - which I think is more universal?

**Comment by kcoley** [comment]
@Ben-Mack thanks for the suggestion, I agree that `Uri.EscapeDataString` is a much better fix for this, though this too also causes an error when using `Export & Run`:

![image](https://user-images.githubusercontent.com/3946928/50527915-39aa0680-0aa0-11e9-9c13-8087ff35ea49.png)

![image](https://user-images.githubusercontent.com/3946928/50527928-4d556d00-0aa0-11e9-9961-14ff8c6eca44.png)

However, this works fine when dragging and dropping into the sandbox manually.  

I will re-implement using `Uri.EscapeDataString`, though the texture name resolution may need to be file separately on the Babylon.js main repo for the sandbox.

Below is a sample export with the new change I will implement:
[test.zip](https://github.com/BabylonJS/Exporters/files/2715689/test.zip)
