### ISSUE TITLE
Incorrect indices when saving to json

### ISSUE THREAD

**Issue by gsrmeen** [BabylonJS/Exporters#422]
I already described my problem here:

https://stackoverflow.com/questions/53987062/exporting-blender-mesh-to-json-with-babylon

**Comment by kcoley** [comment]
@gsrmeen the indices seem to be correct.  Based on your question, here is a sample playground which constructs the cube based on the indices and positions from the babylon file: 

https://playground.babylonjs.com/#0YHD7Y

For your custom tool, you may need to take into account handedness.  Babylon.js is left-handed by default, so the indices and positions are assuming you are in a left-handed coordinate system, where +z is into the screen, +y is up and +x is to the right.  If you are trying to import into a right-handed coordinate system, you will need to modify the position values.  

When constructing your triangles, you will need to use the indices to index into the positions to get the values, which should get you something like this:
```
positions = [1, -1, -1, -1, -1, 1, 1, -1, 1, -1, 1, 1, 1, 1, -1, 1, 1, 1, -1, -1, -1, -1, 1, -1]
indices = [0, 1, 2, 3, 4, 5, 5, 0, 2, 4, 6, 0, 6, 3, 1, 2, 3, 5, 0, 6, 1, 3, 7, 4, 5, 4, 0, 4, 7, 6, 6, 7, 3, 2, 1, 3]

// 12 triangles, where three tuples represent the triangle vertices
0: [(1, -1, -1), (-1, -1, 1), (1, -1, 1)]
1: [(-1, 1, 1), (1, 1, -1), (1, 1, 1)]
2: [(1, 1, 1), (1, -1, -1), (1, -1, 1)]
3: [(1, 1, -1), (-1, -1, -1), (1, -1, -1)]
4: [(-1, -1, -1), (-1, 1, 1), (-1, -1, 1)]
5: [(1, -1, 1), (-1, 1, 1), (1, 1, 1)]
6: [(1, -1, -1), (-1, -1, -1), (-1, -1, 1)]
7: [(-1, 1, 1), (-1, 1, -1), (1, 1, -1)]
8: [(1, 1, 1), (1, 1, -1), (1, -1, -1)]
9: [(1, 1, -1), (-1, 1, -1), (-1, -1, -1)]
10: [(-1, -1, -1), (-1, 1, -1), (-1, 1, 1)]
11: [(1, -1, 1), (-1, -1, 1), (-1, 1, 1)]
```
Then you can draw these triangles to assemble the cube.

Hopefully this makes sense!

**Comment by kcoley** [comment]
@gsrmeen btw, triangles 5 and 11 in your post will create one of the faces of the cube:

![vertindices](https://user-images.githubusercontent.com/3946928/50621049-42dc0e80-0eb8-11e9-920a-fac443b321e3.jpg)
