### ISSUE TITLE
Max2Babylon: can't export bitmap in a Physical Material

### ISSUE THREAD

**Issue by echadwick-wayfair** [BabylonJS/Exporters#423]
Max2Babylon-1.3.23
3ds Max 2018.4

This seems like something new. Maybe a bad commit?

1. Create a Plane primitive.
2. Create a Physical Material, assign it to the Plane.
3. Add a bitmap to the material.
4. Export.
Result attached. If I remove the bitmap, it exports without errors. Tried it with different bitmaps, JPG, PNG, same error.

![image](https://user-images.githubusercontent.com/40177036/50614382-934e6e80-0eae-11e9-9e7e-79928ff97404.png)

[Max2Babylon export error.zip](https://github.com/BabylonJS/Exporters/files/2722211/Max2Babylon.export.error.zip)

**Comment by echadwick-wayfair** [comment]
It's also spawning a warning about KHR_texture_transform, even though the Bitmap uses default settings. There seem to be no Offset/Tile/Angle settings that should call for the extension.

**Comment by echadwick-wayfair** [comment]
Tested with Max2Babylon-1.3.21... the red error is not spawned, but the KHR_texture_transform warning is still being spawned.

**Comment by kcoley** [comment]
@echadwick-wayfair I'll take a look

**Comment by kcoley** [comment]
@echadwick-wayfair I was able to get the bmp to export from your provided scene by re-assigning the material to the mesh, though I'm not sure why that fixed it.  This was done with version 1.3.23.  Can you try that on your end?

I also tried to follow the creation steps you outlined using your source bmp with a new scene, but I was not able to repro the issue that way.

As for the KHR_texture_transform warning, I have been trying to fix the warning (the conditional check is not passing for some reason), though it should not cause an issue with the scene.

**Comment by echadwick-wayfair** [comment]
Nope that wasn't it. Installed & Unblocked 1.3.24, but it still occurs. Won't write a GLB. Have to revert back to .21 for now to get a project done.

**Comment by echadwick-wayfair** [comment]
Actually, 1.3.22 works.

**Comment by kcoley** [comment]
@echadwick-wayfair it seems to be an issue with exporting to glb, when converting textures to binary.  I am looking into a fix.

**Comment by kcoley** [comment]
@echadwick-wayfair I found the issue and merged a fix.  It was how I was handling uri paths .  Feel free to try on version 1.3.25.

**Comment by echadwick-wayfair** [comment]
It works now, thanks for the fix!
