### ISSUE TITLE
Max2Babylon request: version number in exporter window?

### ISSUE THREAD

**Issue by echadwick-wayfair** [BabylonJS/Exporters#424]
It would be helpful to see the exporter version number in the exporter window. 

I take a screenshot to share error messages, but also to document which options were used with a file, so having the version info would help if I need to reproduce a specific export. 

It would also help to determine if someone is using an out-of-date exporter.

**Comment by kcoley** [comment]
@echadwick-wayfair you read my mind, I was thinking of adding that to the exporter window title.  I'll see if I can get an update for that today too.

**Comment by kcoley** [comment]
@echadwick-wayfair just merged an update for this: https://github.com/BabylonJS/Exporters/pull/425
