### ISSUE TITLE
Max2Babylon Export & Run: point to new Khronos viewer instead of Sandbox?

### ISSUE THREAD

**Issue by echadwick-wayfair** [BabylonJS/Exporters#427]
3ds Max 2018.4
Max2Babylon 1.3.22

The "Export & Run" button currently spawns the Sandbox viewer.
https://sandbox.babylonjs.com/?assetUrl=http://localhost:45478/myfilename.glb

But we would prefer it spawn the new reference viewer.
http://gltf.ux3d.io/

For these reasons:
1. Punctual light is needed to evaluate the model and material.
2. The sandbox IBL is very colorful which makes it difficult to evaluate accurate color reproduction.
3. The new ref viewer has helpful Debug viewing modes.

The new ref viewer is robust enough in our tests, but maybe it's not ready yet?

Thanks!

**Comment by kcoley** [comment]
@echadwick-wayfair we can probably add an option to do this, though do you know if the reference viewer accepts url parameters?

**Comment by deltakosh** [comment]
Hey !

1. This could be an option of the sandbox
2. You can change the IBL image by drag and dropping a new one in the sandbox after having loaded your scene
3. The sandbox has tons of debug feature in the inspector. If you find some that may be missing I will gladly add them

Closing for now as we do not plan to add the reference viewer as default loader
