### ISSUE TITLE
Maya exporter "texture not supported"

### ISSUE THREAD

**Issue by Turtleted21** [BabylonJS/Exporters#442]
Hello,
I use Maya 2017 and I have this error when I export, I use a jpeg file.
![exporter](https://user-images.githubusercontent.com/46889785/51469046-a4cdbc80-1d70-11e9-9d34-ff571579e70d.jpg)

Thanks

**Comment by Turtleted21** [comment]
I see you have a extension for Maya 2017, where I must copy .cs files?

**Comment by kcoley** [comment]
Hi @Turtleted21 , do you have a sample scene that repros the issue?  
What do you mean by copying the .cs files?
