### ISSUE TITLE
Renamed C# EditorScript causes .ts file to not be updated

### ISSUE THREAD

**Issue by davidzwa** [BabylonJS/Exporters#447]
If I rename an EditorScript it wont be updated and the Babylon export fails with:
`Error occurred in onSucces` which is caught by the general Babylon error handler.
I can do what I want, but there is no option to fix it unless delete the file (even moving it doesnt work, but that is probably because it doenst change namespace)

Any idea what might be wrong? It seems to be related to the fact that the PROJECT reference also doesnt update unless you reattach the .cs script to a gameobject. 
![image](https://user-images.githubusercontent.com/6005355/51950474-f0e3c580-2430-11e9-8c85-7a1fa02cb7ad.png)

P.s. Im not sure if it is the EditorScript class, file, .ts reference or the .ts class/filename. I didnt have the time to consistently find the cause, sorry. Might do that later.
P.p.s. Re-attaching also doesnt seem to change anything.

**Comment by deltakosh** [comment]
Pinging @MackeyK24

**Comment by MackeyK24** [comment]
The class name for the C# should be same as file name of .cs editor script component.

The .ts file doesn’t really matter, but I like to keep the file names the same for the .cs/.ts pair. 

What matters is the class name you create for the typescript class. That gets set in the construction of the c# class. The property is called babylonClass. That’s is what links the editor script to the backing Babylon script class

If you wanna send me a unitypackage with all the classes and files in question... I’ll take a look at it

**Comment by davidzwa** [comment]
Same here, setting up a repo [Github repo](https://github.com/davidzwa/BabylonUnityLearnings)

**Comment by davidzwa** [comment]
https://github.com/davidzwa/BabylonUnityLearnings/tree/master/RollABall
