### ISSUE TITLE
Fix material export when its type is not handled

### ISSUE THREAD

**Issue by noalak** [BabylonJS/Exporters#45]
Currently, only standard and physical materials are supported by the exporter.
For other materials only a warning is displayed but mesh's materialId remain unchanged.

To do to fix issue:
Such material should be ignored and meshes' materialId set to null.

**Comment by Selmar** [comment]
I have a suggestion: allow extensions to the exporter. Then users can more easily fork it and create a custom material exporter.

I envision it'd work like this: you create a new class with a custom attribute (e.g. `MaterialExporterAttribute`), which has an interface that allows the exporter to get the MaterialID associated with it and provides a function to export from a material handle.

The exporter can find all these material exporters using reflection.

The only remaining difficulty is that when you add files to a project, the solution file is changed (and thus merging is still slightly annoying).

Thoughts?

**Comment by noalak** [comment]
If someone wants to add support for another material type, we will consider adding extra classes instead of flooding BabylonExporter.Material.

Eventually not all material types can be handled and this issue focus on handling such case.

**Comment by Selmar** [comment]
We want to add an in-house material type, which is not (yet) ready to be published. Should I open a new issue?

**Comment by noalak** [comment]
Yes, renaming this issue
