### ISSUE TITLE
Plugin does not match the current architecture (Maya2Babylon.nll)

### ISSUE THREAD

**Issue by coldestheart** [BabylonJS/Exporters#455]
// Error: file: /Applications/Autodesk/maya2018/Maya.app/Contents/scripts/others/pluginWin.mel line 909: does not match the current architecture (Maya2Babylon.nll) // 

I was tried to recompile it from source with monodev, but still have the same error.

Using High Sierra 10.13.6

**Comment by deltakosh** [comment]
We are currently only supporting windows. We plan to add support for MacOS in the future though
