### ISSUE TITLE
Maya Exporter = Animation Ghosts Frames being added on export

### ISSUE THREAD

**Issue by spkopa** [BabylonJS/Exporters#459]
Hey guys,

So recently been experimenting with the exporter from Maya version 2018.4

Found out the exporter is adding a keyframe at the end of the animation. This is preventing exports that allow for smooth loops. Because you get a ghost keyframe that causes a hiccup in the playback. 

Any help on this would be appreciated. 
Thanks!
-Sk

**Comment by deltakosh** [comment]
Can you share a sample file?

**Comment by spkopa** [comment]
Hey Deltakosh,

Here is the outputted version to Babylon 

https://www.babylonjs-playground.com/#0CSD1T#114

Showing the loop bug in animation from the ghost frames.

**Comment by deltakosh** [comment]
Can we get the initial 3d file?
@kcoley do you have any free cycles? (pretty please?)

**Comment by spkopa** [comment]
Your wish is granted!

https://github.com/spkopa/GLTF_Sandbox/tree/master/Assets/Maya_Scenes

Maya version 2018.4

There is a baked out version of the particles, using instances. In a grp called instancer1_geo_grp


If you export that using the Babylon exporter, you will get the ghost frame. 

Thank you for the help!

**Comment by kcoley** [comment]
Hi @spkopa .  Did you try manually setting an animation group to the frame range you want to export?: https://doc.babylonjs.com/resources/maya_to_gltf#how-to-export-multiple-animation-clips-to-gltf-format

I'm having trouble reproducing the issue, though is it only coming up with baked particle animations?

**Comment by spkopa** [comment]
Hey @kcoley,

Thanks for checking this out. I'm not sure about the animation group frame range matching the export. I will test this out with something much more simple to see if I can repro the bug. 

Thank you!

**Comment by spkopa** [comment]
Hey @kcoley,

I think I found the bug,

So it doesn't appear to be related to time-frame range set on the timeline or even the animation group.

If your settings in the maya Prefs are set to 30fps, you will get the hiccup on export. But if it is set to 60fps. There appears to be no hiccup.

Still testing this out completely but this seems to be it.

**Comment by kcoley** [comment]
@spkopa nice find, I can try to take a look at the code to see how FPS is handled

**Comment by deltakosh** [comment]
Thanks a lot @kcoley

**Comment by spkopa** [comment]
@kcoley  @deltakosh , Thank you both.

Still digging around on my side as well to see if there is anything else to gleam. Will post updates if so.

Much appreciated!
-Sk

**Comment by kcoley** [comment]
@spkopa this line looks suspicious:
https://github.com/BabylonJS/Exporters/blob/6843fe4f52e855065c0db5576dbaebec08363390/Maya/Exporter/BabylonExporter.Animation.cs#L327

Though you mentioned that fps looks bad when set to 30 fps in the Maya preferences.  What kind of behavior are you seeing (staggering animation, non-looping, etc)?

**Comment by spkopa** [comment]
@kcoley 

interesting, So in the tests I was running. I was getting the stuttering, non-looping aspects at 30fps, But running those same tests in 60fps seemed to work. With nothing being done to the animation itself. 

I got pulled onto other things. But let me see about setting up a scene that can prove this out easily.

**Comment by spkopa** [comment]
@kcoley 

Ok, So just ran a fresh setup of a test scene to repro. Found out that it was a false positive on my side with the animation being switched between 30 and 60fps.

The way I was able to reproduce the bug is this.

Create cube
Animate on Y from (Frame 1 = 0) to (Frame 120 = 360) 

If you export at 30fps or 60fps. No bug

But if you change your time slider to be anything above 120
![hiro_template_hub_ss_352_maya_exporter_animation_bug](https://user-images.githubusercontent.com/40442596/53589423-2e2c9780-3b44-11e9-9073-656fa83f2074.PNG)

And export, you will get the stutter bug.

The way around this bug, if your time slider doesn't exactly match your animation is to have the animation groups setup. So this is definitely user error on my part. But interesting behavior as well on the exporter side. 

I will setup some maya scenes and post them here for you to see. 

Best
-Sk

**Comment by spkopa** [comment]
@kcoley 

Posted the maya files here. 

https://github.com/spkopa/GLTF_Sandbox/blob/master/Assets/Maya_Scenes/Maya_Babylon_Exporter_01_30fps_Not_Working_Time_Slider_Set_120by180.mb

https://github.com/spkopa/GLTF_Sandbox/blob/master/Assets/Maya_Scenes/Maya_Babylon_Exporter_01_30fps_Working.mb

To get the not working version to work, just add animation group to go from frame 1-120


Thanks for the help!

**Comment by kcoley** [comment]
@spkopa sorry for the delay, didn't have access to a PC for a few days.  
So it looks like, if the animation group is not set for the scene, the exporter uses the end frame of the animation timeline, not the end frame of the playback range.  The stuttering is freezing the last frame of animation until the end of the animation timeline.  So to fix the behavior, would be to either set the end of the animation timeline to the end frame of your animation (which you have done for your working scene), or set the animation group to the range of animation you want.  This is probably something that can be documented better to better explain this.  

Hope this makes sense!

**Comment by spkopa** [comment]
@kcoley 

Totally makes sense, Thank you for the help on this!
