### ISSUE TITLE
Rotate camera/light 90°

### ISSUE THREAD

**Issue by noalak** [BabylonJS/Exporters#46]
Conventions:
- in 3ds max, camera and light default direction is downward
- in Babylon, their default direction is sideways

As such, a FreeCamera (no target) with a (0,0,0) rotation is looking wrong way once exported to babylon.

As for TargetCamera, since the rotation of the camera is dynamic, the camera is looking correctly to the target once exported.
However, camera's children are rotated 90°. A TargetCamera with a (0,0,0) rotation (target is below camera), when exported to babylon will have a (90,0,0) rotation, looking at its target.

To do to fix issue:
- for FreeCamera, add a 90° rotation to the camera (and its animations).
- for TargetCamera, if it has any child, add a TransformNode with a 90° rotation as child to the camera. Camera's children are then added as child to this extra node.

**Comment by rlouvat** [comment]
Sorry my previous pr was only for the cameras. I'm still investigating for the lights.
So is it possible to reopen the issue?

**Comment by deltakosh** [comment]
Actually please open a new one with checkbox so we can track remaining work:)
