### ISSUE TITLE
Max2Babylon: Invalid Rank passed to CreateTreeNode 

### ISSUE THREAD

**Issue by echadwick-wayfair** [BabylonJS/Exporters#460]
Edit for specs: 
3ds Max 2018.4
Max2Babylon 1.3.32

Getting these errors consistently on export. I think we talked about this before, sorry I can't find the last thread on this.

Scene is very simple. Plane primitive, with Physical Material, with four JPG textures, all default settings except Base Color swatch changed to white instead of default gray. No UV adjustments made in the bitmap settings. All four bitmaps are 512x512 JPG.

```
GLTFExporter.Texture | KHR_texture_transform is not enabled, so the texture may look incorrect at runtime!
Invalid Rank passed to CreateTreeNode (through RaiseMessage, RasieWarning or RaiseError)!
```
![image](https://user-images.githubusercontent.com/40177036/53177994-088d1480-35bf-11e9-8290-8684a114995a.png)

**Comment by echadwick-wayfair** [comment]
Here's a repro example.
![test_export_log](https://user-images.githubusercontent.com/40177036/53181711-14c8a000-35c6-11e9-9615-45af1f67e0fa.jpg)
[Invalid-Rank-passed-to-CreateTreeNode.zip](https://github.com/BabylonJS/Exporters/files/2889975/Invalid-Rank-passed-to-CreateTreeNode.zip)

**Comment by deltakosh** [comment]
Pinging @kcoley

**Comment by kcoley** [comment]
@echadwick-wayfair I just merged a fix for this: https://github.com/BabylonJS/Exporters/pull/461

**Comment by echadwick-wayfair** [comment]
Thank you!
