### ISSUE TITLE
Export Cancelled

### ISSUE THREAD

**Issue by BaldSavant** [BabylonJS/Exporters#464]
Export cancelled: (kFailure): Unexpected Internal Failure   at Autodesk.Maya.OpenMaya.MGlobal.executeCommand(String command, MStringArray result) at Maya2Babylon.BabylonExporter.GetBoneFullPathName(MFnSkinCluster skin, MFnTransform transform) at Maya

and I have no idea what that error is trying to tell me, but it happens every time I try to use the exporter, regardless of which options I seem to have enabled or which file type is my target. I've just started using it and have not yet had a successful export, so I may have installed something wrong or similar. 

Suggestions?

**Comment by deltakosh** [comment]
Can you share the scene that produces this error?

Pinging @patrickryanms

**Comment by PatrickRyanMS** [comment]
Also, can you share with us what version of Maya you are currently using?

**Comment by kcoley** [comment]
@BaldSavant and did you unblock the dlls before installing?
 https://doc.babylonjs.com/resources/maya
![3_dll_unlocking](https://user-images.githubusercontent.com/3946928/53675507-d0837280-3c4b-11e9-8e57-e8723c3c6422.jpg)

**Comment by BaldSavant** [comment]
@deltakosh I can't share the scene, unfortunately. NDA and all that. It is, as far as I can tell, happening across multiple scenes. All of which are a single rigged character with some amount of keyframe animation present. 

@PatrickRyanMS I'm using 2018. Service pack 3 I believe. 

@kcoley Yes, that was required before the plugin would even appear in maya. The plugin is there and working mostly, aside from the ever-present error mentioned above.

**Comment by deltakosh** [comment]
Can you try to repro on a non NDA scene perhaps?

**Comment by BaldSavant** [comment]
ok, I'm not sure what this file is/was, but it's giving me the same error. Hopefully that's helpful to you!

https://drive.google.com/open?id=1qdPDHK-Kob_wF7_YclP1BsnInIt0UuHH

**Comment by kcoley** [comment]
Hi @BaldSavant , when I try to load your scene, it looks like it is looking for another referenced scene:
![image](https://user-images.githubusercontent.com/3946928/53786034-30d61680-3ecf-11e9-896b-4eb3726e014f.png)

Since that scene is not available, the export fails.  Is this prompt coming up for you?

**Comment by BaldSavant** [comment]
lol, sorry, I forgot that would be an issue. 

Fortunately, I was able to resolve this problem. I don't know WHY it was happening, exactly, but some combination of "Export Only Selected", having "Export Normal" deselected, and "Optimize Vertices" as well as "Export Hidden Objects" seems to now allow me to export my files as expected. One of our tech people helped me resolve this.
