### ISSUE TITLE
[Max][glTF] Wrong texture offset values

### ISSUE THREAD

**Issue by EtagiBI** [BabylonJS/Exporters#465]
Hello,

My texture has the following properties:
![image](https://user-images.githubusercontent.com/20855725/54121029-2eb60f80-441b-11e9-9a03-9354b8d8547e.png)
When I export the model to GLTF, I have the following properties:
![image](https://user-images.githubusercontent.com/20855725/54121085-560cdc80-441b-11e9-95c5-f60ebe384471.png)
As you can see, offset parameters are different. Is it OK?

**Comment by kcoley** [comment]
Hi @etagibi the parameters should be different since Max and glTF have different coordinate systems. But does the resulting glTF look incorrect? And if so, do you have a sample model?

**Comment by EtagiBI** [comment]
> Hi @EtagiBI the parameters should be different since Max and glTF have different coordinate systems. But does the resulting glTF look incorrect?

Well, it's hard to tell for sure, but for me there's no visual difference.
![Max](https://user-images.githubusercontent.com/20855725/54256125-b9fae680-457c-11e9-892c-7ae818cfdda7.png)
![GLTF](https://user-images.githubusercontent.com/20855725/54256127-bb2c1380-457c-11e9-924d-6c5be01844c8.png)

Thanks for clarification.
