### ISSUE TITLE
Max2Babylon doc: which is latest?

### ISSUE THREAD

**Issue by echadwick-wayfair** [BabylonJS/Exporters#469]
I noticed this section didn't include the full information on PNG usage, Image Alpha option, Alpha Test, etc. 
https://doc.babylonjs.com/resources/3dsmax#texture-transparency

I had to dig into the Physical Material section to find this info. 
https://doc.babylonjs.com/resources/3dsmax_to_gltf#alpha-mode

Looks like you have duplicate and out-of-date info in the former link, versus more up-to-date info in the latter link? Should there be two pages or one? Which should users trust to be the most accurate?

The former link is from the readme for the master branch
https://github.com/BabylonJS/Exporters/blob/master/3ds%20Max/readme.md

The latter link is accessed from this link:
https://doc.babylonjs.com/resources/3dsmax#physical-materials

**Comment by deltakosh** [comment]
Yes we need to clean all of that..But luckily we finally hire someone to help us :)

**Comment by deltakosh** [comment]
cc @drigax

**Comment by sebavan** [comment]
I added the link to the former documentation. As the UI will be revamped soon, I won t add more information at the moment.
