### ISSUE TITLE
Unable to get alpha to work with Maya 2019 Maya2Babylon

### ISSUE THREAD

**Issue by Misterboogie** [BabylonJS/Exporters#473]
I am having an issue where I am unable to export alpha to Gltf. I can export everything except alpha and I've tried the two ways outlined in the docs. First way I tried to plug in png's with alpha. Second way I separated the alpha's into their own png's. Both methods didn't work. I am using AIstandard with Opaque turned off on the hair meshes. I have tried viewing the gltf on multiple gltf viewers and I get no alpha? Am I missing something? I will try to attach zip. Windows 10 Enterprise. Maya 2019. Maya2Babylon 1.2.30

Thanks for any help!

![Uploading 
![mayaGltf01](https://user-images.githubusercontent.com/34957210/55421214-9993cb80-552d-11e9-82dd-854e9c9d4a25.jpg)
mayaGltf02.jp

![mayaGltf02](https://user-images.githubusercontent.com/34957210/55421318-d6f85900-552d-11e9-88fa-1ddc1f02613a.jpg)

g…]()
![mayaGltf03](https://user-images.githubusercontent.com/34957210/55421227-a0bad980-552d-11e9-8497-d9530a62d912.jpg)

Cheers,
Misterboogie

**Comment by deltakosh** [comment]
Pinging @PatrickRyanMS :)

**Comment by PatrickRyanMS** [comment]
I'm finding some strange behavior with transparency at the moment. Let me chat with @Drigax and we will open a bug.

**Comment by sebavan** [comment]
Closing as dupplicate of #535.

@Misterboogie  Would you be able to share a zip on #535 ? thanks a lot
