### ISSUE TITLE
No relative path for texture image while exporting with "Blender2Babylon-6.0"

### ISSUE THREAD

**Issue by Androidest** [BabylonJS/Exporters#474]
In _**version 5.6 -> material.py**_, there are codes for adding relative path to image file path, but no such codes in _**version 6.0 -> texture.py**_. 
![23a4abe4a5fcb212af2d202390acbe6](https://user-images.githubusercontent.com/10008376/55870409-17ee0e80-5bbb-11e9-9e6a-a442f47d7889.png)
![532a6e0014c6301da1342d36439e786](https://user-images.githubusercontent.com/10008376/55870427-23d9d080-5bbb-11e9-81ec-2c1f22a56d80.png)

when i export the .babylon file with **_Blender2Babylon-6.0_**, i can't load the images if i put them and the .babylon file in different directories.
with version 6.0:
![09f76bc6c204c2b9e16336663e791c6](https://user-images.githubusercontent.com/10008376/55870435-263c2a80-5bbb-11e9-9bae-4ad16a1b53e7.png)
with version 5.6:
![f1066abeb0f9fcf53f9598542a85c29](https://user-images.githubusercontent.com/10008376/55870439-2805ee00-5bbb-11e9-97a0-145a9b38a322.png)

**Comment by Palmer-JC** [comment]
Just saw this.  The full path is being passed to [Texture Process](textureFullPathDir), which actually writes the file.  The file itself should be should be being written to the correct place.

I will have to look at this next week.  FYI, the place to set the relative path has moved from the `scene` tab to the `world` tab for version 6.0.

**Comment by Palmer-JC** [comment]
completed
