### ISSUE TITLE
Blender Exporter : Visible and Enabled (Outliner) do not work on InstanceMeshes

### ISSUE THREAD

**Issue by cstfan** [BabylonJS/Exporters#487]
When I create InstanceMeshes on Blender (alt + d), visible and enabled (Outliner)  do not work for them.

**Comment by Palmer-JC** [comment]
My answers do not change by which channel things get reported.  .babylon format does not support this, so there is no point in writing it to the file.

**Comment by cstfan** [comment]
Sorry, but I understood that you were telling me in the forum to make a message on GitHub for this problem. I am not here to be unpleasant to you, but just to suggest improvements to export it, which seems to me to be more than logical and important for everyone.

**Comment by Palmer-JC** [comment]
No I said, if you do the PR on the main repo to look at that type of info,
I would provide it on the export.
