### ISSUE TITLE
Animations associated with Morphed Models don’t play in the Babylon Sandbox

### ISSUE THREAD

**Issue by Pratyush1184** [BabylonJS/Exporters#496]
I used a model named Morph Anim.fbx and exported it into .babylon using 3DS Max. The exported model when opened in the BabylonJS Sandbox renders a sphere without the associated animation where the mesh gets morphed into an irregular shape. The fbx model when viewed in Maya, plays the associated animations which involve morphing as can be seen in the video(morph.avi within the Morph Anim.zip file).

I have also uploaded the model Morph Anim.fbx and it’s corresponding babylon model. I have also sent a screenshot of the view obtained in the babylon sandbox(https://sandbox.babylonjs.com/)
Please look into the issue.
I exported the model as per the given documentation(https://doc.babylonjs.com/resources/3dsmax#scene-properties)
![Screenshot from 2019-04-26 18-57-04](https://user-images.githubusercontent.com/20305094/56887294-de5c4500-6a8e-11e9-9012-d6e8fb881e2f.png)
[Morph Anim.zip](https://github.com/BabylonJS/Exporters/files/3126803/Morph.Anim.zip)

**Comment by deltakosh** [comment]
@drigax can you have a look as soon as possible? Thanks!

**Comment by Drigax** [comment]
Sure, looking at the Morphy Anim.babylon file, it doesnt appear to have the morph targets included.

Also, after importing and reexporting the Morph Anim.fbx file, I noticed that the exporter's skipping the morph target animation data:
![image](https://user-images.githubusercontent.com/3952729/56930379-50ce2480-6a91-11e9-9406-625e39080565.png)

Will continue to investigate, also noticed a similar fault in the Blender -> Babylon 6.0 exporter as well. @Palmer-JC

**Comment by Drigax** [comment]
@deltakosh, this seems like an exporter problem, the Blender default GLTF exporter seems to work and load into the Babylon sandbox fine.

**Comment by Drigax** [comment]
[Morph_Anim_blender.zip](https://github.com/BabylonJS/Exporters/files/3129382/Morph_Anim_blender.zip)

**Comment by Drigax** [comment]
Yikes. this is looking a bit bigger than I initially thought, I think I can narrow this down into some related faults.

1) The BabylonFileLoader checks the loaded meshes for an autoAnimate flag on import, but the exporters currently set this flag on the animations themselves, so we don't automatically animate on load.

2) Shapekey animations don't appear to be exported for the Max, Maya and Blender Babylon exporters. The Kronos GLTF exporter for blender exports them as an animation track.

3) the 3dsMax Babylon exporter currently exports a morph target manager, but doesn't include the actual morph targets.

**Comment by Drigax** [comment]
Ok after taking a good look at the Autodesk API, I don't think this is entirely fixable:
1) @Pratyush1184 your FBX does not contain the full morph targets. If we load it into Max, we see:
![image](https://user-images.githubusercontent.com/3952729/57927700-a8c3a400-7863-11e9-8b83-6e16716695c7.png)
Indicating that the FBX includes transformation data to deform the mesh to the morph target, but the API doesn't currently provide a way to bake this data into the morph target meshes, so we can't export this without manual work to extract the morph targets.

After manually recreating the morph targets via Extract->Pick Object From Scene, I can see we still don;t export the shapekey animation frames, but I think I can at the very least provide a fix for that.

**Comment by Drigax** [comment]
Still unable to find a definitive reason why we can't export the Morpher animation frames either. 
when we try to get the animation keyframes via:
https://github.com/BabylonJS/Exporters/blob/a639bbb62ef39e23639c80847dd4af204f96fbb8/3ds%20Max/Max2Babylon/Exporter/BabylonExporter.Animation.cs#L295

The API returns nothing.

Unfortunately this looks like a bug in 3dsMax, but if anyone has some time to double check my findings, I'd be more than happy to reopen with a fix.

I also opened https://forums.autodesk.com/t5/3ds-max-programming/unable-to-access-morpher-keyframes-via-script/td-p/8802916

to see if anyone on the Max Forums can provide some answers as well.
