### ISSUE TITLE
Add exporter support for modifying BabylonMaterial.maxSimultaneousLights

### ISSUE THREAD

**Issue by Drigax** [BabylonJS/Exporters#501]
We should be able to modify this property at export time to allow users to better preview their .BABYLON scenes without additional scripting.

**Comment by Drigax** [comment]
I should be able to implement this in around 2 months, I want to tackle some higher priority issues first.

**Comment by sebavan** [comment]
Closing for house keeping as we are grouping all the UI work in one place #537
