### ISSUE TITLE
[3DsMax] Crashes/Freezes while Exporting GltF

### ISSUE THREAD

**Issue by Sknueppel** [BabylonJS/Exporters#502]
Hey there, 
I have an Issue with the newest Exporter and the Substance Plugin (https://www.allegorithmic.com/integrations/substance-in-3ds-max)

As long as it is installed, my Exportprogress on GLTF files freezes and Max Chrashes.
and ion my listener Window I get these messages

<img width="559" alt="Substance Error" src="https://user-images.githubusercontent.com/50370211/57306692-9028f080-70e3-11e9-8582-a4d5b50bd564.png">

Some Hard Facts:
Max Version 2018.4
Windows 10 Pro, build 17134.706

Im curios to see if there is another fix than "uninstalling" the substance plugin.

All the best
Sebastian

**Comment by Drigax** [comment]
Hi @Sknueppel, I was able to reproduce the 3dsMax crash, before we finish writing to our output file, we broadcast a PreExport Notification to Max, Substance and the other plugins listening:

https://github.com/BabylonJS/Exporters/blob/1b20a40bdc5d4ab92ece04de1fe25280013a1d40/3ds%20Max/Max2Babylon/Exporter/BabylonExporter.cs#L580

I got a slightly different callstack than the one you're observing, but it appears that substance is crashing when baking procedural materials to a texture for export. 👎 
 
![image](https://user-images.githubusercontent.com/3952729/57472961-9afa9700-7243-11e9-98ca-3ac52d4e0649.png)

Unfortunately I'm not sure If this can be fixed on our end.
