### ISSUE TITLE
Max2Babylon 1.3.36 - not showing version update in UI?

### ISSUE THREAD

**Issue by echadwick-wayfair** [BabylonJS/Exporters#506]
Header in the Max2Babylon exporter is showing 1.3.33, but I've closed 3ds Max, downloaded and installed 1.3.36, and restarted 3ds Max.

Do I actually have the latest? Or does the header need to be updated?

Thanks!

![image](https://user-images.githubusercontent.com/40177036/57396130-aee8bf00-7197-11e9-9cb5-d93ee7666b72.png)

->

![image](https://user-images.githubusercontent.com/40177036/57395992-629d7f00-7197-11e9-8ea2-531784ab70a8.png)

->

![image](https://user-images.githubusercontent.com/40177036/57396025-7517b880-7197-11e9-9fe9-aed7ac327059.png)

**Comment by Drigax** [comment]
Sorry about that, I neglected to update the UI to reflect the new versioning, but that should contain the latest build. I'll fix this moving forward

**Comment by echadwick-wayfair** [comment]
Ok, no problem, just want to make sure I'm not going crazy!

**Comment by kcoley** [comment]
Hi @drigax, there is also a changelog you can update if you like with your new changes: https://github.com/BabylonJS/Exporters/blob/master/3ds%20Max/CHANGELOG.md

**Comment by Drigax** [comment]
Thanks @kcoley, this changelog is so well organized! I'll keep it up to date moving forward.

Updated the version UI and updated our changelog for v1.4.0 (yay minor update)
https://github.com/BabylonJS/Exporters/pull/511
