### ISSUE TITLE
All files fail to load in windows gltf viewer, and babylon sandbox

### ISSUE THREAD

**Issue by BryanChrisBrown** [BabylonJS/Exporters#508]
weird issue where the gltf files exported via 3ds max 2019 and the most recent babylon exporter can't be read by sandbox.babylonjs.com or by the "object viewer" present on windows 10. 

The models are readable via Don Mccurdy's gltf viewer. 

I've attached a zip file with the 3ds max file and the resulting gltf file

[teapot.zip](https://github.com/BabylonJS/Exporters/files/3179242/teapot.zip)

**Comment by deltakosh** [comment]
adding @bghgary

**Comment by bghgary** [comment]
I just tried and the teapot works in both sandbox and 3d viewer?

**Comment by bghgary** [comment]
What error are you getting?

**Comment by BryanChrisBrown** [comment]
I just got it to work by clicking and dragging it into the window, after refreshing my browser.

 however the "export and run" option doesn't seem to work and gives me this error:
![image](https://user-images.githubusercontent.com/22871421/57722818-4f862580-7655-11e9-87d4-c90ac41e9f65.png)

**Comment by bghgary** [comment]
@Drigax can you take a look?

**Comment by Drigax** [comment]
I'm not entirely sure what's going on here either. looking at my developer console, I can see:
![image](https://user-images.githubusercontent.com/3952729/57872568-cf7cce80-77c0-11e9-8068-1ac4202d91d7.png)

Which suggests that our http request is being blocked.

switching this to use https results in the request still being blocked:
![image](https://user-images.githubusercontent.com/3952729/57872977-dd7f1f00-77c1-11e9-8be0-f6ee16ff9d71.png)

I'm not very proficient with web requests, but I assume there's something off with how we are creating our local web server to host the generated glTF that's causing the request to fail. I noticed that making a direct request to the generated gltf URI fails as well. I don't think i can fully look into this for around 2 weeks, but thankfully we can still drag->drop as a workaround 
(personally I don't think that export&run ever worked for me)

**Comment by deltakosh** [comment]
Yep this seems to be a problem with the net http listener we use. Search for disable CORS on http lsitener (or maybe we need to use another .net web server?)

**Comment by Drigax** [comment]
After giving this a thorough look, I think our current implementation limits our browser compatibility, unfortunately we only fully support Export & Run on Chrome.

My previous testing was done solely on Firefox, which blocks Cross-Origin requests (requesting from our locally hosted fileserver as part of our request to sandbox.babylonjs.com) for HTTP as a security feature.

There is a way to disable this via about:config, but I highly highly recommend against this.

The only way to fully support this for Firefox and other equally strict browsers would be to implement HTTPS for our exporter fileserver, which isn't quite worth the squeeze in doing, sorry :(

I'll update the Babylon docs for this limitation.

**Comment by Palmer-JC** [comment]
FYI:  Yes, Firefox changed recently to block.  I switched to Edge, which
does allow file:// for textures.
