### ISSUE TITLE
"Export Canceled: Object reference not set to an instance of an object." when exporting with physical material

### ISSUE THREAD

**Issue by BryanChrisBrown** [BabylonJS/Exporters#509]
I'm currently getting this issue trying to export a model with physical materials. This occurs when exporting to any file type, gltf, babylon, glb or binary babylon

The material is setup as a "multisubobject" material with 7 sub materials. 

I've attached an archive of the 3ds max 2019 model. 
[3dsMaxBug.zip](https://github.com/BabylonJS/Exporters/files/3182997/3dsMaxBug.zip)

![image](https://user-images.githubusercontent.com/22871421/57783826-d0e4c300-76fc-11e9-9a7d-d3552acb22b1.png)

**Comment by BryanChrisBrown** [comment]
The issue does not occur when using 3ds max "standard" materials, but we haven't had this issue with physical materials with past versions of the exporter.

**Comment by deltakosh** [comment]
Ok thanks we are going to check asap

**Comment by Drigax** [comment]
Thanks, this was a regression I introduced that was fixed via:
https://github.com/BabylonJS/Exporters/pull/500

I'll publish a new version of the exporter to include this.

**Comment by BryanChrisBrown** [comment]
Awesome, thanks for the quick response!

**Comment by Drigax** [comment]
fix should be in master now :)
