### ISSUE TITLE
roughness/metalness swap

### ISSUE THREAD

**Issue by BryanChrisBrown** [BabylonJS/Exporters#517]
Placing a map under roughness in a physical material on 3ds max 2019 causes it to be placed under metalness instead of roughness/reflection in the exported model. 

Placing the map under metalness in 3ds max corresponds to the metalness option in the gltf file as intended.

**Comment by Drigax** [comment]
Hi, @BryanChrisBrown

**Comment by BryanChrisBrown** [comment]
My apologies, I thought the reflection map was akin to roughness, that's my bad. I forgot that metal and roughness maps were merged in gltf. I got confused in the babylon viewer since it just says "metalness" instead of metalness/roughness

![image](https://user-images.githubusercontent.com/22871421/58096003-1e9c7800-7ba2-11e9-882e-6d6326f30f38.png)

**Comment by Drigax** [comment]
No problem :) I always appreciate bug reports. Please let me know if you run into any further issues.
