### ISSUE TITLE
Parenting object to bones not working at export with 3ds max

### ISSUE THREAD

**Issue by Gil-1** [BabylonJS/Exporters#518]
Hello,

I made a simple scene to debug another bug but when I export the objects, the parented one are not parented in the babylon file.
here, the red boxes are skinned to one bones each. The green boxes are parented to the same bones as the red one.

If I parent a box to a bones not used in a skin the parenting is working.

Here is the playground
https://www.babylonjs-playground.com/#TH16ID#12

You can download the 3ds max file here
https://files.cynaptek.com/Parenting_bug.zip

The exported babylon is here
https://cdn.jsdelivr.net/gh/Gil-1/babylon-debug@c00737518283ec2f7e61ea888fc6743c526c63e1/parenting_bug.babylon
Apparently there are no weights or skeletons in the babylon file.

The conversation started here
https://forum.babylonjs.com/t/parenting-object-to-bones-not-working-at-export-with-3ds-max/3131

**Comment by deltakosh** [comment]
Hello bones are not meshes in .babylon file format unfortunately.
This feature is not supported directly from max but you can then use mesh.attachToBone using code to simulate the same effect.

**Comment by Gil-1** [comment]
Ah ok. It was kind (a little bit buggy) of supported three versions ago but ok :)
Will add a skin to attach from 3ds max.

**Comment by deltakosh** [comment]
My pleasure!
