### ISSUE TITLE
Support grouping animation clips together in Max/Maya to glTF exporter

### ISSUE THREAD

**Issue by bghgary** [BabylonJS/Exporters#52]
@noalak 

See https://github.com/BabylonJS/Babylon.js/issues/3411 for context.

Since Max/Maya support animation clips, but don't support animation groups, it would be good if the glTF exporters for Max and Maya supported some mechanism (some additional options in the export window, etc.) that allow selecting of animation clips that should play together in a single Babylon animation group and export them to glTF as a single glTF animation with multiple channels.

**Comment by deltakosh** [comment]
I agree this is an important one

**Comment by Selmar** [comment]
This is basically the same: https://github.com/BabylonJS/Exporters/issues/7. We need this, so I'd like to offer my help, although I have the feeling someone more familiar with the plugin would do this better.
