### ISSUE TITLE
3ds Max opacity animations

### ISSUE THREAD

**Issue by byelik** [BabylonJS/Exporters#521]
Hi.
I've created a scene with a box and added an animation of opacity. Then i exported it to gltf. I checked exported an animation in the [sandbox](https://sandbox.babylonjs.com/) and there is no animation with opacity.
I checked a FBX file in the Unity and it works without any problems.
I atteched a project.
[Opacity animation.zip](https://github.com/BabylonJS/Exporters/files/3216274/Opacity.animation.zip)

**Comment by deltakosh** [comment]
I do not think that opacity is something that gltf format can animate.
Pinging @bghgary for confirmation

**Comment by bghgary** [comment]
Yes, I confirm. Animations in the glTF 2.0 core spec can only target TRS and weights. There is a PR and discussion about animating other properties [here](https://github.com/KhronosGroup/glTF/pull/1301), but until that's ready it won't be possible to do in glTF.

**Comment by byelik** [comment]
Hi, thanks for your reply. It is sad 😢, about opacity....
Anyway, thanks....

Пт, 24 трав. 2019, 19:40 користувач Gary Hsu <notifications@github.com>
пише:

**Comment by deltakosh** [comment]
If you are not attached to gltf you can use .babylon file format which supports that feature

**Comment by byelik** [comment]
Thanks

Сб, 25 трав. 2019, 16:38 користувач David Catuhe <notifications@github.com>
пише:
