### ISSUE TITLE
Add Clearcoat support

### ISSUE THREAD

**Issue by echadwick-wayfair** [BabylonJS/Exporters#522]
I’d like to see support in Max2Babylon for the new Clearcoat features, via the Physical Material.

Possible implementation design here:
https://forum.babylonjs.com/t/max2babylon-feature-request-clearcoat/3498

Thanks!

**Comment by Drigax** [comment]
I agree. We should make sure our exporters work with our fancy new Babylon.JS features ;)

I'll try to get to this as soon as I'm done putting out fires, definitely sometime this or next month.

**Comment by sebavan** [comment]
Work to be done:

- [ ] Create entities
- [ ] Export max Phys Mat
- [ ] Export max Arnold std Surface
- [ ] Export Maya

**Comment by sebavan** [comment]
Finishing the documentation and I ll be able to close the issue. Please note it is only available in .babylon format as GLTF does not support Coating.

**Comment by sebavan** [comment]
@echadwick-wayfair you can early test from our github prerelease : https://github.com/BabylonJS/Exporters/releases/tag/preRelease20190614.4

all the deployable files are available under assets.

both docs are available:
- Max: https://doc.babylonjs.com/resources/3dsmax#physical-materials
- https://doc.babylonjs.com/resources/maya#physical-materials
