### ISSUE TITLE
Animation Export only feature. 

### ISSUE THREAD

**Issue by jcartie** [BabylonJS/Exporters#525]
Hello I saw a ticket of yours that was closed a year ago

https://github.com/BabylonJS/Exporters/issues/203

and its describing what were hoping to accomplish. 

Which is an option to only export animation data. 

The ideal hope would be to split animation and geometry into 2 files.

that way we can swap animations only. 

any possibility that this request has been reconsidered?

Thanks!

Juan Carlos Leon
Rigging TD
Artie Inc.

**Comment by Drigax** [comment]
Hi @jcartie,

I believe @elpie89  and @Selmar added a feature via #492 that allows usto export animation data as JSON.

Let me know if this solution works for you, else I can think of ways to enhance it. :)

**Comment by elpie89** [comment]
Our features only export a list of animation groups from one file to another, allowing you to avoid to recreate animations group when node have been merged into a new scene for example.
What you are asking is something that our animators requested as well
They asked this feature some days ago, the possibility to split animation info from the GLTF itself
like in an fbx when you export only animations
I think is possible.
@Selmar @Drigax , @deltakosh should I proceed with something like this? 

Imagine you are exporting a scene that will take many minutes to export the binary, but you only updated the animation

This could be a big improvement in term of productivity

**Comment by YossiMH** [comment]
@Drigax @elpie89 -- I work with @jcartie  .

Here's some context about what we're to do:
- This is about the Maya GLTF exporter, and exporting assets for integration into our apps and delivery, as-is, to end users
- We want a really small initial payload with a GLB that only includes our characters' geometry, materials, and textures
- We want to then stream in other animations later on during the lifetime of the app and play them back on the models which were included with the app's initial payload

@jcartie has already figured out how to use the Babylon Maya GLTF exporter to export GLBs with geometry, skeletons, materials, and textures; but no animations. Now he's trying to export GLBs with skeletons and animations; but no geometry, materials, or textures.

Thanks! :)

**Comment by Selmar** [comment]
@YossiMH What we did was on the 3dsmax side, and it does not export glTF/glB.

**Comment by Drigax** [comment]
@YossiMH Makes sense. Currently we haven't supported this in our exporters because we currently don't have support for retargeting the animations exported in the rig-only GLTF to the rig that would be exported with the mesh GLTF in the babylon engine.

@PatrickRyanMS, @bghgary would you be able to chime in on this as well? I am unsure if GLTF supports armatures without an associated mesh. This was something we discussed a few months ago as well as far as how to best support GLTF "assembly"

**Comment by YossiMH** [comment]
@Drigax It does; see here: https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/figures/dictionary-objects.png

**Comment by Drigax** [comment]
Great, then this should be doable. Currently I'm planning on tackling this in the next month along with some other high priority asks.

@PatrickRyanMS, Can you help in designing some good UX to allow this? Going off my previous blender experience, I'm biased to adding separate flags for different scene element types to include at export similar to this FBX exporter dialog:

![image](https://user-images.githubusercontent.com/3952729/58981130-a085c700-8786-11e9-93cc-5e6561dc94c9.png)

**Comment by sebavan** [comment]
Closing for house keeping as we are grouping all the UI work in one place #537
