### ISSUE TITLE
add backface culling and double sided support in Maya

### ISSUE THREAD

**Issue by vortice3D** [BabylonJS/Exporters#529]
Hello,
We usually deal with transparency in our PBR materials, but don't have any way to specify the backfacing culling and double sided attributes later on.
How are these attributes handle, if they are?
Just in case, we would like to have a way to specify these attributes on a per material basis, like in Blender.
Thanks in advance.

**Comment by Drigax** [comment]
Hi @vortice3D. I don't believe that the maya exporter currently supports backface culling. We just added the funcitonality to the 3dsMax exporter, so we should add this to the Maya exporter as well. Unfortunately, you may have to add the material property manually as a workaround for now, but I'll try to get this parity in our Maya exporter in the next few weeks.

Can you give me a simple scene to test the correctness of the implementation?

**Comment by vortice3D** [comment]
Hi there,
I don't know which information do you have for the implementation.
But basically, there should be a way to tell the glTF material to disabled the backface culling attribute when there is any transparency or opacity going on.
In the attached sample file, the cube is red and semi transparent, and it appears as this inside sandbox:
![imagen](https://user-images.githubusercontent.com/1760601/59086704-ccc65280-8902-11e9-81ab-0245de69d3d8.png)

But it should have the backface culling turned OFF and be like this:
![imagen](https://user-images.githubusercontent.com/1760601/59086802-19aa2900-8903-11e9-8197-ed3afbf59a3a.png)

If this is implemented by adding custom attrbitues to the material, that's fine for now (you'll have to explain if that custom attribute should be added to the material itself or to the Shading Group).
I forgot to mention that we use Arnold's aiStandardSurface materials, but with StingrayPBS ones the problem is the same. The backface culling attribute can't be set, so it won't be exported at all.

Aside from that, there should be a way to control the transparency mode also.

[MAYA_SingrayPBS.zip](https://github.com/BabylonJS/Exporters/files/3264772/MAYA_SingrayPBS.zip)

**Comment by sebavan** [comment]
Closing for house keeping as we are grouping all the UI work in one place #537
