### ISSUE TITLE
3D Max Exporter flips model normals

### ISSUE THREAD

**Issue by total3dx** [BabylonJS/Exporters#53]
Models look inside out. 3D max 2016.
![inside-out](https://user-images.githubusercontent.com/639878/34322416-de38235a-e7f4-11e7-9b83-3c976ff4cefc.jpg)

**Comment by deltakosh** [comment]
Are exporting Babylon or gltf files? How do you load them?

**Comment by total3dx** [comment]
@deltakosh , thanks for a quick response. I use gltf format and click "Export & Run". The same thing happens in Threejs.

**Comment by deltakosh** [comment]
OK thanks we need to investigate 
Do you mind sharing your max scene?

**Comment by total3dx** [comment]
Sure, here it is https://www.dropbox.com/sh/ea6yzvjv50w1l04/AACG1pzNrbNpV9rv-0ypde7ka?dl=0

**Comment by deltakosh** [comment]
Thanks we will check early next year now;)
