### ISSUE TITLE
[Max][glTF] Exported textures're MUCH darker than original ones

### ISSUE THREAD

**Issue by EtagiBI** [BabylonJS/Exporters#533]
Hello,

Yesterday I updated 3DS Max to Babylon exporter and encountered a problem. All exported textures now are MUCH darker than original ones. 
![original_texture](https://user-images.githubusercontent.com/20855725/58939289-5570b180-8790-11e9-8daa-2c740dee72d8.jpg) ![exported texture](https://user-images.githubusercontent.com/20855725/58939292-573a7500-8790-11e9-8b1a-d3e3f4f942ca.jpg)

All my models use Standard materials, so It might be a Standard-to-PBR conversion issue, but previous versions of the exporter didn't have this problem.

**Comment by deltakosh** [comment]
Can you provide a max scene that highlights the issues?

**Comment by Drigax** [comment]
@EtagiBI what version did you update from? I do recall changing our PBR conversion algorithm via #485, which should have shipped as part of [v1.3.35](https://github.com/BabylonJS/Exporters/blob/master/3ds%20Max/CHANGELOG.md#v1335)

**Comment by EtagiBI** [comment]
> Can you provide a max scene that highlights the issues?

Here's a model example:
[Door_model.zip](https://github.com/BabylonJS/Exporters/files/3261065/Door_model.zip)
My exporting options are as follows:
![image](https://user-images.githubusercontent.com/20855725/59025061-bc639880-886c-11e9-879a-5389762484b4.png)


> @EtagiBI what version did you update from? I do recall changing our PBR conversion algorithm via #485, which should have shipped as part of [v1.3.35](https://github.com/BabylonJS/Exporters/blob/master/3ds%20Max/CHANGELOG.md#v1335)

Everything worked fine in v1.3.33.

**Comment by sebavan** [comment]
Also reported on the forum here: https://forum.babylonjs.com/t/exporting-from-3ds-makes-jpg-png-textures-gray-must-manually-hack-the-gltf-glb/3787

**Comment by sebavan** [comment]
@EtagiBI I found the issue, I am double checking the full extends of it and a fix should be in tomorrow.

**Comment by sebavan** [comment]
@Drigax Could you release a new version of the exporter ?

**Comment by Drigax** [comment]
linking this change to the commit:
https://github.com/BabylonJS/Exporters/commit/7df0e691cbd099bd56514c233d63e8dabd46c32a
