### ISSUE TITLE
Help could be improved.

### ISSUE THREAD

**Issue by biomorphica** [BabylonJS/Exporters#536]
Thanks for this excellent exporter. I finally got it working in Max 2017. The instructions, 
"move all .dll files into the installation directory of 3DS Max"
 were a little bit unclear, so here is what worked for me:

copy this file to 3ds Max 20##\bin\assemblies
Exporters/Max/Max2Babylon/20##/refs/Autodesk.Max.dll

and then also download
Exporters/3ds Max/Max2Babylon-1.4.0.zip
and put those .dlls into 3ds Max 2017\bin\assemblies

but ignore this file
Exporters/3ds Max/Max2Babylon/Refs/Autodesk.Max.dll

I suggest mentioning the extra zip Max2Babylon-1.4.0.zip in your instructions, as the installation failed until I added them. It took quite a while to figure this out. Other noobs would probably appreciate clear, thorough instructions.

**Comment by deltakosh** [comment]
This should fixed soon with installers

**Comment by deltakosh** [comment]
Furthermore this is already mentioned
![image](https://user-images.githubusercontent.com/1306056/59212937-8a05b400-8b68-11e9-81f5-45b2c852c118.png)
