### ISSUE TITLE
Instances with unique materials not working if exported in one file

### ISSUE THREAD

**Issue by BryanChrisBrown** [BabylonJS/Exporters#541]
I am trying to export a file from 3ds max 2019 with instanced objects that each have a unique material on them. 

Upon export, only one of the materials is chosen, and the others are not exported. (textures are also not exported)

also of note, These are skinned instances, and only one instance exports with the applied animation.  

I'd make the instances into unique objects but due to the skin modifier applied it'd reset their world position and I'd rather not have to do that. 

Exporting the instances individually respects both the animation and the material.

**Comment by Drigax** [comment]
Ah, i see. That's definitely wrong behavior. Looks like we're treating 3ds Max instances with the same restrictions as Babylon instances, so we make them all share materials.

As a quick fix I can change the exporter to treat instances as unique meshes if they don't share materials, but that will bloat the filesize with extra mesh data for the time being.

I'll try to powwow with @sebvan and @bghgary on how to best add support for this in the .babylon fileformat. I'm interested in any ideas for implementations.
