### ISSUE TITLE
unity exporter not support unity's normalmap 

### ISSUE THREAD

**Issue by sonygod** [BabylonJS/Exporters#55]
![image](https://user-images.githubusercontent.com/748320/34512624-a2162b58-f09e-11e7-8119-3acda43ea386.png)
![image](https://user-images.githubusercontent.com/748320/34512640-add43ab6-f09e-11e7-8575-1074da8337b7.png)
![image](https://user-images.githubusercontent.com/748320/34512653-bc7f10a4-f09e-11e7-8c2b-14cd95838432.png)

**Comment by deltakosh** [comment]
Pinging @mackeyk24

**Comment by MackeyK24** [comment]
Exactly what is problem ???

**Comment by sonygod** [comment]
the result is not same as unity's.



@MackeyK24

**Comment by MackeyK24** [comment]
Can you package up and send me the scene ?

Maybe move this issue to the http://www.html5gamedevs.com/forum/30-bugs/ forums too

**Comment by MackeyK24** [comment]
I dont know about this one... i asked guy to send me a sample unity scene package so i can check it out. But never heard back from him

**Comment by deltakosh** [comment]
Yep that's why I closed the issue
