### ISSUE TITLE
Exporter Installer Neats

### ISSUE THREAD

**Issue by sebavan** [BabylonJS/Exporters#550]
I can still experience the UI overlap:
![image](https://user-images.githubusercontent.com/16655165/59846398-0b76f680-9360-11e9-9244-126b71eb46e7.png)

and also the update button is still visible after install:
![image](https://user-images.githubusercontent.com/16655165/59846430-277a9800-9360-11e9-87e2-05efe08ed43b.png)

Both pictures have screen shoted after update.

**Comment by Jaskar** [comment]
1601 is for file not found. I fixed it -> Maya2Babylon.nll.dll instead of Maya2babylon.dll. My bad.
PR is coming !

**Comment by Jaskar** [comment]
https://github.com/BabylonJS/Exporters/pull/551

**Comment by sebavan** [comment]
Thanks
