### ISSUE TITLE
Flatten Hierarchy flag on 3DSMAX export

### ISSUE THREAD

**Issue by elpie89** [BabylonJS/Exporters#557]
We are encountering performance on our GLTF because many of them contain too many nodes.
It could be useful to add a flag to flatten all the hierarchy and combine everything into one mesh,
if there are no animations of course.
I was starting to do this to eventually create a pull request later but this is really complex to do with the C# API, I am not even sure that this is possible.
Would you eventually accept a routine like this made in python or maxscript and then evaluate everything from c#?

**Comment by sebavan** [comment]
I do not personnaly see any issue with a max script :-)

**Comment by sebavan** [comment]
It would even be great to surface in the UI in some ways as some of the artist I worked with told me they often merge unmerge before export.

Sounds more and more like a really nice idea :-)

**Comment by elpie89** [comment]
perfect I'll work on it soon

**Comment by Drigax** [comment]
@elpie89 when do you plan on starting this?

**Comment by elpie89** [comment]
sorry I had to work on the containers stuff.
I think next week anyway

**Comment by elpie89** [comment]
So I'm working on this right now and I see two solutions possible
First solution:
- We hold the file (save a temp copy of the file)
-flatten what should be flatten
-Export
-fetch the file()restore the file previously saved)

Second Solution:
-copy the content of the root node into a temp Master noder
-flat
-export 
-remove the Master node

Third solution:
during export we read the BabylonScnene istance
we create new flatten object based on the BabylonScene
export
remove object previously created

What do you think?
How should I proceed

**Comment by elpie89** [comment]
So after some time spent on this task
I have some report todo.

- The third solution is impossible, everything in this exporter is based on the IGameScene that is initialized at the beginning we cannot play with nodes during export as there is no possibility to add a node to the IGameScene interface during the export stage
Replace a node hierarchy with a new flattened node is not possible in my opinion

- The second option is dead as well, we should clone the entire scene, move the cloned nodes into a "BabylonMasterNode" and then export.
This for a huge scene is a pain, and can eventually end up with crushes
In other, we should refactor the entire exporter to avoid reference to the real root node

- The only possibility is the first one
Holding the scene then do whatever we want with the scene -> export->then revert
This solution, unfortunately, has  a con...user will loose all his undo history after the export

**Comment by elpie89** [comment]
@Selmar you should take a look on this to have an idea.

**Comment by elpie89** [comment]
To be honest, in our company we already have this solution but we are using maxscript or python to call Babylon exporter.
Actually, we have 3 tools that 
-plot animations then export using Babylon
-merge containers (to benefit of the reference system )then export using Babylon
-flatten meshes then export using Babylon

Obviously, I need to merge all these tools into one.
I really would like to add all these features in Babylon but I need some approval to do it

Please take a look on this 
https://knowledge.autodesk.com/support/3ds-max/learn-explore/caas/CloudHelp/cloudhelp/2016/ENU/3DSMax/files/GUID-4083A03C-E635-4911-9EAA-5791859EEC3E-htm.html

I think the best solution is using the Hold/Fetch logic
