### ISSUE TITLE
Export window clipped off on bottom.

### ISSUE THREAD

**Issue by BaldSavant** [BabylonJS/Exporters#558]
So while I'm endlessly filing bug reports, I've got a relatively minor one:

![Capture_babylonError6](https://user-images.githubusercontent.com/17505845/60284196-cd2d8a00-98bf-11e9-801c-cca040f834b6.png)

The edge of the window is clipped off at the bottom. I can't resize the window to get it to show the loading bar or the abort button down below, which isn't bothering me too much right now, but could be a pretty annoying issue down the road.

Maya 2019 (but it also happens in 2018), most recent update to the babylon editor (updated this morning, but it's been happening for some time, well before this update)

**Comment by BaldSavant** [comment]
And here's  gif so you can see how it's behaving when I DO resize:

![Capture_babylonError7](https://user-images.githubusercontent.com/17505845/60284854-71640080-98c1-11e9-8dd0-078e64b8ccd5.gif)

**Comment by sebavan** [comment]
I just can not repro this is so weird... What hardware scaling do you use on Windows ?

**Comment by BaldSavant** [comment]
I'm actually not sure (and google isn't helping me). Where do you find these settings?

**Comment by sebavan** [comment]
in Windows display settings 
![image](https://user-images.githubusercontent.com/16655165/60309200-eb8d9700-994c-11e9-864b-4039ad125f31.png)

**Comment by sebavan** [comment]
and under advanced 
![image](https://user-images.githubusercontent.com/16655165/60309218-0233ee00-994d-11e9-8e94-0eee114a53b5.png)

**Comment by BaldSavant** [comment]
Ah. So mine was set to off, but I've just relaunched Maya with it set to On and it's still giving the same behavior. 

My screen scale is set to 100%, if that's relevant.

**Comment by sebavan** [comment]
So we now have 2 reports of it highlighting that smthg is wrong. The main issue is now to find the culprit as I am totally unable to repro locally :-(

What screen resolution are you using ?

**Comment by sebavan** [comment]
Actually not related to the max issue so still no clue what could go wrong here.

**Comment by sebavan** [comment]
I attempted a workaround, could you try https://github.com/BabylonJS/Exporters/releases/tag/preRelease20190628.7 ?

**Comment by sebavan** [comment]
@BaldSavant let me know once you tried the new version. I double checked but can not find anything wrong in here.

**Comment by BaldSavant** [comment]
Sorry for the delay, it's been A WEEKEND. 

I'm running 1920x1080 on my end, 2 monitors both running at the same. Extended display, though I somehow doubt it's because I've got multiple monitors...

![Capture_babylonError8](https://user-images.githubusercontent.com/17505845/60458447-7c859c00-9bf3-11e9-97d6-fd57bce0716f.gif)

And just for the record, because I'm not sure if it was clear on the other gif, I can't see the bottom of this window no matter how I extend the editor size. It's like it's defaulted down below what I can see and it's adapting THAT to whatever size I adjust the window.

**Comment by sebavan** [comment]
Even on the latest ?

**Comment by BaldSavant** [comment]
yeah, even on the latest you linked above. Installed it twice to be sure it installed, once manually and once via the installer. Nothing changes with this issue.

**Comment by sebavan** [comment]
Unfortunately we would need to figure a repro to fix it... Do you have any zooming tool or accessibility setup in place ?

Else, a big UI revamp is incoming and should address the issue.

Also, are you able to repro on several machines ?

**Comment by BaldSavant** [comment]
nope, doesn't seem to be happening on my coworkers' machine (He's on version 1.3.0). I have gremlins. 

He also just had my try the win + Up/Down Arrow thing because I hadn't thought to try that and even when maximized/minimized, the babylon window on my machine still won't show its bottom stuff.

**Comment by sebavan** [comment]
Ok I ll try to see if anybody else can repro, cause it sounds highly linked to your environment :-(

**Comment by sebavan** [comment]
I am closing it for now, as I can not repro on already 6 different machines so I guess it is really some kind of conf on your workstation. Feel free to reopen if you are able to grab more info.
