### ISSUE TITLE
3dsmax exporter progress bar disappeared

### ISSUE THREAD

**Issue by elpie89** [BabylonJS/Exporters#560]
The progress bar of the exporter is disappeared.
Is this normal? Was it planned with the ui update? Because it was really useful and now there is no feedback

**Comment by sebavan** [comment]
So you are experiencing the same issue than #558 on Maya.

Unfortunately, I still can not repro this behaviour locally to troubleshoot. It does not seem to be related to hardware scaling nor auto dpi.

Is that also happening when you compile locally ?

I really want to fix this ASAP but can not find a way to repro :-(

**Comment by elpie89** [comment]
![image](https://user-images.githubusercontent.com/4441151/60331174-5a421300-9994-11e9-9a60-2448e2efe018.png)
It is just a merge problem, the progress bar is still there but hidden.
I live you to fix it

**Comment by sebavan** [comment]
Thanks a lot this is fixed, thought it was related to the maya issue but nope :-(
