### ISSUE TITLE
Feature Request: GPU-ready texture exporting

### ISSUE THREAD

**Issue by BaldSavant** [BabylonJS/Exporters#561]
My lead programmer is requesting a feature to allow exporting of multiple glbs at a time, each housing a different GPU-ready texture (as explained about half down the page here: https://m.makemepulse.com/nanogl-a-crafted-webgl-2-microframework-39837889f6a4 (and to be clear this isn't us, this is just a useful article)).

The goal would be to click export once and have it output a set of glb files. Each of these glb files would come packaged with the platform-appropriate decompressed image files generated based on the jpg/png images present in the maya file.

Ideally there would be a set of checkboxes to decide which of these to generate/not generate on export.

**Comment by sebavan** [comment]
This would not be part of the exporter directly but probably in an external tool targetting optimization in general.

@bghgary for pipeline ???

**Comment by bghgary** [comment]
This definitely seems like a good candidate for a component of a content pipeline. Doing this during export might be a bit heavy. Also, would [Basis support](https://opensource.googleblog.com/2019/05/google-and-binomial-partner-to-open.html) in glTF help with this scenario instead of different encoding for each platform?

**Comment by BaldSavant** [comment]
My programmer says that sounds like it'll do very nicely, @bghgary

**Comment by Drigax** [comment]
Created an issue to track this feature on the the content pipeline repository.

It is currently private due to red tape in open sourcing this project, but the expectation is that we'll be open sourcing the repo soon™.

Closing this issue since this isn't exporter work.
