### ISSUE TITLE
XREF/Containers support is missing, regeneration of handle is causing many problems

### ISSUE THREAD

**Issue by elpie89** [BabylonJS/Exporters#564]
I'm exploring the possibility to integrate containers, to use a reference system
after some day of tests, I came to the conclusion that is not possible right now because of the way the AnimationGroup system is serialized
I discussed this with @Selmar and he agrees with me

We cannot use node handles to serialize animation because they are regenerated in many different ways.
Speaking about containers this happens when a container is closed/opened
Node handles are also regenerated when merging/import scenes 
For that situation, we implemented some months ago the JSON system, but this is a temporary solution
The real problem is that we need to assign to each node a unique GUID and I would like to serialize this as a UserDefiniedProperties
What do you think?
To ensure that the GUID saved in the UserDefiniedProperties  in other we will have to register to some max notification system
For example:
we will have to register to NotificationCodes_NodeCloned to generate a new GUID when a node is cloned

I'm doing all of this because in my team we need to use containers but this will be a benefit for other problem in the future.
For example, doing this we could start to think on the possibility to move the serialization from the root node allowing to merge node between scene and keeping AnimationGroup without transferring the data with JSON

I need to solve this problem asap in my team so I already started, and the  retro-compatibility is guaranteed 

Let me know what do you think, or if you know another system to keep an id consistent when a two-scene are merged or a container  is loaded
I'm open for discussion

**Comment by elpie89** [comment]
Actaully register to the notification Create Object should be enough in my opinion
` m_CreateObjectDelegate = new GlobalDelegates.Delegate5(this.AssignGUID);
                GlobalInterface.Instance.RegisterNotification(this.m_CreateObjectDelegate, null, SystemNotificationCode.NodeCreated);`

**Comment by deltakosh** [comment]
I think this works well! Fancy doing the PR?

**Comment by elpie89** [comment]
yes I will do it tomorrow morning probably

**Comment by Drigax** [comment]
I really like this approach because it gives us an avenue to decouple our
babylon->gltf logic from the max->babylon logic. I was running against our
current implementation of AnimationGroup yesterday when working on #537.

Look forward to seeing the PR.

Thanks,
Nick
