### ISSUE TITLE
Blender exporter does not export diffuse bsdf but bakes texture

### ISSUE THREAD

**Issue by ettr** [BabylonJS/Exporters#57]
Hello everybody,
I try to export a simple meeple from blender to babylon. It does not export the materials which consist of a simple diffuse bsdf shade. The exporter always bakes the texture which is not my intendet aim.
Does anyone have an idea about it? The corresponding files are attached below.
Thanks a lot in advance!
[meeple.zip](https://github.com/BabylonJS/Exporters/files/1609822/meeple.zip)

**Comment by deltakosh** [comment]
Hey:)
Would you mind asking the question on our forum?
