### ISSUE TITLE
Ability to export multiple UV sets for one object through 3ds max Gltf exporter

### ISSUE THREAD

**Issue by candirsky** [BabylonJS/Exporters#572]
Hi, I'm working on some architectural configurator based on Gltf and three.js and I'm trying to export multiple UV sets for some scene objects for further texture swapping through three.js. I need these multiple UV sets for seeing different textures on the proper scale.
And the resulting Gltf file has only 2 UV sets after export instead of 10 expected UV sets. It would be great to have the ability to export more than 2 UV sets per object. 
Thanks,
Eugene.

**Comment by Drigax** [comment]
I see. Currently the 3dsMax exporter exports 2, since we initially export to the .Babylon format, which only supports 2 per-material. I don't like the idea that we're limiting our glTF functionality to the Babylon capabilities, however. but this will need some significant re-architecting, as we'll most likely have to call back to our modeling engine to request the number of UV sets.

I'll have to prioritize implementing this after the gltf refactor in #537, but I'm sure I can use an interface in the Babylon2Gltf pipeline to support this.

**Comment by Drigax** [comment]
As an update, I haven't forgotten about this issue, but I have some pressing work to do regarding resolving our currently reported bugs and . Currently, I don't believe I'll be able to tackle this properly until around November, but if anyone wants to make a PR, I'd be happy to review this.

**Comment by cptSwing** [comment]
> 
> 
> Hi, I'm working on some architectural configurator based on Gltf and three.js and I'm trying to export multiple UV sets for some scene objects for further texture swapping through three.js. I need these multiple UV sets for seeing different textures on the proper scale.
> And the resulting Gltf file has only 2 UV sets after export instead of 10 expected UV sets. It would be great to have the ability to export more than 2 UV sets per object.
> Thanks,
> Eugene.

Hey Eugene, are you sure threeJS supports more than 2 UV channels though?

**Comment by candirsky** [comment]
> Hey Eugene, are you sure threeJS supports more than 2 UV channels though?
Hey! I can't state 100% that threeJS supports more than 2UV channels. I'm a 3d artist and the developers I'm working with told me that it's possible. Here is the only pointer to an "array of UVs" I managed to find in threeJS documentation:
https://threejs.org/docs/#api/en/core/Geometry.faceVertexUvs
With that said, we moved recently our architectural configurator from three.js to fully pre-rendered 2d image-based workflow so my initial question isn't relevant anymore.

**Comment by cptSwing** [comment]
> 
> 
> > Hey Eugene, are you sure threeJS supports more than 2 UV channels though?
> > Hey! I can't state 100% that threeJS supports more than 2UV channels. I'm a 3d artist and the developers I'm working with told me that it's possible. Here is the only pointer to an "array of UVs" I managed to find in threeJS documentation:
> > https://threejs.org/docs/#api/en/core/Geometry.faceVertexUvs
> > With that said, we moved recently our architectural configurator from three.js to fully pre-rendered 2d image-based workflow so my initial question isn't relevant anymore.

I think what tickled the back of my mind was this: https://discourse.threejs.org/t/lightmap-second-set-of-uv-coordinates/5189/9

(IE we can't pass more than 2 channels in via gltf, at least)
