### ISSUE TITLE
Export at specific scale

### ISSUE THREAD

**Issue by BaldSavant** [BabylonJS/Exporters#576]
While doing some testing with our exported files we found that we could manually manipulate the "scale" value of the root node in the gltf file and get a nice scale adjustment on a file that would otherwise cause rig issues at extreme scale values (100x or 0.01 scale or greater/lesser). We're fixing our rig to be able to make this adjustment there, but there are circumstances when it would be much preferred to simply change the scale on export to our desired scale. 

Is this a feature that could be added, please?

**Comment by Drigax** [comment]
What 3d Modelling program are you using? Currently the 3dsMax exporter supports world coordinate unit scaling (cm, m, mm, etc...). 

but I'd like to know a bit more about what your specific use-case is, though.

**Comment by BaldSavant** [comment]
sorry, this is for the Maya version of the exporter.

So we're using GLTF files in a process of shipping animated characters to a variety of mobile platforms, including web AR. Due to the multitude of platforms being targeted at any given time, the ability to alter scale on export (rather than having to make pipeline changes for each platform) is much preferred, so we can work once, and then adjust swiftly.

**Comment by Drigax** [comment]
I see. I can understand the need for controlling this scale at export, but I don't think I can prioritize this work with my current backlog in bug fixes and refactoring work. If you or anyone else is able to work on this, I'd be more than happy to merge it in.

I am curious. I took [an authored animated GLTF](https://github.com/BabylonJS/MeshesLibrary/tree/master/vintageDeskFan) and modified the root node to change its scaling, but the keyframing in the object's animation groups undo that root transform. How are you currently working around this?

**Comment by BaldSavant** [comment]
interesting. I didn't see that when we altered a test file. When we played back the file it played back just fine at the smaller scale we changed it to. We did not test this extensively, admittedly, so there could be other factors at play. 

And alright. I'm not sure what our capacity to make this edit will be, but I'll definitely keep in mind that we can get it merged in if we do!
