### ISSUE TITLE
[3dsMax] MaxScript .NET runtime exception

### ISSUE THREAD

**Issue by xiazhvera** [BabylonJS/Exporters#577]
Hi there,
I tested the Exporters/3ds Max/MaxScripts/Max2Babylon.ms and got the following .NET runtime exception on "maxScriptManager.Export param". Any idea? 
```
-- MAXScript FileIn Exception:
-- Runtime error: .NET runtime exception: Object reference not set to an instance of an object.
```

**Comment by Drigax** [comment]
Oopsies. Our export parameters downcasting broke with the change to the export parameters. I made a few changes to fix this :)
