### ISSUE TITLE
3dsMax 2019 Crash with latest update (CD Pre Release 20190807.5)

### ISSUE THREAD

**Issue by Mustard-Design** [BabylonJS/Exporters#586]
When opening a .max file (3dsMax2019) with a biped rig with morph targets (and Point Helpers), Max crashes instantly with Application Error message.
If I replace the updated Babylon .dll's with older itterations, the issue goes away.

**Comment by Drigax** [comment]
I'll take a look, I'm not sure what contributed to this crash off hand (since yesterday's changes don't seem related) but if you have a simple repro file, that may speed things up for me as I try to reproduce teh crash.

**Comment by Drigax** [comment]
I currently don't have any ready-made test scenes for complex skeletal rigs with morph targets and IK, I was able to export the test scene you provided for #571 without error, however...

**Comment by Drigax** [comment]
Hi @Mustard-Design are you still encountering this crash?

**Comment by Drigax** [comment]
Hi @Mustard-Design, I'll have to close this ticket since I am unable to reproduce on my own. Please feel free to reopen this in the future with a repro scene, and I'll be sure to take a look 🙂
