### ISSUE TITLE
3ds max crashing with Babylon libraries 

### ISSUE THREAD

**Issue by Prospector-au** [BabylonJS/Exporters#587]
Tried 2015 and 2019 3ds max versions. .NET is installed. 
Windows 7 Ultimate SP1 updated
Radeon R9 390

**Comment by Drigax** [comment]
What version of .Net do you have installed? The exporters require [Atleast .NET 4.5-4.7 depending on your version](https://doc.babylonjs.com/resources/3dsmax#dependencies)

**Comment by Prospector-au** [comment]
Checked with 4.7 and 4.7.2 on 2015 and 2019 3ds max

**Comment by Drigax** [comment]
I was able to fix this via #589. Previously, we included ManagedServices.dll in our build, and deployed it with the rest of our dependencies, when it already ships inside Max, causing max to crash when loading the additional library.

You should be able to fix your Max installation by deleting ManagedServices.dll from your bin/assemblies folder.
