### ISSUE TITLE
Lightmap on UV2 is not correctly exported

### ISSUE THREAD

**Issue by kevinshane** [BabylonJS/Exporters#594]
Hi, the latest 3ds max 2015 plugin doesn't export the uv2 correctly, my model has uv2, if I put that baked map into AO channel, it correctly shown up in babylon sandbox page, but when I try to add the lightmap in that babylon sandbox, it's broken(I assume it should show the correct result on the uv2 channel?). would you please take a look at it? thanks

**Comment by Drigax** [comment]
Sure, I can take a look. It'll take me a bit to setup a test scene, as I'm not too familiar with the light baking workflow in Max. Can you send me a repro scene as well?

**Comment by kevinshane** [comment]
Hi @Drigax thank you for taking time to investigate this problem
I am using a lightmap(a baked image which contains light color information etc)
please use this test scene
[teapot.zip](https://github.com/BabylonJS/Exporters/files/3507533/teapot.zip)

as you can see that, the glb exported to babylon sandbox shows it has 2 uv set(not sure why they call it "set" but they seems correctly exported the uv2 channel)
![01](https://user-images.githubusercontent.com/10471026/63134160-d3580100-bffa-11e9-94dc-aa378f824916.jpg)

next I apply the lightmap image to the scene lightmap channel, the result is totally wrong
![02](https://user-images.githubusercontent.com/10471026/63134209-12865200-bffb-11e9-999a-93f2a28d81e6.jpg)

I also set the imported lightmap as uv set1 channel, result still wrong
![03](https://user-images.githubusercontent.com/10471026/63134267-4a8d9500-bffb-11e9-8623-c65897c34f09.jpg)

Do you think what happen? Thanks

**Comment by Drigax** [comment]
Hmm, I'm not sure. Can you also share the Max scene files? I was interested in seeing how you have UV coordinates configured as well.

**Comment by kevinshane** [comment]
sure, here is the max scene, you also need to install Corona render, because I use corona to bake the lightmap. but if you just want to check how I apply the uv2, then you don't need Corona of cause
[teapot.zip](https://github.com/BabylonJS/Exporters/files/3507751/teapot.zip)

**Comment by Drigax** [comment]
Thank you,

I looked at the teapot UVs and the resulting lightmap, everything looks properly setup in 3dsMax, and the UV sets and lightmap do appear to be correct, This is looking to be a bug, as I'm not convinced that the exported UV2 set is correct, or if the map is being applied correctly in-engine.

**Comment by Drigax** [comment]
Small update:

I was playing around with the lightmap and UV2 coordinates of the teapot, and modifiying the glTF to switch UV coordinate axes allows me to view the UV2 mapping in a viewer.

![image](https://user-images.githubusercontent.com/3952729/64467982-a071cc00-d0d3-11e9-88e7-b871c4f2fb77.png)

Modifying the U angle of the texture gives us a properly applied map....but I'm not sure what that means. @PatrickRyanMS  can you help explain what the UVW angles represent?

**Comment by Drigax** [comment]
Looking deeper, I think this a bug in our loader/inspector:
![image](https://user-images.githubusercontent.com/3952729/65005792-f86bb800-d8b5-11e9-864b-70e756c63e0a.png)


[UVPlane_tests.zip](https://github.com/BabylonJS/Exporters/files/3618925/UVPlane_tests.zip)

In this test scene we have three meshes, all planes with 2 triangles.
Planes 1 and 2 have identical UV1 and UV2, while plane 3 has a rotated UV2.
Plane 1 was exported with a UV texture assigned to the albedo channel.
Planes 2 and 3 share a  material, with manually assigned albedo texture, but the texture displays with inverted Y. strange...

This discovery pointed me to this line in our inspector texture loader:
https://github.com/BabylonJS/Babylon.js/blob/08950637e62da912da8440d478056f64b1549442/inspector/src/components/actionTabs/lines/textureLinkLineComponent.tsx#L143

Which explains why our textures are appearing inverted...

@deltakosh, sounds about right? I opened
