### ISSUE TITLE
3dsMax to GLTF: alphaCutoff set to 0.4 when using transparency map

### ISSUE THREAD

**Issue by JonnyBlackburnCore** [BabylonJS/Exporters#597]
#### Problem
When a mesh has a transparency map the exporter combines it with the base color map and exports a PNG, but it arbitrarily sets the alphaCutoff in the gltf to 0.4.

#### Expectation
I was expecting the alphaCutoff to be 0.
Not sure if this is designed behaviour, but it definetly tripped me up while trying to change the alpha of a mesh with a transparency mask on.
I think the documentation also needs updating. At the moment it says that the alphaMode will be set to BLEND, but it's actually set to MASK.
https://doc.babylonjs.com/resources/3dsmax_to_gltf#alpha-mode

---
I've attached a simple gltf scene with this issue and a screenshot of my material nodes in 3dsMax 2019.

[test.zip](https://github.com/BabylonJS/Exporters/files/3521083/test.zip)
![image](https://user-images.githubusercontent.com/45765943/63355743-89ef1500-c35e-11e9-8039-b88b3ca6fa50.png)

**Comment by Drigax** [comment]
I see, I can change the default alphaMode to use blend instead of Mask, this doesn't seem like proper behavior.

**Comment by echadwick-wayfair** [comment]
How about simply adding a Babylon Attribute at the bottom of the material? We're already using this for babylonUnlit. (https://github.com/BabylonJS/Exporters/issues/292#issuecomment-414372887).

I can't find it now, but I thought someone had already added an alphatest attribute to the MAXScript.

**Comment by Drigax** [comment]
I found the alpha test toggle thanks to @echadwick-wayfair, this seems like a sufficient way to indicate blend vs mask. I was able to add another custom attribute that also allows us to set our mask cutoff. I'll add this change in combination with the changes I want to make to support #602
