### ISSUE TITLE
Max2Babylon won't export transparency JPG

### ISSUE THREAD

**Issue by echadwick-wayfair** [BabylonJS/Exporters#598]
The exporter fails when a material uses a JPG for transparency, and a color (not a texture) for albedo.

It seems to me it should convert the transparency texture + base color into a single PNG, storing the JPG in the Alpha, and the color in the RGB. 

Or even better, make it an 8bit PNG since it's just one color (would that work? as long as we can customize the PNG LUT we should be able to represent any solid color). Are 8bit PNGs supported?

To get around this error, we could simply pre-process our transparency into a PNG, but this would add a couple extra steps to our automation, which I'd like to avoid. 

Plus it seems like the proposed behavior would fit with the existing exporter step where it creates a single PNG when it encounters textures in both Base Color and Transparency Weight inputs. 

The error this example generates:

Export cancelled: Object reference not set to an instance of an object.
System Null Reference Exception: Object reference not set to an instance of an object. at Max 2Babylon.Babylon Exporter. Export BaseColorAlpha Texture(ITexmap baseColorTex Map, ITexmap alpha Tex Map. Single[] baseColor, Single alpha, Babylon Scene babylon Scene, Stri

![image](https://user-images.githubusercontent.com/40177036/63355679-83e43e80-c334-11e9-91cf-765d5aa20176.png)

Max2Babylon 1.4.2
3ds Max 2018.4

[vvro3496_3dsmax2018.zip](https://github.com/BabylonJS/Exporters/files/3521168/vvro3496_3dsmax2018.zip)

**Comment by echadwick-wayfair** [comment]
I found it does export correctly if I use an 8-bit PNG.

![image](https://user-images.githubusercontent.com/40177036/63359341-96fa0d00-c33a-11e9-92d5-35b791b1857d.png)

![vvro3496_shadow](https://user-images.githubusercontent.com/40177036/63359374-a5482900-c33a-11e9-85d1-d70af33b8776.png)

**Comment by echadwick-wayfair** [comment]
Actually, in the above setup, none of those options need to be set for it to export properly. They can all be left at the defaults. Those settings just make it easier to preview inside 3ds Max.

I do find however that the transparency map doesn't appear as an option in the Textures section. It would be helpful to be able to toggle the opacity map in an unlit mode on the model, like we can with the wrench icon.
![image](https://user-images.githubusercontent.com/40177036/63360219-f9074200-c33b-11e9-83b3-f381b68cd222.png)

[vvro3496_8bitPNGshadow.zip](https://github.com/BabylonJS/Exporters/files/3521367/vvro3496_8bitPNGshadow.zip)

**Comment by Drigax** [comment]
Thanks for the investigation! Solid base color material with a transparency map sounds like a bug that we should support. I can modify the updater to create a alpha texture sized texture filled with the base color as soon as I return from vacation. :)

I was able to find the source of the nullreference [where we dereference the texture object unsafely](https://github.com/BabylonJS/Exporters/blob/4e169a42baaeabacc74b594deca5e81b393d5578/3ds%20Max/Max2Babylon/Exporter/BabylonExporter.Texture.cs#L299), but to be honest I don't really like how this entire function flows, our format and alpha mode checking logic is a bit convoluted and should be tweaked for clarity.

**Comment by Drigax** [comment]
I was able to fix the null reference via:

I don't currently plan on supporting 8bpp PNG export however, since glTF requires alpha to be included in the base color map.

**Comment by echadwick-wayfair** [comment]
Thanks for the fix!

I am able to use PNGs using 8bit RGB + 8bit Alpha format. Max2Babylon exports those just fine, as long as I precreate them in Photoshop. I just have to wire the same single PNG into both Base Color and Transparency. Then I get a proper transparent material in glTF.

My suggestion was that the exporter could create this bit format if those conditions were present. Simple color in Base Color, texture in Transparency. But this is pretty low priority for me.

In a related bug, I did discover an odd issue with "regular" 32bits-per-pixel PNG. 

1. If I wire one PNG into both Base Color and Transparency of the Physical Material, then export, the glTF does not enable alpha blend.
2. But if I wire the PNG into Transparency, then duplicate the Bitmap node and wire that into Base Color, the exported glTF **does** use alpha blend. 

It's still the same PNG in both inputs. The difference is, it's not an instanced Bitmap node. I wonder why this occurs?

**Comment by Drigax** [comment]
I see, thanks for clarifying the usecase, I didn't consider formatting as 16 bit, with 8bit RGB & 8-bit alpha channel. It's definitely possible, I'd keep this as a very low priority optimization we can make. 

The disparity in alpha mode setting sounds very important to address, however. (And most likely related to an alpha mode test toggle we appear to ignore in #602)

I'll close this bug and investigate these issues next.

**Comment by Drigax** [comment]
I also created:
https://github.com/BabylonJS/Exporters/issues/609

to track our texture export optimization.
