### ISSUE TITLE
Expose Maya exporter to MEL commands

### ISSUE THREAD

**Issue by Drigax** [BabylonJS/Exporters#599]
Similarly to the [3dsMax MaxScript Manager](https://github.com/BabylonJS/Exporters/blob/master/3ds%20Max/Max2Babylon/MaxScriptManager.cs) [And associated sample script](https://github.com/BabylonJS/Exporters/blob/master/3ds%20Max/MaxScripts/Max2Babylon.ms), the Maya exporter entrypoint and parameters should be exposed to MEL.

**Comment by Drigax** [comment]
I'm currently occupied resolving reported bugs, and will be helping with the Babylon Native Open Transcoder Project until November, But any help regarding implementing this would be greatly appreciated.

**Comment by Ziethriel** [comment]
I would love to have this.

**Comment by Mudoglu** [comment]
I see the issue is closed but i dont se a way in maya to start the exporter with a python or mel command. Do i miss here something.?

**Comment by Drigax** [comment]
Hey oglu,

We just added support for this back in December. Here is a sample script using the ScriptToBabylon command:
https://github.com/BabylonJS/Exporters/blob/master/Maya/MELScripts/exportScriptExemple.mel

**Comment by Mudoglu** [comment]
Thanks!
Thats great!
