### ISSUE TITLE
Alpha Test Custom Attribute does't exported from 3ds max

### ISSUE THREAD

**Issue by Prospector-au** [BabylonJS/Exporters#602]
![1](https://user-images.githubusercontent.com/24756885/63651593-09198a00-c75f-11e9-853c-258c2c134540.jpg)
![2](https://user-images.githubusercontent.com/24756885/63651594-09198a00-c75f-11e9-9548-8ce5189e14cd.jpg)

**Comment by Drigax** [comment]
Ah, this definitely looks like a regression. I'll have to take a look at this asap.

**Comment by Drigax** [comment]
This sounds somewhat related to how we assign Alpha mode as observed by @echadwick-wayfair:
https://github.com/BabylonJS/Exporters/issues/598#issuecomment-526831230

I believe somewhere in our export process we override our alpha mode setting, I'll be taking a close look at this today.

**Comment by Drigax** [comment]
Weird, I setup this test scene to reproduce this,
[SimpleCubeWithTransparency.zip](https://github.com/BabylonJS/Exporters/files/3572375/SimpleCubeWithTransparency.zip)

I am unable to find the Babylon Attributes panel though, a quick search through the codebase wasn't very fruitful either...

@PatrickRyanMS, can you please help me find this "Babylon Attributes" panel shown in the original post?

![image](https://user-images.githubusercontent.com/3952729/64219954-825e5e80-ce7c-11e9-8ec6-b5cc81a0858b.png)

**Comment by echadwick-wayfair** [comment]
Babylon Attributes is added to the material via MAXScript. Sample provided here;
https://doc.babylonjs.com/resources/3dsmax_to_gltf#alpha-mode

**Comment by echadwick-wayfair** [comment]
I believe Max2Babylon doesn't support OSL inputs, like you're doing with the invert node there.

And if you want to see a material preview in the viewport, check out https://help.autodesk.com/view/3DSMAX/2019/ENU/?guid=GUID-39E321E5-962B-49C2-BD05-B1FA3F48BA26

**Comment by Drigax** [comment]
Thanks @echadwick-wayfair , I think I can see what's happening here.

It appears that we don't serialize the alpha transparency mode for standard materials. 
I'm not sure if there's a reason why yet unfortunately.
