### ISSUE TITLE
Max2Babylon baseColorFactor multiplier change request

### ISSUE THREAD

**Issue by echadwick-wayfair** [BabylonJS/Exporters#605]
I would like to recommend changing the baseColorFactor color-multiplier behavior to **opt-in.** 

Base Color in the Physical Material defaults to gray. This is too easy for new users to miss, and it makes all surfaces look dull. 

We're seeing this error a lot with contractors, many of whom are less technically inclined, so remembering to always set this to white can be a bit of an educational challenge.

![image](https://user-images.githubusercontent.com/40177036/63864590-1e203400-c97e-11e9-9a6c-0e593a55ce70.png)

![image](https://user-images.githubusercontent.com/40177036/63864744-5758a400-c97e-11e9-862e-112abe22b1af.png)

My proposed change:
1. If there's no bitmap in Base Color, exporter would set Base Color swatch as the baseColorFactor. This is the current behavior, no change suggested.
2. If there's a bitmap in Base Color, then ignore the color in the Base Color swatch. Set the baseColorFactor to white. Look for a RGB Multiply node, and if present, export the Color#2 value as the baseColorFactor.

Example file attached.

Base Color does not preview in Max Viewport as a color multiplier, but RGB Multiply does, and it works in renders too.

If there's a concern about breaking existing content, perhaps you could suggest this is what version control is for? If someone had reams of content using the existing Base Color method, it could be advised for them to use the previous version of the exporter, once the proposed change was implemented. 

This could also be MAXScripted if they wanted to stay current. A custom script could convert older content to the newer RGB Multiply method without much trouble. 

Related: https://github.com/BabylonJS/Exporters/issues/367

[rgb-multiply-for-basecolorfactor.zip](https://github.com/BabylonJS/Exporters/files/3551381/rgb-multiply-for-basecolorfactor.zip)

Thanks for listening!

**Comment by Drigax** [comment]
Thanks for your request!

Currently I'm personally tied up resolving reported bugs, and assisting with the Babylon Open Transcoder project, but this seems like a great enhancement to make.

I'll leave this flagged for anyone to feel free to submit a PR for, else I'll take a good look at implementing this around November.

**Comment by noalak** [comment]
Working on it.

**Comment by Drigax** [comment]
Fixed via #761
