### ISSUE TITLE
3dsMax Texture Export - Optimize material color + alpha texture export to use 8bppRGB + 8bpp alpha formatted PNG

### ISSUE THREAD

**Issue by Drigax** [BabylonJS/Exporters#609]
To further optimize our base color alpha texture export, in cases where no base texture is provided, we should generate an 8bpp RGB + 8bpp alpha formatted png texture, as opposed to our current 32bpp generated texture.

**Comment by Drigax** [comment]
Better description can be found here:
https://github.com/BabylonJS/Exporters/issues/598#issuecomment-526831230

**Comment by echadwick-wayfair** [comment]
Thanks for driving this! Might be a good time to put in appropriate hooks for KTX2 / Basis, so it's easier to enable once that's ready...?

**Comment by noalak** [comment]
Hi there,

Looking at this issue, I don't think there is an easy way to fix it.

The 8bpp RGB + 8bpp alpha pixel format means:
- 8bpp for a grayscale
- 8bpp for alpha

Name this format _Format16bppAGrayScale_

To get such texture using Photoshop, you can do Mode > Image > Grayscale. The software prompts you to confirm if you want to switch the pixel format and ignore colors.
The result is a lighter texture file, but not by much (25% reduction).
@echadwick-wayfair Have you been using Photoshop and some procedure as above to get 8bpp RGB + 8bpp alpha textures ? Do you experiment similar reduction in texture weight ?

What is asked for is to reproduce this behavior inside the Exporter when there is no base color texture as input.

As such, the 8bpp grayscale are not necessary as they would all hold the same value, which is the base color factor. Thus even a 1bpp RGB would be enough, always storing value 1 (white).
The base color factor would be stored in the similary named field of a Babylon or glTF material. And engines will multiply this value with the texture one.

Name this format _Format9bppAGrayScale1_

In both cases, the format is absent from [PixelFormat enum in .NET 4+](https://docs.microsoft.com/fr-fr/dotnet/api/system.drawing.imaging.pixelformat?view=netframework-4.8).

Another format could be intersting here: PixelFormat.Alpha
But this format is [depecrated ](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/bb321548(v%3Dvs.85)) and [not suitable for Bitmap constructor](https://docs.microsoft.com/fr-fr/dotnet/api/system.drawing.bitmap.-ctor?view=netframework-4.8#System_Drawing_Bitmap__ctor_System_Int32_System_Int32_System_Drawing_Imaging_PixelFormat_) as it's not starting with _Format_.

As a result, System.Drawing.Bitmap doesn't seem to answer our needs.

---

There is however an API that is doing the desired conversion (_Format32bppArgb_ to _Format16bppAGrayScale_) named [graphicsmill](https://www.graphicsmill.com/docs/gm/M_Aurigma_GraphicsMill_ColorManagementProvider_Convert_1_3e209c07.htm).

But this API is not free nor licence free. I don't think it's something you would consider for your open source exporters.

Tested and functionnal. The gain is minimal though, as is the photoshop manipulation.

For now, we don't have a better solution to offer.
Does anyone has further insights on this issue ?

**Comment by echadwick-wayfair** [comment]
This is a low priority issue for us. 

The manual process to save a 16bpp PNG in Photoshop:  
1. File menu, Export, Export As. 
2. Format: PNG
3. Transparency: Enabled
4. Smaller File (8-bit): Enabled.
5. Export All.
6. Save.

File sizes compared:
![image](https://user-images.githubusercontent.com/40177036/74347439-17944600-4d7f-11ea-8431-c0ea4220999e.png)

**Comment by deltakosh** [comment]
Closing for now as we have no resources to work on it
