### ISSUE TITLE
Any installation of the gltf exporter for 3DS Max 2018 says "Can't reach Github". I'm just a beginner so forgive my lack of knowledge. Any help is appreciated. Thank you

### ISSUE THREAD

**Issue by Fizzelini** [BabylonJS/Exporters#615]
![Screenshot (1045)](https://user-images.githubusercontent.com/53847398/64582625-b8da3300-d3c0-11e9-9192-baa5a69c6062.png)

**Comment by ephb** [comment]
I have no idea why the installer fails for you but the manual also has a section for the manual installation of the plugin:
https://doc.babylonjs.com/resources/3dsmax#manual-install

**Comment by Drigax** [comment]
Hi @Fizzelini 

Unfortunately, the Max 2018 updater appears to work properly for me:
![image](https://user-images.githubusercontent.com/3952729/64639736-4e73c380-d3bd-11e9-886f-21f3c8341463.png)

Can you check that you can access https://github.com/BabylonJS/Exporters/releases/download/preRelease20190910.4/Max_2018.zip?

I'd assume that something is blocking your access to github or the exporters repo, but unfortunately I can't debug this anymore in depth.

**Comment by Fizzelini** [comment]
> 
> 
> I have no idea why the installer fails for you but the manual also has a section for the manual installation of the plugin:
> https://doc.babylonjs.com/resources/3dsmax#manual-install

Thank you for your feedback. I have tried the manual installation as well and it still doesn't seem to work.

**Comment by Fizzelini** [comment]
> 
> 
> Hi @Fizzelini
> 
> Unfortunately, the Max 2018 updater appears to work properly for me:
> ![image](https://user-images.githubusercontent.com/3952729/64639736-4e73c380-d3bd-11e9-886f-21f3c8341463.png)
> 
> Can you check that you can access https://github.com/BabylonJS/Exporters/releases/download/preRelease20190910.4/Max_2018.zip?
> 
> I'd assume that something is blocking your access to github or the exporters repo, but unfortunately I can't debug this any further on my end.

Yes i can access it and have downloaded the file multiple times. Nonetheless, I appreciate your time. Thank you

**Comment by Jaskar** [comment]
Hi @Fizzelini ,

Simple question, but did you launch the tool with admin rights ?
If so, maybe your firewall is blocking the ping ...

**Comment by Fizzelini** [comment]
> 
> 
> Hi @Fizzelini ,
> 
> Simple question, but did you launch the tool with admin rights ?
> If so, maybe your firewall is blocking the ping ...

Hey @Jaskar ,
Yes I've tried launching it with admin rights as well as disabling my firewall. Still doesn't seem to work :/

**Comment by Jaskar** [comment]
The error is from :

            url_toTest= "github.com";
            var ping = new System.Net.NetworkInformation.Ping();

            try
            {
                var result = ping.Send(url_toTest);

                if (result.Status != System.Net.NetworkInformation.IPStatus.Success)
                {
                    this.form.error("Error : Can't reach Github.");
                    return false;
                }

Can you simply try to ping github.com ?
If it was a downloading problem, or just gathering information from the last version, you'd have more explicit error messages...

**Comment by irawoodring** [comment]
I believe this issue should be reopened; many network administrators block ping.  I receive this same issue on my work network, but can download from home.  A better mechanism for checking for connectivity should be used.  A better mechanism might be checking for an HTTP connection and checking the status code perhaps.

**Comment by trexguo** [comment]
> I believe this issue should be reopened; many network administrators block ping. I receive this same issue on my work network, but can download from home. A better mechanism for checking for connectivity should be used. A better mechanism might be checking for an HTTP connection and checking the status code perhaps.

+1

**Comment by looeee** [comment]
I'm getting the same issue. 

I can access/ping github and download the exporter file manually without any issues. 
I have also added the installer to windows defender exceptions and given it access through the defender firewall. 
I'm not running any other firewall or virus scan software that might block access.

**Comment by Jaskar** [comment]
Hi @irawoodring @trexguo @looeee ,

As I'm no longer working on this project, I can't help, unfortunately.
However, I'll reopen the issue.

@sebavan @pandaGaume , any ideas of who could help here ? :)

**Comment by pandaGaume** [comment]
Hello,
humm, this is an old thread... just let me have a look into the code to better understand the subject. In all case I'm agree we should remove ping.
