### ISSUE TITLE
Improve exporter consistency

### ISSUE THREAD

**Issue by deltakosh** [BabylonJS/Exporters#619]
- [ ] Align Max and Maya Supported Features
- [ ] Share the main exporter form to ensure consistency

**Comment by deltakosh** [comment]
@Drigax: can you chime in to do a precise list of features to add / remove / align?

**Comment by Drigax** [comment]
Sure, I think most of the additions are to Maya, but I'll update this as needed

Maya:
[ ] Add support for node selection for Animation groups
[ ] Add support for invoking Maya2Babylon via MEL
[ ] Add layer-based export selection

**Comment by Drigax** [comment]
@elpie89 I created 628 for this feature.

**Comment by Vinc3r** [comment]
Why not also improve consistency with Blender exporter too by the way?

**Comment by deltakosh** [comment]
Blender is not handled by us

**Comment by deltakosh** [comment]
Closing for now
