### ISSUE TITLE
3dsMax - Add Animation Baking

### ISSUE THREAD

**Issue by Drigax** [BabylonJS/Exporters#628]
Deliverable for #619.

- [x] Similar to the [Maya implementation](https://github.com/BabylonJS/Exporters/blob/master/Maya/Exporter/BabylonExporter.Animation.cs#L56-L165), it would be a great addition to the 3dsMax exporter to add the option to bake animations per-frame.

- [ ] an additional deliverable would be to use the baking functionality to bake the first and last frames of an animation group at export, as requested via #596

**Comment by elpie89** [comment]
I need to spend time on #632 then I can work on this

**Comment by Drigax** [comment]
removing the second deliverable from this task, it's already best tracked via #596.
