### ISSUE TITLE
Maya Exporter - Second Animation Clip Incorrect Length

### ISSUE THREAD

**Issue by HidingGlass** [BabylonJS/Exporters#634]
My model has 2 looping animation states:
- State01 - (frame 1-24)
- State02 - (frame 25-48)

I have added both of these states as Animation Groups in Maya and can successfully export to GLB or GLTF.

My first animation group plays correctly and as expected in Sandbox, but my second animation group seems like it’s playing from frame 1-48 instead of 25-48 and the first half is just still (no animation).Is this a bug or am I doing something incorrectly?

PC
Maya 2019
Babylon Exporter v20190918.9
Blendshape Animations

![BabylonExportBug_01](https://user-images.githubusercontent.com/11765663/65621047-f9c17280-df90-11e9-8375-882f95ab5028.jpg)

**Comment by Drigax** [comment]
Thanks for the report @HidingGlass. Do you have a scene that you can share that reproduces this?

**Comment by HidingGlass** [comment]
OK I set up a quick test scene. Here is the MA file and corresponding GLB file. You can see in Sandbox that "Anim_B" looks almost stuck or paused for the first half and is twice as long as it should be.

 
[AnimationGroupTest_01.zip](https://github.com/BabylonJS/Exporters/files/3653840/AnimationGroupTest_01.zip)

**Comment by Drigax** [comment]
Thanks for the repro file, I think I see the issue here:
Looking at our exported morph target weight accessor for animation A:
![image](https://user-images.githubusercontent.com/3952729/65713830-e07efb80-e04e-11e9-81ac-dcdc3f83a929.png)

All the keyframes are between 0-1 seconds.

While for Animation B:

![image](https://user-images.githubusercontent.com/3952729/65713920-03a9ab00-e04f-11e9-9821-4836456962ac.png)

**Comment by HidingGlass** [comment]
Thanks for looking into this. OK so it seems like this is a bug with the exporter itself right? Unfortunately I'm not very experienced with Babylons JSON objects or compiling C# into a maya plugin. 

Do you see an easy way to edit the GLTF JSON data to fix this issue for now? Or is it possible there would be a hotfix for this issue on the exporter plugin itself some time soon? Unfortunately this is project-breaking for us at this stage.

**Comment by Drigax** [comment]
Unfortunately I don't think there's an easy way to modify GLTF animation buffer data, the JSON is fine for the most part here. but I'm working on getting a fix out ASAP.

**Comment by Drigax** [comment]
Found the issue, turns out our GLTF exporter wasn't properly offsetting morph target keyframe data based off the animation group frames. Fix should be available as soon as CI publishes the next build.
