### ISSUE TITLE
exporter is broken

### ISSUE THREAD

**Issue by elpie89** [BabylonJS/Exporters#648]
After last vertex optimization pull request max  exporter is broken
step to repro
open max
export a teapot
display it in vscode or Babylon web  viewer

**Comment by Drigax** [comment]
Sorry about that, looking into it now.

**Comment by elpie89** [comment]
no worries

**Comment by Drigax** [comment]
Got the fix, I think that we copy our Global vertex when appending to our hashtable, so changing its index after doesn't affect the hashtable entry. Changing our order of operations and making an in-memory copy of the vertex appears to fix this.
