### ISSUE TITLE
How can I export animation groups?

### ISSUE THREAD

**Issue by AndresCH10** [BabylonJS/Exporters#652]
Buenos dias, tengo un problema y es el siguiente : 
Al exportar mi modelo 3D con mis grupos de animación, solo me  sale la primera animacón.
Como podría exportar las animaciones con el pluging babylon desde 3D Max ?

**Comment by Drigax** [comment]
Hi, my spanish isn't too good, but i assume you mean:

"Good morning, I have a problem and it is as follows:
 When exporting my 3D model with my animation groups, I only get the first animation.
 How could I export the animations with the babylon pluging from 3D Max?"

I'm not sure if i understand the issue, you claim that you only get your first animation group when exporting? Can you share a scene that reproduces your issue?

**Comment by AndresCH10** [comment]
Good morning, as for the description of the problem is the following:

-> I have animation groups, I have 3 animations for an animated object, but when I export it with the "Babylon" pluging it only exports one of the three animations.
-------> I add image
![Captura de pantalla (193)](https://user-images.githubusercontent.com/56534602/66909060-6b2e9700-f00c-11e9-8654-56f934124bb0.png)
![Captura de pantalla (194)](https://user-images.githubusercontent.com/56534602/66909086-72ee3b80-f00c-11e9-9341-c500951960fb.png)

**Comment by Drigax** [comment]
Interesting...can you share your scene? My current testing scenes don't reproduce this.

**Comment by AndresCH10** [comment]
Of course, here I attached the Max file.
Another little thing, the version of the pluging I use is:
CD Pre Release 20191016.5 
----->Max
[Bee3.zip](https://github.com/BabylonJS/Exporters/files/3738360/Bee3.zip)

**Comment by Drigax** [comment]
Hmm, I'm not sure if I can reproduce what you're seeing on preRelease20191016.5:

In the scene there are 3 animation groups assigned:
![image](https://user-images.githubusercontent.com/3952729/67045306-df3b6e80-f0e2-11e9-8838-80ce98d3dd6c.png)

And the log appears to export them properly:
![image](https://user-images.githubusercontent.com/3952729/67044754-d9915900-f0e1-11e9-930c-31f73f4f0479.png)

Looking at the scene export, I can see three distinct animation groups as well:
![image](https://user-images.githubusercontent.com/3952729/67045176-9daac380-f0e2-11e9-8dc9-cd8b47f6a68c.png)

But I can't quite tell the difference between the groups by looking at them. I modified the nodes to include in the animation group to separate parts of the model to show this more distinctly: 
![image](https://user-images.githubusercontent.com/3952729/67045369-01cd8780-f0e3-11e9-87f3-700682512370.png)

And the output scene looks proper as well:
![image](https://user-images.githubusercontent.com/3952729/67045418-1e69bf80-f0e3-11e9-8d98-5d99b31055c4.png)

Can you send an output glb of what you get when exporting the BeeModifiedAnimationGroups.max scene?
[Bee_Modified.zip](https://github.com/BabylonJS/Exporters/files/3741219/Bee_Modified.zip)

**Comment by AndresCH10** [comment]
Good one question:
Could you explain to me how you have selected the hierarchy of the bones in each group of animations?
I don't understand that step very well, and if you could explain it step by step, I would really appreciate it

**Comment by AndresCH10** [comment]
Hi, I could ask you a question:
Could you explain to me how you have selected the hierarchy of the bones in each group of animations?
I don't understand that step very well, and if you could explain it step by step, I would really appreciate it

**Comment by Drigax** [comment]
Sure, I agree that the current process is somewhat unintuitive.

Generally you want to:
1) Select the bones/objects that you want included in the animation group. Its important to decide for your usecase whether you want to include the full hierarchy of bones, or just a subset of your full bone hierarchy.
2) Create animation group in the "Animation Groups" popout window.
3) Click "Add Viewport Selection" to add the selected nodes to the animation node list.
4) Click "Confirm" to save changes to the animation group.

**Comment by AndresCH10** [comment]
OK, thank you very much, I will try to do everything you told me in 3D MAX, and in this way I can export my animations of the model.
