### ISSUE TITLE
CAT Bones IK 3DS Max 2019 to threeJS

### ISSUE THREAD

**Issue by kavikode** [BabylonJS/Exporters#664]
From 3DS Max 2019 I have been trying to use the CAT as bones and I'd like to include IK targets for the human character of the foot and hands for exporting in threeJS. When I use the .glb file in threeJS, I want to move the IK targets to dynamically reposition the arms and legs of the human character.

Can you please add me know how I can achieve this task?

**Comment by Drigax** [comment]
I don't have much experience with the CAT, but I'd assume that the exported glb should contain empty nodes for the IK handle. You should be able to animate your IK handles in your DCC, and the tracks should be included in your glb.

There aren't any extensions that I know of in gltf to specify the IK chains in a given scene, so you'd most likely need to configure this in three manually.

**Comment by kavikode** [comment]
Thank you so much @Drigax @PatrickRyanMS ! I really appreciate your feedback.  

How can I create a custom model with IK bones in 3DS Max? Please help.

I saw this example using the MMD model, link: https://rawgit.com/takahirox/three.js/GLTFMMD/examples/webgl_loader_gltf_miku_ik.html

The file format does not matter as long as I can create a custom character model with IK bones in 3DS Max. Will you please advise?

**Comment by Drigax** [comment]
Autodesk has some guidance on how to use IK constraints here:

https://knowledge.autodesk.com/support/3ds-max/learn-explore/caas/CloudHelp/cloudhelp/2017/ENU/3DSMax/files/GUID-AE4A0089-95F5-4199-A853-ABB8E0DB3439-htm.html

Also, you can try looking at some simple character rigging tutorials on Youtube as well:
This one assumes no prior experience and should give you a head start on rigging a bipedal character (similar to the Miku model):
https://www.youtube.com/watch?v=C6E5Hco3ICQ

**Comment by Drigax** [comment]
Closing this issue, since it's not really related to the exporters.

Try reaching out to http://www.maxforums.org/ or another 3ds Max artist or general character rigging/animation community, they may be able to help you as well and point you to some best practices in this regard.

Best of luck  :)

**Comment by kavikode** [comment]
I am able to have the IK chains working in 3DS Max 2019 using bones. I'd like to include IK targets for the human character of the foot for exporting and it does not work. When I use the .glb file, I want to move the IK controls to dynamically reposition the arms and legs of the human character in the browser should.

The exporter should include the IK target goals. The exporter should include this feature in the future.   Can you please add me know how I can achieve this task now?

**Comment by PatrickRyanMS** [comment]
@kavikode the issue we have with exporting IK targets is that the glTF spec does not support IK at all. That means there's no way for us to logically write the IK targets into the file because we can't just make assumptions that the user wants to bring along extra nodes. There are two solutions here. The first if for you to create a glTF extension that supports IK and thus has a spec for writing out IK targets and how to handle IK. That option would be a large undertaking. 

The second option would be to add a 3ds Max dummy which is constrained to the IK target. The glTF spec has a notion of an empty transform being saved as a node, so it will get written into your glTF as a node. However, once you load your glTF, there will be no connection from the dummy node to your skeleton and you will need to create that connection and how the bones are constrained to it yourself. Hope this helps.

**Comment by kavikode** [comment]
@PatrickRyanMS I love the 2nd option! Thank you so much! Is there a simple way to create that connection to the IK node and how the bones are constrained to the IK node?

**Comment by PatrickRyanMS** [comment]
@kavikode I would use position constraint: 

[3ds Max Animation Constraints docs](https://knowledge.autodesk.com/support/3ds-max/learn-explore/caas/CloudHelp/cloudhelp/2016/ENU/3DSMax/files/GUID-10AC3D82-523D-4670-8240-D6E3AC79F0BF-htm.html)

**Comment by kavikode** [comment]
@PatrickRyanMS Can a position constraint be exported ?

**Comment by kavikode** [comment]
perhaps the better question is… How can we export animation constraints from 3DS Max to dynamically move them in threeJS so the rest of the bones move with respect to it? What is the workflow? 

Thank you in advance!

**Comment by PatrickRyanMS** [comment]
@kavikode there is no method for writing the constraints into the glTF format. The only thing you will be able to do is export the dummy so you have a node in the glTF so you have a representation of your target with your animation baked to it. You will then need to hook up the IK in three.js. Unfortunately, I won't be able to help you with that part as I don't know anything about three.js. I work on the Babylon.js team. This part of your question is probably better asked on the three.js forum.
