### ISSUE TITLE
3dsMax 2018 & 2020 - Animation Group menu options unreachable

### ISSUE THREAD

**Issue by arccentric** [BabylonJS/Exporters#666]
I'm unable to access some of the options that should be available from the middle menu of the Animation Groups menu (labeled Animation). The menu is too narrow, and unlike the first menu that has a draggable size adjuster, I'm unable to do the same with the middle menu. Here's a screenshot:

![babylon_3dsmax_error](https://user-images.githubusercontent.com/13156144/67901321-8f25c880-fb34-11e9-9592-6857265546dc.jpg)

After seeing [this issue](https://github.com/BabylonJS/Exporters/issues/558) I thought it might be a scaling issue, so I tried changing my resolution / scaling settings, but that didn't work.

Here are some troubleshooting steps I've taken, to no success:

- decrease screen resolution
- decrease / increase scaling in tandem with resolution changes
- change 3dsmax preferences to use smaller icons
- decrease / increase size of the Animation Group window

Any time I adjusted the resolution / scaling, all of the elements within the window scaled proportionally. It seems like this issue could be solved by giving that middle menu a draggable width adjuster similar to the first menu, but hopefully there might be a more immediate solution?

System information:

Microsoft Surface Book 2 (with dGPU)
Windows 10 (x64)
Display Resolution: 3240x2160
Scaling: 200% (recommended)

Max versions tested: 2018, 2020

**Comment by Drigax** [comment]
Hey @arccentric, thanks for reporting this. I'm not very talented with winforms, so I'm not sure what the best way to design this form to work well with higher UI scaling, but I noticed that the splitter control between the center and right panel was disabled:

![image](https://user-images.githubusercontent.com/3952729/67905482-b5486a00-fb2e-11e9-8963-62bcfeb4cdda.png)

To quickly unblock you, I can reenable this control so that you can readjust the panes to fit for your resolution and scale.

**Comment by arccentric** [comment]
That seems like a good solution. Do you need anything in particular from me, or are you able to easily compile a new build?

**Comment by Drigax** [comment]
Should be all set on my end, fix is checked in and should be deployed for our installer soon. The release should be published in the next 10 mins.

**Comment by Drigax** [comment]
Release is available here or through version 1.2.1+ of the installer (also available through the link):
https://github.com/BabylonJS/Exporters/releases/tag/Release20191030.2

**Comment by Drigax** [comment]
Also, if you're interested in improving the UI responsiveness, I'm always welcoming of PRs 😀

**Comment by arccentric** [comment]
Thanks for the quick turnaround on this @Drigax! 

Do you have a roadmap or notes on any particular UI changes you're hoping to make?

**Comment by Drigax** [comment]
Long term, we want to share the UI forms between our Max and Maya exporters.

But some small enhancements that are pretty straightforward like to do now
is properly anchor and constrain the elements in each UI form so they scale
properly when the window is resized. The animation group and main form are
probably the worst offenders.

**Comment by arccentric** [comment]
I'm not very familiar with C#, but when I have some free time I can take a look and see if that's something manageable for me to contribute!
