### ISSUE TITLE
Max2Babylon ZIP file confusion

### ISSUE THREAD

**Issue by echadwick-wayfair** [BabylonJS/Exporters#669]
I used to get the latest Max2Babylon exporter by going directly here and downloading the ZIP:
https://github.com/BabylonJS/Exporters/tree/master/3ds%20Max

(https://github.com/BabylonJS/Exporters/blob/master/3ds%20Max/Max2Babylon-1.4.2.zip)

But now there are more recent builds here:
https://github.com/BabylonJS/Exporters/releases

Should Max2Babylon-1.4.2.zip be removed to prevent confusion?

**Comment by Drigax** [comment]
Yes, it should be removed, I agree. Since we moved to an installer model
this definitely redundant and outdated.

**Comment by Drigax** [comment]
We also updated our docs to point users to the new installation path, so I don't see why we should continue to maintain an in-repo committed exporter build.
