### ISSUE TITLE
Add support for Maya 2020 Standard shader

### ISSUE THREAD

**Issue by Drigax** [BabylonJS/Exporters#676]
The Standard Shader model is changing in Maya 2020, we should figure out what is changing, see what our current exporter does not support, and officially support this.

**Comment by Drigax** [comment]
I'm currently still in the process of setting up my Maya 2020 Beta license, I should be able to look into this in about a week.

**Comment by Drigax** [comment]
I have a beta license, but I'm currently in the process of open sourcing a transcoder project that we use internally. Most likely I won't be able to start on this until January at the earliest. If anyone wants to take on this project, feel free, I'd be more than happy to help.

**Comment by Mudoglu** [comment]
If you need any Maya files showing the new shader in action please contact me.

**Comment by Drigax** [comment]
@Mudoglu, sure! any little bit helps. Feel free to attach them to this issue

**Comment by Mudoglu** [comment]
@Drigax 
Here is the scene.  Have fun!
https://gumroad.com/oglu#YLnnr

**Comment by Drigax** [comment]
Thanks so much! The plan is currently to address this as soon as we can verify #718 is fixed and working

**Comment by Mudoglu** [comment]
@Drigax 
Thanks that sounds great to me. If the export is working with the new Shader i will upload a new version to my Gumroad for everyone to play with.

**Comment by thomlucc** [comment]
Not an issue (backward compat)
