### ISSUE TITLE
Allow easy definition of custom material exporters for project forks.

### ISSUE THREAD

**Issue by Selmar** [BabylonJS/Exporters#68]
For our project, we require a custom material exporter. At this point, the material is not ready for public usage, nor may it even be proper to add it to babylon. Thus, we would like a way to add a custom material exporter to the project, preferably with minimal merging effort.

I envision it'd work somewhat like this: you create a new class that has an interface (e.g. `IMaterialExporter) that allows the exporter to get the material class ID associated with it and provides a function to export from a material handle. The exporter will find and create these material exporters using reflection.

I believe this material exportation should somehow allow for custom parameters that can be added to the glTF file format (like "extras" or material extensions).

Another difficulty is that when you add files to a project, the solution file is changed (and thus merging is still slightly annoying). Perhaps a good idea is to create a separate project for.. well.. extensions to the plugin?

Any thoughts are welcome.

**Comment by Selmar** [comment]
I have created a draft [here](https://github.com/Selmar/Exporters/commit/caaea953438a7a771a3787fef89001596c031446).

**Comment by deltakosh** [comment]
Looks really good to me!

**Comment by Selmar** [comment]
I will continue with this, then. I had some problems with the draft as-is, I will update it next week.

There are some additional problems I face right now when building an actual material exporter, which will require some changes to the exporter code. Most of these are related to the fact a lot of functionality is not available outside the BabylonExporter class, like logging and texture building.

I have one question: at this point, it is not so easy to export a glTF material with this, as the MaxMaterial information is not available once we get to the gltf exporter. The intermediate materials are (currently) not suitable to store this data, as we have more data than is defined in the existing babylon materials. We have also planned a glTF material extension.
However, the 3dsMax material information is not available when we get to the glTF exporter. Do you have any ideas on how to refactor this, if you even want that? If not, I'll figure something out for our purposes eventually.

**Comment by Selmar** [comment]
I've implemented this for the glTF exporter pipeline and am successfully using it. There is no doubt it is incomplete, but it is functional.

The babylon version is still a draft and I won't have time to develop that part.

Do you want me to submit a pull request, or keep it where it is for now?

**Comment by deltakosh** [comment]
If it is incomplete I would prefer not merging it because we will need to maintain it

**Comment by Selmar** [comment]
Right, that makes sense.

From what I can tell, the only missing feature at this point is being able to combine different textures into the correct layouts (e.g. putting metal and roughness together in one texture, might the material have them separate). I'm not sure if I will need it.

**Comment by deltakosh** [comment]
Closing for now
