### ISSUE TITLE
[3ds Max] If texture folder set to same as glTF location, image uri is incorrect

### ISSUE THREAD

**Issue by PatrickRyanMS** [BabylonJS/Exporters#685]
If you set the texture folder to the same location as your glTF file, the uri that is encoded looks like:

..%5C FolderName %2F imageName.ext

The %5C is breaking the loading of the glTF. There could be a use case to store glTF files and images in sibling folders, so we need to figure out how to path between them correctly. 

To start, we should determine if the path to the glTF and the path to the images folders as set in the exporter are the same and if so, just use the file name as the uri rather than going up one folder and then back down. 

It would also be an improvement to the UX if we either spell out in the export window that the texture folder is optional or we add a checkbox to enable the image folder field. Right now, users can interpret the UI as the texture folder is required.

**Comment by Drigax** [comment]
Hey @elpie89 , I remember you added support for exporting to a separate texture folder, can you help explain the use-case for this?

**Comment by elpie89** [comment]
I'll take a look at this asap

**Comment by Drigax** [comment]
Much appreciated.
