### ISSUE TITLE
Maya - Scale factor not being applied

### ISSUE THREAD

**Issue by aguaviva** [BabylonJS/Exporters#687]
There seems to be a bug when exporting the gltf model with scale factor.The scale factor is not being applied to the model in the gltf export from **Maya**. Even when changing the scale factor it does not seem to add the scaling root in the exported gltf.

This issue was solved for **Max** but we desperately need it for **Maya**.

**Comment by Drigax** [comment]
Sure, I'm sure the fix is similar, as the exporters have a similar architecture. Let me take a quick look...

**Comment by Drigax** [comment]
Unfortunately everything looks functional as far as I can tell.

I'm testing this on Maya 2019, using Maya2Babylon v20191118.2.

![image](https://user-images.githubusercontent.com/3952729/69394139-fa743d80-0c8f-11ea-8499-77626f552f11.png)

Using a scale factor of 3.141593, It appears that the exported glTF has a proper scaling root node added to the scene:
![image](https://user-images.githubusercontent.com/3952729/69394181-21cb0a80-0c90-11ea-894c-085f41c3d45e.png)

Can you confirm your version of Maya and the version of Maya2Babylon that you're using? The more info the better, as it will help me best understand what may be happening here 😊

**Comment by serendipidipity** [comment]
We're still having problems on 20191118.2. I dont see the scaling applied.
We solved this by manually adding scaling nodes to the scene, but it wont scale the light matrices correctly then.

![grafik](https://user-images.githubusercontent.com/20571774/69414534-3d2b2980-0d13-11ea-98fe-d3c024ecbb9d.png)

**Comment by serendipidipity** [comment]
In this case, we need to scale the light matrices at runtime by a factor of 100 (1/0.01) for them to be correct.

**Comment by Drigax** [comment]
Strange...I'm looking into this now, but I can't quite figure out why this is happening:

We check this scale factor here, and this code seems pretty reliable:
https://github.com/BabylonJS/Exporters/blob/cb62e1a30443511db7a0f60982563d597eccab74/Maya/Exporter/BabylonExporter.cs#L321-L331


and testing with your scale factor of 0.01 appears to work well for me as well:
![image](https://user-images.githubusercontent.com/3952729/69467051-492ae180-0d3b-11ea-988a-5b6541b4af48.png)

**Comment by Drigax** [comment]
@aguaviva When you get the chance, can you test if https://github.com/BabylonJS/Exporters/releases/tag/Release20191123.1 changes the current output? It will print an error message if it detects an invalid scale factor, and will print the scale factor in the output message now.

It should be available to the installer when run.

**Comment by aguaviva** [comment]
Thanks for taking the time to look into this. the new build has the same behavior as the old one. it does not print an error message and it doesn't do any scaling.

Some more info, the reason behind this is that despite that we are using meters in Maya the exporter exports centimeters. So what we do is to scale all the scene in maya by 1/100 to get meters.

It turns out the lights' matrices scaling is still wrong, and in Cauldron we need to scale the light matrix by 100 in order to get things rendered properly (all works fine in Blender)

The scaling thing (in Maya and also in Cauldron) is just a workaround, the good fix would be to have the scene export in meters (or whatever is set in Maya) and not in centimeters.

**Comment by Drigax** [comment]
Can you share your scene? I'd like to take a closer look to see if we're hitting some edge case, as I'm not sure what may be causing you to skip our scene scaling.

I believe that we added unit scaling support via #481 in 3dsMax, but I don't think we ever added the same support in Maya. I'll create #694 to address this, but I don't expect to get to this myself immediately.

**Comment by aguaviva** [comment]
yeah, there is support for Max but not for Maya. I'll get you a scene so you can test it. Thanks so much!

**Comment by Drigax** [comment]
Hi @aguaviva were you able to create the test scene?

**Comment by noalak** [comment]
#748 fixes the initial issue. Adding manually scaling nodes is no longer necessary and light matrices should be unaffected. @aguaviva Can you confirm ?

The scale factor from the exporter form is working fine for me as well. Nothing changed on this side.

**Comment by aguaviva** [comment]
That is really nice! We haven't tested the exporter in a while, we got everything working a while back. Here is the proof: https://github.com/GPUOpen-Effects/TressFX and thanks for your help :) I am not sure I can get the artist to export things again as that was a one time job.
