### ISSUE TITLE
3dStudio Max 2020.2 Keep Crashing

### ISSUE THREAD

**Issue by ManuelGPz** [BabylonJS/Exporters#693]
I have tried to export several times from 3dsMax 2020.2 and the plugin crashes.
I have tried exporting simplex boxes with no material associated. 
Same process in 3dsMax 2019 Version works ok.
![SharedScreenshot](https://user-images.githubusercontent.com/58131591/69491540-b761d680-0eea-11ea-8e5f-70ad107836ed.jpg)

**Comment by Drigax** [comment]
Are you sure you have the 2020.2 update installed? When updated you should have a version number of 2020.2.0, rather than 2020.0.0 😊
![image](https://user-images.githubusercontent.com/3952729/69492036-a87b1580-0e51-11ea-8e80-f8a5f6dbce38.png)

**Comment by ManuelGPz** [comment]
Im sure.... I was totally wrong.... 
Apologies...

And thanks so much for such a fast answer and dot take it bad...
Thank yu :)

**Comment by Drigax** [comment]
No worries, I'm always happy to help 😁
