### ISSUE TITLE
Light orientation is exported incorrectly

### ISSUE THREAD

**Issue by Drigax** [BabylonJS/Exporters#696]
There seems to be some inconsistency between Babylon->glTF light orientation export.

as exposed in #689, a scene exported correctly to .Babylon:
![image](https://user-images.githubusercontent.com/3952729/69589421-e0dd3980-0fa0-11ea-8793-cf3d1946bae5.png)

will have its lights oriented incorrectly when exported to glTF:
![image](https://user-images.githubusercontent.com/3952729/69589464-023e2580-0fa1-11ea-91d6-112464b57f54.png)

Attached are Maya and 3dsMax source scenes, and resulting exports:
[LightOrientationExportIncorrect.zip](https://github.com/BabylonJS/Exporters/files/3889470/LightOrientationExportIncorrect.zip)

**Comment by noalak** [comment]
As you said in https://github.com/BabylonJS/Babylon.js/issues/7377, let's first fix light gizmos before going into this issue.

**Comment by Drigax** [comment]
On second thought, https://github.com/BabylonJS/Babylon.js/issues/7377 should not block this issue, just gizmo validation. Light orientation is still incorrect when a glTF scene is exported, and should be fixed.
