### ISSUE TITLE
Auto-Updating installer

### ISSUE THREAD

**Issue by Drigax** [BabylonJS/Exporters#698]
It would be nice to have a solution for our installer to auto-update as well, this would get us more aligned with modern software distribution solutions like VSCode, etc...where the user no longer has to manually download their software updates.

This will also help avoid situations where long-time users miss out on exporter updates due to being on an old installer version, or when bugs are discovered in the installer such as #683

**Comment by Drigax** [comment]
Honestly, given more thought this should be part of the exporters themselves. At the very least the exporter should be able to:
[ ] check github for more recent releases
[ ] prompt the user to update this tool.

**Comment by Jaskar** [comment]
Hi,
At first I thought about "Click Once Deployment", which is easy to use with Visual Studio.
BUT, it's not working when the app requires admin access.

**Comment by Jaskar** [comment]
Here it is !
https://github.com/BabylonJS/Exporters/pull/703
