### ISSUE TITLE
Convert any 3dsmax file's units to meters when exporting.

### ISSUE THREAD

**Issue by Selmar** [BabylonJS/Exporters#70]
Currently, if the system unit scale is set to 1 unit = 1 centimeter, the exporter exports the units as if they were meters regardless.

Correct behavior would be to convert all units to meters before exporting, as per spec:
> The units for all linear distances are meters.

**Comment by WVNicolayeff** [comment]
Hey there. I'd really love to see automatic unit conversion for GLTF as well. Some other people on my team have also been asking me about this as well. The type-in conversion box helps a lot, though it also resets every session.

As the other guy said, the GLTF 2.0 spec wants everything standardized in terms of meters. [Linked here](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#coordinate-system-and-units) for reference.

**Comment by TyLindberg** [comment]
Would also love to see this implemented in the Maya exporter to improve standardization across the board. Right now it's difficult to guarantee the export scale, since the certain artists may work in different scales in the editor.

**Comment by Drigax** [comment]
Thanks again to @elpie89 for adding the unit conversion support.
