### ISSUE TITLE
Max2Babylon: Convert old attributes to new attributes

### ISSUE THREAD

**Issue by echadwick-wayfair** [BabylonJS/Exporters#715]
Can we combine existing attributes into the new structure?

If I load a model that was exported with a previous version of the exporter, and has an older set of Custom Attributes, the material retains both sets. 

This creates conflicts. The exporter uses the older attributes if present instead of the newer ones. 

Is there a way to apply the older attributes into the new structure, instead of adding a second set?

![image](https://user-images.githubusercontent.com/40177036/70740440-2c088380-1ce7-11ea-8245-fa504aac7ebc.png)

It's using the older green Unlit flag, rather than the newer red Unlit flag.
![attributes-pre-existing_unlit](https://user-images.githubusercontent.com/40177036/70740492-480c2500-1ce7-11ea-9fa8-a773587ab9ca.jpg)

[multiple_attributes.zip](https://github.com/BabylonJS/Exporters/files/3957367/multiple_attributes.zip)

**Comment by Drigax** [comment]
Hmm, I remember discussing this usecase with @PatrickRyanMS when we were first hashing out the UX changes. 

Looking at the code, we would need to convert the old material attributes to the new ones. here's a mapping:

babylonAlphaTest -> babylonTransparencyMode (0 for opaque, 1 for AlphaTest, 2 for Blend)
babylonUnlit -> babylonUnlit (I'm not sure why the checkboxes don't share the same state, most likely we're touching on a 3dsMax edgecase here)
babylonAlphaTestPercent -> currently, nothing! (I'll have to update the implementation to add a float to contain the test cutoff percent as well)

**Comment by echadwick-wayfair** [comment]
Oooh, awesome! Thank you!

**Comment by deltakosh** [comment]
is it still a need? Or should we close it?

**Comment by echadwick-wayfair** [comment]
I think we can close this.

**Comment by deltakosh** [comment]
Thanks eric! I try to rationalize where we should invest
