### ISSUE TITLE
Max2Babylon: Save the export log?

### ISSUE THREAD

**Issue by echadwick-wayfair** [BabylonJS/Exporters#717]
Is there a way to save the contents of the log window after export? Would be helpful to have a "Copy to Clipboard" or somesuch.

**Comment by Drigax** [comment]
Sure, that should help when providing bug reports, and wasn't too difficult to address. I have a PR pending now, should be available shortly.

**Comment by echadwick-wayfair** [comment]
Thanks this is great! Can it be more verbose? In the log window, there's a ton of useful info inside the +'s. Seems like all this should be in the Clipboard export?

**Comment by Drigax** [comment]
Currently everything that is expanded in the log window will be copied to the clipboard. I was not sure If I wanted to use max verbosity by default

**Comment by echadwick-wayfair** [comment]
Oooh you're sneaky! Thanks.
