### ISSUE TITLE
Maya 2020 Support

### ISSUE THREAD

**Issue by BaldSavant** [BabylonJS/Exporters#718]
Hello!

My company is looking to upgrade to Maya 2020 to get some of those sweet new tools, but we've just tried to install the current babylon on it and it doesn't look to be supported yet. I see some threads for specific features for Maya 2020, but nothing about overall support.

If I'm missing something obvious, would you mind pointing me to where I need to go? And if I'm not missing anything, could you tell me when Maya 2020 support is expected?

Thanks!

**Comment by Drigax** [comment]
Thanks for reaching out! Currently we don't support Maya 2020. I'm working closely with @noalak 's team to handle some missing feature support, and I have yet to test the exporter plugin installation as well. 

I'll try to get this up ASAP, but I'll most likely not have this supported by the end of the year.

**Comment by BaldSavant** [comment]
Sure. End of year is no worry, but can I assume based on that response that you'll have support some time fairly early in the new year? As opposed to, say, April and beyond?

**Comment by Drigax** [comment]
Yes, that's definitely the plan. Provided that we don't run into any issues with Maya, we're currently slating this to be done by February

**Comment by BaldSavant** [comment]
Perfect. Thanks for the quick response!

**Comment by Drigax** [comment]
Going to reopen this issue to track progress with Maya 2020 support :)

I expect that we can break this down into 4 subtasks:
- [ ] Create Maya2Babylon project targeting the 2020 SDK
- [ ] Validate proper plug-in functionality
- [ ] Update Installer client for Maya 2020
- [ ] Update Azure CI pipeline to build package and publish the Maya2Babylon 2020 project.

**Comment by Drigax** [comment]
I believe I was able to address task 1 via #729 , however upon loading the plugin into Maya2020, it fails with the following error log:

```
waitCursor -state on;										 $gIgnoreUpdateCallback = true;loadPluginCmd( "C:/Program Files/Autodesk/Maya2020/bin/plug-ins/Maya2Babylon.nll.dll"); 		   updatePluginUI( "92" );waitCursor -state off;									   $gIgnoreUpdateCallback = false;
menu - parent MayaWindow - label "Babylon";
// Result: MayaWindow|menu36 // 
menuItem - label "Babylon File Exporter..." - command "toBabylon";
// Result: MayaWindow|menu36|menuItem940 // 
menuItem - label "Animation groups" - command "AnimationGroups";
// Result: MayaWindow|menu36|menuItem941 // 
// Babylon plug-in initialized // 
menu - parent MayaWindow - label "Babylon";
// Result: MayaWindow|menu37 // 
menuItem - label "Babylon File Exporter..." - command "toBabylon";
// Result: MayaWindow|menu37|menuItem942 // 
menuItem - label "Animation groups" - command "AnimationGroups";
// Result: MayaWindow|menu37|menuItem943 // 
// Babylon plug-in initialized // 
// Error: file: C:/Program Files/Autodesk/Maya2020/scripts/others/pluginWin.mel line 317: Invoking ExecuteInDefaultAppDomain() failed. // 
// Error: file: C:/Program Files/Autodesk/Maya2020/scripts/others/pluginWin.mel line 317:  (Maya2Babylon.nll) // 
updatePluginCallback();
// Result: 0 // 
toBabylon;
// Error: line 1: Cannot find procedure "toBabylon". // 
```

I suspect that this is an error in the Maya plugin loader, as the sample plugins provided with the Maya SDK fail similarily, I've reached out to Autodesk concerning this, but we may be delayed in supporting 2020 until the next update if we're running into a bug here.

**Comment by Drigax** [comment]
I received word from autodesk that we are currently affected by issue:
`MAYA-102551 “.NET API plugin examples won't load”`

Luckily, this is a known "showstopper" urgent issue on their end, and Autodesk is working to provide an update to address this. Unfortunately I do not have an ETA for resolution right now, but I'll extrapolate that this should be addressed by Q2 (around spring 2020) going off their usual update cadence.

**Comment by Drigax** [comment]
As an update, we can expect Maya to be patched by early March at the latest.

**Comment by kerihobo** [comment]
Any update on this one?  The institute where I teach adopted Maya 2020 unusually fast.

**Comment by Drigax** [comment]
No update. I'll try to get to this in the next few weeks, else feel free to
work off of my open PR.

**Comment by Drigax** [comment]
Autodesk has released Maya 2020.1 update as of 3/17. I can continue with this as soon as I can get access to the update binaries. Tenatively removing the blocked tag.

I'm personally still occupied with other work, but I plan to be able to focus on this 100% by the beginning of April.

**Comment by Drigax** [comment]
If anyone is desperate for a 2020 version of this , feel free to look at previous pull requests for 2019 and 2018 for an example. I'm currently prioritizing incoming bugs and some exploratory work regarding texture compression methods, but I'll try to get to this before June.

**Comment by shibberd** [comment]
AR is kicking off big time and would love to not go back to Maya 2019.
I look forward to the release soon.
Thanks for your efforts it's really appreciated.

**Comment by Tangerine-Chang** [comment]
Hi~I just download the version of Maya 2020 and also add Babylon data to Maya. I also meet the same error 317. Does it have any update or solution on this? 
It will be a grateful for your help.

**Comment by Drigax** [comment]
Hi @Tangerine-Chang Maya 2020 is not supported right now. I plan to start on porting the exporter over, but currently installing the 2019 version will not work

**Comment by Tangerine-Chang** [comment]
thank you!! I look forward to the new release version.

**Comment by Drigax** [comment]
2020 support is in :)

**Comment by Tangerine-Chang** [comment]
![image](https://user-images.githubusercontent.com/66812304/84969733-db695b80-b14b-11ea-9c8d-04f9b820ff15.png)

Sorry , when I set up the latest version but it can't work, please refer to the attached image. 
Appreciate

**Comment by Drigax** [comment]
Thanks, this is a known issue with the Maya 2020 release:
https://help.autodesk.com/view/MAYAUL/2020/ENU/?guid=Maya_ReleaseNotes_2020_1_release_notes_htm

See: `.NET API plugin examples do not load MAYA-103283`

This has been fixed in Maya update 2020.1
 and appears to work.

**Comment by Tangerine-Chang** [comment]
You mean I need to update the version Maya 2020.1 and the procedure will be work, right?

**Comment by Drigax** [comment]
Yes. I'll add a note to the installer to make that more clear
