### ISSUE TITLE
Maya Exporter v20191220.1 "gltf-pipeline" module not found

### ISSUE THREAD

**Issue by vanlicht** [BabylonJS/Exporters#724]
Hi,
I am testing the draco compression to gltf as output format in Maya. The exporter message: 
"GLTFExporter | Draco compression" -> " gltf-pipeline module not found."
 
I tested in 3ds Max and the draco works in the exporter. Wonder if I miss anything?

Thanks,
Thomas

**Comment by Drigax** [comment]
Hmm, I'm not sure. I'll see if there's anything wrong with the Maya exporter. Personally I've never tested the draco compression feature, but now's as good a time as any to make sure this is working :)

**Comment by Drigax** [comment]
For lack of a better way to put it, the logic that we used to invoke the draco compression pipeline tool was really bad. I was able to refactor it to be more consistent, the only requirement is that gltf-pipeline  (like other npm packages) can be found via your system PATH variable. if properly installed, this should work much better.

https://github.com/BabylonJS/Exporters/pull/726
