### ISSUE TITLE
Max2Babylon: rotated AO causes index failure

### ISSUE THREAD

**Issue by echadwick-wayfair** [BabylonJS/Exporters#735]
When I use Export & Run on this file, the output GLB has an UNRESOLVED_REFERENCE issue, which prevents it from loading in the Sandbox 
`/materials/1/occlusionTexture/index: Failed to find index (1)`

I'm using the same 512x4 PNG texture for both Albedo and Occlusion, except I'm using KHR_texture_transform to rotate the Occlusion 90 degrees.

It works fine if I reset the rotation to zero.

3ds Max 2020.3
Max2Babylon v20191220.1

The material setup. Red box causes the error. Green box exports and runs fine.
![2020-01-17 10_53_35-](https://user-images.githubusercontent.com/40177036/72628267-f6753c80-391b-11ea-9bb0-67ba1b6a9ff3.jpg)

Zip contains Max file, texture, and two GLBs ("Rotated" is the erroreous one).
[AQ_rotated_3dsmax.zip](https://github.com/BabylonJS/Exporters/files/4077696/AQ_rotated_3dsmax.zip)

glTF Validator:
`
{
    "uri": "ball_grid_occlusion_albedo_Rotated.glb",
    "mimeType": "model/gltf-binary",
    "validatorVersion": "2.0.0-dev.3.1",
    "validatedAt": "2020-01-17T15:57:23.642Z",
    "issues": {
        "numErrors": 1,
        "numWarnings": 0,
        "numInfos": 0,
        "numHints": 0,
        "messages": [
            {
                "code": "UNRESOLVED_REFERENCE",
                "message": "Unresolved reference: 1.",
                "severity": 0,
                "pointer": "/materials/1/occlusionTexture/index"
            }
        ],
        "truncated": false
    },
    "info": {
        "version": "2.0",
        "generator": "babylon.js glTF exporter for 3dsmax 2020 v20191220.1",
        "extensionsUsed": [
            "KHR_texture_transform"
        ],
        "extensionsRequired": [
            "KHR_texture_transform"
        ],
        "resources": [
            {
                "pointer": "/buffers/0",
                "mimeType": "application/gltf-buffer",
                "storage": "glb",
                "byteLength": 967580
            },
            {
                "pointer": "/images/0",
                "mimeType": "image/png",
                "storage": "buffer-view",
                "image": {
                    "width": 512,
                    "height": 4,
                    "format": "luminance",
                    "primaries": "srgb",
                    "transfer": "srgb",
                    "bits": 8
                }
            }
        ],
        "animationCount": 0,
        "materialCount": 2,
        "hasMorphTargets": false,
        "hasSkins": false,
        "hasTextures": true,
        "hasDefaultScene": true,
        "drawCallCount": 4,
        "totalVertexCount": 23099,
        "totalTriangleCount": 37557,
        "maxUVs": 1,
        "maxInfluences": 0,
        "maxAttributes": 3
    }
}
`

**Comment by echadwick-wayfair** [comment]
Interestingly, I am able to switch the bitmap from occlusion to metalness, or to roughness, both of which export & load correctly.

**Comment by echadwick-wayfair** [comment]
Rotating the emissive also causes it.

**Comment by Drigax** [comment]
Ok, I think I have a proper fix, we missed updating a reference when exporting an texture that's referenced multiple times in the scene, but with different properties, such as rotation.

**Comment by echadwick-wayfair** [comment]
I imagine if it was me working on it, I'd want to know. Sorry to keep reporting all these little issues. Probably edge cases. But probably valuable nonetheless. I really appreciate all the effort you put into this!

**Comment by Drigax** [comment]
No worries, every bug helps us make this as reliable as possible 😁
