### ISSUE TITLE
MAYA KHR_texture_transform turns texture upside down

### ISSUE THREAD

**Issue by vanlicht** [BabylonJS/Exporters#738]
Hi,

I noticed that when I turned on the toggle of "KHR_Texture_Transform" in the Maya Babylon Exporter for glTF, the texture flipped upside-down. As you can see the "color map" with letters "A" is reversed, and so are the letters embedded in the "AO" texture.
[uvtest.zip](https://github.com/BabylonJS/Exporters/files/4088075/uvtest.zip)

Kindly advice. Thanks.
Thomas
[Maya_UVTranform.zip](https://github.com/BabylonJS/Exporters/files/4092939/Maya_UVTranform.zip)

**Comment by Drigax** [comment]
Hi,
Can you share your Maya scene as well?

**Comment by vanlicht** [comment]
Hi Drigax, sure. I updated the previous post with Maya file attached.
Thanks,
Thomas

**Comment by Drigax** [comment]
Thank you,
Looks like our exporter is inverting the KHR_texture_transform scaling:
![image](https://user-images.githubusercontent.com/3952729/72947560-3b8fd900-3d37-11ea-9ea1-82f4264e3470.png)

**Comment by Drigax** [comment]
Yeah this is bad, not sure why this is explicitly inverted:
https://github.com/BabylonJS/Exporters/blob/73e8b6d1014c6102b67df3c13f737c52a27797e5/SharedProjects/Babylon2GLTF/GLTFExporter.Texture.cs#L441-L447

**Comment by Drigax** [comment]
Thanks, I think we're finally consistent between .babylon and glTF texture orientation export for both exporters!
