### ISSUE TITLE
Texture exported with incorrect name in glTF

### ISSUE THREAD

**Issue by noalak** [BabylonJS/Exporters#739]
Bug repro: 3ds Max file in New.zip from https://github.com/BabylonJS/Exporters/issues/700
Expected result: The textures are exported and linked to Texture object in glTF using their name.
Current result: The name in Texture object does not match texture's name. The import of the scene into the sandbox is failing due to missing texture file "panel_baseColor.jpg". Image in output folder is named "dashboard.jpg".

**Comment by Drigax** [comment]
Closing via #740
