### ISSUE TITLE
[Max][glTF] The exporter seems to ignore opacity values

### ISSUE THREAD

**Issue by EtagiBI** [BabylonJS/Exporters#744]
Hello,

It seems that after [eyeball correction fix](https://github.com/BabylonJS/Exporters/issues/700) something went wrong with opacity values. Opacity is always 1 for all materials now.

Material properties in 3DS Max:
![image](https://user-images.githubusercontent.com/20855725/73422620-5ff94000-434b-11ea-9e57-35cda4628825.png)

Material properties in Babylon Sandbox (exported as gltf):
![image](https://user-images.githubusercontent.com/20855725/73422978-89ff3200-434c-11ea-893f-b01cd8b305cc.png)

Model sample:
[New.zip](https://github.com/BabylonJS/Exporters/files/3900148/New.zip)

**Comment by Drigax** [comment]
With all due respect, this doesn't seem related to the diffuse change. Are you sure this has only just occured?

**Comment by EtagiBI** [comment]
> With all due respect, this doesn't seem related to the diffuse change. Are you sure this has only just occured?

Perhaps I missed some intermediate updates of the exporter, but as of November 28 it definetely worked fine in terms of opacity values. That's why the first sentence in this thread starts with "It seems..." =).

**Comment by Drigax** [comment]
No worries, just wanted to make sure that we didn't fat finger a simple fix, I'll try to take a look at this as soon as I get the time. There was a couple of other exporter issues I plan to get to first thing next week.

**Comment by Drigax** [comment]
Ah, Looks like the scene has the babylon material attribute set to Opaque:
![image](https://user-images.githubusercontent.com/3952729/74578067-5674f800-4f47-11ea-8d48-f652a92b5fdd.png)

if we set the wire_153228214 and Material__6156 materials to use Transparency Mode: Blend, the opacity values appear respected. I believe that @PatrickRyanMS and I decided to have the babylon export setting override the in-application opacity setting. See:

![image](https://user-images.githubusercontent.com/3952729/74579478-b40d4280-4f4f-11ea-9572-def5166e197d.png)

**Comment by EtagiBI** [comment]
@Drigax , does it mean that for every transparent material of every scene I should manually change Transparency mode?

**Comment by Drigax** [comment]
Yes, all non-opaque materials should have their alpha mode manually set.
