### ISSUE TITLE
Babylon for 3ds Max 2018 not showing up in menu (Max2Babylon-0.36.0)

### ISSUE THREAD

**Issue by gentlemanjohn** [BabylonJS/Exporters#75]
I'm following the instructions here: [https://doc.babylonjs.com/resources/3dsmax](https://doc.babylonjs.com/resources/3dsmax)

Using the latest 0.36.0 zip:
I unblocked all the 2018 dll files and copied over to 3ds Max 2018/bin/assemblies/

Restarted 3ds Max and still no Babylon menu item.

**Comment by davilovick** [comment]
The same problem here.

I found a workarround. If you delete the <AppData folder>\Local\Autodesk\3dsMax (or rename if you want a backup) when you launch 3dsMax, the Babylon menu appears

This remove all your 3ds max preferences, so be careful :)
Best regards

**Comment by deltakosh** [comment]
Yes this is a known bug with autodesk 
We can't do anything on our side unfortunately

**Comment by deltakosh** [comment]
Pinging @noalak to add this information on the doc
