### ISSUE TITLE
Headless Maya Execution (kFailure): Unexpected Internal Failure

### ISSUE THREAD

**Issue by Ziethriel** [BabylonJS/Exporters#758]
**_Issue_**

When running file export from Headless MAYA
`Error: Export cancelled: (kFailure): Unexpected Internal Failure`

**_Background_**

I'm creating a batch exporter that will convert files into a variety of formats.
The exporter works in the script editor but fails to run from a python script.
I've created a simple Example Problem to demonstrate the issue.

**_Example Problem_**

```
#Example Problem

import os
import maya.standalone
import maya.mel as mel
import maya.cmds as mc

maya.standalone.initialize(); # Start Headless Maya
import pymel.core as pm; # Import Plugins

#Copy Pasting This Line Down Into The Maya Script Editor (Python) Works
mel.eval('file -f -new')
mel.eval('file -import -type "FBX"  -ignoreVersion -ra true -mergeNamespacesOnClash true -namespace ":"  -pr  -importTimeRange "combine" "C:/Users/measter/Desktop/TestObject.fbx";')

mel.eval("string $parameters[] = `GenerateExportersParameter`;")
mel.eval('$parameters[0] = "C:/Users/measter/Desktop/TestExports/BABYLON/testObject";')
mel.eval('$parameters[1] = "babylon";')
mel.eval('$parameters[2] = "";')
mel.eval('$parameters[3] = "1";')
mel.eval('$parameters[4] = "True";')
mel.eval('$parameters[5] = "True";')
mel.eval('$parameters[6] = "False";')
mel.eval('$parameters[7] = "True";')
mel.eval('$parameters[8] = "False";')
mel.eval('$parameters[9] = "False";')
mel.eval('$parameters[10] = "True";')
mel.eval('$parameters[11] = "True";')
mel.eval('$parameters[12] = "False";')
mel.eval('$parameters[13] = "False";')
mel.eval('$parameters[14] = "False";')
mel.eval('$parameters[15] = "True";')
mel.eval('$parameters[16] = "True";')
mel.eval('$parameters[17] = "True";')
mel.eval('$parameters[18] = "True";')
mel.eval('$parameters[19] = "100";')
mel.eval('$parameters[20] = "True";')
mel.eval('$parameters[21] = "False";')
mel.eval('$parameters[22] = "False";')
mel.eval('$parameters[23] = "False";')
mel.eval('$parameters[24] = "False";')
mel.eval('$parameters[25] = "False";')
mel.eval('$parameters[26] = "False";')
mel.eval('$parameters[27] = "False";')
mel.eval('$parameters[28] = "";')
mel.eval('ScriptToBabylon -exportParameters $parameters;')
```

**_Test Components_**
[TestObject.zip](https://github.com/BabylonJS/Exporters/files/4188892/TestObject.zip)
[ExampleProblem.zip](https://github.com/BabylonJS/Exporters/files/4188900/ExampleProblem.zip)

**_Running the Test_**

_Both Methods_
1. Copy TestObject.fbx to your computer
2. Line 13 of Example Problem, change the path to where you placed TestObject.fbx
3. Line 15 of Example Problem, change the path to any empty directory
*Note because this Is Python and `\` is an escape character I need to use `/` paths*

_Headless Mode_

1. Copy Example Problem to path/to/maya2019/install/bin
2. `cd path/to/maya2019/install/bin`
3. `mayapy ExampleProblem`

_This results in the error you can see in the command prompt_

![Command Prompt Result](https://user-images.githubusercontent.com/30094778/74287777-9d60b480-4cdf-11ea-9903-e3ec4a24977a.jpg)

_Maya Script Editor_
1. Open Maya
2. Load Babylon Plugin
3. Open Script Editor
4. Create New Python Script Tab
5. Paste Example Problem from line 11 down
6. Execute Script

_This is successful_

![Script Editor Result](https://user-images.githubusercontent.com/30094778/74287787-a2bdff00-4cdf-11ea-8c0b-93c6a2792116.jpg)

My Test Environment Details:
Windows 10
Maya 2019
Plugin Version "Release20200206.11"

**Comment by Drigax** [comment]
Sorry, I have no idea what's causing this. Since the in-application python interpreter appears to work, and it seems that I can attach to the headless Maya session via attaching to the mayapy.exe process.

We appear to fail when invoking python scripts via the MGlobal module, which we do throughout the codebase to control Maya and perform certain actions:
![image](https://user-images.githubusercontent.com/3952729/74292220-55945a00-4cec-11ea-9ef0-5224a2aadac5.png)

Perhaps this is a bug in OpenMaya or Mayapy (Why do they need their own python exe)? Unfortunately I don't think that this is addressable on our end.

**Comment by Ziethriel** [comment]
Upon further investigation I've noticed that running this in the Maya Python Interpreter (Script Editor) with the new file mel and fbx import mel, the script editor lags and doesn't continue unless the user clicks between the result and script menu.

Any idea what might cause this? I assume this delay mechanism is responsible for my error.

**Comment by Drigax** [comment]
Just tested the python script in the application editor, but everything appears to operate fine. I'm not sure what may be causing the headless instance to fail, but unfortunately I can't say that this is a usecase that we plan to officially support.
