### ISSUE TITLE
NullReferenceException Babylon2GLTF when exporting FurMaterial

### ISSUE THREAD

**Issue by seth-cohen** [BabylonJS/Exporters#766]
Support for the "hair and fur" world modifier was added as a result of #51 to the Max2Babylon exporter. However, functionality was never extended to GLTFExporter. 

In fact when trying to export from 3dsMax 2020 using the exporter to gltf or glb format, a NullReferenceException is thrown when we get [here](https://github.com/BabylonJS/Exporters/blob/master/3ds%20Max/Max2Babylon/Exporter/MaxGLTFMaterialExporter.cs#L43.)

The BabylonFurMaterial, when exported [here](https://github.com/BabylonJS/Exporters/blob/330e43fb83c7edad726c577b4b1963dab3df5738/3ds%20Max/Max2Babylon/Exporter/BabylonExporter.WorldModifiers.cs#L70) never gets a `maxGameMaterial` property populated (for good reason I am sure).

I'm trying to work on a solution and so I've added a check there, and begun to add support to converting BabylonFurMaterial to GLTF. Yet, adding that check has us fall through to [this](https://github.com/BabylonJS/Exporters/blob/5db7bbdb24095f5f9deb421900ebeb8e071989a0/SharedProjects/Babylon2GLTF/GLTFExporter.Material.cs#L380) `else`

I'm trying to add support for `BabylonFurMaterial` there in the same manner as support for `BabylonStandardMaterial` and `BabylonPBRMetallicRoughnessMaterial` above. Unfortunately, I am at a loss as to how to represent the `BabylonFurMaterial` as a GLTFMaterial. I've taken a look at the [loader](https://github.com/BabylonJS/Babylon.js/blob/master/loaders/src/glTF/2.0/glTFLoader.ts) and don't see the loader supporting FurMaterial either. 

Can anyone lead me along further? I'm stuck and honestly don't have too much experience with Babylon and I am having trouble locating how/if GLTF supports Fur/Hair.

**Comment by Drigax** [comment]
I think you've stumbled onto the root issue here. I agree, I don't think glTF formally supports fur type materials, I don't really see any proposed extensions either, maybe there is an opportunity here.

Personally, I'm not too familiar with the babylon fur material or other representations of fur and hair type materials aside from cards with transparency and normals, which _should_ export using the normal methods.

**Comment by Drigax** [comment]
We should fix this null reference. I'd expect anything that doesn't export properly, to export as some placeholder, or not export at all.

**Comment by seth-cohen** [comment]
Yeah, tried that and unfortunately you end up with an "/meshes/{mesh_index}/primitives/0/material: Failed to find index ({material_index})".

But that's just because the material isn't handled so the gltfMaterial [remains null](https://github.com/BabylonJS/Exporters/blob/5db7bbdb24095f5f9deb421900ebeb8e071989a0/SharedProjects/Babylon2GLTF/GLTFExporter.Material.cs#L20) and doesn't get added to the `MaterialsList`.  So, Added basic support:
```cs
else if (babylonMaterial.GetType() == typeof(BabylonFurMaterial))
{
    // TODO - Implement proper handling of BabylonFurMaterial once gLTF spec has support
    var babylonPBRFurMaterial = babylonMaterial as BabylonFurMaterial;

    gltfMaterial = new GLTFMaterial
    {
        name = name
    };
    gltfMaterial.id = babylonMaterial.id;
    gltfMaterial.index = gltf.MaterialsList.Count;
    gltf.MaterialsList.Add(gltfMaterial);

    //Custom user properties
    if (babylonPBRFurMaterial.metadata != null && babylonPBRFurMaterial.metadata.Count != 0)
    {
        gltfMaterial.extras = babylonPBRFurMaterial.metadata;
    }
}
```

Which works like a charm to, at least export a default material and this is probably OK. I can put up a PR if you think the above is OK.

Personally, I'd rather have it export the **Physical Material** I have mapped to the **Editable Poly** until fur is actually supported. I'd want to do that only for gLTF/glb only, for Babylon I'd rather use the fur Material. 

Though I'm pretty sure that we lose that other material mapping during export to babylon phase.  I'm now looking into a way to preserve that information during the original conversion even if we only use it if we export to one of those formats that are non-supporting (maybe utilizing the empty maxGameMaterial property or some type of secondary material mapping). I'm open if you have any ideas here.

>  I agree, I don't think glTF formally supports fur type materials

Glad you've said, that. I came across [this post elsewhere](https://www.html5gamedevs.com/topic/39028-gltf-exporter-fur-material-issue/) that to me implied that at **_some point_** it **_was_** handled in gLTF. So I dug deeper but found nothing more.

**Comment by Drigax** [comment]
Looking at:
https://www.html5gamedevs.com/topic/39028-gltf-exporter-fur-material-issue/?do=findComment&comment=223587

Seems to imply that the fur material itself was not necessarily serialized to glTF itself, but rather after importing the scene to banylon, they then added a fur material to the grass mesh in the scene manually.

>Yeah, tried that and unfortunately you end up with an "/meshes/{mesh_index}/primitives/0/material: Failed to find index ({material_index})".

Ah, it seems like we dont update the meshes that reference this material in the case of gltf conversion failure. That may bw worth looking into fixing as well, but its somewhat messy to fix, since we'd need to keep a node:material mapping in memory, or iterate over all nodes in the exported scene and remove their material...

**Comment by Drigax** [comment]
I like your proposed fix, mind opening a PR?

**Comment by seth-cohen** [comment]
I don't mind at all. I'm a little swamped at work so, right now I just have a hot fix I posted above setting a default material. But that is not my long term solution, that is just getting me from keeping the pipeline on working on now from crashing.

When I have a bit of time (maybe next week or this weekend) I'll look into getting a PR up.

Also, I noticed a colleague of mine had an open [issue...](https://github.com/BabylonJS/Exporters/issues/715) (a few actually 🤣).  I might take a stab at that as well if I get to it.

**Comment by Drigax** [comment]
Ever find some time? Else I can check this in ASAP :)

**Comment by seth-cohen** [comment]
OK put PR up as-is. Still hoping to be able to put in a proper patch to grab the underlying material from memory.

**Comment by Drigax** [comment]
Ok, I merged the current fix to resolve our nullreference breaking export. I'm going to close this bug and move conversation to.

https://github.com/BabylonJS/Exporters/issues/774

Thanks for your help!
