### ISSUE TITLE
Maya Texture Image Mimetype Not Set Properly for GLB

### ISSUE THREAD

**Issue by hujasonx** [BabylonJS/Exporters#772]
Hi all, unfortunately I don't have access to Maya (so i can't test any changes) nor can I provide sample models as I am working with partners on proprietary content. However, with multiple partners I have seen this issue when validating glb models exported from babylon maya:

                "code": "VALUE_NOT_IN_LIST",
                "message": "Invalid value 'image/'. Valid values are ('image/jpeg', 'image/png').",
                "severity": 1,
                "pointer": "/images/0/mimeType"

Validator: https://github.khronos.org/glTF-Validator/
The original texture was .png.
Some tools recognize that the texture should be .png but not all tools are able to do so, as they rely on reading the mimetype or require fully valid glbs.

Can anyone repro this issue? It looks like we are setting the mimetype based on the image file format but we aren't setting the image file format until after we already set the mimetype:
https://github.com/BabylonJS/Exporters/blob/master/SharedProjects/Babylon2GLTF/GLTFExporter.Texture.cs

If it helps, the glb was generated with babylon.js glTF exporter for Maya 2018 v20200211.10

Thank you very much for the help!

**Comment by Drigax** [comment]
I'm not sure how much I can help regarding this without a repro. If you can provide some approximation that reproduces this issue, I'll be more than happy to investigate further.
