### ISSUE TITLE
[3dsMax] Export FurMaterial backup material for glTF export

### ISSUE THREAD

**Issue by Drigax** [BabylonJS/Exporters#774]
Continuing from #766 conversation:

Currently Fur materials are replaced with default materials during glTF export via #773.

If we want to improve this experience, we should save in-memory a BabylonMaterial representing the base material without the Hair modifier in 3dsMax in the BabylonFurMaterial, and export this fallback material during glTF export.

**Comment by Drigax** [comment]
Currently I'm not sure how the Modifier stack can be traversed in 3dsMax. 

As @seth-cohen suggested via https://github.com/BabylonJS/Exporters/issues/766#issuecomment-586727881 we should be able to export the base Physical Material assigned to the Editable poly used in the object modifier stack.

Currently I'm not sure how to utilize the API to do just that.

**Comment by Drigax** [comment]
Adding the help wanted label. This seems like a "nice to have" but I don't really want to spend too much time investigating this personally.

**Comment by deltakosh** [comment]
Agree. I'm closing it as we will not work on it
