### ISSUE TITLE
Extra bits are exported to a glTF that shouldn't be

### ISSUE THREAD

**Issue by bghgary** [BabylonJS/Exporters#777]
- [x] There is always a "Default light" node that is exported even when not exporting lights.
- [x] `scenes.extensions` has an empty object
- [ ] nodes.extras.currentUVSet is sometimes written out

Repro:
1. Open https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/sourceModels/FlightHelmet/MayaProject/scenes/FlightHelmet.ma in Maya 2019.
2. Export to glTF using Babylon exporter.

The result is this (only the gltf file was included).
[FlightHelmet.zip](https://github.com/BabylonJS/Exporters/files/4278763/FlightHelmet.zip)

**Comment by belfortk** [comment]
Did not make a code change for nodes.extras.currentUVSet because exporter is working as intended. 

There is an extra attribute on the Lenses_low mesh which was being written out.

![image](https://user-images.githubusercontent.com/25019989/75935887-6b052b80-5e35-11ea-97c5-bee2afa07013.png)
