### ISSUE TITLE
Morph Target file exports animation to glTF when "export animations" unchecked

### ISSUE THREAD

**Issue by PatrickRyanMS** [BabylonJS/Exporters#778]
## Bug
This file has a morph target with two influences in it. The morph target is wired up and works, but when I export to glTF, even with export animations unchecked, I get blank animation data in the glTF which is causing validation errors. 

[axe_low.zip](https://github.com/BabylonJS/Exporters/files/4283610/axe_low.zip)

**Comment by Drigax** [comment]
Thanks! fix was very straightforward, we forget to check a flag before exporting morph target animation tracks. Should be available shortly.
