### ISSUE TITLE
[Maya ] Babylon- Animation Groups

### ISSUE THREAD

**Issue by grodigan** [BabylonJS/Exporters#787]
Hi! Is it possible to enhance Animation Group window?

![Babylon](https://user-images.githubusercontent.com/62152049/76644375-8c65c600-655f-11ea-9610-a66486e74939.jpg)

 In order to fill animation list by loading some file. Like in attached image below.

![Babylon2](https://user-images.githubusercontent.com/62152049/76644869-84f2ec80-6560-11ea-8c01-257383ddc6e4.jpg)

**Comment by Drigax** [comment]
You want to be able to serialize the animation group frames? Shouldn't be too difficult. We currently have an implementation in Max:

https://github.com/BabylonJS/Exporters/blob/31ab33de5cf81e81d441d30b9ea882fce0e10780/3ds%20Max/Max2Babylon/Exporter/AnimationGroup.cs#L394-L397

Where we serialize the Max exporter only class AnimationGroup to json, and deserialize via:

https://github.com/BabylonJS/Exporters/blob/31ab33de5cf81e81d441d30b9ea882fce0e10780/3ds%20Max/Max2Babylon/Exporter/AnimationGroup.cs#L399-L491

I think there's a lot in this implementation that we can reuse, mainly the properties of AnimationGroup (Minus the max-specific stuff, that would probably be best left relegated to a subclass of AnimationGroup)

I currently don't really have the time to do this refactoring and integration into Maya, but I'd be more than happy to help someone else :)

**Comment by Drigax** [comment]
Currently the max serialization will give us a file similar to this:

![image](https://user-images.githubusercontent.com/3952729/76672382-908ee500-6559-11ea-8b24-22e91567166e.png)

**Comment by elpie89** [comment]
I'm not merging from the Babylon master branch to our project since December. The way the official exporter is handling unique nodes names instead of unique ID could brake to many stuff on our side. So no problem from my side, maybe you could just change the serialization on the JSON file an not the animation group itself. It will not break retro compatibility

**Comment by grodigan** [comment]
> You want to be able to serialize the animation group frames? Shouldn't be too difficult. We currently have an implementation in Max:

Thanks a lot for sharing your work! We will try to find out how it would work for maya. For now It seems not possible to serialize animation groups from file.

**Comment by Drigax** [comment]
Not possible without some code changes ;), but I don't think that this is impossible in the slightest.

**Comment by Drigax** [comment]
Hey @grodigan di you make any progress with the maya animation group window?

**Comment by grodigan** [comment]
Hi, we use open maya to generate uuid https://help.autodesk.com/view/MAYAUL/2016/ENU/?guid=__cpp_ref_class_m_uuid_html then using this comand fileInfo "01bf067f-d5c5-4026-a590-4133a525672e" "Animation;-10;8101;";
fileInfo "babylonjs_AnimationList" "01bf067f-d5c5-4026-a590-4133a525672e";

**Comment by Drigax** [comment]
ah, would you like to make a PR?

**Comment by grodigan** [comment]
sorry i'm new here, what the PR means?

**Comment by Drigax** [comment]
Ah, would you like to make a Pull Request to contribute your work to the project?

**Comment by grodigan** [comment]
i will speak with bigwigs and let you know

**Comment by Drigax** [comment]
@grodigan, I'm going to close this issue. If you'd like to contribute your work back, feel free to reopen or open a pull request, we always welcome contributions :)
