### ISSUE TITLE
Add .basis compression in Exporters

### ISSUE THREAD

**Issue by thomlucc** [BabylonJS/Exporters#788]
(from 4.2 Brainstorm)

**Comment by Drigax** [comment]
To further improve the KTX2+Basis Universal ecosystem, it is a good idea to integrate a .basis compression option into the 3dsMax and Maya glTF exporters. 

As a prerequisite, I want to complete a study with @PatrickRyanMS regarding acceptible compression limits for different types of textures before implementing this into the exportes outright.

**Comment by Drigax** [comment]
I don't want to add this compression without putting in the due diligence into understanding the best uses of the basisUniversal texture format, and when and where and how to use it appropriately. Adding the blocked tag, and closing this issue until the Khronos Group can provide users with accurate guidance.
