### ISSUE TITLE
Changing animation name from "All Animations" to "default"

### ISSUE THREAD

**Issue by atari83** [BabylonJS/Exporters#790]
Hello there,

I'm using BabylonJS Exporter on 3D Max for exporting 3d animated objects to glTF (binary) format.
Everything is fine, and the .glb file exported with no issue.

However and although it sounds a bit weird, the tool that I'm working with and want to import the glb into is looking for the 3d animated objects that are using "default" as animation name, or it doesnt work ...  (we dont have access to its code to change its logic).

So, I want to ask, can anybody help me with a patch or guide to export my glb files with another animation name ? ("All Animations" -> "default")

Thanks.

**Comment by Drigax** [comment]
Thanks for reaching out 🙂.

The easiest solution would be to define a single animation group, and add all your animated objects to that group, give it the full animated timeline frame ranges, then give it the name you desire.

**Comment by atari83** [comment]
> Thanks for reaching out .
> 
> The easiest solution would be to define a single animation group, and add all your animated objects to that group, give it the full animated timeline frame ranges, then give it the name you desire.

Thank you @Drigax ,
It solved my problem :)
