### ISSUE TITLE
Install to custom location

### ISSUE THREAD

**Issue by CountZer0** [BabylonJS/Exporters#791]
We need to run the plugin in Maya in a sync'd location that is not the default location:
C:/Program Files/Autodesk/Maya2018/bin/plug-ins

When I move the .dlls to a locally synced project location and the NE/AETemplates to the default ../scripts/AETemplates folders. I get this error when trying to load the plugin:

// Error: file: C:/Program Files/Autodesk/Maya2018/scripts/others/pluginWin.mel line 909: Invoking ExecuteInDefaultAppDomain() failed. // 
// Error: file: C:/Program Files/Autodesk/Maya2018/scripts/others/pluginWin.mel line 909:  (Maya2Babylon.nll) // 

Is the plugin compiled to only work in the default maya plug-ins location?

**Comment by Drigax** [comment]
Currently, yes. Would you like to help add this feature?

**Comment by Drigax** [comment]
closing this issue, as the installer I use does not allow me to install to a custom location. If anyone is interested in providing a fix, I'd be happy to reopen.
