### ISSUE TITLE
[Max][gltf] IMAGE_MIME_TYPE_INVALID errors and warnings (bin/jpg/png)

### ISSUE THREAD

**Issue by tkazik** [BabylonJS/Exporters#792]
Hey folks!

Hope you are doing fine!
I recently updated my 3ds max exporter to the newest version and now I get the following validation errors and warnings: 

![2020-04-04 16_33_16-Window](https://user-images.githubusercontent.com/15689124/78453450-0f2afe00-7692-11ea-9f85-6afb8152b6cc.png)

I had a quick look at the gltf-files and noted the following differences:
![2020-04-04 16_28_14-Window](https://user-images.githubusercontent.com/15689124/78453468-28cc4580-7692-11ea-8714-429d920f0459.png)
Left side: Old exporter;                           Right side: New exporter version

So my guess is that there must be something incorrect with the file endings (jpg/png/bin). Could you please have a look?

All the relevant files (model and glbs) can be found [here](https://github.com/BabylonJS/Exporters/files/4431676/exporter_bug_files.zip).

Thank you!

**Comment by Drigax** [comment]
Its important to specify that this only occurs with glb export. in this instance, the image data is preserved, just given the wrong extension?:

If one was to export to gltf, the file and textures are exported as expected:

![image](https://user-images.githubusercontent.com/3952729/78683168-d19dbf00-78a3-11ea-82d2-9d23c6e7c3f4.png)

This appears to only occur during glb export where our image mime type appears to be not set?:
![image](https://user-images.githubusercontent.com/3952729/78684742-b2a02c80-78a5-11ea-997a-7c2af832c7da.png)


Not currently sure exactly what's going on. I'll continue to investigate.

**Comment by Drigax** [comment]
As a note, this bug also exists in the latest maya exporter as well. I suspect the glb-specific code in our texture export process is at fault here.

**Comment by Drigax** [comment]
Looks like we weren't properly setting the mimetype, I made multiple changes to our gltf texture export via:
https://github.com/BabylonJS/Exporters/commit/8ae609579ffbfd7cd83a65ffce3bfde59de59896

Looks like I missed this detail.

**Comment by Drigax** [comment]
https://github.com/BabylonJS/Exporters/pull/797

**Comment by tkazik** [comment]
Awesome, thank you for the quick fix!
