### ISSUE TITLE
Max 2021 Support

### ISSUE THREAD

**Issue by Drigax** [BabylonJS/Exporters#803]
3ds Max 2021 was released to market March 25th 2020.

We should try to port the existing codebase to work with the latest release and evaluate:

1. If any major changes should be made to the exporter project for max 2021 for compatibility
2. If any major changes need to be made to support any [Relevant new features](http://help.autodesk.com/view/3DSMAX/2021/ENU/?guid=GUID-566A8DA5-C3EA-472F-B846-AB334616D6BD)
      2a. The largest concerns for support are supporting the PBR metal rough, and PBR spec gloss workflows to some degree.
3. Is there a release channel somewhere to know when these new iterations are in the pipeline?
4. Update the relevant installers, documentation, and whatnot to support these changes as well.

**Comment by animech-sijo** [comment]
Support for the new PBRMetalRough and PBRSpecGloss materials would be fantastic, as it would allow WYSIWYG between glTF viewers and Max's viewport. With the regular Physical material you have to jump through a few hoops to get there.

**Comment by cptSwing** [comment]
To anyone hoping 20's dll files would work in Max 21 (since other plugins do not seem to need recompilation between these two versions): Nah ;/

I'd love for a quick and dirty working version, new materials be damned!

**Comment by Drigax** [comment]
> To anyone hoping 20's dll files would work in Max 21 (since other plugins do not seem to need recompilation between these two versions): Nah ;

Nah, Unfortunately, one needs to compile against the 3dsMax .net libraries, which change between versions. If anyone is desperate for a 2021 version of this , feel free to look at previous pull requests for 2020 and 2019 for an example. I'm currently prioritizing incoming bugs and some exploratory work regarding texture compression methods, but I'll try to get to this before June.

**Comment by cptSwing** [comment]
I gave it a cursory glance, but I'm in waaay over my javascript-noob's head I'm afraid ;)

**Comment by Drigax** [comment]
@cptSwing  ask and ye shall receive...eventually atleast. I had some free cycles to do the initial port job over, looks like the max2020 featureset is fully supported in 2021. currently no support for any of the new goodies, but feel free to open issues for the missing features. the current largest thing on my list is the new Standard Surface implementation, as we may need to get a bit dirty depending on how the old Blinn/Phong materials are implemented with regards to the new standard surface.

**Comment by Drigax** [comment]
At the very least, I was able to open an old complex testing scene created in Max2020, and it loaded and exported out of the 2021 build without issue :)

**Comment by cptSwing** [comment]
> 
> 
> @cptSwing ask and ye shall receive...eventually atleast. I had some free cycles to do the initial port job over, looks like the max2020 featureset is fully supported in 2021. currently no support for any of the new goodies, but feel free to open issues for the missing features. the current largest thing on my list is the new Standard Surface implementation, as we may need to get a bit dirty depending on how the old Blinn/Phong materials are implemented with regards to the new standard surface.

Nice nice nice, I've just installed and will fool around with it on my current production. Already enjoying 21's (subjective?) greater viewport and ux speed. I'll bug you when things pop up!

The standard surface, do you mean the new PBR materials? I was under the impression that under the hood they are just implementations of the Physical Material (which AD is indeed turning into their own standard surface afaik)
