### ISSUE TITLE
[Maya 2018] Export BabylonJS scene parameters from Maya and support for transparent materials

### ISSUE THREAD

**Issue by Munghior** [BabylonJS/Exporters#808]
When I export from Maya a glb/gltf model with some transparent materials, I have some issues in the BabylonJS Sandbox viewer, when I see a transparent shape through another transparent shape. The problem is the rendering order that can be corrected by the alpha index parameter of the meshes.

There is a way to set it properly in Maya (and also the other Sandbox parameters), before/during the export and not inside the viewer?

I know that there is an object properties window for the 3DSMax plugin. Will this support be in the roadmap for the Maya plugin?

**Comment by Drigax** [comment]
Hi Munghior,

I'm not sure what you mean, I'm not aware of an "alpha index" in the glTF format. Can you clarify?

**Comment by Munghior** [comment]
Alpha Index is not in the gltf format, it's a BabylonJS parameter (https://doc.babylonjs.com/resources/transparency_and_how_meshes_are_rendered#alpha-index) and it can be set from an object properties window in BabylonJS plugin for 3DSMax (https://doc.babylonjs.com/resources/3dsmax#object-properties) but not in Maya.

When I export from Maya a gltf object with transparent materials, the Sandbox cannot correctly render this transparency, but it can be corrected by setting the alpha index properly.

![Babylon Alpha Index](https://user-images.githubusercontent.com/33691530/79804710-de6ee800-8364-11ea-948c-b7a1bc6794b2.png)

**Comment by Drigax** [comment]
How would the loader know what alpha index to assign to each object in scene if it is not available in the glTF file format? It sounds like we're losing data here due the the format, that may not be possible to recreate.

**Comment by Drigax** [comment]
There are 2 possible workarounds for this:
1) add the alpha index data you need to the mesh extras as a custom attribute that we'll serialize. This will be specific to your application.

2) propose an extension for alpha index for glTF to adopt

**Comment by Drigax** [comment]
I'm going to close this issue, as I don't know if there's anything we can do to the glTF exporter to support this. If you want to continue this conversation feel free to re-open with some proposed changes you'd like to make to support this.
