### ISSUE TITLE
bonesIndicesMerged's bit operation bug?

### ISSUE THREAD

**Issue by ProgC** [BabylonJS/Exporters#810]
Somehow our mesh with the animation is not showing correctly on the google's scene viewer (include other gltf viewers) and I think bit operation makes this bug.

On BabylonExporter.Mesh.cs, there is a code like this.

-----
int bonesIndicesMerged = babylonMesh.matricesIndices[indexVertex];
int bone3 = bonesIndicesMerged >> 24;
bonesIndicesMerged -= bone3 << 24;
int bone2 = bonesIndicesMerged >> 16;
bonesIndicesMerged -= bone2 << 16;
int bone1 = bonesIndicesMerged >> 8;
bonesIndicesMerged -= bone1 << 8;
int bone0 = bonesIndicesMerged >> 0;
bonesIndicesMerged -= bone0 << 0;
----

Our mesh uses around 190 bones and I think those code should be changed like down below.

----
uint bonesIndicesMerged = (uint)babylonMesh.matricesIndices[indexVertex];
uint bone33 = bonesIndicesMerged >> 24;
uint bone22 = (bonesIndicesMerged << 8) >> 24;
uint bone11 = (bonesIndicesMerged << 16) >> 24;
uint bone00 = (bonesIndicesMerged << 24) >> 24;
----

Regards

**Comment by Drigax** [comment]
Yes! that is the bug I'm looking into currently, thanks! I knew we were improperly exporting signed bits, but I didn't quite root cause to this specific code! Thanks for the solution, I'll check that this works.

**Comment by ProgC** [comment]
Great~!
