### ISSUE TITLE
Custom attributes don't export in 3ds max

### ISSUE THREAD

**Issue by sinokgr** [BabylonJS/Exporters#817]
Hi all,
Any ideas why custom attributes don't export in 3ds Max?
Am I missing something?
![extras](https://user-images.githubusercontent.com/22396951/81456004-9e4b9a00-9199-11ea-9e1d-0c6179260943.gif)

Thanks,
Nick

**Comment by sinokgr** [comment]
![image](https://user-images.githubusercontent.com/22396951/81538013-c5ab8e00-9376-11ea-89b8-a3f603e07668.png)
I did notice that on the output below, it displays an "ExportExtraAttributes". But I can't find them anywhere still.

**Comment by Drigax** [comment]
Ah, Looks like something is broken in how we retrieve these attributes from Max via maxscript:

https://github.com/BabylonJS/Exporters/blob/440294393759f5d1faf9c774da1e6a21636ec8e6/3ds%20Max/Max2Babylon/Exporter/BabylonExporter.CustomAttributes.cs#L52-L74

Should simplify down to:
```
s = for objDef in (custAttributes.getDefs obj) do
                (
                    pbArray = custAttributes.getPBlockDefs objdef
                    for indexPBlock = 1 to pbArray.count do
                    (
                        itms = pbArray[indexPBlock]
                        for y = 5 to itms.Count do
                        (
                            s = s + "_$€PParam_" + itms[y][1]
                            for z = 1 to itms[y][2].Count by 2 do
                            (
                                key = itms[y][2][z] as string
                                if (findString key "type") != undefined then
                                (
                                    s = s + "_$€PType_" + itms[y][2][z+1]
                                )
                            )
                        )
                    )
                )
```

when evaluated, which appears to trigger an error in our custom attribute sample scene:
https://github.com/BabylonJS/Exporters/blob/master/3ds%20Max/Samples/sourceModels/CustomAttributes/CustomAttributes.max

![image](https://user-images.githubusercontent.com/3952729/81599997-d14e8300-937d-11ea-9ce7-fff9a6eb5daa.png)


I'm a little stumped on what exactly this is complaining about. I'll have to take a closer look at this.

**Comment by Madlios** [comment]
Im also having problem with this, please update on this asap. I tried to look through the source code but not sure how to run it properly for debugging

**Comment by Madlios** [comment]
I tried to replace "obj" with "selection[1]" and it seems to work, not sure what this means:
![image](https://user-images.githubusercontent.com/6091905/81822716-c0477280-9533-11ea-86b2-32d0e9caf1c8.png)

**Comment by Drigax** [comment]
Check my previous post for details on what's going on...

I'm no maxscript expert, we use this snippet to retrieve all the custom attributes for a given node in scene, but its broken. And I have no idea why because i dont fully understsand the 3dsMax IGameNode data structure. Ny help with this would be appreciated.

**Comment by Madlios** [comment]
The maxscript works for me. In fact the exporter can export attributes fine if I assign custom attributes on the material level, as long as that material cannot be a multi-subobject material.

i.e if I define attributes for either a physical material or standard material the exporter can export fine. The exporter however fail to export on the object level.

**Comment by Drigax** [comment]
Strange, I'm still not sure why this is failing particularly for Objects...I think the actual custom attribute parsing code works as expected, as your and my manual testing seems to suggest.

I took a step back and tested how we try to retrieve the object reference in scene in the Maxscript context:
https://github.com/BabylonJS/Exporters/blob/4755d285625c77f27eae8f15df0f4078362052df/3ds%20Max/Max2Babylon/Exporter/BabylonExporter.CustomAttributes.cs#L30-L37

![image](https://user-images.githubusercontent.com/3952729/81870539-e61c4980-952a-11ea-9646-b2120efd11df.png)

Ok, I think we're getting somewhere. I don't know if this snippet ever worked...

**Comment by Drigax** [comment]
Bingo Bongo. Fix should be up soon

**Comment by renderappco** [comment]
oh, that's amazing! Many thanks @Drigax ! :)

**Comment by sinokgr** [comment]
Oh that's amazing! Many thanks @Drigax ! :)
