### ISSUE TITLE
The Babylon GLTF export for Maya does not follow the GLTF schema for KHR_light_punctual lights and nodes.

### ISSUE THREAD

**Issue by imbrig** [BabylonJS/Exporters#818]
1. Install the latest BabylonJS GLTF exporter for Maya. Currently supported on Windows.
See guide at https://doc.babylonjs.com/resources/maya_to_gltf
2. Load a scene and place lights inside of the node hierarchy.
[Maya_Mannequin_Lights.zip](https://github.com/BabylonJS/Exporters/files/4602508/Maya_Mannequin_Lights.zip)
3. Select the Babylon export and check the "KHR_lights_punctual" box.
4. Open the GLTF file in VSCode and notice the warnings on the nodes with the lights.
5. Observe the nodes with the lights will have "intensity": 0, and "spot": null which do not follow the node schema.
6. Observe the file gltf "KHR_lights_punctual" extension which will include "spot": null and "range": 3.40282347e+38 which was not specified.

Observed Results:
The exported gltf with "KHR_lights_punctual" extension has a different scheme for nodes and gltf file levels than what is in the documented in the gltf repo.

Expected Results:
The exported gltf with KHR_lights_punctual should follow the examples and schema outlined.
Node https://github.com/KhronosGroup/glTF/blob/master/extensions/2.0/Khronos/KHR_lights_punctual/schema/node.KHR_lights_punctual.schema.json
Light
https://github.com/KhronosGroup/glTF/blob/master/extensions/2.0/Khronos/KHR_lights_punctual/schema/light.schema.json

Here are the exported GLTF and the one that I fixed manually following the schemas.
[GLTF_Mannequin_Lights.zip](https://github.com/BabylonJS/Exporters/files/4602516/GLTF_Mannequin_Lights.zip)

**Other issues to note:**
The "outerConeAngle" value is in radians and did not match the degrees given in Maya, it seems to only be half, in this case 45 degrees was set on the spot light cone angle.
![rad2deg](https://user-images.githubusercontent.com/47464835/81461902-c8826500-9163-11ea-8d13-07f335ad7599.png)
Intensity seems weaker in the gltf that what is visible in Maya but this could related to scale or something I'm not aware of.
![intensity_maya](https://user-images.githubusercontent.com/47464835/81461931-f5cf1300-9163-11ea-809e-a0d2f9eec0e3.png)

**Comment by Drigax** [comment]
Lets try to itemize this into specific tasks:

For KHR_Lights_Punctual:

- [ ] We are improperly serializing some of the light properties with the extension declaration on the node.
        -Ok, makes sense. Not sure why we are serializing this with the extension. this should be removed. Should be a trivial fix.

- [ ] Light angle appears off by a factor of 1/2.
        - i'm not too sure if this is the case, I remember noting the difference between Maya and glTF's representation of light angles via: https://github.com/BabylonJS/Exporters/issues/689#issuecomment-557742710

I use a testing scene here that has a number of lights, with cone angle ranging from pi/16-pi/4 radians iirc to verify the export: https://github.com/BabylonJS/Exporters/files/3882064/TestSpotlightAngle.zip

**Comment by Drigax** [comment]
Regarding the lighting angle, I retested our sample scene export:
Just from a purely visual test, everything looks pretty correct, we have exported lights with pi/32, pi/16/pi/8 and pi/4 radian cone angles, respectively
![image](https://user-images.githubusercontent.com/3952729/81613847-fcdc6800-9393-11ea-82db-7c8093552777.png)

imported into the babylon sandbox everything looks as expected:

![image](https://user-images.githubusercontent.com/3952729/81613831-f64df080-9393-11ea-85a0-048c7016d2ed.png)

**Comment by imbrig** [comment]
Thanks for looking at this. I've looked at your post and it makes sense, I was only looking at the values not the visual results. The big issue for me is just the schema stuff.

**Comment by Drigax** [comment]
can do, I'll try to get a fix for that ASAP
