### ISSUE TITLE
Invalid gltf

### ISSUE THREAD

**Issue by tkazik** [BabylonJS/Exporters#82]
Hi folks

Probably a simple fix for this issue (or I am missing something basic in my .max file).
A simple chair model without animation produces an invalid gltf file, see:

![report](https://user-images.githubusercontent.com/15689124/35564492-9ab4a16a-05ba-11e8-9932-2b0ca0e12ef4.png)

These last lines of the gltf seem to cause troubles to the validator: 
`"animations": [{
		"channels": null,
		"samplers": null
	}
]
`
Deleting the "animations" resolves the issue.
But why are these exported at all?

Thx!

PS: Model and gltfs are here [chairs.zip](https://github.com/BabylonJS/Exporters/files/1677494/chairs.zip)

**Comment by noalak** [comment]
Hi tkazik,

Issue has been fixed in this [commit](https://github.com/BabylonJS/Exporters/commit/3fd22ac95023f242d8a0c99f98ff76614cc81e16).
You just need to update to last version.

Sorry for the inconvenience.
