### ISSUE TITLE
Maxscript exporter conflict with Progress Bar Display

### ISSUE THREAD

**Issue by sinokgr** [BabylonJS/Exporters#821]
Hi there,

I just noticed another small bug. It looks like, that if you use the Progress Bar Display the exporting is happening in the background. 

Add a few objects in the scene and run the following script. It will export fine. If you uncomment the progress code and run it again, you'll see that the code within the progress, will run super quick, 3ds Max will become semi-working again (like the script finished executing) while the objects export in the background.

```maxscript
(
	local dir = getSavePath()
	if dir != undefined then (
		local maxScriptManager = dotNetObject "Max2Babylon.MaxScriptManager"
		param = maxScriptManager.InitParameters "C:\\test.glb"
		param.exportOnlySelected = true
		
		-- ProgressStart "Start exporting..."
		-- local count = 0.0
		for obj in objects do (
			select obj
			param.outputPath = dir + "\\" + obj.inode.handle as string + ".glb"
			maxScriptManager.Export param
			
			-- count += 1
			--  ProgressUpdate ((count/objects.count)*100)
		)
		-- ProgressEnd()
		
		Messagebox "Finished!"
	)
)
```

I used 3ds Max 2017, even though I don't think it matters.

It's not super important, as I can work around it, but it would be great if it could be fixed.

**Comment by Drigax** [comment]
Very strange. I'm currently looking into some higher priority issues, but would you be interested in looking into what may be causing this?

**Comment by sinokgr** [comment]
> Very strange. I'm currently looking into some higher priority issues, but would you be interested in looking into what may be causing this?

Hi @Drigax , many thanks for the reply. I'll try to find some time, but as we're currently very busy, I can't promise that I will have the time. If I do, I'll post my findings here.

**Comment by pandaGaume** [comment]
Can not reproduce under 2021. I change the code a bit, but can not see any difference between commented and uncommented progress version.

```
(
	local dir = getSavePath()
	if dir != undefined then (
		local maxScriptManager = dotNetObject "Max2Babylon.MaxScriptManager"
		--ProgressStart "Start exporting..."
		local count = 0.0
		for obj in objects do (
		       select obj
		       local path = dir + "\\" + obj.inode.handle as string + ".glb"
		       param = maxScriptManager.InitParameters path
		       param.exportOnlySelected = true

                       maxScriptManager.Export param
			
			count += 1
			--ProgressUpdate ((count/objects.count)*100)
		)
		--ProgressEnd()
		Messagebox "Finished!"
	)
)
```

**Comment by pandaGaume** [comment]
[testAsync.zip](https://github.com/BabylonJS/Exporters/files/5502058/testAsync.zip)
