### ISSUE TITLE
Export cancelled: (kFailure): Unexpected Internal Failure

### ISSUE THREAD

**Issue by vsnappy** [BabylonJS/Exporters#822]
Similar issue to that reported here: [Issue #464](https://github.com/BabylonJS/Exporters/issues/464)

Babylon.js - Exporter v20200513.4
Maya 2019

Simple repro file attached.
[export_issue.zip](https://github.com/BabylonJS/Exporters/files/4639328/export_issue.zip)

Export started
DAG: full
DAG: relevant
Exporting nodes
	pTorus1
	Total meshes: 1
	No camera defined
	Total lights: 0
Exporting materials
**Export cancelled: (kFailure): Unexpected Internal Failure
	System.ApplicationException: (kFailure): Unexpected Internal Failure
   at Autodesk.Maya.OpenMaya.MGlobal.executeCommand(String command, String& result)
   at Maya2Babylon.BabylonExporter._ExportCustomUserAttributes(BaseObject baseObject)
   at Maya2Babylon.BabylonExporter.ExportMaterial(MFnDependencyNode materialDependencyNode, BabylonScene babylonScene, Boolean fullPBR)
   at Maya2Babylon.BabylonExporter.Export(ExportParameters exportParameters)
   at Maya2Babylon.Forms.ExporterForm.<DoExport>d__32.MoveNext()**

**Comment by saidmoya12** [comment]
Try to set babylon transparency to opaque

**Comment by vsnappy** [comment]
> 
> 
> Try to set babylon transparency to opaque in your materials

In the file I posted, there is no babylonStingrayPBSMaterialNode.  That seems to be created automatically at some point after not encountering whatever bug it is that I'm hitting above.

**Comment by pandaGaume** [comment]
@vsnappy This is internal Maya custom attribute export failure. I made a quick fix to prevent the entire export to crash. However, the custom user attribute WILL NOT be correctly exported yet, so it may lead to future issues. This will be updated in the same release as other issues such #822 and #874
