### ISSUE TITLE
problem of file size with morph

### ISSUE THREAD

**Issue by lo-th** [BabylonJS/Exporters#825]
Hi first thank's for this great exporter 
i have problem with some of my files
i export in glb with draco compression

i make a car model on export i have 117 ko great. ( 2.45 Mo without compression  )
but i make one simple morph on suspension spring  
and my file jump to 2.05 Mo ( 2.65 Mo without compression  )

so maybe draco can't compact morph.
is there a way to improve draco file size with morph 
thank's

![spring](https://user-images.githubusercontent.com/1553208/82786526-1803a900-9e65-11ea-8e99-2eb894394384.jpg)

**Comment by Drigax** [comment]
Unfortunately I don't know the internals of draco compression, and can't really help with this. This is more of an issue for the glTF schema and compression tooling. I can see some proposed extensions to support draco compression of morph targets, but they are not ratified or widely adopted...:

https://github.com/mrdoob/three.js/issues/17878#issuecomment-550397731
https://github.com/KhronosGroup/glTF/pull/1702

My assumption is that while we can compress the mesh data, we cannot compress the morph targets, as they are direct transformations of the original mesh's vertices, and may not be able to be compressed without hassle, as vertex indices may not be preserved via our compression mechanisms. Unfortunately, you may want to look into using a skeletal animation strategy for this part if file size is most important.

**Comment by lo-th** [comment]
ok thank's Drigax 
another solution is recreate morph on code side.
