### ISSUE TITLE
[3ds max] The normalTexture scale / weight set in my physicalmaterial does not tag along in the gltf file.

### ISSUE THREAD

**Issue by ogmasoul3d** [BabylonJS/Exporters#826]
this is very related to the closed issue:
https://github.com/BabylonJS/Exporters/issues/311
But it does not solve the problems I have..

Hi, I hope I am doing something wrong.. but I cannot get the Bump map weight param from the Physical Material in max 2019 to do anything to the normalTexture scale parameter on export.
![normalTextureScale-bug](https://user-images.githubusercontent.com/136207/82835879-95f79c80-9ec5-11ea-9f26-f5ec3668e321.jpg)

From what I can see I never get that parameter written in the gltf file?
![normalTextureScale-bug_p2](https://user-images.githubusercontent.com/136207/82836359-a8260a80-9ec6-11ea-93d4-a50608d66776.jpg)

I can manually add the normalTexture.scale property to the gltf and then I get the behaviour that I expected.

**Comment by Drigax** [comment]
Thanks for reporting, I'll try to take a look as soon as I can

**Comment by ogmasoul3d** [comment]
Here is a small teapot.. with a physicalMaterial using a bumpmap.. nomatter what value I set the bump strength to be. It does not get exported to the gltf file..
[GltfBumpTest_3dsmax.zip](https://github.com/BabylonJS/Exporters/files/5317725/GltfBumpTest_3dsmax.zip)

Here is the output I get when exporting from 3dsmax 2019 using babylonJs exporter version:  Using Max2Babylon for 3dsMax version v21.3.4.0

[GltfBumpTest_gltTF_no_Scale_set_for_normal.zip](https://github.com/BabylonJS/Exporters/files/5317726/GltfBumpTest_gltTF_no_Scale_set_for_normal.zip)

**Comment by pandaGaume** [comment]
@ogmasoul3d Many Thanks.
