### ISSUE TITLE
Shading Artifact

### ISSUE THREAD

**Issue by anteaterho** [BabylonJS/Exporters#836]
![Skinning Issue_01](https://user-images.githubusercontent.com/773412/84463471-dd936c00-acac-11ea-9766-b014f3c678f3.JPG)

Hello.

When I exported character modeling included animation I got a strange artifact.
I used  Babylon exporter for Maya(20200611.5)

On the narrow part, for instance kind of a armpit there ware some kind of a strange shading.

As you can see from the attached picture, it is the same cylinder, but when the angle of the bend increases, the artifact becomes more pronounced.

I check the normal and skinning but it was fine.

Only I got this kind of artifact when I exported with babylon export for maya.

How could I erase or solve this kind of artifact when I export to *.gltf format babylon exporter for Maya. 

PS 
I included example maya *.ma and *.gltb files.

[test_ani.zip](https://github.com/BabylonJS/Exporters/files/4768651/test_ani.zip)

[Cylinder_Anim_Test_02.zip](https://github.com/BabylonJS/Exporters/files/4768960/Cylinder_Anim_Test_02.zip)

**Comment by Drigax** [comment]
Due to restrictions in the Maya API, you have to export your scene with the playhead set to the frame that you want to use as your binding pose. See #737

**Comment by anteaterho** [comment]
I got it thanks a lot!
