### ISSUE TITLE
When I export 3D model with animation to .babylon, meshes with animations gettting misplaced inn blender as well as when loaded in babylon sandbox

### ISSUE THREAD

**Issue by ravip** [BabylonJS/Exporters#84]
When I export 3D model with animation to .babylon, meshes with animations gettting misplaced inn blender as well as when loaded in babylon sandbox

**Comment by deltakosh** [comment]
Pinging @palmer_jc

**Comment by deltakosh** [comment]
Please also use the forum for support on blender:
http://www.html5gamedevs.com/forum/16-babylonjs/

**Comment by Palmer-JC** [comment]
The key i am taking from this is meshes, not mesh.  When multiple meshes have animation you either need to name the actions to say which mesh gets which action, or using exporter 5.5, indicate only the current animation for each.  I suspect the later.  [See](http://www.html5gamedevs.com/topic/34898-blender-55-exporter/)
