### ISSUE TITLE
Support for KHR_materials_refraction

### ISSUE THREAD

**Issue by Tangerine-Chang** [BabylonJS/Exporters#840]
Hi, everyone,

I wonder know the GLB/GLTF which could be shown the transparent material (ex: glass, plastic)? As I export to the GLB/GLTF file, it will be shown the clear (just clear not glass texture) or black. Is possible to export the GLB/GLTF with transparent texture correctly?

I am grateful for your help.

**Comment by Drigax** [comment]
Do you have a sample?

**Comment by Tangerine-Chang** [comment]
Hi, Drigax,

I am new to MAYA and just start to use the GLB/GLTF. 

The 3D is build by MAYA. The JPG is show what I want and I export the fbx from MAYA2020 and covert to GLB file via ADOBE Dimension. 

JPG:
![0612-tarsparent-fly](https://user-images.githubusercontent.com/66812304/84623665-547d6e80-af12-11ea-91f8-4d96b6f44a92.jpg)

GLB:
https://adobe.ly/2UMhIud

**Comment by cptSwing** [comment]
You will at the very least have to work on shaders in-engine to acheive the look from the screenshot? It looks like refraction & real-time reflections are things you might want to look into!

**Comment by Drigax** [comment]
That looks like it's using https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Vendor/ADOBE_materials_thin_transparency

Unfortunately, the babylon.js gltf export plugin doesn't support transparency or glass-like refractive material behavior currently, there are current developments around https://github.com/KhronosGroup/glTF/pull/1800/files?short_path=bc75459#diff-bc75459ee3647bb530c5e0b0a74bf92e

That we do plan to support soon, as it's close to ratification.

**Comment by Drigax** [comment]
I'll update this issue to track this.

[ ] - 3ds Max
[ ] - implement KHR_materials_ior
[ ] - implement KHR_materials_transmission
[ ] - implement KHR_materials_refraction

[ ] - Maya
[ ] - implement KHR_materials_ior
[ ] - implement KHR_materials_transmission
[ ] - implement KHR_materials_refraction

**Comment by Tangerine-Chang** [comment]
Hi Everyone, 

Thank you for your explaining. 
Yes, my problem is how to show glass refractive on GLB/GLTF file. Now I understand that it is hard to show the transparency or glass-like refractive whatever I export from different 3D softwares, is it right?

I have one more question. Could anyone understand how to work on this which is the sample I saw from web?
![EXAMPLE](https://user-images.githubusercontent.com/66812304/84845621-9ed02e00-b07f-11ea-8410-0593508476da.JPG)

https://threejs.org/examples/#webgl_materials_cubemap_refraction

I really appreciate your help!!

**Comment by Drigax** [comment]
I want to clarify that we plan to support these extensions as _soon_ as they are close to ratification, unfortunately the specs are still in flux as discussions regarding requirements and intentions change regularly. Once the specification nears ratification, i'll feel comfortable implementing it here, as we have less risk of lost work.

**Comment by Tangerine-Chang** [comment]
Noted, hope one day the extensions could be work. 
Thank you.

**Comment by deltakosh** [comment]
Actually closing because Autodesk will soon provide a gltf exporter. So we do not plan to add more extension support in our gltf exporter.

That being said we will gladly merge any PR regarding that works if someone is ok to do it
