### ISSUE TITLE
Flicker when using a alpha texture

### ISSUE THREAD

**Issue by anteaterho** [BabylonJS/Exporters#841]
![alpha_test_05](https://user-images.githubusercontent.com/773412/84629870-fd819480-af25-11ea-93c6-48addf7665b3.gif)

Flicker when using a alpha texture.

Hello Everyone.

When I use alpha texture with Sting-ray Material I got this kind of artifact.
[I use Babylon exporter for Maya.]

It seems to have a alpha sorting problem.

There are any solution for this kind of problem?

I set up String-ray Material like what I attached images.

![alpha_mat_settings](https://user-images.githubusercontent.com/773412/84630297-b3e57980-af26-11ea-8c16-ca87c3fbb6b3.JPG)

![alpha_mat_settings_02](https://user-images.githubusercontent.com/773412/84630316-b9db5a80-af26-11ea-9d75-631ff660317d.JPG)

PS
Also disappeared AO map slot when I use transparent mode.

**Comment by Drigax** [comment]
@anteaterho few things here: 1) glTF doesnt support alpha ordering, when we use AlphaMode = Blend, all the transparent elements to render over each other in a given fragment, as alpha blended e. Looking at our docs suggests that using Alpha Mode = Test may allow for proper ordering:

https://doc.babylonjs.com/resources/transparency_and_how_meshes_are_rendered#opaque-or-transparent
