### ISSUE TITLE
3DS MAX 2021 UI padding problem

### ISSUE THREAD

**Issue by hjlld** [BabylonJS/Exporters#842]
![20200615180054](https://user-images.githubusercontent.com/11457246/84644766-2e67c680-af32-11ea-9ae8-23e3480b36da.png)

there is an ui problem, i can't tell if `Use Draco compression` checkbox is checked or not.

Max Version: 3DS MAX 2021
OS: Windows 10 1909 / 18363.900
Resolution: 1920 x 1080
Retina: False

**Comment by Drigax** [comment]
I'm not sure if we can fix this meaningfully using winforms. The main issue is that your system font is wider than expected.

here is the form at design time:
![image](https://user-images.githubusercontent.com/3952729/84687014-d4dfa780-aef1-11ea-8651-bfb3a328b3d2.png)

Winforms doesn't really have a concept of a relative positioning layout schema, everything is anchored to its parent, I'll spotfix this by shortening the previous label, but I don't see a meaningful way to fix this for all resolutions for all fonts for all configurations...

**Comment by Drigax** [comment]
here's the fix https://github.com/BabylonJS/Exporters/pull/845
