### ISSUE TITLE
3dsMax 2021: Draco compression not working with .gltf

### ISSUE THREAD

**Issue by cptSwing** [BabylonJS/Exporters#843]
Here's a screen of my settings and the log:

![image](https://user-images.githubusercontent.com/18466732/84667269-69fa9480-af22-11ea-8b50-f72355378b1b.png)

Exporting to GLB does not throw an error and seems to be working, for some odd reason

**Comment by Drigax** [comment]
You have to install the gltf-pipeline tool, the exporter doesn't perform the compression itself

https://doc.babylonjs.com/resources/3dsmax_to_gltf#draco-compression

**Comment by cptSwing** [comment]
I have gltf-pipeline installed, and things work when compressing a glb:

![image](https://user-images.githubusercontent.com/18466732/84671715-feb3c100-af27-11ea-8050-d9f8ed53fbd4.png)


This bug seems to be limited to this mesh/max scene though?? I can draco-compress other gltf meshes just fine

**Comment by Drigax** [comment]
Ok, so only this particular scene fails to compress, and only when exported as glb? Or does this particular scene fails to compress regardless?

**Comment by cptSwing** [comment]
It's only this mesh/selection of meshes, it's quite odd. Creating a box right next to it and exporting as compressed gltf works, and still works when I add anim keyframes and export (another guess)..

I'll ask for permission to share, thanks!
