### ISSUE TITLE
Is there a more verbose log than the one showing in the exporter window?

### ISSUE THREAD

**Issue by leoncvlt** [BabylonJS/Exporters#848]
I have got a scene where the exporter often crashes at the material export stage. Sometimes the export would work fine, but if I export again right afterwards, without changing any parameter, it crashes the scene. Now I'm stuck because I really need to change a material on an object but the exporter will crash every time I dare doing so, even when assigning a default physical material.

It's very hard to try and troubleshoot the reason of these crashes because the exporter window doesn't tell me anything, other than "Export materials" being the last step on the log window before Max encounters an error and closes. Is there a more verbose .log than I can check in the hope of shedding more light on these issues?

**Comment by Drigax** [comment]
Currently the log only exists in the dialog window, we don't currently log to disk. I'm always happy to accept contributions improving this functionality 😊

**Comment by leoncvlt** [comment]
I see, thanks for coming back at me - what about verbosity then? Is there any option to expand on the information being printed in the dialog window during the exporting process?

**Comment by Drigax** [comment]
Yes, the dialog is a tree view, you can expand the nodes to see additional logging information:
![image](https://user-images.githubusercontent.com/3952729/85066788-72daa880-b164-11ea-92ab-485ea6a8f43e.png)

**Comment by leoncvlt** [comment]
Cheers. I know it's outside the scope of this issue, but could I trouble you to give me a quick rundown on what the "ExportExtraAttributes" step during materials export consists of? That seems to be step that causes the exporter to crash in my specific case.

**Comment by Drigax** [comment]
Ah, so exportExtraAttributes exports the custom attributes added to a material

**Comment by Drigax** [comment]
it may be that you've added some attribute that doesnt export well, can you share your scene?

**Comment by deltakosh** [comment]
Closing the issue for lack of activity
