### ISSUE TITLE
Maya Exporter: Animations and texture are not coming in exported .gltf and .babylon formats

### ISSUE THREAD

**Issue by ravip** [BabylonJS/Exporters#85]
Maya Exporter: Animations and texture are not coming in exported .gltf and .babylon formats

BabylonJSExporters version: 3.0.0
Original fbx model used: [original_fbx.zip](https://github.com/BabylonJS/Exporters/files/1689122/original_fbx.zip)

Exported GLTF:
[exported_gltf.zip](https://github.com/BabylonJS/Exporters/files/1689127/exported_gltf.zip)

Exported .babylon
[exported_babylon.zip](https://github.com/BabylonJS/Exporters/files/1689129/exported_babylon.zip)

BabylonJS Sandbox is used for testing purpose: http://sandbox.babylonjs.com/

**Comment by noalak** [comment]
Actually it's not a bug. Maya exporter is a work in progress.
Currently exporting: Geometry + Hierarchy
Soon: Materials
After that: Animations, Instances, Morph targets, Skeleton...

**Comment by ravip** [comment]
@noalak Thanks for the update, it helped us. I was curious like when can we get the full fledged Maya exporter for babylon and gltf.

**Comment by noalak** [comment]
@deltakosh about milestones

**Comment by deltakosh** [comment]
The plan is to have it by end of Feb

**Comment by ravip** [comment]
@deltakosh Thanks a lot for update.
