### ISSUE TITLE
Bake Animation Frames problem in v20200618.4

### ISSUE THREAD

**Issue by AlexIbanez16** [BabylonJS/Exporters#851]
Hello,

I'm currently working in Maya 2018.5 and have been using BabylonJS Exporter for several months now.

But since I updated to version 20200618.4, all of my glb exports have animation problems that previous versions didn't.

There's an example of animation bugs that I encountered. 
![Robot_Problem](https://user-images.githubusercontent.com/67418085/85709197-50590a00-b6e5-11ea-89fd-77b46d2f2465.png)

Here are the parameters I'm using.
![Exporter_Parameters](https://user-images.githubusercontent.com/67418085/85709199-518a3700-b6e5-11ea-8d87-f61ab3b9008e.png)

This only occurs with glb exports. When I export in babylon, everything works fine.

Thank you in advance,
Alexis

**Comment by Drigax** [comment]
Can you share your scene?

**Comment by AlexIbanez16** [comment]
Hello!

Here's two examples: https://we.tl/t-uFa2FA2iPN
I've put the Maya file and GLB export (I deleted textures to make it lighter).

Thanks

**Comment by AlexIbanez16** [comment]
I've found something! If I remove the animations groups, the GLB export works fine, but when I keep them, the animations don't work properly in the GLB export.

**Comment by sebavan** [comment]
Thanks a ton I bet this will help @Drigax  :-)

**Comment by Drigax** [comment]
@AlexIbanez16 can you help pinpoint the last working exporter version before this broke?

**Comment by AlexIbanez16** [comment]
@Drigax I think the last version I worked with before updating and the bugs was from April or May 2020.
A friend of mine had a December 2019 version and it worked well.

**Comment by Drigax** [comment]
Thanks, I figured out what was going wrong, we were only exporting a single animation track for a given node in the glTF export pass. Fix should be available shortly...
