### ISSUE TITLE
Morph targets are not exported on 3ds Max 2021

### ISSUE THREAD

**Issue by andreix2c** [BabylonJS/Exporters#855]
I try to export to GLTF a character which has a morph target for blinking and even though in the logs it says that the morph target is exported, it does not appear in the output GLTF file. The checkboxes "Export morph tangents","Export morph normals" and "Export tangents" are all checked.
Is it a bug or am I doing something wrong?

**Comment by Drigax** [comment]
Can you share a source scene?

**Comment by andreix2c** [comment]
[fbx.zip](https://github.com/BabylonJS/Exporters/files/4915862/fbx.zip)
I've attached the fbx file with the character.

**Comment by pandaGaume** [comment]
@andreix2C i can not find morph modifier into the scene, only animations with skeleton. Moreover Eyes are not linked to any blink animation... I'm on Max2021.

**Comment by pandaGaume** [comment]
@andreix2c I can not see the dragoblink  attached with animation on Max
![blink2](https://user-images.githubusercontent.com/22658224/98400085-bc6c5700-2063-11eb-83e6-d93a0dc85479.png)

**Comment by pandaGaume** [comment]
The Max interface for IIGameMorpher. GetMorphTarget(0) is returning a null reference, then the target is not processed (even if the count of target is set to 1). On this [line](https://github.com/BabylonJS/Exporters/blob/a385d71f7df04f0259c58946a47eca687f84a66d/3ds%20Max/Max2Babylon/Exporter/BabylonExporter.Mesh.cs#L515).

**Comment by pandaGaume** [comment]
@andreix2c I understand this is quite old issue, but it was not obvious to track. I finally find my way to rebuild automatically the morph target (the official way from max does not work at all) and I put in place an ugly (but functional) MaxScrip patch.
BTW, your original file does not use the "blink" morph in animation, so i put a dummy one in place.
Here the result.
[draco.zip](https://github.com/BabylonJS/Exporters/files/5879771/draco.zip)
Note the gltf file has still some validation issues that we may address in the near futur. 
I will continue tests on this skin & morph topic.
