### ISSUE TITLE
Max2Bablyon: Reuse same texture for both Opaque and Blend materials?

### ISSUE THREAD

**Issue by echadwick-wayfair** [BabylonJS/Exporters#859]
Can the exporter reuse a texture asset instead of creating separate textures for opaque vs transparent materials? 

![image](https://user-images.githubusercontent.com/40177036/88219044-fc333e00-cc2e-11ea-80a0-034452912955.png)

The example is two meshes, each with its own material. They both share the same set of textures, except the 2nd mesh (green wireframe) uses an additional transparency texture, and the material is set to Blend.

![image](https://user-images.githubusercontent.com/40177036/88219647-e8d4a280-cc2f-11ea-8c55-128b7e9a11de.png)

The exporter creates two baseColor textures, RGB and RGBA. This wastes file size and memory. Instead the exporter should detect when materials use the same baseColor input texture, then it should create a single RGBA and reuse it for both materials,

Exported:
![image](https://user-images.githubusercontent.com/40177036/88219178-37ce0800-cc2f-11ea-9629-ea538e1e8f6b.png)

Edited to reuse the same RGBA (note the size savings):
![image](https://user-images.githubusercontent.com/40177036/88219206-41f00680-cc2f-11ea-8a95-5baaf2d91182.png)

I manually edited the .gltf to remove the RGB-only texture; it validates OK and renders well.
![image](https://user-images.githubusercontent.com/40177036/88218957-d27a1700-cc2e-11ea-8264-daace27f65e6.png)

Max2Babylon v20200721.1
3ds Max 2020.3

Source files and exports:
[max2babylon-reuse-alphablend-png.zip](https://github.com/BabylonJS/Exporters/files/4962008/max2babylon-reuse-alphablend-png.zip)

Thank you!

**Comment by Drigax** [comment]
That would be a nice optimization, I'll currently put it in the backlog, especially if anyone wants to contribute this improvement.

**Comment by deltakosh** [comment]
Fancy doing a PR?

**Comment by pandaGaume** [comment]
Proposal could be to assign new BaseAlphaPair (which is BasePath and AlphaPath) to the BabylonTexture during 
`ExportBaseColorAlphaTexture` on BabylonExporter.Texture #l333
Then use same pattern as GLTFExporter.Material.Optimizer to merge [base] key with the first of [base]_[any] texture (depending the order of arrival)
However, Question is : do you aware of any transformation may occur on Bitmap in the mean time (i do not find any) ???

**Comment by pandaGaume** [comment]
@echadwick-wayfair Please review the 3D file to verify the optimized and the non optimized version
[results.zip](https://github.com/BabylonJS/Exporters/files/5397903/results.zip)

**Comment by pandaGaume** [comment]
@Drigax @deltakosh I beleive we need to expose a parameter to choose over optimization or not... if yes, how to you want to expose the parameter ? in the main panel ?

**Comment by pandaGaume** [comment]
Let's do some tests guys.
