### ISSUE TITLE
Problems with glTF export, bone animation and scale factor

### ISSUE THREAD

**Issue by qualmon** [BabylonJS/Exporters#869]
Bone animation gets messed up when I used a scale factor of 100.
The animation was a simple rotation of shoulder joint just for testing.

I instead scaled my mesh+skeleton and exported to glTF with scale factor=1 and it worked better.

Some screenshots and further info can be found here:
https://forum.babylonjs.com/t/maya-babylon-maya-exporter-issues/13514

**Comment by deltakosh** [comment]
pinging @thomlucc

**Comment by JasXSL** [comment]
I'm still having this issue on version 20210607.3 max 2017. Any scale factor other than 1 causes weird strechiness.

Scale factor 1:
![](https://i.gyazo.com/3f5b57156cda40f9105ac9829b65decf.png)

Scale factor 10:
![](https://i.gyazo.com/5091ed4aab6ad2e17204fc6f113eb3a0.png)

Settings:
![](https://i.gyazo.com/3b8eeedd58289774d0947d7c21f790d2.png)

No errors in the log.

**Comment by pandaGaume** [comment]
@JasXSL  Could you share a very simple repro MAX scene with us please, this give us the opportunity to spot on the issue faster. The previous issue was for maya.

**Comment by JasXSL** [comment]
Sure thing. Try this at 1 and 10 scale factor

[animation_test.zip](https://github.com/BabylonJS/Exporters/files/6644039/animation_test.zip)

**Comment by pandaGaume** [comment]
Published a PR for Max exporter, scale was duplicated at root level and at node level.
Regards

**Comment by pandaGaume** [comment]
Still some issue to address with the way of scale between Babylon and Gltf, expect a bit more delay for the merge.

**Comment by JasXSL** [comment]
Still having this issue on Max 2017 v20210811.2.
