### ISSUE TITLE
Maya2Babylon.ScriptToBabylon.doIt kFailure

### ISSUE THREAD

**Issue by efsjouw** [BabylonJS/Exporters#871]
Hi am getting this unexpected failure either with the MEL script or using python with mayapy (batch mode), can't really see what is going here.

----------------------------------------------

Note that this is just the end of the script

Python:

```
cmds.GenerateExportersParameter

parameters = [None] * 32

parameters[0] = output_path #DESTINATION PATH 
parameters[1] = "glb" #EXPORT FORMAT
parameters[2] = "" #TEXTURES FOLDER
parameters[3] = "1" #SCALE FACTOR
parameters[4] = "True" #WRITE TEXTURES
parameters[5] = "True" #OVERWRITE TEXTURES
parameters[6] = "False" #EXPORT HIDDEN OBJECTS
parameters[7] = "True" #EXPORT MATERIALS
parameters[8] = "False" #EXPORT ONLY SELECTED
parameters[9] = "False" #BAKE ANIMATION FRAMES
parameters[10] = "True" #OPTIMIZE ANIMATION
parameters[11] = "True" #OPTIMIZE VERTICES
parameters[12] = "False" #ANIMATION GROUP NON EXPORTED
parameters[13] = "False" #GENERATE MANIFEST
parameters[14] = "False" #AUTO SAVE SCENE FILE
parameters[15] = "True" #EXPORT TANGENTS
parameters[16] = "True" #EXPORT SKINS
parameters[17] = "True" #EXPORT MORPH TARGET
parameters[18] = "True" #EXPORT MORPH NORMALS
parameters[19] = "100" #TEXTURE QUALITY
parameters[20] = "True" #MERGE AO WITH MR
parameters[21] = "False" #DRACO COMPRESSION
parameters[22] = "False" #ENABLE KHR LIGHTS PUNCTUAL
parameters[23] = "False" #ENABLE KHR TEXTURE TRANSFORM
parameters[24] = "False" #ENABLE KHR MATERIALS UNLIT
parameters[25] = "False" #PBR FULL
parameters[26] = "False" #PBR NO LIGHT
parameters[27] = "False" #CREATE DEFAULT SKYBOX
parameters[28] = "" #PBR ENVIRONMENT
parameters[29] = "True" #EXPORT ANIMATIONS
parameters[30] = "False" #EXPORT ANIMATIONS ONLY
parameters[31] = "True" #EXPORT TEXTURES

cmds.ScriptToBabylon(exportParameters=parameters)
```

----------------------------------------------
Traceback (most recent call last):
  File "glb_gltf_export.py", line 135, in <module>
    cmds.ScriptToBabylon(exportParameters=parameters)
  File "<string>", line 2, in ScriptToBabylon
RuntimeError: Exception found:
Message --- (kFailure): Unexpected Internal Failure
Source --- openmayacs
StackTrace ---    at Autodesk.Maya.OpenMaya.MArgList.asStringArray(UInt32& index)
   at Maya2Babylon.ScriptToBabylon.doIt(MArgList argl)
   at Autodesk.Maya.OpenMaya.MPxCommand.SwigDirectordoIt(IntPtr args)
TargetSite --- Autodesk.Maya.OpenMaya.MStringArray asStringArray(UInt32 ByRef)

------------------------------------------------------

So the MEL script does work when in the Maya editor but in batch mode it gives me this message while calling it through python.

https://github.com/BabylonJS/Exporters/blob/master/Maya/MELScripts/exportScriptExemple.mel

````
mel.eval('source "./exportScriptExemple.mel"')
````

Error: Export cancelled: (kFailure): Unexpected Internal Failure

EDIT - I also realize I am not sure how to convert this line to python to test it out? What is even going on here, made a string array and then put the command in these quotes `? I can't figure out what they mean, it doesn't appear to be string.

````
string $parameters[] = `GenerateExportersParameter`;
````

**Comment by sebavan** [comment]
Could you check it with the maya folks as well ? It seems more related to the python/maya bits than the exporters as the script works fine from Maya itself. 

And my knowledge in this area is pretty pretty pretty thin ;-)

**Comment by efsjouw** [comment]
I asked on the forum, first thing I could think about though is that maybe the plugin uses some GUI function that is not available in batch mode.

**Comment by sebavan** [comment]
I do not think it does but this is really strange :-( @bghgary do you remember how we could call into it from the command line ? I feel so n00b with this part :-)

**Comment by efsjouw** [comment]
> I do not think it does but this is really strange :-( @bghgary do you remember how we could call into it from the command line ? I feel so n00b with this part :-)

Right now i use this eval state in python to call the .mel script, note that this is also my first time doing this stuff (both maya and python ;P)

So make a python script with:
mel.eval('source "./exportScriptExemple.mel"')

And then call it from command line with (mayapy needs to be in windows PATH):
mayapy yourscript.py

**Comment by bghgary** [comment]
I know almost nothing about this :-( Hopefully someone on the forum has done this before.

**Comment by efsjouw** [comment]
Nobody has ever tried to use the exporter in the command line? Seems like the most useful thing to me.

**Comment by pandaGaume** [comment]
According the script, you used OptimizeVertices = true. A bug was introduced into this during summer.
try your script without this option.

**Comment by pandaGaume** [comment]
This was fixed by previous PR on November. This Issue is not active since September.
