### ISSUE TITLE
glTF with KHR_texture_transform contains default values that shouldn't be written

### ISSUE THREAD

**Issue by bghgary** [BabylonJS/Exporters#872]
Repro:

1. Export a model with texture transform.
2. Look at the glTF.

Result:
```json
"KHR_texture_transform": {
    "offset": [
        0.0,
        0.0
    ],
    "scale": [
        30.0,
        -30.0
    ],
    "texCoord": 0
}
```

Expected:
```json
"KHR_texture_transform": {
    "scale": [
        30.0,
        -30.0
    ]
}
```

**Comment by deltakosh** [comment]
Max or maya or both?

**Comment by bghgary** [comment]
The model I have is exported with "babylon.js glTF exporter for Maya 2018 v20200617.6"

**Comment by bghgary** [comment]
I don't consider this a bug though since everything still works. It's just a minor annoyance.

**Comment by pandaGaume** [comment]
@bghgary
I beleive the code is located in this [method](https://github.com/BabylonJS/Exporters/blob/4348cb1f37aef82ec58233ebc36e6b39151cd1b0/SharedProjects/Babylon2GLTF/GLTFExporter.Texture.cs#L466)
 Is it reasonable to keep an empty KHR_texture_transform when all parameters are default ??
when default are 

```
"offset": [0.0,0.0],
"scale": [0.0,0.0],
"texCoord": `0`

```
In the case of removing the empty transformation, do you want to notify the user by a message such "KHR_texture_transform is selected but none of the parameters are set - discard transform"

Also there is 
`float angleDirect = -babylonTexture.wAng;`
which is unused.. do you want to keep it for futur ehancement or reference ??


In other hand, the default values SHOULD NOT beeing serialized thanks to the serialization logic into the [KHR_texture_transform](https://github.com/BabylonJS/Exporters/blob/4348cb1f37aef82ec58233ebc36e6b39151cd1b0/SharedProjects/GltfExport.Entities/GLTFMaterial.cs#L88) class 
_`public bool ShouldSerializesXXXXX()`_
but, as an example, regarding the array comparaison the [statement ](https://github.com/BabylonJS/Exporters/blob/4348cb1f37aef82ec58233ebc36e6b39151cd1b0/SharedProjects/GltfExport.Entities/GLTFMaterial.cs#L105)
`...this.offset != new float[] { 0f, 0f })`
will be always true, while array equality operators are not compare contents.

to solve both case we may use a kind of IsZero extension to test an array about filled with zero, and use it at creating the object and serializing it.
Direct way is also to use 
`Enumerable.SequenceEqual(A, B);`
but implies to create dummy array to test against...

**Comment by pandaGaume** [comment]
BTW, according to the following properties of texture into Hypeshade
![texture properties](https://user-images.githubusercontent.com/22658224/99558006-9039ca00-29c3-11eb-9dec-492abca041f9.PNG)
where do we find the scale property ??? And for info, actually the RotateUV is NOT propagated to the underlying Babylon model

**Comment by pandaGaume** [comment]
Finally, after code update, the following hypershade texture properties
<img width="331" alt="texture properties" src="https://user-images.githubusercontent.com/22658224/99560672-6b932180-29c6-11eb-96ec-f24f5c82d2a6.PNG">
lead to 
```
        "baseColorTexture": {
          "index": 0,
          "extensions": {
            "KHR_texture_transform": {
              "rotation": 3.14159274,
              "scale": [
                1.0,
                -1.0
              ],
              "texCoord": 0
            }
          }
        },
```
