### ISSUE TITLE
Exception raised during export. Node will be exported as dummy node. 

### ISSUE THREAD

**Issue by SPalaia** [BabylonJS/Exporters#873]
I am running Maya 2019 on 2 separate machines. A home computer and a work computer.

My home computer can export a glb with a rig and animation no problem but the work machine give me this:

Export started
Selected nodes full path
DAG: full
DAG: relevant
Exporting nodes
	locator1
	pCube1
		no morph targets
		mFnMesh.fullPathName=|locator1|pCube1|pCubeShape1
		Exception raised during export. Node will be exported as dummy node. 
Message: 
Object reference not set to an instance of an object. 

	pCube1
	Total meshes: 3
	No camera defined
	Total lights: 0
Exporting materials
Export animation groups
GLTFExporter | Exportation started
GLTFExporter | Exporting nodes
GLTFExporter | Exporting meshes
GLTFExporter | Exporting skins, lights and cameras
GLTFExporter | Exporting materials
GLTFExporter | Exporting Animations
GLTFExporter | Saving to output file
Export done in 0.29s
 

I have tried the simplest of exports, just a cube with a stingrayPBS material and its the same message. It makes me believe it isnt a model issue but an exporter / installation issue.  

.net framework is up to date and I have installed visual studio.

Does anyone have any ideas? Thank you in advance.

<img width="666" alt="ExporterWindow" src="https://user-images.githubusercontent.com/71730965/93934070-30d37c80-fce8-11ea-9916-2890464a4942.png">

<img width="1920" alt="ExporterIssue" src="https://user-images.githubusercontent.com/71730965/93933917-fc5fc080-fce7-11ea-8539-e91f2e8f9654.PNG">

**Comment by pnut** [comment]
This is the same as https://github.com/BabylonJS/Exporters/issues/874

In the latest release from September 17, the "Optimize Vertices" option prevents all geometry from being exported.
