### ISSUE TITLE
Maya Plugin - September 17 release 

### ISSUE THREAD

**Issue by IoanVulturar** [BabylonJS/Exporters#874]
Maya 2020 plugin - September 17 release - doesn't export geometry.
Instead it adds a dummy node. I also have locators exported and they look fine.

This is the error I received from Babylon.js Maya Exporter:
"Exception raised during export. Node will be exported as dummy node. 
Message: Object reference not set to an instance of an object.  "

I was trying this release because August 13 release was setting the pivot for every mesh, in the origin of the scene (0,0,0).

**Comment by pnut** [comment]
I'm finding that this happens specifically when the "Optimize Vertices" option is turned on.

**Comment by pnut** [comment]
attaching a repro file (maya file with a single sphere)
[sphere.ma.zip](https://github.com/BabylonJS/Exporters/files/5300840/sphere.ma.zip)

**Comment by IoanVulturar** [comment]
Thanks!
I left only option "Export only selected" checked  and the mesh is exported correctly now.
But the pivot is reset for every mesh to the origin.

**Comment by IoanVulturar** [comment]
Just tested October release exporter for Maya and it's still resetting mesh pivot to origin. I need it to keep its original pivot because the application uses this pivot to put together different gltf files

**Comment by vsnappy** [comment]
> I'm finding that this happens specifically when the "Optimize Vertices" option is turned on.

I'm seeing **all** of my exports fail when this "Optimize Vertices" is checked.  Unfortunately, leaving it off creates significantly larger glb files.

**Comment by pandaGaume** [comment]
@vsnappy i just published a PR for the purpose an hours ago, the time it beeing introduce into release and you will be able to continue enjoying the exporter. Thanks for your support.
