### ISSUE TITLE
Expose settings for Draco

### ISSUE THREAD

**Issue by kyoa** [BabylonJS/Exporters#878]
I export a glb file from 3DS Max with BabylonJS tool, the geometry is a bit out of shape after using Draco compression.The shape is totally fine without Draco, but the file size is too big,almost 7 times bigger.
The major problem here is the default property draco.quantizePositionBits in BabylonJS plugin is too low, and there isn’t an option to modify.
I change this to 20, then everything is fine.
The compression level does not affect the geometry at all even set to 10.
BTW, model export from this plugin also got normal problem, the color looks different from FBX file and not good.I’m using FBX now, so I didn’t look into this.

**Comment by pandaGaume** [comment]
As far i know, we have this default parameters to pass to gltf-pipeline which perform Draco Compression.

compressionLevel default is 7 
quantizePositionBits  default is 14
quantizeNormalBits default is 12
quantizeColorBits default is 8
quantizeGenericBits default is 12
unifiedQuantization default is false.

But they are not exposed yet

While we have several parameters, maybe it's might be located into specific "Draco" panel, which will be enabled when hitting draco checkbox ?

**Comment by bghgary** [comment]
For reference, the forum thread: https://forum.babylonjs.com/t/geometry-looks-bad-after-using-draco-compression/14884

**Comment by cptSwing** [comment]
I came here just now for this exact same request and voilá there it is, haha
