### ISSUE TITLE
Max2Babylon Exporter - Mesh is being exported with too many verticies

### ISSUE THREAD

**Issue by Chase-Reid** [BabylonJS/Exporters#888]
### CONDITIONS
- Autodesk 3ds Max 2021
- Babylon Max Exporter v1.6.0

### STEPS TO REPRODUCE
1. Create a sphere
2. Press 7 on the Viewport to see the Vertex count for the sphere mesh
3. Open the Babylon Exporter Window
4. Toggle on EXPORT ONLY SELECTED
5. Click on EXPORT & RUN
6. In the babylon sandbox editor expand the scene graph and select the sphere mesh
7. In the inspector window and view the vertex count

### RESULT
Mesh is being exported with too many verticies

![3dsMaxVertCount](https://user-images.githubusercontent.com/26173435/98316164-b9ebfd80-1f8e-11eb-95f9-29182427b064.JPG)
![SandboxBabylonVertCount](https://user-images.githubusercontent.com/26173435/98316172-bd7f8480-1f8e-11eb-8f49-e813c2bc8a4f.JPG)

**Comment by Chase-Reid** [comment]
I discovered the TRY TO OPTIMIZE VERTICIES toggle in the Babylon Properties Menu.

![TryToMergeText](https://user-images.githubusercontent.com/26173435/98316700-bf961300-1f8f-11eb-8c90-42fe68f391f9.JPG)

I see why the "TRY" text was added. It does lower exported vertex count but not the number specified in the 3dsMax viewport. **Can we expose a tolerance slider for how aggressive this feature attempts to optimize verticies?**

![TryToMerge](https://user-images.githubusercontent.com/26173435/98316618-9bd2cd00-1f8f-11eb-99f1-5a002d6d2da5.JPG)

**Comment by pandaGaume** [comment]
Actually, by default the vertices are duplicated by faces (3 times the number of triangle). When trying to optimize, comparaison is done using XYZ, UV1, UV2, weights and colors.  It might be difficult to introduce kind of tolerance slider without changing the final result. You might use draco compression for the purpose.

**Comment by Chase-Reid** [comment]
@pandaGaume Thank you for the response.

We will look into Draco
