### ISSUE TITLE
3ds Max Exporter: Could not able to export all animation frames using babylon exporter of 3d Max

### ISSUE THREAD

**Issue by ravip** [BabylonJS/Exporters#89]
3ds Max Exporter: Could not able to export all animation frames using babylon exporter for 3d Max.

Used FBX has 0 to 8000 animation frames but only small part of animation got exported in final .babylon file.

Used FBX Model: 
[GE FBX_max.zip](https://github.com/BabylonJS/Exporters/files/1695224/GE.FBX_max.zip)

Exported (.babylon + texture) files:
[ge6.zip](https://github.com/BabylonJS/Exporters/files/1695231/ge6.zip)

Tested exported (babylon + texture) using sandbox: http://sandbox.babylonjs.com/

**Comment by ravip** [comment]
Hi Team,

I could able to get away from this issue by using some settings. Here the the document with proper steps to export 3D model with animation using 3ds 2017 babylon/gltf plugin.
[steps_to_3dmax_model_export_to_babylon_gltf.pdf](https://github.com/BabylonJS/Exporters/files/1698316/steps_to_3dmax_model_export_to_babylon_gltf.pdf)

Please do not work on this issue. Thanks all for your valuable support.

Regards,
Ravi

**Comment by deltakosh** [comment]
Wonderful! Would you be kind enough to add this information to our Doc?

**Comment by ravip** [comment]
@deltakosh I would definitely like to add this information to doc as specified. Could you please help me with initial steps how can I start adding this. I have tried checking out wiki but its not in editable mode for me.

**Comment by deltakosh** [comment]
Sure, here is some help: http://www.html5gamedevs.com/topic/16365-contributing-to-documentation-101/

**Comment by ravip** [comment]
![time_configuration_window](https://user-images.githubusercontent.com/714971/36024243-296ae318-0db5-11e8-91c3-53ba8bfb849e.jpg)
![3ds_babylon_plugin_properties_window](https://user-images.githubusercontent.com/714971/36027052-a4bc1816-0dbf-11e8-8fc7-cc8364ece708.jpg)
![babylon_exporter](https://user-images.githubusercontent.com/714971/36027124-e9cb5dc2-0dbf-11e8-8a61-4b6909bd5377.jpg)

**Comment by deltakosh** [comment]
What are these screenshots?
