### ISSUE TITLE
Mirror not working with Transform option

### ISSUE THREAD

**Issue by noalak** [BabylonJS/Exporters#90]
Mirror feature can be applied to Transform or Geometry.

It does work properly for Geometry but not for Transform.
The mirrored mesh (with Transform option) must be ResetXForm + normal flip to make it work.

![mirrors](https://user-images.githubusercontent.com/20560340/35813610-5824feba-0a94-11e8-969b-18693078f00c.png)
![mirrors2](https://user-images.githubusercontent.com/20560340/36147487-b7a14d38-10b8-11e8-9861-56f0817eb041.png)
Left to right: Original, Mirrored Transform, Mirrored Geometry

Max file + babylon file:
[Mirrors.zip](https://github.com/BabylonJS/Exporters/files/1695747/Mirrors.zip)

**Comment by Selmar** [comment]
We had this issue as well. The artist in question assumed this was why his mesh wasn't working and fixed it by doing exactly what you said. He told me it is a very common thing that it exports incorrectly for many exporters.

**Comment by deltakosh** [comment]
Do we have a way to automatically fix it

**Comment by Selmar** [comment]
My best guess is that this value is simply stored elsewhere and/or IGameNode does not take it into account (whether by accident or on purpose, I don't know).

Internally, mesh and transform matrices are probably separate. There are things like object offsets (for scale as well). But perhaps getting the transform in a different way is sufficient, e.g as described in [this pdf](http://dl3d.free.fr/resources/3DSMAX_SDK_DavidLanier.pdf):
```
Matrix3 parentTM  = node->GetParentTM(ip->GetTime()); 
Matrix3 nodeTM    = node->GetNodeTM(ip->GetTime()); 
Matrix3 localTM   = nodeTM*Inverse(parentTM); 
```

Some debugging to look at all the values and find out where this change is actually stored is probably required. Unless someone knows! :-P

**Comment by deltakosh** [comment]
If we can't fix it we need to document the workaround then

**Comment by tkazik** [comment]
I guess @Selmar's idea sounds good. Maybe checking that the rotation matrix is +1 or something similar.

**Comment by deltakosh** [comment]
documentation updated

**Comment by tkazik** [comment]
Sure, there isn't a data-driven approach, that fixes this one?

**Comment by tkazik** [comment]
This already sounds promising:

http://help.autodesk.com/view/3DSMAX/2018/ENU/?guid=__developer_3ds_max_sdk_features_modeling_transformation_and_rotation_emulating_reset_transform_and_re_html

I am sure there is something similar for the normals as well and then we just have to check if the object is sound (maybe by looking at some negative scale values) and apply the fix or not.

What do you think?

**Comment by deltakosh** [comment]
I'm not opposed to do a test. Fancy trying to implement it?

**Comment by tkazik** [comment]
Well, I can have a look at it...my gut feeling tells me that it should be solvable somehow, but it's certainly not trivial.
The mean thing about this artifact is, that it only shows up at export time and there is no way to figure out which objects are affected in 3ds max beforehand. Or do you have an idea how to detect these?

**Comment by deltakosh** [comment]
No idea unfortunately. Only the original creator of the mesh knows I guess

**Comment by tkazik** [comment]
After a few hours of debugging 3ds max, I finally got some insight:
If using the mirror tool with the transform option in 3ds max, the new transform is actually in a lefthanded system: The determinant of the rotation matrix is -1. Thus, we now have a way to determine, which meshes are "corrupt".

Furthermore, I discovered this [exporter,](https://github.com/paulvortex/MaxDpMd3Exporter) that also provides a fix for the issue (change the winding order):

```
Matrix3 tm = node->GetObjTMAfterWSM(time);
if (DotProd(CrossProd(tm.GetRow(0), tm.GetRow(1)), tm.GetRow(2)) < 0.0) {
    ExportWarning("Object '%s' is mirrored (having negative scale on it's transformation)", node->GetName());
    for (i = 0; i < (int)vTriangles.size(); i++) {
        put32(vTriangles[i].b, file);	// vertex index
        put32(vTriangles[i].c, file);	// for 3 vertices
        put32(vTriangles[i].a, file);	// of triangle
      }
} else {
    for (i = 0; i < (int)vTriangles.size(); i++) {
        put32(vTriangles[i].a, file);	// vertex index
        put32(vTriangles[i].c, file);	// for 3 vertices
        put32(vTriangles[i].b, file);	// of triangle
    }
}
```

I am not yet sure, whether I would prefer to use `tm = node->GetNodeTM(time)` instead of `tm = node->GetObjTMAfterWSM(time)`.
Also, I haven't yet figured out, how to implement that in the C# interface of this exporter. Can you give me some directions? Thx!

PS: Would you mind reopening this issue? :)

**Comment by deltakosh** [comment]
Sure thing!
I let @noalak chime in but this looks like a feasible update

**Comment by tkazik** [comment]
I decided to have a look at this exporter's code. The compilation runs nicely, however the `GLTFExport.dll` does not appear. My solution explorer looks like this (removed all versions except 2018):

![solution_explorer](https://user-images.githubusercontent.com/15689124/36123568-68b05342-104d-11e8-8cfb-8b0761ff60d8.png)

In the output path, I find the following files (`GLTFExport.dll` is lacking):

![gltf_dll_missing](https://user-images.githubusercontent.com/15689124/36123600-8494dc04-104d-11e8-8da1-42d5422b9c96.png)

What do I have to do in order to get the missing .dll compiled? Thx!

**Comment by noalak** [comment]
GLTFExport.dll file was created in previous versions of the exporter.
It's no longer the case so you are good to go!

**Comment by noalak** [comment]
@tkazik You can update the BabylonExporter.Mesh.cs file.
You could add mirror checking line 360 after indices have been set.
About node transform matrix, you have an example line 845 in the exportTransform method.
From a node in max api, you can get the local, object or world transform matrices (Matrix4). Api provides method to extract a matrix3 from a matrix4.

Hope it helps!

**Comment by noalak** [comment]
However fixing winding order would not fix the whole issue.

![mirrors2](https://user-images.githubusercontent.com/20560340/36150702-d6fdbe30-10c4-11e8-8705-dcf22040f7f6.png)

Babylon file: [Mirrors2.zip](https://github.com/BabylonJS/Exporters/files/1719935/Mirrors2.zip)

The axis are also inverted.

**Comment by tkazik** [comment]
@noalak thx for the test and the hint for the implementation.
I will also give it a try. However, I am struggling a bit with the setup for debugging.
If starting the debugger with the following setup, I get an crash-report of 3ds max shortly after launching.

![props_build](https://user-images.githubusercontent.com/15689124/36178010-dfc03c2a-1117-11e8-81b6-25813423bd60.png)

![props_debug](https://user-images.githubusercontent.com/15689124/36178012-e26a9696-1117-11e8-88bf-73b1ddf9488c.png)

Any hints and tips? Thx!

**Comment by noalak** [comment]
No i don't use it. Using RaiseError instead as a console.log

**Comment by tkazik** [comment]
No debugger?!
I managed to use it with the "attach to process" option. However, somehow the debugger seems pretty unstable as some values are just changing on the fly!
One good thing though: The `worldMatrix` on line 530 in BabylonExporter.cs has two properties, which make it fairly easy to discover, which objects are flipped: Either `Determinant` or  `Parity` can be used, as they both result in being -1 for a mirrored object (with transform option).

**Comment by Selmar** [comment]
It looks to me like you won't have to invert the winding order, just flip the axis of the vertex positions. Just take a look whether the normals are correct (I think they will be).

You will also need to verify if models with a negative scale on one or three axis still export correctly (they also have a negative determinant).

For debugging, I use attach to process as well, without any problems so far!

**Comment by tkazik** [comment]
Thx for your input, @Selmar ! Time is a bit sparse right now, but I will eventually have a closer look.
Regarding the (intended) negative scale: I just ran a small test sample with negative scale along one axis on object level: The result looks similarly wrong as the one obtained from mirroring (with transform option). Is this working properly with your models?

**Comment by Selmar** [comment]
We don’t actually support that feature in our games, so I don’t know. It just seems like something that should work as well. It may very well be that the viewer doesn’t handle it correctly either, but I have not investigated that. I guess @noalak knows more about that.

De : tkazik [mailto:notifications@github.com]
Envoyé : Tuesday, February 20, 2018 09:37
À : BabylonJS/Exporters <Exporters@noreply.github.com>
Cc : Selmar <selmar21@hotmail.com>; Mention <mention@noreply.github.com>
Objet : Re: [BabylonJS/Exporters] Mirror not working with Transform option (#90)


Thx for your input, @Selmar<https://github.com/selmar> ! Time is a bit sparse right now, but I will eventually have a closer look.
Regarding the (intended) negative scale: I just ran a small test sample with negative scale along one axis on object level: The result looks similarly wrong as the one obtained from mirroring (with transform option). Is this working properly with your models?

**Comment by tkazik** [comment]
Found this in the docs:

![parity](https://user-images.githubusercontent.com/15689124/36414311-23197482-1622-11e8-8c23-187634caa31c.png)

Would be interesting to look under the hood of the renderer.

**Comment by Selmar** [comment]
This is expected behavior of a renderer. This parity boolean is basically telling you the sign of the determinant. I mentioned the viewer, because it's easy to forget, but the spec defines it:

```
Implementation Note: If the determinant of the transform is a negative value, the winding order of the mesh triangle faces should be reversed. This supports negative scales for mirroring geometry.
```

**Comment by deltakosh** [comment]
To set a Matrix you can use the setPreTransformMatrix API
Or we can also use the decompose API to break your matrix into position quaternion and scaling

**Comment by tkazik** [comment]
The matrix cannot be broken in to position, quaternion and scaling: No quaternion can represent a rotation matrix that contains reflections (axis flipping), as these 3x3 matrices are strictly speaking no valid rotation matrices anymore (determinant -1).
However, your first suggestion with ´setPreTransformMatrix´ sounds interesting. Just read your [recent announcement](http://www.html5gamedevs.com/topic/35354-setpivotmatrix-setpretransformmatrix/) and I will have a look at it.

**Comment by Selmar** [comment]
When a node is targeted for animation, the gltf spec enforces TRS values and not matrices.

Decomposition is still possible if there is negative scale. Consider the fact that a rotation matrix is basically three vectors that represent a coordinate system. You can see that you can simply flip one of those vectors together with the extracted scale vector to get correct TRS values.

Note: it may be that any animation data targeting this node will also have to be transformed in the same way for animations to work correctly.

**Comment by tkazik** [comment]
Finally:

![mirror_working](https://user-images.githubusercontent.com/15689124/36937020-54d01582-1f0d-11e8-98f7-a58eadb23c66.png)


Thank you very much for your inputs!
@deltakosh: Using `decompose` as you suggested works perfectly to extract the correct TRS values.
@Selmar: Animation data is now also decomposed the same way and they seem to be fine.

Interested in a PR?

**Comment by deltakosh** [comment]
For sure!
