### ISSUE TITLE
Using Multi-File Export insertion point is reset to the center of the figure

### ISSUE THREAD

**Issue by maxstefaniv** [BabylonJS/Exporters#904]
Hello this looks like an issue, maybe I just cant find the configuration option but for testing I am using the hotel.rvt file from the Autodeks Revit API tutorial. There I made 8 room shapes. And the idea is to export them as .gltf files separately and then when imported in other environment they will be blaced the same way as they were in 3ds Max. 
If I select each Room Shape separately and export them they stay in the same relative position to origin as they were on the blueprint. When I use the Multi-File export all 8 rooms have their insertion point reset to their center so consecutive insertion lets say in Blender results in obtaining all the rooms in the same place. 
This is how the rooms are placed in 3ds Max.
![image](https://user-images.githubusercontent.com/62515255/101172386-6928fc80-3641-11eb-9f66-ede1a6c226d7.png)
Exporting one by one with the option "Export only selected" and then importing in Blender:
![image](https://user-images.githubusercontent.com/62515255/101172566-9d9cb880-3641-11eb-9b7d-c29f3cf9bb1d.png)
Finally exporting with the Multi-File Export and then importing in blender:
![image](https://user-images.githubusercontent.com/62515255/101172767-e2c0ea80-3641-11eb-87ac-4f4c6ba1afa6.png)
Being able to do Multi-File Export but keeping the same reference point for further insertion would allow to export components partially and separately and being able to rebuild the same figure partially or completely. In my case I am interested to load separate gltf to a web so their positions would recreate the same scene.
Are you considering to implement that as a possible improvement? I am pretty new in this matter, at least tell me in which .cs file I should look to try and implement this functionality.

Thank you very much.

**Comment by pandaGaume** [comment]
It's an ehancement while other user may want to re-center each of selected item. We might introduce a check box to "reset position" for each of selected item into the multi-export dialog.

**Comment by WVNicolayeff** [comment]
Please absolutely keep the re-centering in! I just had to export a 24 piece wall kit that our engine requires centered pivots on, and the multi-export feature as-is worked wonderfully!

**Comment by pandaGaume** [comment]
@WVNicolayeff  we will NOT change the actual behavior, only expose an option to keep object position. If you have suggestions on the topic you're very welcome.

**Comment by pandaGaume** [comment]
Introduced a Keep pos flag. This one is unchecked (false) by default. So existing behavior is NOT changed.
![image](https://user-images.githubusercontent.com/22658224/118146336-c99d4080-b40e-11eb-8c9d-ad4c4ea354a5.png)
