### ISSUE TITLE
Maya : Backface culling reset when exporting

### ISSUE THREAD

**Issue by AlexIbanez16** [BabylonJS/Exporters#913]
Hello,

I'm using the Maya 2019 Exporter 20201214.2 version of the exporter, and I noticed that everytime I export a mesh with the backface culling disabled, it resets. So I'm unable to turn it off and thus unable to have doublesided faces on my meshes.

Here are the parameters I use when exporting. But I doubt it's the problem since I used previous version of the exporter with the same settings and didn't have this problem.
The shader doesn't affect the bug since it happened with lambert and stingray pbs alike.

![20201222_BabylonJS-Exporter-settings](https://user-images.githubusercontent.com/67418085/102915909-e1d1ea80-4482-11eb-9902-7a288536afc6.png)

I've also linked you the log of the export, if it can help.

Thank you in advance,
Alexis

[20201222_Backface-culling-problem_log.txt](https://github.com/BabylonJS/Exporters/files/5731191/20201222_Backface-culling-problem_log.txt)

**Comment by pandaGaume** [comment]
Hello, could you elaborate on "it resets" and the way to reproduce. Thanks.

**Comment by AlexIbanez16** [comment]
Well, I untick the box of the Backface Culling Option, and when I launch the export, it automatically ticks it back on and exports with backface culling.

![2020-12-23 18_53_33-Hypershade](https://user-images.githubusercontent.com/67418085/103024545-56bf2600-4550-11eb-9253-2a51c5e170ae.png)

I can replicate it with every geometry I tried.

**Comment by pandaGaume** [comment]
@AlexIbanez16 Thank's for the info, we will have a look on it.
