### ISSUE TITLE
Max2Babylon: emissiveFactor VALUE_NOT_IN_RANGE

### ISSUE THREAD

**Issue by echadwick-wayfair** [BabylonJS/Exporters#919]
Here's a fun one. 

Max2Babylon exports an emissiveFactor as 3.14159274 when a Physical Material has only an Emissive at 1.0 and using the color white. 

Repo example attached.
[2020-12-30_emissiveFactor.zip](https://github.com/BabylonJS/Exporters/files/5755757/2020-12-30_emissiveFactor.zip)

Max2Babylon v20201223.2
3ds Max 2020.3

`{
  "uri": "emissiveFactor.glb",
  "mimeType": "model/gltf-binary",
  "validatorVersion": "2.0.0-dev.3.3",
  "validatedAt": "2020-12-30T21:13:34.974Z",
  "issues": {
    "numErrors": 3,
    "numWarnings": 0,
    "numInfos": 2,
    "numHints": 0,
    "messages": [
      {
        "code": "VALUE_NOT_IN_RANGE",
        "message": "Value 3.14159274 is out of range.",
        "severity": 0,
        "pointer": "/materials/0/emissiveFactor"
      },
      {
        "code": "VALUE_NOT_IN_RANGE",
        "message": "Value 3.1415925 is out of range.",
        "severity": 0,
        "pointer": "/materials/0/emissiveFactor"
      },
      {
        "code": "VALUE_NOT_IN_RANGE",
        "message": "Value 3.14159322 is out of range.",
        "severity": 0,
        "pointer": "/materials/0/emissiveFactor"
      },
      {
        "code": "UNUSED_OBJECT",
        "message": "This object may be unused.",
        "severity": 2,
        "pointer": "/meshes/0/primitives/0/attributes/TEXCOORD_0"
      },
      {
        "code": "NODE_EMPTY",
        "message": "Empty node encountered.",
        "severity": 2,
        "pointer": "/nodes/1"
      }
    ],
    "truncated": false
  },
  "info": {
    "version": "2.0",
    "generator": "babylon.js glTF exporter for 3dsmax 2020 v20201223.2",
    "resources": [
      {
        "pointer": "/buffers/0",
        "mimeType": "application/gltf-buffer",
        "storage": "glb",
        "byteLength": 3264
      }
    ],
    "animationCount": 0,
    "materialCount": 1,
    "hasMorphTargets": false,
    "hasSkins": false,
    "hasTextures": false,
    "hasDefaultScene": true,
    "drawCallCount": 1,
    "totalVertexCount": 96,
    "totalTriangleCount": 32,
    "maxUVs": 1,
    "maxInfluences": 0,
    "maxAttributes": 3
  }
}`

**Comment by pandaGaume** [comment]
Well, this value is comming from 
`materialNode.MaxMaterial.GetSelfIllumColor(0, false)`
which is an API of Max SDK.
However 3.14, which is PI, is a known value for Luminance as Apostlib Unit (which is obsolete) where 3.14 asb = 1cd/m2 ( the SI unit of candela per square meter).
Also another currently used unit is lambert(L) which is 1/PI candela per square centimeter

GLTF enforce Emissive factor to be of range [0,1] but do not state on the "physical" meaning in term of unit.
`"items": {
                "type": "number",
                "minimum": 0.0,
                "maximum": 1.0
            }`

3DSMax also enforce Emissive factor to be of range [0,1] but do not state on the "physical" meaning in term of unit.
It's appear that under Max SDK Luminance is computed on the range of [0,PI].

Question is : did the luminance is the correct value to use as emissive Factor? 
If yes we may think the value as Lambert and divide the value by PI
`materialNode.MaxMaterial.GetSelfIllumColor(0, false).ToArray().Select(v=>v/Math.PI).ToArray()`

@bghgary  could you give us your opinion ?

**Comment by bghgary** [comment]
Hmm, this one is interesting. The emissive factor in glTF was unintentionally clamped to one when originally written. See here: https://github.com/KhronosGroup/glTF/issues/1083. Lacking a unit is also something mentioned in the thread. I'm not sure what the right solution is here. A couple of options:

1. Clamped the value to 1.0
2. Divide by PI

> 3DSMax also enforce Emissive factor to be of range [0,1] but do not state on the "physical" meaning in term of unit.
> It's appear that under Max SDK Luminance is computed on the range of [0,PI].

I think you are saying that the 3DSMax UI enforces the factor to be 0 to 1 but the SDK returns 0 to PI? What does the SDK return if the UI is set to 1?

**Comment by pandaGaume** [comment]
Max UI Emission factor is about [0,1] 
<img width="263" alt="emission" src="https://user-images.githubusercontent.com/22658224/103568198-739b1800-4ec5-11eb-86b4-1c8d35dc0dcb.PNG">
and 
`GetSelfIllumColor()`
is returning a Self Illumination color [0,PI] which seem to be the result of an "opaque" formula  involving factor, luminance, color and heat

**Comment by bghgary** [comment]
Does changing the units or temperature settings change the mapping?

**Comment by pandaGaume** [comment]
We can not change the units into [Physical material](https://knowledge.autodesk.com/support/3ds-max/learn-explore/caas/CloudHelp/cloudhelp/2021/ENU/3DSMax-Lighting-Shading/files/GUID-C1328905-7783-4917-AB86-FC3CC19E8972-htm.html), emission group.
"The Physical Material supports an emissive component, additive light on top of other shading. Emission identity is defined by the weight and color multiplied by the luminence, and also tinted by the Kelvin color temperature (where 6500=white)."
Seems the formula is given a [0,PI] value for each rgb component, then divide by PI seems the best strategy so far. I will try to find the c++ source code responsible of that.
