### ISSUE TITLE
Issue with installer BabylonJS Exporter for Maya

### ISSUE THREAD

**Issue by Flamee1** [BabylonJS/Exporters#921]
Installer doesn't seem to open after opening, am running window 7 64 bit. Maya 2020, most recent version. 

https://gyazo.com/e79a7a7ee7eb09cc0e1c7298cd65e11e

Tried the manual installation with /bin .dll, NET and AET in their specific folders. But didn't have much luck, something along the lines that line 64, within the node didn't load. The addon did show at the top of my Maya toolbar. 

Will try the /myDocuments way of installing the plug in next by creating a folder /plugin, /scips/ ect.

**Comment by Flamee1** [comment]
Hey, I can't right now, I have a lot of university deadline.
________________________________

**Comment by bghgary** [comment]
Okay, I'm closing this for now. If you can repro with Windows 10, we will investigate.
