### ISSUE TITLE
Error when trying to install BabylonJS Exporter for 3dsMax 2021

### ISSUE THREAD

**Issue by ThomasBoute** [BabylonJS/Exporters#922]
I have a problem installing BabylonJsExporter for 3dsMax 2021 from Installer.
I always get this error (Can't download the files.)
![issueBablylonJsExporter3dsMax](https://user-images.githubusercontent.com/43601556/104465962-f2264280-55b4-11eb-8e81-093031cd5828.jpg).

I tried the manual installation also, copying the dlls in bin/assemblies but the babylon exporter tab doesn't appear in 3dsMax (next to the help tab).

I didn't have this pb with 3dsMax 2020 and the babylon plugin.

Any issue?

Thank you

**Comment by ThomasBoute** [comment]
Thank you, the last version fixed the installation issue!

But there's no export button to export!
![image](https://user-images.githubusercontent.com/43601556/104563209-a83b6c00-5649-11eb-8320-4554eb57ec90.png)

**Comment by Flamee1** [comment]
How did you thread get a instant reply, mines still sitting, instead of using this software I converted to FBX format then to GLB, did waste 2 days of work time trying to get this software to work but we move

**Comment by ThomasBoute** [comment]
With a previous version for 3ds max 2020, it was working for me.
It seems to be a display issue as reported in this thread.
https://forum.babylonjs.com/t/3ds-max-export-console/11040/37

Were your materials & textures still there after conversion from Fbx to glTF? If so, which converter did you use?
Thanks for your answer and help!

**Comment by pandaGaume** [comment]
Hi, the form was designed using 1920x1200.

**Comment by ThomasBoute** [comment]
Thank you Guillaume for your answer. I don't have the same screen as yours with 1600*900 ...
I will try with higher resolution.

Have a nice day

**Comment by ThomasBoute** [comment]
It's working when I connect my pc on my TV ;)

**Comment by pandaGaume** [comment]
@ThomasBoute  i will have a discussion with the team about this issue. However 1600*900 seem low res for 3DSMax ? is it usable ?

**Comment by ThomasBoute** [comment]
I don't know, I only get scenes from graphists and convert them to glTF ;) 
But, it seems usable. I need to get more into it as the exporter doesn't export my materials and textures from my scenes and I need to understand why.
Have a nice weekend

**Comment by pandaGaume** [comment]
Send me a simple scene with this material and texture issue (if disclosable) and i can get a look on it.

**Comment by ThomasBoute** [comment]
Thank you for your help.
I think I got my answer in another issue.
It's a scene with Corona materials with textures and it seems that it's not supported yet (I know it's a lot of work to make all materials work since all renderers work differently for materials).
https://github.com/BabylonJS/Exporters/issues/490

**Comment by pandaGaume** [comment]
@ThomasBoute  Feel free to make a PR on the Corona Topic. In the mean time let's continue this discussion on the forum. Thank. G.
