### ISSUE TITLE
Set material environmentIntensity in 3DS Max 

### ISSUE THREAD

**Issue by supershwa** [BabylonJS/Exporters#923]
Is there a way to set the material's environmentIntensity to 0 in 3DS Max before exporting, or do I need to hand-code this after loading the mesh?

**Comment by pandaGaume** [comment]
environmentIntensity is hardcoded to 1.0f and not accessible in 3DSMax.

**Comment by pandaGaume** [comment]
@supershwa after discussing with the team, we may add this to futur ehancement.  Please do not hesitate if you want participate, through PR or user point of view recommandations.

**Comment by Drigax** [comment]
@pandaGaume agreed, we'll have to add this as a per-material custom parameter, similar to our transparency settings.

**Comment by pandaGaume** [comment]
@supershwa i just published a PR about this. It'll be merge shortly i guess.
