### ISSUE TITLE
[3ds max] Export does not use the IDs defined on the multi-sub material.

### ISSUE THREAD

**Issue by ogmasoul3d** [BabylonJS/Exporters#926]
### This is how the material Assignment should look..
![3dsmax_viewport_expected look](https://user-images.githubusercontent.com/136207/106153243-9fd14e00-617e-11eb-9b65-39dd100a1084.png)

### This is the material assignment I get on export to glTF
![Incorrect material assignment on gltf export](https://user-images.githubusercontent.com/136207/106153297-af509700-617e-11eb-9260-dd0d9b7e53ce.png)

![materialNodes_graph](https://user-images.githubusercontent.com/136207/106153383-c7281b00-617e-11eb-83c5-482a8406c114.png)
### This is the two multi-sub materials that I have assigned. The first one gets exported as expected but the second one visualizes the problem.
 It looks like that you are assuming that a multi-sub material is just an array and the first item in the multi-sub material is id:1

### When I do maxscripts and work with multi-sub materials I always ask the multi-material to give me its [materialIDList](http://help.autodesk.com/view/3DSMAX/2019/ENU/?query=materialIDList)

That property is exposed in maxscript.. not sure if it is in max.net.
I have two multisub materials.. both containing 4 materials..
![Material_ShowingIDs](https://user-images.githubusercontent.com/136207/106152204-75cb5c00-617d-11eb-9e0f-fd09f357603d.png)

If you look in the bottom one.. I have set the First material in the multi-sub material to use ID:4
and if I run this in maxscript,with objects using that multimaterial selected,
```
m = $.material
m.materialIDList
```

I get this respons:
```
#Multi/Sub-Object:INCORRECT EXPORT.. LOOK AT THE IDS(Physical Material:RED, Physical Material:YELLOW, Physical Material:GREEN, Physical Material:BLUE)
#(4, 3, 2, 1)

--if I do this on the correctly exported material I get this.
#Multi/Sub-Object:CORRECT LOOKING MULTISUB(Physical Material:BLUE, Physical Material:GREEN, Physical Material:YELLOW, Physical Material:RED)
#(1, 2, 3, 4)
```

So I think there is a bug that you are not reading the actual ID of the material.. you are mainly relying on the order of the material array..

I have attached a 3dsmax file.. that you can test with
[3dsmaxFile_BABYLONJS-MULTIMAT-BUG.zip](https://github.com/BabylonJS/Exporters/files/5888050/3dsmaxFile_BABYLONJS-MULTIMAT-BUG.zip)

**Comment by pandaGaume** [comment]
Hello @ogmasoul3d,
Thanks for this. 
Let me discuss with the team if this is a bug or advanced feature, while indexing the sub material by row or id is only a question of choice.

**Comment by ogmasoul3d** [comment]
Hmm I consider this a bug.. since the actual ID you assign to faces in 3dsmax.. correspond to the ID field.. not the order they come in the MultiSubMaterial UI..

**Comment by ogmasoul3d** [comment]
So in this example I have a multi-material with **5** materials.
I have given the last material ID 9
On my faces in 3dsmax edit-poly I have assigned them to use ID 9

![image](https://user-images.githubusercontent.com/136207/106159018-a662c400-6184-11eb-98bd-3df176edb784.png)

When I export this to gltf..
![image](https://user-images.githubusercontent.com/136207/106160090-bfb84000-6185-11eb-9675-8691a6260f6f.png)

I get this.. the geometry which was using materialID 9 is not visible..
![image](https://user-images.githubusercontent.com/136207/106160273-f0987500-6185-11eb-968f-82add0241255.png)

So I consider this a bug since you are not reading the values they way they function in 3dsmax..

So if some users have been complaining that parts of the mesh does not show up.. this could very well be the cause of thoose issues. This is what made me look for this in the first place.

**Comment by pandaGaume** [comment]
@ogmasoul3d  Thanks for the clarification, it's seem to be inconsistent between Face and Material Id . I will have a look on it.

**Comment by pandaGaume** [comment]
@ogmasoul3d  Fixed with Babylon, still an issue with Gltf, have to check the serialization
![image](https://user-images.githubusercontent.com/22658224/106177026-48d87280-6198-11eb-9cc2-55927cacc8a8.png)

**Comment by pandaGaume** [comment]
@ogmasoul3d PR done, thanks for you help.

**Comment by ogmasoul3d** [comment]
thank you so much for that quick fix @pandaGaume
