### ISSUE TITLE
no save,export button 3d max 2021.3

### ISSUE THREAD

**Issue by hadibeiki** [BabylonJS/Exporters#929]
i have no export and save button in gui...
![image](https://user-images.githubusercontent.com/4311329/106377315-849a5480-63b1-11eb-8433-523b3d0d790c.png)
how can solve this problem!?

**Comment by pandaGaume** [comment]
hello @hadibeiki. What is your screen resolution ?

**Comment by pandaGaume** [comment]
@hadibeiki did u manage to make it work ?? I'm not able to reproduce it here at any resolution, so i'm blind...
If not resolved, could you test to replace (under the \bin\assemblies of the max installation root) your Max2Babylon dll with the one attached and tell me if this fix the issue.
[Max2Babylon.zip](https://github.com/BabylonJS/Exporters/files/5899529/Max2Babylon.zip)
regards

**Comment by hadibeiki** [comment]
replaced with Max2Babylon dll not worked for me i install 3ds max 2020 and still not work
i solved with replace older version of babylon.js and it work.
i used verion 2020 of 20200107.2 in 3ds max 2021.
maybe this help

**Comment by pandaGaume** [comment]
Thanks, we will review that. This is clearly a regression we introduced when maintain the form, but while no ones from the team is able to reproduce, it is difficult to solve.
BTW, what is your screen resolution?
G.

**Comment by pandaGaume** [comment]
@Drigax this is clearly introduced when i changed the form in october, could you tell me what setup did you used to make your change in june when you add this same kind of issue (screen resolution, dpi, scale).
I updated the form with a 1920 x 1200 resolution, 100%. I will try to regenerate the form using lower resolution display. But this is not obvious to see whats happen, because no one of us are able to reproduce.

**Comment by Drigax** [comment]
@pandaGaume i use 1920x1080 as my reference resolution, 100% scaled.

**Comment by hadibeiki** [comment]
my resolution is 1600*900, my log file is clear.
i tried many of them but i used version 20200107.2 and it worked.

**Comment by hadibeiki** [comment]
> @hadibeiki did u manage to make it work ?? I'm not able to reproduce it here at any resolution, so i'm blind...
> If not resolved, could you test to replace (under the \bin\assemblies of the max installation root) your Max2Babylon dll with the one attached and tell me if this fix the issue.
> [Max2Babylon.zip](https://github.com/BabylonJS/Exporters/files/5899529/Max2Babylon.zip)
> regards

the file you attach to this comment is show like this...
![image](https://user-images.githubusercontent.com/4311329/106708728-9b86b400-6608-11eb-91c6-8a73d49b489a.png)

**Comment by hadibeiki** [comment]
when i change the resolution and bring back ... its look like this
![image](https://user-images.githubusercontent.com/4311329/106709023-1c45b000-6609-11eb-8c9e-30671b8e2098.png)

**Comment by gnervous** [comment]
![image](https://user-images.githubusercontent.com/70817684/107650767-91466480-6c5d-11eb-85e4-adfccc99204e.png)

Same for me, resolution 1366x768.

Uninstalled the 3ds max 2020 version and downgraded to 2018 thinking that would solve, but not. I'm trying on another screen this afternoon.

**Comment by pandaGaume** [comment]
FYI, I just publish a PR when i re-generate the form using 1920x1080 as reference, 100% scale.

**Comment by Drigax** [comment]
PR #931 should fix this issue. Thanks @pandaGaume!
