### ISSUE TITLE
Maya optimitize vertices disabled on meshes with morph targets

### ISSUE THREAD

**Issue by agibli** [BabylonJS/Exporters#933]
When exporting a mesh with blendshapes / morph targets, and the Optimize Vertices option is enabled, the Maya exporter plugin raises a warning "Unable to optimize a mesh with morph targets. Disabling optimization for this mesh."

I'm curious what might break if this limitation is removed, maybe something to do with edge smoothing angles? I've tested removing this check and the resulting glTF appears to be valid, but it was on simple geometry.

**Comment by pandaGaume** [comment]
Hi guy's,
Optimizing mesh is an heavy change process, about re-indexing and re-use vertices. As the morph target has been defined using vertices index into maya, this might result on unpredictible behavior. However we revisiting how the morph target is exported few month ago and this solve few of the issues underlying this warning (the morph target is now rebuild on the fly, using stored delta, if been deleted from the source scene. This rebuild process is taking optimizing into account ).

**Comment by agibli** [comment]
Thanks for the response Guillaume!

I'm eager to see if the recent improvements to the way morph targets are exported allow this limitation to be removed. I'd like to use the Babylon.js exporter to export glTFs from Maya, but we have meshes with morph targets (and skin clusters) and would need vertex optimization in order to achieve reasonable file sizes / vertex counts (we need sparse accessors also, though that is a different subject).

In the meantime I can try to see if there are tools (like glTF-transform) that can perform these optimizations after export.

**Comment by pandaGaume** [comment]
@agibli , you may test, removing the check and seeing the result. And post failed scene here to allow us to improve the export process. But without any guarantee as optimizing vertices is a whole process by itself :-).
If enought scenes pass the test, then we may transform the guard into a warning.

**Comment by pandaGaume** [comment]
@agibli  did you had a chance to try on some models ?

**Comment by thomlucc** [comment]
Closing the issue as no answer. @agibli , we'll be happy to re-open the issue, please reach-out if necessary. Thanks!

**Comment by agibli** [comment]
@thomlucc can we re-open this one? I have confirmed it is still an issue on the latest release (as of yesterday), i.e. that the behavior of disabling vertex optimization is still there.

I did some followup tests removing this check and exporting some more complex assets, and so far have not noticed any issues related to morph targets. Unfortunately I don't think I can share the scenes I tested.... but if there is a test suite someone can run on the sample Maya scenes in this project, the only change I made to the plugin was deleting these lines: https://github.com/BabylonJS/Exporters/blob/master/Maya/Exporter/BabylonExporter.Mesh.cs#L515-L519
--

**Comment by agibli** [comment]
@bghgary  Hi Gary! This is Alon at FB, Nicholas Hendricks told me you were interested in knowing the issues I hit using the Babylon exporter, and asked me to reach out. This was one of them, but I'll keep testing and report anything else I find.

**Comment by pandaGaume** [comment]
Guy's, i will have a look on it tomorrow morning (my Time).
G.

Send From Mars Rover.

**Comment by pandaGaume** [comment]
Guy's, 
I had a quick check of the code I introduce to support MorphTarget and confirm that we put everything in place to MorphTarget supporting optimizing - remember that optimizing here is to share vertices, normals and UVs beetwen faces, nothing to do with mesh optimization such Draco - ( and as far i tested :-)). I guess it's time to make a PR to remove this big limitation. If somes issues arise with the use of the both (morph + optimize), then we may deal with it case by case. I have a call with the team today. We gona address the question.
G.
