### ISSUE TITLE
Exporter log blank

### ISSUE THREAD

**Issue by RowanGryder** [BabylonJS/Exporters#934]
Hello,

Upon updating to the latest release it appears the export log no longer reads out anything. I did a clean reinstall and issue persists.
I'm using 3Ds Max 2021
https://user-images.githubusercontent.com/23561431/108601678-bd539b00-736b-11eb-9298-caa0fb53397e.png

**Comment by WollieWoltaz** [comment]
Same here, also on Max 2021

**Comment by pandaGaume** [comment]
if you're going back to release 241, this might be ok. We had to introduce change to support lower resolution with WinForm. This apparently has some border effect. 242 is where this changes has been introduced, 243 is a very specific minor update. We will work on it this week.

**Comment by RowanGryder** [comment]
Rolling back to CD Release 20210201.13 worked. Thanks for the quick response.

**Comment by pandaGaume** [comment]
I just published a PR.

Send From Mars Rover.
