### ISSUE TITLE
3ds Max2020：Exporter Crash

### ISSUE THREAD

**Issue by jack-wangss** [BabylonJS/Exporters#937]
After exporting finished,exporter will kill itself and 3ds max,sometimes it happened in the process of exporting, that means no files will be exported.

video:
https://user-images.githubusercontent.com/37041538/108824252-79c39000-75fc-11eb-9097-eacf18edbfc6.mp4

**Comment by pandaGaume** [comment]
Hi guy's,
Could you share the exception which is raised when it's happen ? And a specific scene to reproduce ?

**Comment by LIJIJIN763436239** [comment]
Can this problem be solved？

**Comment by pandaGaume** [comment]
Hey guys, i need a repro to try to solve it. Could you share the scene ? There is no information at all into the video.

**Comment by LIJIJIN763436239** [comment]
Create a new box and export it

**Comment by LIJIJIN763436239** [comment]
![image](https://user-images.githubusercontent.com/45351528/109622556-324a8000-7b77-11eb-90bc-c694ef5a2d9f.png)

**Comment by pandaGaume** [comment]
Sorry guy's this is perfecly working here.
![image](https://user-images.githubusercontent.com/22658224/109626930-61de9580-7b41-11eb-901c-fd14b8a3c3dd.png)
did you try to reset the max environment using this [official procedure](https://knowledge.autodesk.com/support/3ds-max/learn-explore/caas/sfdcarticles/sfdcarticles/Resetting-3ds-Max-3ds-Max-Design.html)
If Max crash, it might come with a Popup with detail of the crash. Can you share the content of the message ?

**Comment by LIJIJIN763436239** [comment]
After this operation, 3dmax will also be closed，no message

**Comment by pandaGaume** [comment]
OK re-installed 2020 and reproduced. I will investigate. In the mean time you may use 2021 which is fine.
