### ISSUE TITLE
Normal green channel inverted on GLB export, using 3DsMax2021

### ISSUE THREAD

**Issue by lc-virtualretail** [BabylonJS/Exporters#940]
When trying to export an asset with the normals backed into a texture, the green channel in the normal texture is not converted to the right format. 

Using latest release: CD Release 20210308.2

The asset in 3DsMax 2021 with the correct normals.
![image](https://user-images.githubusercontent.com/60696815/110674762-20498c80-81ca-11eb-93a1-80a9ec9ed3dc.png)

Image Babylon Sandbox after export as GLB and run. (green channel inverted)
![image](https://user-images.githubusercontent.com/60696815/110674164-897cd000-81c9-11eb-9871-685278fe2bd4.png)

Image Babylon Sandbox. Corrected by inverting the green channel manually on the material.
![image](https://user-images.githubusercontent.com/60696815/110674611-f4c6a200-81c9-11eb-8091-309b7240531c.png)

**Comment by lc-virtualretail** [comment]
Here is the max scene:
[NormalDemosScene.zip](https://github.com/BabylonJS/Exporters/files/6117866/NormalDemosScene.zip)

This is exported and running in the sandbox
![image](https://user-images.githubusercontent.com/60696815/110675168-80d8c980-81ca-11eb-98e0-b7e7ad84f409.png)

To see the asset correctly, invert manually the normal Y-axis on the material.
![image](https://user-images.githubusercontent.com/60696815/110675209-8d5d2200-81ca-11eb-8084-67ee302ac7ba.png)

**Comment by pandaGaume** [comment]
Hi guy's,.
thanks for the model.
You're using tangent mode, into the normal map. 
![image](https://user-images.githubusercontent.com/22658224/110766654-b1b21080-8255-11eb-9eef-0f580975ad09.png)
in Babylon Exporter, "Export tangent" option is build for this purpose. 
![image](https://user-images.githubusercontent.com/22658224/110766770-d1493900-8255-11eb-8682-4389f3bf84b2.png)
So you must check it in this case, otherwise you get a wrong result, because the normal/tangent/bitangent calculation is different into Babylon/GLTF and 3DSMax. Honestly this is a tricky subject where there is a lot of traps and config patterns (not standard at all between tools and viewers- shaders). We will continue to improve. Let me know if it's work for you into your process.

**Comment by lc-virtualretail** [comment]
exporting using tangents gives me the same bad result. But with one difference, now I can not override Y-axis on the material, both options show the same bad result.


exported with tangetns
![image](https://user-images.githubusercontent.com/60696815/110768466-29307180-824f-11eb-9e69-173694504d18.png)

With tangents exported, inverting Y-axis on the normal map does not apply.
![image](https://user-images.githubusercontent.com/60696815/110768691-5c730080-824f-11eb-8725-4b15bd48928d.png)



This is an image from the right model with the green channel inverted, you can look at the light in the laces to see the difference, sometimes it is hard to spot when the green channel is correct or not. 
![image](https://user-images.githubusercontent.com/60696815/110769136-c8556900-824f-11eb-807c-f72ec4f821a8.png)

**Comment by lc-virtualretail** [comment]
tested with the same results with:
3DsMax 2019 exporter version 20200130.3
3DsMax 2020.3 exporter version 20200215.2

Looks like it is not introduced by 3DsMax 2021.3

**Comment by lc-virtualretail** [comment]
I created a bespoke test scene to check the normals, I hope that helps.
In this scene, it is easier to spot that the light coming from the left is not correct in the baked asset. Also, it is present on the normal debug mode.

[NormalSceneTest.zip](https://github.com/BabylonJS/Exporters/files/6124087/NormalSceneTest.zip)


The scene in 3DsMax: 

- Direct light coming from the left of the scene
- Left asset, bake geometry into a normal map. Looks correct on the 3DsMax display but incorrect on Babylon Sandbox.
- Center asset. Original geometry.
- Right asset, bake geometry into a normal map, and manually inverted the green channel. - Looks incorrect on the 3DsMax display but correct on Babylon Sandbox.

![image](https://user-images.githubusercontent.com/60696815/110812538-9bb94580-827f-11eb-93ac-1f30fa2daeb0.png)

the scene in Babylon sandbox:
![image](https://user-images.githubusercontent.com/60696815/110812675-b8557d80-827f-11eb-9143-d3801c64ad9a.png)

The scene in Babylon sandbox with Material debug mode: Normal Bump.
![image](https://user-images.githubusercontent.com/60696815/110813043-0bc7cb80-8280-11eb-8217-73544cd96fb7.png)

**Comment by pandaGaume** [comment]
There is no operation into the exporter regarding the normal map. It take it at is it. However according to specifications, [glTF uses OpenGL as the format for its normal textures](https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#materialnormaltexture).
also glTF uses a right-handed coordinate system.
![image](https://user-images.githubusercontent.com/22658224/110815017-4d5d7400-828a-11eb-892a-a1d316042c5c.png)
So, to export a GLTF/GLB you need to set a normal map using OpenGL format.
(Babylon js use DirectX format , but assume to load the gltf correcly by inverting the tangent space in Y)
Looking at your map, according the lightest tones on an embossed detail are on the bottom, suggesting the light is below the texture, I simply beleive your map is constructed with DirectX standard which is lead to incorrect rendering.
Also Under max, you can define which bump standard you're using File->preference
![image](https://user-images.githubusercontent.com/22658224/110814177-80533800-8289-11eb-9706-8a1b4c5c3f0f.png)
You may play with theses parameters to find the right workflow configuration.

**Comment by lc-virtualretail** [comment]
It doesn't matter what normal Bump mode is applied. All work as Direct X because Nitrous render is built upon Direct X.

![image](https://user-images.githubusercontent.com/60696815/110816925-b1306e80-8283-11eb-968a-6119ced4f3c8.png)

I already tried all Normal Bump Modes, they do not change the Direct X /  OpenGL normal map behavior. The only solution I have is to manually invert the green channel using 3rd party software or creating complex scripts to manage that.

I also tested by using the inverted green on the normal node:
![image](https://user-images.githubusercontent.com/60696815/110817843-9dd1d300-8284-11eb-84fd-1cef9c32db80.png)

But no luck:
![image](https://user-images.githubusercontent.com/60696815/110818023-cb1e8100-8284-11eb-895f-720d320fef17.png)

**Comment by pandaGaume** [comment]
I have a meeting with the team tonight, I will see if they ok to support the Flip Green.
However; because Max did not doing any computation for us, we need to address the change at texture level and create a new texture to export.
assuming working with a normalized values 
`r = r; g1 = 1.0-g; b = b;`

**Comment by lc-virtualretail** [comment]
It will be good to have the DirectX/OpenGL conversion as an export option, rather than support the flip green node perse, and accessible by MaxScript.

That would be my dream scenario, allowing a scalable bath process, and keeping the same visualization consistency. (To see the asset on 3dsmax with their native DirectX normals and export the GLTF/GLB with an OpenGL format.)

Thanks for your help. Very appreciated.

**Comment by pandaGaume** [comment]
Hi guy's,
I manage to add Babylon custom attributes to Normal Bump Map automatically when binded to a physical material.
![image](https://user-images.githubusercontent.com/22658224/110989394-211d2280-8372-11eb-8b4c-455c0a31bb3f.png)

- The Use 3dsMax channel is apply the transformation located above to the texture prior to export
- The Normal Map format let the user define the format he bind to the material. 

This let us to tell the exporter how to transform the texture without interfering with the Max rendering pipeline. 
Please let me know what you're thinking about.

**Comment by lc-virtualretail** [comment]
I think this approach adds the possibility to work with mixed pipelines, where in the same scene, it is possible to export assets to Babylon or GLTF format by selecting the desired normal format on the Normal Bump material node.

My worry is that I will need to manually set up all materials before exporting or create a script to loop the materials to setup OpenGL in order to export for GLB.

Due to a workflow is normally already decided before exporting, all the assets are going to be exported to the same format.

It will be very useful to expose the option for selecting between OpenGL/DirectX in the Babylon Export Menu. Where a user can choose the right output format for GLTF. It will help people with less experience to select the right choice.

![image](https://user-images.githubusercontent.com/60696815/111140373-2c429f00-857a-11eb-937b-5895c3afcdb1.png)

**Comment by pandaGaume** [comment]
Understand the point, however we perfectly know which is the desired output format. We need to know which is the input one. 
For the purpose I already provisionning a global attribute it take the default value for all the materials, and could be override by material specific configuration.
![image](https://user-images.githubusercontent.com/22658224/111155035-340f3d00-8594-11eb-9bcd-5111e7b644d8.png)
Every material with `unknown `(which is the default), will be save using the global attribute.
if both local and global `unknown `(default) nothing change from today.

**Comment by pandaGaume** [comment]
Hello @lc-virtualretail ,
I get this result now
[test.zip](https://github.com/BabylonJS/Exporters/files/6149491/test.zip)
I beleive it's ok. However, your texture is half directx and half opengl. you have the normal G value of directx, but the Y layout of OpenGl. This make the change OpenGl<->Directx not possible to fully address.
I guess this might be a pretty common scenario, so we maybe propose a set of individual operation such

- InvertY
- FlipGreen

instead of declaring the input format.
G.
