### ISSUE TITLE
how to use with unity?

### ISSUE THREAD

**Issue by huangdebin** [BabylonJS/Exporters#942]
hi,my unity version is 2018.03，i have download this repo,but i  do not where to place it to my unity files?Anyone can help me ?

**Comment by pandaGaume** [comment]
Hello @huangdebin. This repo has nothing to do with Unity, this is 3DSMax/Maya to Babylon js and GLTF exporter.
Regards

**Comment by huangdebin** [comment]
@pandaGaume thank you!
