### ISSUE TITLE
[3dsMax] [Textures] 16-bit channels texture not exported correctly

### ISSUE THREAD

**Issue by Selmar** [BabylonJS/Exporters#95]
The second material in the given example does not export the alpha channel correctly. 
[textureproblem.zip](https://github.com/BabylonJS/Exporters/files/1711858/textureproblem.zip)

I have the impression it might be because the second texture is using 16bit channels instead of 8bit.

We have similar issues with our custom material, where the texture channels seem to be pre-multiplied with the alpha (or something similar) and the texture ends up being a lot darker than it should be. Any hints for that problem are welcome. :)

**Comment by tkazik** [comment]
Do you get the same info?
![opacity_texture_removed](https://user-images.githubusercontent.com/15689124/36078910-3f48044e-0f7d-11e8-9f0c-02f36c084eb4.png)

**Comment by Selmar** [comment]
Yes. The materials are set up identically, except for using different maps. After synchronizing the maps, the problems still persist. Whether I set `alpha source = none` or `= image alpha` on both diffuse textures, nothing changes in the output.

It seems like something goes wrong when reading the opacity map; `opacityBitmap.GetPixel(x, y).A / 255.0f` seems to always be 1, even though we can clearly see there is alpha in the texture in 3dsmax.

**Comment by Selmar** [comment]
Reading this, it seems to be a problem that is part of the Bitmap class: https://social.msdn.microsoft.com/Forums/en-US/62a8f092-ce4f-4324-bc76-4892742d7e06/get-16bit-per-channel-values-of-r-g-b-from-48bit-bitmap?forum=Vsexpressvb

However, it should convert the pixels into a 0-255 range, so I still don't understand why the alpha values are always 255.

**Comment by deltakosh** [comment]
Closing as we do not plan to support them
