### ISSUE TITLE
3ds Max exporter. "Object reference not set to an instance of an object" when exporting tangents

### ISSUE THREAD

**Issue by wandrzej** [BabylonJS/Exporters#951]
`Exception raised during export node will be exported as dummy node. Object reference not set to an instance of an object`
This started to happen on some geometry and I don't really see any common thread here - even a newly generated box with the option export tangents gets this message. Newly generated sphere doesn't. 
Anything that starts as a box primitive is 'cursed' no matter later modifiers, smoothing etc. 
Using Mesher, exporting to fbx and re-importing ... all the usually tricks to get rid of geometry junk don't work here. 
The only object I found that is also not exporting properly (apart from Box primitive) is anything that starts of as an extruded spline. 

I've gone through a lot of strange 'adventures' with 3ds Max, but this is on a completely new level. 

plugin version v20210401.5 (edit: updated to the latest version, has the same issue)

edit: I think I've solved this puzzle. Adding UnwrapUVW modifier fixed the issue.  So it needed a UV channel and the script I was using to generate boxes with the 'Generate Mapping Coords.' set to off.

**Comment by pandaGaume** [comment]
Generate Mapping Coords is set Tangent and UV. I'm agree that uncheck this box is resulting on exception. So we have to catch it into the code.
![image](https://user-images.githubusercontent.com/22658224/116877908-d952a300-ac1e-11eb-80b9-bc727e825745.png)
