### ISSUE TITLE
Maya exporter reports version 2018 regardless of Maya version

### ISSUE THREAD

**Issue by Drigax** [BabylonJS/Exporters#956]
This is probably an oversight resulting of #593, but it would be nice to reimplement the exporter versioning. We should futureproof this by investigating if Maya has an API that reports its version, before we resort to using preprocessor defs.

ex:
![image](https://user-images.githubusercontent.com/3952729/117461024-f8dd1a80-af01-11eb-90d3-2c50947e192e.png)

**Comment by pandaGaume** [comment]
The easy going solution is to relay on c# API  `MGlobal.mayaVersion`
then you wrote
```
            babylonScene.producer = new BabylonProducer
            {
                name = "Maya",
                version = MGlobal.mayaVersion,
                exporter_version = exporterVersion,
                file = outputFileName
            };
```
MGlobal does not provide a way (as far i know) to retreive the Name.

So another solution is to use MEL script command `about -v` and call it using 
`version = MGlobal.executeCommandStringResult("about -v")`
Alternative is to use `'about -p'` which return " Maya 2020" or
`'about -iv'` which return Autodesk Maya 2020.3
then parsing the returned string with `value.Split()`
The last solutions give both the product name and version.
