### ISSUE TITLE
babylon.js glTF exporter for 3dsmax 2018 issues

### ISSUE THREAD

**Issue by Youmyin** [BabylonJS/Exporters#959]
I used babylonjs exporters for 3dsmax2018 to export the model into a glTF file, then imported the file into sandbox, and found that all the textures could not be displayed.

I tested the exported glTF file through the glTF Viewer website, and the error was reported as follows:
![image](https://user-images.githubusercontent.com/54265150/117771304-8903c280-b268-11eb-86f3-5dc1af5c18a3.png)
![image](https://user-images.githubusercontent.com/54265150/117771349-9620b180-b268-11eb-8d77-4e86c62f0f9c.png)

How can I solve this problem?

**Comment by pandaGaume** [comment]
Hello, if you're able to share your files with us, we may help.

**Comment by Youmyin** [comment]
Yes,here is the model file
[demo2.zip](https://github.com/BabylonJS/Exporters/files/6464344/demo2.zip)

**Comment by pandaGaume** [comment]
Thanks for the file, but i was meaning source **Max file** in order to test into Max. The GLTF result give us only indication about the reason it doesn't work.

**Comment by Youmyin** [comment]
Oh,sorry!
[room.zip](https://github.com/BabylonJS/Exporters/files/6464807/room.zip)

**Comment by pandaGaume** [comment]
You're welcome. Your object does NOT define UV map, so texture can not being mapped correctly.
You may add UVW modifiers to your meshes
![image](https://user-images.githubusercontent.com/22658224/117956230-24ed0700-b319-11eb-970c-547c525a7ae6.png)
Here the scene exported correctly.
[demo2.zip](https://github.com/BabylonJS/Exporters/files/6465319/demo2.zip)
Please use the forum for this kind of case. Here it's about bug and ehancement :-)

**Comment by Youmyin** [comment]
Thank you very much!I'm sorry for asking quesitons in the wrong palce,anyway,thanks agian!
