### ISSUE TITLE
Maya exporter should default point lights to no direction

### ISSUE THREAD

**Issue by jlivak** [BabylonJS/Exporters#961]
Using the Maya exporter with Maya 2020, I've noticed that exporting a scene to .babylon will include a default direction of (0,0,1) on point lights.  This causes issues with shadow casting, so I would think exported point lights should follow the default behavior of babylon and just exclude any direction value.

**Comment by pandaGaume** [comment]
We inherit here from the gltf history of point light which was [0,0,1] and become today [0,0,-1].
We will address this question this week with the team.

**Comment by pandaGaume** [comment]
@jlivak do you mean you're set a point light into maya and it exported with additional direction (as directional light) ??
Or do you talk about the default light wich is exported if no light are set ???

**Comment by pandaGaume** [comment]
@Drigax  according the code i see two points here to address (remember we talk about .Babylon and not GLTF)
```
            ....
            {
                ExportHierarchy(babylonLight, mFnLightTransform);
                // Position / rotation / scaling
                ExportTransform(babylonLight, mFnLightTransform);

                // Direction
                vDir = new MVector(0, 0, -1);
                transformationMatrix = new MTransformationMatrix(mFnLightTransform.transformationMatrix);
                vDir = vDir.multiply(transformationMatrix.asMatrixProperty);
                vDir.normalize();
                babylonLight.direction = new[] { (float)vDir.x, (float)vDir.y, -(float)vDir.z };
            }

            // Common fields 
            babylonLight.intensity = mFnLight.intensity;
            babylonLight.diffuse = mFnLight.lightDiffuse ? mFnLight.color.toArrayRGB() : new float[] { 0, 0, 0 };
            babylonLight.specular = mFnLight.lightSpecular ? mFnLight.color.toArrayRGB() : new float[] { 0, 0, 0 };

            // Type
            switch (mFnLight.objectProperty.apiType)
            {
                case MFn.Type.kPointLight:
                    babylonLight.type = 0;
                    break;
                case MFn.Type.kSpotLight:
               ....

```
The first one is WHY we systematically add minus term to Z in the following line
```
                vDir = new MVector(0, 0, -1);
                ....
                babylonLight.direction = new[] { (float)vDir.x, (float)vDir.y, -(float)vDir.z };

```
The second, which is obvious,  is about the case of Point Light where we keep the direction set previously instead as clearing the direction property.
```
                case MFn.Type.kPointLight:
                    babylonLight.type = 0;
                    break;

```
We may have
```
                case MFn.Type.kPointLight:
                    babylonLight.type = 0;
                    babylonLight.direction = null;
                    break;
```

**Comment by jlivak** [comment]
> @jlivak do you mean you're set a point light into maya and it exported with additional direction (as directional light) ??
> Or do you talk about the default light wich is exported if no light are set ???

The first one.  When exporting a maya scene that has one or more point lights, the .babylon file includes a direction value for them rather than leaving direction undefined, causing Babylon to treat it as a directional light.  (Looks like you've already found why that is though above)

I haven't used lights with gltf files and wasn't aware that was a behavior from them, but for .babylon files it would be a nice quality of life improvement to not need to do addition processing on outputted files to remove those directions.

**Comment by pandaGaume** [comment]
You're right we will fix this. Do you experienced the same with Ambient light?
regarding GLTF, I was meaning the default value for directional light ( which is hold by the node transformation).

**Comment by jlivak** [comment]
> You're right we will fix this. Do you experienced the same with Ambient light?
> regarding GLTF, I was meaning the default value for directional light ( which is hold by the node transformation).

Ambient lights also export with a default direction, however I think that's fine since HemisphericLights are meant to have a direction.
