### ISSUE TITLE
Update Optimize Vertices label and checkbox behavior

### ISSUE THREAD

**Issue by PatrickRyanMS** [BabylonJS/Exporters#970]
To better communicate what the checkbox for "optimize vertices" is doing and to imply that it should always be enabled unless the user wants a quick export of an unoptimized file, we would like to change the label and behavior of the checkbox for Max and Maya (Maya shown below)

![image.png](https://images.zenhubusercontent.com/5dc2034af3f3b50001abf7aa/077d7c71-fa2d-4c9e-b817-c095c865b6f1)

The new label should be: **Quick Export (unoptimized)**
Checkbox checked: **Disable optimize vertices**
Checkbox unchecked: **Enable optimize vertices**
Default state: **Unchecked**

I realize this label may not fit in the current space available, so we can revisit the label if this is the case.

**Comment by pandaGaume** [comment]
@bghgary  do we use this PR to turn on this "optimizing" feature ON by default, which MUST be the fact since the begining?, then we only need to change the label.

**Comment by bghgary** [comment]
Is there ever a reason to turn this option off?

**Comment by PatrickRyanMS** [comment]
@bghgary, yes, if you want a quick export to test something in your scene. The optimization step can really slow down the export of a model with a lot of vertices. If you are making some simple changes to your model like texture and want to test the asset out quickly during iteration, turning off the vertex optimization can make your iteration quicker and then you want to run it once with optimize vertices for final.

**Comment by PatrickRyanMS** [comment]
@pandaGaume, this change would be to change the label for sure, but the box would also need to be unchecked since you are correct that the optimization of vertices is enabled by default. That would not change, but the state of the checkbox would be inverted from what it is today.

**Comment by pandaGaume** [comment]
Actually the box is unchecked by default, which mean "Quick Export" by default. 
If we want to keep the same behaviour, we need to check the box by default. In all case we must reverse the logic within the code.
I will make a PR, then we can discuss on it.
