### ISSUE TITLE
Old model is mixed in the sample folder of T-Rex

### ISSUE THREAD

**Issue by cx20** [BabylonJS/Exporters#976]
Previously, the [T-Rex model was broken](https://github.com/BabylonJS/Exporters/issues/943) and was exported again.
However, it seems that old models are still mixed. It's confusing, so I think it's better to remove the old model (`trex_running.*`) and textures (`*.jpg`).

Probably the red part is the old model and texture. (It seems that the old model uses `jpg` for the texture and the new model uses `png`.)
https://github.com/BabylonJS/Exporters/tree/master/Maya/Samples/glTF%202.0/T-Rex
![image](https://user-images.githubusercontent.com/1833979/120838559-e6a6d880-c5a2-11eb-9e8b-e7d9425d1b4c.png)

**Comment by pandaGaume** [comment]
done, thanks for pointing this.
