### ISSUE TITLE
Exception on large mesh export

### ISSUE THREAD

**Issue by Selmar** [BabylonJS/Exporters#98]
Unfortunately I can't give you the model file. We haven't been able to reproduce it in a different mesh, but exporting only the offending meshes causes this issue. Perhaps skinning is the cause, we did not try that. The number of vertices in the meshes seem to be over short.maxValue. I have included the exception message.

![image](https://user-images.githubusercontent.com/3010534/36472352-e09df42c-16f1-11e8-9a1f-fc6ee84c50ef.png)

**Comment by Selmar** [comment]
As soon as you affect a multi-material to a plane, if a polygon has a material ID that is not in the multi-material, it crashes with this message. In addition, it seems to have to have a large amount of polygons.

The artists currently "fix" it like this:
•	Split the mesh into smaller elements
•	Apply to the mesh a single material

**Comment by deltakosh** [comment]
We can also fix it at export with a warning

**Comment by Selmar** [comment]
That's a good thing, of course. It took quite a while to figure out what was going on (especially because the crash is in the 3dsmax api).

**Comment by noalak** [comment]
The bug only occured for 3ds max 2016 but i don't have it. What i did is simulate the issue on 3ds max 2017. Fix and tests are made on 2017.

Tell me if it fixes the issue for you on 3ds max 2016.

**Comment by noalak** [comment]
@Selmar Did fix solved issue for you ?

**Comment by Selmar** [comment]
I’m sorry, I haven’t gotten around to testing it yet.

De : Tambrun Fabrice [mailto:notifications@github.com]
Envoyé : Friday, March 9, 2018 16:11
À : BabylonJS/Exporters <Exporters@noreply.github.com>
Cc : Selmar <selmar21@hotmail.com>; Mention <mention@noreply.github.com>
Objet : Re: [BabylonJS/Exporters] Exception on large mesh export (#98)


@Selmar<https://github.com/selmar> Did fix solved issue for you ?

**Comment by Selmar** [comment]
See #108.
