### ISSUE TITLE
Add EXT_mesh_gpu_instancing support?

### ISSUE THREAD

**Issue by Ben-Mack** [BabylonJS/Exporters#980]
It would be great to have `EXT_mesh_gpu_instancing` support in 3ds Max Exporter.

**Comment by pandaGaume** [comment]
Hello, 
EXT_mesh_gpu_instancing is experimental for now, we are concentrate our effort to, first support a maximum of official extensions (see #892) .
We currently support Clonning, which is also, allow viewer to perform such optimisation.
However if you wish to contribute on this open source project your are welcomed.
How do you imagine to put this in place from 3DSMax perspective?

**Comment by pandaGaume** [comment]
@Ben-Mack any ideas ?

**Comment by pandaGaume** [comment]
closed, transfered to #892
