### ISSUE TITLE
What about exporting files ”IGlobalTNodeTab Autodesk. Max. IGlobal. get INoderab"

### ISSUE THREAD

**Issue by ZhhHugoChang** [BabylonJS/Exporters#982]
No model

**Comment by pandaGaume** [comment]
hello, could you elaborate ?

**Comment by 291601511** [comment]
Error：
Exception raised during export. Mode will be exported as dunmy node. Message：Can't find a way：“IGlobalINodeTab Autodesk.Max.IGlobal.get＿INodeTab（）” 

I am using autodesk 3dsmax 2020

**Comment by 291601511** [comment]
[https://github.com/291601511/image/blob/main/QQ%E6%88%AA%E5%9B%BE20210703064234.png](url)

**Comment by 291601511** [comment]
[https://raw.githubusercontent.com/291601511/image/main/QQ%E6%88%AA%E5%9B%BE20210703064234.png](url)

**Comment by 291601511** [comment]
[https://github.com/291601511/image.git](url)

**Comment by 291601511** [comment]
[https://github.com/291601511/image/blob/a7497487798866a6a018b5b9b08747b718e70e04/QQ%E6%88%AA%E5%9B%BE20210703064234.png](url)

**Comment by bghgary** [comment]
Please provide a repro scene. It will hard to figure out without it. :-)

**Comment by 291601511** [comment]
[image](https://github.com/291601511/image/blob/main/20210703064234.png)

**Comment by bghgary** [comment]
Can you provide a repro scene so that we can debug the export process?

**Comment by 291601511** [comment]
[](https://github.com/291601511/image/blob/main/Models.zip)

**Comment by 291601511** [comment]
https://github.com/291601511/image/blob/main/Models.zip

**Comment by pandaGaume** [comment]
thanks for the repro.
Here the result with Max 2020.2 (note i do not not have the material link with the repro)
![image](https://user-images.githubusercontent.com/22658224/124351135-e2e59080-dbf8-11eb-810a-0543f8ed031f.png)
I beleive you have to patch 3DSMax with Update 2020.2, because of an internal Autodesk issue with plugin dll loading.

**Comment by 291601511** [comment]
Thank you. I'll try again

**Comment by pandaGaume** [comment]
@291601511 did you solve it ?

**Comment by ZhhHugoChang** [comment]
thank you . I solved it @pandaGaume

**Comment by wellchichi** [comment]
> 谢谢你 。我解决了@pandaGaume

咋解决的？

**Comment by ZhhHugoChang** [comment]
@wellchichi 3dsmax升级到2020.2版本即可

**Comment by wellchichi** [comment]
> @wellchichi3dsmax升级到2020.2版本更新

更新到2020.3了还是出这个错误。。

**Comment by ZhhHugoChang** [comment]
@wellchichi 必须是2020.2版本，我前面也是2020.3不行
