### ISSUE TITLE
Error while exporting CoronaMaterial from 3DS Max

### ISSUE THREAD

**Issue by Priya12592** [BabylonJS/Exporters#983]
![Error](https://user-images.githubusercontent.com/87110998/124866860-6db2fa80-e000-11eb-98a3-4b05e11a5e1f.JPG)
I'm trying to export GLTF file from my 3DS and view it in the glTF Viewer. I understand that it's because of the Corona Materials that it's failing to load in the viewer.

Can someone please guide me on how to fix this issue??

**Comment by pandaGaume** [comment]
Hey guy's,
Thank's using our exporter. Unfortunately, Corona Material is not supported yet by the exporter.  see #490. We are welcoming any contribution.
