### ISSUE TITLE
Max2Babylon: Don't use relative paths if same folder?

### ISSUE THREAD

**Issue by echadwick-wayfair** [BabylonJS/Exporters#985]
Currently the Max2Babylon exporter writes relative paths into glTF files, even if the Textures Path is the same as the Model Path. It should probably not do this when they are the same path.

![image](https://user-images.githubusercontent.com/40177036/126171470-ca88e71c-da59-4ed9-b0a6-e816754a5db7.png)

For example please see:
https://github.com/KhronosGroup/glTF-Sample-Models/blob/PearlGoldOliveCoveredGlassDish/2.0/IridescentDishWithOlives/glTF/IridescentDishWithOlives.gltf#L613-L645

`"uri": "./glassdish_spec.png"`

The glTF specification does not have a problem with relative paths being used, but some online glTF viewers (For example, PlayCanvas glTF Viewer) seem to give an error if relative paths are used. 

This is probably something that needs to be fixed by these glTF viewers. However, I don't think it is necessary to specify a relative path when the textures are being exported to the same folder as the .gltf and .bin files.

Thanks!

3ds Max 2020.3
Max2Babylon v20210624.1

**Comment by bghgary** [comment]
This title is a bit confusing. I think when you say "relative path" you mean the "./" in the uri? Even without the "./", the path is still a relative path. Anyways, it seems like something we could fix, but viewers should be able to handle this.

**Comment by emackey** [comment]
From following the issue links, it looks like the viewer in question was having trouble with drag-and-drop of all of the glTF's assets together on a viewer, where the relative `./` part was a reference to a sibling file in the drop.

Perhaps this is something the Khronos samples should test more explicitly?  Looks like the viewer in question fixed it for their own system, anyway.

**Comment by bghgary** [comment]
> Perhaps this is something the Khronos samples should test more explicitly?

Either that or asset generator.

**Comment by pandaGaume** [comment]
We gona fix it. It's not against the standard and it will bring better user experience.
