### ISSUE TITLE
material exportes error

### ISSUE THREAD

**Issue by arthur7921** [BabylonJS/Exporters#989]
if a material has a map texture，After  exporting, its color is #ffffff, not mine in 3dsmax

**Comment by arthur7921** [comment]
release 20210624.1 max2017

**Comment by pandaGaume** [comment]
Hi,
Could you elaborate please, which kind of material (physical ?), which map (base Color?), which color (base color ?). Do you export to GLTF, GLB, Babylon ?
In the case of base Color, under Max, the behavior of Max is Map **OR** Color, then we reproduce this behavior at export time.

**Comment by arthur7921** [comment]
> Hi,
> Could you elaborate please, which kind of material (physical ?), which map (base Color?), which color (base color ?). Do you export to GLTF, GLB, Babylon ?
> In the case of base Color, under Max, the behavior of Max is Map **OR** Color, then we reproduce this behavior at export time.

export to fgltf,  in exported gltf, if a material have a prop baseColorTexture, and baseColorFactor ,baseColorFactor  is  aways 0,0,0, if there is not a baseColorTexture, baseColorFactor is mine which in max

**Comment by pandaGaume** [comment]
Hi,
Perfectly understood.
As far i know, Max did not combine BaseColorMap & BaseColor.
Then BaseColor (3dsMax)& BaseColorFactor(Gltf) are 2 partially differents concepts.
According to GLTF spec, the BaseColorFactor contains scaling factors (not in 3dsMax) for the red, green, blue and alpha components of the color. If no texture is used, these values will define the color of the whole object (same as baseColor in 3dsMax).
The exporter is trying to mimic 3dsMax behavior then this is BaseColorMap **OR** BaseColor, not the both.

**Comment by arthur7921** [comment]
![image](https://user-images.githubusercontent.com/51526225/126966757-97d7774e-21e1-45d8-9095-4665f2667c66.png)
see this

**Comment by pandaGaume** [comment]
Again, i understood.
This modification was done for purpose because BaseColor and BaseColorFactor ARE NOT THE SAME.
In other use cases it's considered as Bug.
Again we want here the SAME result in gltf AND 3dsMax.

**Comment by arthur7921** [comment]
ok，thx、i understood ,too,realy thx for your replying

**Comment by pandaGaume** [comment]
You are welcome.
We can either work on ehancement and we may add this on additional factor for babylon exporter attributes
![image](https://user-images.githubusercontent.com/22658224/126970758-94da128d-84bc-4b12-b8d2-d2d0658fab45.png)
Actually this only export         

```
"metallicFactor": 0.0,
"roughnessFactor": 0.0

```
Could you explain your use case ?
