### ISSUE TITLE
Normals of rotated objects

### ISSUE THREAD

**Issue by tkazik** [BabylonJS/Exporters#99]
I have a model where some parts are rotated, see:

![transform2](https://user-images.githubusercontent.com/15689124/36595541-ce3e4b1c-18a2-11e8-9e70-ceebb35703f2.png)

When exported as gltf, some normals (I guess) seem to point into wrong directions;

![surface_issue](https://user-images.githubusercontent.com/15689124/36595593-061af710-18a3-11e8-8efe-e0d1676ede4d.png)

Will be looking into it. Have you experienced something similar? Any ideas?
3ds max file: [engine.zip](https://github.com/BabylonJS/Exporters/files/1751722/engine.zip)
gltf file: [gltf.zip](https://github.com/BabylonJS/Exporters/files/1751730/gltf.zip)

PS: Please ignore the animation part...that is work in progress as well.

**Comment by Selmar** [comment]
We have just found a related issue. Perhaps even the same. I have opened a separate ticket: #102

**Comment by tkazik** [comment]
Solved by https://github.com/BabylonJS/Exporters/commit/aaf48ae0a13ea08b3305f68d8f9e288290f1d568, thanks @Selmar!
