### ISSUE TITLE
some questions about Maya

### ISSUE THREAD

**Issue by qqba** [BabylonJS/Exporters#993]
I have some questions about Maya
1. Two sets of UV export GLB can be considered
2. Consider supporting ext_ mesh_ gpu_ instancing
3. After skin exports GLB / gltf, the hierarchy will be disrupted
Hope to get a reply, thank you

**Comment by pandaGaume** [comment]
Hi, consider using forum to ask questions
1 - Two set of UV are supported 
2 - ext_ mesh_ gpu_ instancing. Duplicated question. We are working on the ehancement for the gltf extensions support, but ext_ mesh_ gpu_ instancing is not an official extension yet, we DO NOT support non official extensions.
3 - Autodesk way of work for skin hierarchy are not the same as Babylon, and also different in gltf. We may choose a way to transform from model to models, which can easely break the initial hierarchy. We are actually  working on this very complex topic.
Hope this help.

**Comment by qqba** [comment]
Thank you for your reply

**Comment by pandaGaume** [comment]
you're very welcome.
