### ISSUE TITLE
[3ds max][glb] transparent material looks solid

### ISSUE THREAD

**Issue by tkazik** [BabylonJS/Exporters#995]
I recently upgraded to the latest 3ds max exporter and noticed that now the material does no longer look transparent. Any ideas, what has changed? Or are my material settings somehow wrong? Thx for any insight!

The files (glb and max): 
[glass_sample.zip](https://github.com/BabylonJS/Exporters/files/6940192/glass_sample.zip)

**Comment by pandaGaume** [comment]
Hey,
We have to re-visit the transparency. in the mean time you may change the Transparency mode of the Babylon Attribute int Slate Material Editor
![image](https://user-images.githubusercontent.com/22658224/128559868-0d4498ac-a79a-4cf1-b1ea-8281f0bc28b4.png)
Selecting `Blend `should make the trick

**Comment by tkazik** [comment]
> Selecting Blend should make the trick

That indeed solves this issue! Thx for your quick reply!
Should we close the issue or do you want to keep it open until you have revisited the transparency?

**Comment by pandaGaume** [comment]
you're very welcome.
We gona revisit transparency within #892

**Comment by sirjiangt** [comment]
> > Selecting Blend should make the trick
> 
> That indeed solves this issue! Thx for your quick reply! Should we close the issue or do you want to keep it open until you have revisited the transparency?
i can't find the Babylon attributes section, clould u tell me
