### ISSUE TITLE
Max2Babylon: Slow export of a single object when using "exportOnlySelected" and scene has 1000's of objects

### ISSUE THREAD

**Issue by boxofapps** [BabylonJS/Exporters#997]
The assumption is that since I'm only exporting a single object, it shouldn't be slowed down by the fact that the scene has 1000s of objects.

Same problem happens if I try to export by layer which btw to use from maxscript I had to do this, please correct me if I'm doing this wrong:
`max2BabylonMaxScriptExportItem = dotNetObject "Max2Babylon.ExportItem" ""
param.exportLayers = max2BabylonMaxScriptExportItem.StringToLayers "layerName"`

If I delete all other scene objects, then it exports instantaneously.

I also noticed that it is exporting light and camera ".target" helper objects, not sure if this is indicative of what could be wrong, since those objects are not selected nor part of any exporting layers. They are being detected as babylonmesh for some reason.

**Comment by pandaGaume** [comment]
which version of max are you using? Could you share such a massive scene with us?

**Comment by boxofapps** [comment]
3ds max 2021, the scene is brand new with a standard box copied a 1000 times, I can save it for you if you still think it is necessary. 

![image](https://user-images.githubusercontent.com/483242/128614813-c9b03233-faf3-4550-97e5-35571858b29f.png)

If I delete everything else and just export the same single box it takes 1s. Tested on 2022 and it is 15s instead of 30s, not sure if it is the fact it is a cleaner more recent installation

This is simulating a complex archviz scene which I'm was planning to make iterative exports of small object selections, maybe more than 10 exports at a time, but exporting a single box can take 3 minutes in some cases, 3 x 10min would be 30 min to export

A second export is even slower for some reason:
![image](https://user-images.githubusercontent.com/483242/128615060-8b6e0587-d1e3-40cb-9330-1c630476aace.png)


You can also see how it is exporting the camera target even though only the box is selected:
![image](https://user-images.githubusercontent.com/483242/128615102-e32ed65e-3561-4d05-8447-2dbb064ef823.png)
If you want I can put this in another issue.

Thanks,

**Comment by pandaGaume** [comment]
please send me your scene, it will save me time, then i can focus on the issue.

**Comment by boxofapps** [comment]
[test.zip](https://github.com/BabylonJS/Exporters/files/6951461/test.zip)

**Comment by pandaGaume** [comment]
Hey,
I used the provided scene and reproduce the following behavior on Max 2021
Using the original scene with more than 1000 boxes, export only selected is
![image](https://user-images.githubusercontent.com/22658224/128834157-75773f86-b8fa-4b5a-9509-576c7d80d0c6.png)
When keeping only few object, export only selected is
![image](https://user-images.githubusercontent.com/22658224/128834403-572f980e-329e-4bee-a6fb-d70d55c6c663.png)
You wrote about 3min and/or 30s, so i'm bit confused here :-)
G.

**Comment by boxofapps** [comment]
> You wrote about 3min and/or 30s, so i'm a bit confused here.

31s-65s-21s you can see on the screenshots above when using the 1000 boxes scene
3 minutes or more when I have a more complex scene where I want to export a simple box for example

On your example both exports should have taken 1s regardless if the scene has more or less objects considering "export selected" should bring the list of items to process to 1. The export process seems to be looping through all nodes of the scene when it is not necessary to do so. 

Quick solution is to delete all other objects before each export. I'm also investigating the c# code to make some local changes so it is faster here.

Thanks for testing, I will try to figure out why my computer is 30x slower while yours is only 3x slower.
