### ISSUE TITLE
3DS Max exporter fails when exporting an unwrapped mesh with morph targets

### ISSUE THREAD

**Issue by leoncvlt** [BabylonJS/Exporters#999]
3DS Max version: 2020.3.2
Exporter version: v20210802.1

Basically, exporting a mesh with a morpher mofier works fine, but if the mesh being exported has a UVW map (the example scene has the UVW map modifier, but I see the same bug on another mesh which had been unwrapped manually) the exporter fails with an `IndexOutOfRangeException` raised by the `_exportMorthTargets` functions.

Box without UVW mapping + morpher (all good)
![image](https://user-images.githubusercontent.com/4929974/129224913-fe600a74-9157-4e60-bfcc-3981d3abd94c.png)

Box with UVW mapping + moprher
![image](https://user-images.githubusercontent.com/4929974/129225040-d8841e1d-afa4-4a1d-8603-518ddf9df7b7.png)

What's curious is that the two meshes are identical, yet the exporter counts 486 vertices on the non-unwrapped box and 503 on the unwrapped one (faces are the same). Maybe a hint?

Adding UVW map to the morph target doesn't seem to change anything.

The warning doesn't appear when exporting to .babylon, yet the morph targets don't seem to work when previewing the file on the sandbox (it's pretty broken actually, the slider is there but as soon as you click on it it disappears).

Attaching a 3ds max 2020 scene file to replicate the issue:
[test.zip](https://github.com/BabylonJS/Exporters/files/6976638/test.zip)

**Comment by leoncvlt** [comment]
Adding to this, I've tried downloading an older release (20210514.3) and the export works fine. If I have time I'll gradually go through each release and try and pinpoint the one where the regression is introduced.

**Comment by pandaGaume** [comment]
For info, this issue was introduced with release (20210727.1).

**Comment by pandaGaume** [comment]
There is a couple of issue here. Both are regarding an old "optimizing mode" which is obsolete now.

1. When trying to change the meaning of the option into the Object Babylon Properties Form, the options is always false for any obvious reason see #970
2. Consequentely, it's turn **ON** the Optimize Mode by default and highlight some issue on poor tested part of the code.

I will first trying to solve the first which give user a functional tool, then dig on the "optimization" process.

I'll keep you posted.

**Comment by pandaGaume** [comment]
Hello,
I found the reason. The historic code for Morph, was not taking in account correct number of vertices when "optimize" the target (here 486 for the target vs 503 for the source)
We have to fix this.
In the mean time, if you delete the morph target (which is the most common practice in 3DSMax) the Babylon code will dynamically rebuild the target and you will be able to export your scene. 
![image](https://user-images.githubusercontent.com/22658224/129731640-83a5ba0d-ce6c-4be9-9087-1b8f312d7bea.png)

**Comment by leoncvlt** [comment]
Thanks for looking into this!
